Repository labring/FastGPT, pull requests merged in 2023-08, with the labels that each got.

#142 Update star default number
  client/src/pages/index.tsx
Labels: size/XS

#158 chat model config
  client/next.config.js
  client/src/constants/flow/ModuleTemplate.ts
  docSite/docs/develop/data_config/chat_models.md
  docSite/docs/develop/data_config/imgs/chatmodels1.png
  docSite/docs/develop/data_config/intro.md
  docSite/docs/intro.md
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current.json
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/develop/data_config/chat_models.md
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/develop/data_config/imgs/chatmodels1.png
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/develop/data_config/intro.md
  docSite/pnpm-lock.yaml
  docSite/sidebars.js
Labels: size/XL

#161 flow moduoles
  client/data/config.json
  client/src/pages/api/system/getInitData.ts
  docSite/docs/develop/data_config/chat_models.md
  docSite/docs/flow-modules/examples/index.md
  docSite/docs/flow-modules/imgs/intro1.png
  docSite/docs/flow-modules/imgs/intro2.png
  docSite/docs/flow-modules/imgs/intro3.png
  docSite/docs/flow-modules/imgs/intro4.png
  docSite/docs/flow-modules/intro.md
  docSite/docs/flow-modules/modules/ai_chat.md
  docSite/docs/flow-modules/modules/guide.md
  docSite/docs/flow-modules/modules/history.md
  docSite/docs/flow-modules/modules/imgs/aichat.png
  docSite/docs/flow-modules/modules/imgs/chatinput.png
  docSite/docs/flow-modules/modules/imgs/guide.png
  docSite/docs/flow-modules/modules/imgs/history.png
  docSite/docs/flow-modules/modules/imgs/specialreply.png
  docSite/docs/flow-modules/modules/imgs/specialreply2.png
  docSite/docs/flow-modules/modules/imgs/trigger1.png
  docSite/docs/flow-modules/modules/imgs/trigger2.png
  docSite/docs/flow-modules/modules/imgs/variable.png
  docSite/docs/flow-modules/modules/imgs/variable2.png
  docSite/docs/flow-modules/modules/special_reply.md
  docSite/docs/flow-modules/modules/trigger.md
  docSite/docs/flow-modules/modules/user_input.md
  docSite/docs/flow-modules/modules/variable.md
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current.json
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/develop/data_config/chat_models.md
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/examples/index.md
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/imgs/intro1.png
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/imgs/intro2.png
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/imgs/intro3.png
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/imgs/intro4.png
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/intro.md
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/modules/ai_chat.md
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/modules/guide.md
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/modules/history.md
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/modules/imgs/aichat.png
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/modules/imgs/chatinput.png
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/modules/imgs/guide.png
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/modules/imgs/history.png
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/modules/imgs/specialreply.png
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/modules/imgs/specialreply2.png
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/modules/imgs/trigger1.png
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/modules/imgs/trigger2.png
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/modules/imgs/variable.png
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/modules/imgs/variable2.png
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/modules/special_reply.md
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/modules/trigger.md
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/modules/user_input.md
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/flow-modules/modules/variable.md
  docSite/sidebars.js
Labels: size/XL

#162 del file
  files/deploy/fastgpt/docker-compose.yml
  files/deploy/fastgpt/nginx/nginx.conf
Labels: size/L

#163 perf: env template
  client/.env.template
Labels: size/XS

#165 docs
  .github/imgs/logo.png
  README.md
  README_en.md
  client/src/pages/_app.tsx
  client/src/pages/api/openapi/v1/chat/completions.ts
  client/src/service/events/generateVector.ts
  client/src/store/chat.ts
  docSite/docs/develop/data_config/intro.md
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/develop/data_config/intro.md
Labels: size/L

#181 Update README.md
  README.md
Labels: size/S

#183 v4.1
  README.md
  client/public/locales/en/common.json
  client/public/locales/zh/common.json
  client/src/api/chat.ts
  client/src/components/ChatBox/index.tsx
  client/src/pages/api/admin/initChat.ts
  client/src/pages/api/admin/initChatItem.ts
  client/src/pages/api/admin/initv4.ts
  client/src/pages/api/chat/delChatRecordByContentId.ts
  client/src/pages/api/chat/history/updateHistoryQuote.ts
  client/src/pages/api/chat/init.ts
  client/src/pages/api/chat/removeHistory.ts
  client/src/pages/api/openapi/v1/chat/completions.ts
  client/src/pages/api/openapi/v1/chat/getHistory.ts
  client/src/pages/app/detail/components/AdEdit/components/Nodes/NodeAnswer.tsx
  client/src/pages/app/detail/components/AdEdit/components/Nodes/NodeCQNode.tsx
  client/src/pages/app/detail/components/AdEdit/components/Nodes/NodeChat.tsx
  client/src/pages/app/detail/components/AdEdit/components/Nodes/NodeEmpty.tsx
  client/src/pages/app/detail/components/AdEdit/components/Nodes/NodeExtract.tsx
  client/src/pages/app/detail/components/AdEdit/components/Nodes/NodeHistory.tsx
  client/src/pages/app/detail/components/AdEdit/components/Nodes/NodeHttp.tsx
  client/src/pages/app/detail/components/AdEdit/components/Nodes/NodeKbSearch.tsx
  client/src/pages/app/detail/components/AdEdit/components/Nodes/NodeQuestionInput.tsx
  client/src/pages/app/detail/components/AdEdit/components/Nodes/NodeTFSwitch.tsx
  client/src/pages/app/detail/components/AdEdit/components/Nodes/NodeUserGuide.tsx
  client/src/pages/app/detail/components/AdEdit/components/Nodes/NodeVariable.tsx
  client/src/pages/app/detail/components/AdEdit/components/modules/NodeCard.tsx
  client/src/pages/chat/index.tsx
  client/src/pages/login/components/LoginForm.tsx
  client/src/service/models/chat.ts
  client/src/service/models/chatItem.ts
  client/src/service/moduleDispatch/chat/oneapi.ts
  client/src/service/mongo.ts
  client/src/service/utils/chat/saveChat.ts
  client/src/types/chat.d.ts
  client/src/types/flow.d.ts
  client/src/types/mongoSchema.d.ts
  client/src/utils/adapt.ts
  client/src/utils/plugin/openai.ts
  docSite/docs/develop/data_config/chat_models.md
  docSite/docs/develop/data_config/default.md
  docSite/docs/develop/data_config/intro.md
  docSite/docs/develop/deploy/docker.md
  docSite/docs/develop/deploy/initv4.1.md
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/develop/data_config/chat_models.md
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/develop/data_config/default.md
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/develop/data_config/intro.md
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/develop/deploy/docker.md
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/develop/deploy/initv4.1.md
Labels: size/XL

#186 perf: logger
  client/.env.template
  client/package.json
  client/pnpm-lock.yaml
  client/src/constants/flow/ModuleTemplate.ts
  client/src/pages/api/openapi/v1/chat/completions.ts
  client/src/pages/app/detail/components/AdEdit/components/Nodes/NodeAnswer.tsx
  client/src/service/events/generateQA.ts
  client/src/service/events/generateVector.ts
  client/src/service/events/pushBill.ts
  client/src/service/moduleDispatch/chat/oneapi.ts
  client/src/service/moduleDispatch/tools/answer.ts
  client/src/service/mongo.ts
  client/src/service/pg.ts
  client/src/service/response.ts
  client/src/service/utils/tools.ts
  client/src/types/index.d.ts
  docSite/docs/develop/deploy/docker.md
  docSite/docs/develop/update/40init.md
  docSite/docs/develop/update/41init.md
  docSite/docusaurus.config.js
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current.json
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/develop/deploy/docker.md
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/develop/update/40init.md
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/develop/update/41init.md
  docSite/sidebars.js
  files/deploy/fastgpt/docker-compose.yml
Labels: size/XL

#185 页面抓取
  client/package.json
  client/src/pages/api/plugins/kb/fetchContent.ts
  docs/zh/examples/ChatGLM2/image.png
Labels: size/M

#199 feat: url fetch and create file
  README.md
  client/public/imgs/files/url.svg
  client/public/locales/en/common.json
  client/public/locales/zh/common.json
  client/src/api/plugins/common.ts
  client/src/constants/flow/ModuleTemplate.ts
  client/src/hooks/useSelectFile.tsx
  client/src/pages/api/plugins/urlFetch.ts
  client/src/pages/kb/detail/components/DataCard.tsx
  client/src/pages/kb/detail/components/Import/Chunk.tsx
  client/src/pages/kb/detail/components/Import/CreateFileModal.tsx
  client/src/pages/kb/detail/components/Import/Csv.tsx
  client/src/pages/kb/detail/components/Import/FileSelect.tsx
  client/src/pages/kb/detail/components/Import/QA.tsx
  client/src/pages/kb/detail/components/Import/UrlFetchModal.tsx
  client/src/types/plugin.d.ts
  client/src/utils/file.ts
  docSite/docs/develop/deploy/docker.md
  docSite/docs/develop/update/41init.md
  docSite/i18n/zh-Hans/docusaurus-plugin-content-docs/current/develop/update/41init.md
Labels: size/XL

#217 v4.2
  README.md
  client/package.json
  client/public/docs/versionIntro.md
  client/public/js/iframe.js
  client/public/locales/en/common.json
  client/public/locales/zh/common.json
  client/src/api/app.ts
  client/src/components/ChatBox/QuoteModal.tsx
  client/src/components/ChatBox/index.tsx
  client/src/components/Icon/icons/light/logs.svg
  client/src/components/Icon/index.tsx
  client/src/constants/chat.ts
  client/src/constants/flow/ModuleTemplate.ts
  client/src/pages/_app.tsx
  client/src/pages/api/chat/getChatLogs.ts
  client/src/pages/api/openapi/v1/chat/completions.ts
  client/src/pages/api/plugins/urlFetch.ts
  client/src/pages/app/detail/components/Logs.tsx
  client/src/pages/app/detail/index.tsx
  client/src/pages/kb/detail/components/Import/Chunk.tsx
  client/src/pages/kb/detail/components/Import/Csv.tsx
  client/src/pages/kb/detail/components/Import/Manual.tsx
  client/src/pages/kb/detail/components/Import/QA.tsx
  client/src/service/models/chatItem.ts
  client/src/service/moduleDispatch/init/history.tsx
  client/src/service/moduleDispatch/tools/http.ts
  client/src/service/pg.ts
  client/src/types/app.d.ts
  client/src/types/chat.d.ts
  docSite/vercel.json
Labels: size/XL

#219 Update favicon
  .github/workflows/deploy-docs.yml
  docSite/assets/images/logos/logo.svg
  docSite/assets/jsconfig.json
  docSite/layouts/partials/docs/sidebar.html
  docSite/resources/_gen/assets/scss/docs/scss/style.scss_b97bf3f19a5ec64d7a7c5d60f7e31818.content
  docSite/resources/_gen/assets/scss/scss/style.scss_6d90bf46f7cdc038e33af2850006d4ba.content
  docSite/static/android-chrome-192x192.png
  docSite/static/android-chrome-512x512.png
  docSite/static/apple-touch-icon.png
  docSite/static/docs/android-chrome-192x192.png
  docSite/static/docs/android-chrome-512x512.png
  docSite/static/docs/apple-touch-icon.png
  docSite/static/docs/favicon-16x16.png
  docSite/static/docs/favicon-32x32.png
  docSite/static/docs/favicon.ico
  docSite/static/docs/favicon.svg
  docSite/static/docs/mstile-150x150.png
  docSite/static/docs/safari-pinned-tab.svg
  docSite/static/docs/site.webmanifest
  docSite/static/favicon-16x16.png
  docSite/static/favicon-32x32.png
  docSite/static/favicon.ico
  docSite/static/favicon.svg
  docSite/static/mstile-150x150.png
  docSite/static/safari-pinned-tab.svg
  docSite/static/site.webmanifest
Labels: size/XXL

#220 Fix CI workflow
  .github/workflows/deploy-docs.yml
Labels: size/XS

#223 修正单词拼写
  README.md
Labels: size/XS

#225 Fix favicon
  docSite/assets/jsconfig.json
  docSite/layouts/docs/baseof.html
  docSite/layouts/partials/docs/footer/footer-scripts.html
  docSite/layouts/partials/docs/head.html
  docSite/resources/_gen/assets/scss/docs/scss/style.scss_38911198a4b6e5419260ce513414dbb7.content
  docSite/resources/_gen/assets/scss/docs/scss/style.scss_38911198a4b6e5419260ce513414dbb7.json
  docSite/resources/_gen/assets/scss/docs/scss/style.scss_b97bf3f19a5ec64d7a7c5d60f7e31818.content
  docSite/resources/_gen/assets/scss/scss/style.scss_455f7551fbe553ac14c8165c2aef533f.content
  docSite/resources/_gen/assets/scss/scss/style.scss_455f7551fbe553ac14c8165c2aef533f.json
Labels: size/L

#228 user feedback and admin mark
  client/public/docs/chatProblem.md
  client/public/docs/versionIntro.md
  client/public/locales/en/common.json
  client/public/locales/zh/common.json
  client/src/api/chat.ts
  client/src/api/plugins/kb.ts
  client/src/api/request/chat.d.ts
  client/src/components/ChatBox/FeedbackModal.tsx
  client/src/components/ChatBox/ReadFeedbackModal.tsx
  client/src/components/ChatBox/SelectDataset.tsx
  client/src/components/ChatBox/index.tsx
  client/src/components/Icon/icons/light/bad.svg
  client/src/components/Icon/icons/light/mark.svg
  client/src/components/Icon/index.tsx
  client/src/constants/kb.ts
  client/src/pages/api/app/getChatLogs.ts
  client/src/pages/api/chat/feedback/adminUpdate.ts
  client/src/pages/api/chat/feedback/userUpdate.ts
  client/src/pages/api/chat/init.ts
  client/src/pages/api/openapi/kb/updateData.ts
  client/src/pages/api/plugins/kb/data/insertData.ts
  client/src/pages/app/detail/components/Logs.tsx
  client/src/pages/kb/detail/components/Import/Csv.tsx
  client/src/pages/kb/detail/components/Import/Manual.tsx
  client/src/pages/kb/detail/components/InputDataModal.tsx
  client/src/service/models/chatItem.ts
  client/src/service/moduleDispatch/chat/oneapi.ts
  client/src/service/pg.ts
  client/src/service/utils/data.ts
  client/src/types/app.d.ts
  client/src/types/chat.d.ts
  client/src/types/mongoSchema.d.ts
Labels: size/XL

#226 add python requirement.txt for running GLM2 model
  files/models/ChatGLM2/requirement.txt
Labels: size/S

#237 私有化模型对接oneapi教程+镜像更新
  docSite/content/docs/custom-models/chatglm2-m3e.md
  docSite/content/docs/custom-models/chatglm2.md
  docSite/content/docs/custom-models/m3e.md
Labels: size/L
