Repository labring/FastGPT, pull requests merged in 2023-12, with the labels that each got.

#553 Optimize apk install process in Dockerfile
  Dockerfile
Labels: size/XS

#556 docker file and version intro
  Dockerfile
  projects/app/public/docs/versionIntro.md
Labels: size/XS

#572 Adjust the api authentication sequence to preferentially process "authentication" to avoid incorrect authentication caused by cookies
  packages/service/support/permission/controller.ts
Labels: size/S

#585 v4.6.4
  packages/global/common/string/textSplitter.ts
  packages/global/common/system/config/constants.ts
  packages/global/common/system/config/type.d.ts
  packages/service/common/system/config/schema.ts
  packages/service/support/permission/controller.ts
  projects/app/src/components/Markdown/CodeLight.tsx
  projects/app/src/components/Markdown/index.module.scss
  projects/app/src/global/core/prompt/agent.ts
Labels: size/M

#597 fix: template
  projects/app/src/web/core/app/templates.ts
Labels: size/XL

#592 Docs:update sealos guide
  docSite/assets/imgs/onSealos1.png
  docSite/assets/imgs/onsealos10.png
  docSite/assets/imgs/onsealos12.png
  docSite/assets/imgs/onsealos2.png
  docSite/assets/imgs/onsealos3.png
  docSite/assets/imgs/onsealos4.png
  docSite/assets/imgs/onsealos5.png
  docSite/assets/imgs/onsealos6.png
  docSite/assets/imgs/onsealos7.png
  docSite/assets/imgs/onsealos8.png
  docSite/assets/imgs/onsealos9.png
  docSite/assets/imgs/onsealosl11.PNG
  docSite/assets/imgs/sealos13.png
  docSite/content/docs/development/sealos.md
Labels: size/L

#599 Add laf and sealos link in readme
  README.md
Labels: size/XS

#603 Update README
  README.md
Labels: size/M

#607 Docs: add data search update OneAPI guide and wechat
  docSite/assets/imgs/data_search1.png
  docSite/content/docs/course/data_search.md
  docSite/content/docs/development/one-api.md
  docSite/content/docs/development/sealos.md
  docSite/content/docs/use-cases/wechat.md
Labels: size/M

#606 PR：解决上传大文件超时的问题
  projects/app/src/web/common/file/api.ts
Labels: size/XS

#608 Docs:add judgement and string modules
  docSite/assets/imgs/judgement1.png
  docSite/assets/imgs/string.png
  docSite/content/docs/workflow/modules/judgement.md
  docSite/content/docs/workflow/modules/string.md
Labels: size/M

#619 Docs:fix sealos.md
  docSite/content/docs/development/sealos.md
Labels: size/XS

#624 fix: worker un exit
  packages/global/common/string/textSplitter.ts
  packages/service/common/string/markdown.ts
  pnpm-lock.yaml
  projects/app/src/components/Markdown/chat/Guide.tsx
  projects/app/src/components/SideTabs/index.tsx
  projects/app/src/components/core/module/Flow/components/modules/ButtonEdge.tsx
  projects/app/src/pages/dataset/detail/components/Import/Provider.tsx
  projects/app/src/web/styles/theme.ts
  worker/html2md.js
Labels: size/L

#625 perf: prompt textarea
  projects/app/src/components/common/Textarea/PromptTextarea/index.tsx
  projects/app/src/components/core/module/AIChatSettingsModal.tsx
  projects/app/src/components/core/module/Flow/components/render/RenderInput/templates/Textarea.tsx
  projects/app/src/pages/app/detail/components/AdEdit/Header.tsx
  projects/app/src/pages/app/detail/components/SimpleEdit/index.tsx
Labels: size/L

#645 Update README
  README.md
  README_en.md
Labels: size/S

#646 Docs: update qr-code
  docSite/content/docs/community.md
  docSite/content/docs/development/intro.md
  docSite/content/docs/intro.md
  docSite/hugo.toml
Labels: size/XS

#653 fix: init
  docSite/content/docs/development/configuration.md
  docSite/content/docs/development/upgrading/465.md
  projects/app/src/pages/api/system/getInitData.ts
Labels: size/S

#662 config
  docSite/content/docs/development/configuration.md
Labels: size/L

#672 fix: 知识库 QA 导入无法选择 md 和 html 文件
  projects/app/src/pages/dataset/detail/components/Import/QA.tsx
Labels: size/XS
