Repository labring/FastGPT, pull requests merged in 2023-10, with the labels that each got.

#368 Docs: update theme
  .gitignore
  docSite/assets/jsconfig.json
  docSite/go.mod
  docSite/go.sum
  docSite/hugo.toml
  docSite/layouts/docs/single.html
  docSite/layouts/partials/docs/head.html
  docSite/layouts/partials/docs/sidebar.html
Labels: size/M

#369 Docs: add Dockerfile for docs
  .github/workflows/docs-image.yml
  docSite/Dockerfile
Labels: size/M

#371 Update README
  .github/imgs/logo-left.svg
  README.md
  README_en.md
Labels: size/L

#372 README
  README.md
  README_en.md
Labels: size/S

#375 Docs: add button for questionnaire
  docSite/assets/docs/scss/custom/pages/_custom.scss
  docSite/content/docs/commercial.md
  docSite/layouts/partials/docs/footer.html
  docSite/resources/_gen/assets/scss/docs/scss/style.scss_38911198a4b6e5419260ce513414dbb7.content
  docSite/resources/_gen/assets/scss/docs/scss/style.scss_38911198a4b6e5419260ce513414dbb7.json
  docSite/resources/_gen/assets/scss/docs/scss/style.scss_b97bf3f19a5ec64d7a7c5d60f7e31818.content
  docSite/resources/_gen/assets/scss/docs/scss/style.scss_b97bf3f19a5ec64d7a7c5d60f7e31818.json
  docSite/resources/_gen/assets/scss/scss/style.scss_455f7551fbe553ac14c8165c2aef533f.content
  docSite/resources/_gen/assets/scss/scss/style.scss_455f7551fbe553ac14c8165c2aef533f.json
  docSite/resources/_gen/assets/scss/scss/style.scss_6d90bf46f7cdc038e33af2850006d4ba.content
  docSite/resources/_gen/assets/scss/scss/style.scss_6d90bf46f7cdc038e33af2850006d4ba.json
  docSite/resources/_gen/images/lotus_docs_screenshot_huea63e9b4b3759fd29bd9f072754ae476_100589_1349x768_resize_q85_h3_lanczos_3.webp
  docSite/resources/_gen/images/specialreply2_huc35579536c06af3925be00dde0fa3246_233826_1024x0_resize_box_3.png
  docSite/resources/_gen/images/specialreply2_huc35579536c06af3925be00dde0fa3246_233826_1320x0_resize_box_3.png
  docSite/resources/_gen/images/specialreply2_huc35579536c06af3925be00dde0fa3246_233826_330x0_resize_box_3.png
  docSite/resources/_gen/images/specialreply2_huc35579536c06af3925be00dde0fa3246_233826_660x0_resize_box_3.png
Labels: size/XXL

#376 Docs: hide button for questionnaire on mobile device
  docSite/assets/docs/scss/custom/pages/_custom.scss
Labels: size/XS

#377 v4.4.6
  docSite/content/docs/installation/upgrading/40.md
  docSite/content/docs/installation/upgrading/41.md
  docSite/content/docs/installation/upgrading/42.md
  docSite/content/docs/installation/upgrading/421.md
  docSite/content/docs/installation/upgrading/43.md
  docSite/content/docs/installation/upgrading/44.md
  docSite/content/docs/installation/upgrading/441.md
  docSite/content/docs/installation/upgrading/442.md
  docSite/content/docs/installation/upgrading/445.md
  docSite/content/docs/installation/upgrading/446.md
  packages/core/ai/config.ts
  packages/core/ai/constant.ts
  packages/core/ai/functions/createQuestionGuide.ts
  packages/core/ai/type.d.ts
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/public/docs/versionIntro.md
  projects/app/public/imgs/module/app.png
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/api/core/ai/agent/type.d.ts
  projects/app/src/components/ChatBox/ResponseTags.tsx
  projects/app/src/components/ChatBox/index.tsx
  projects/app/src/components/Markdown/chat/Guide.tsx
  projects/app/src/constants/chat.ts
  projects/app/src/constants/flow/ModuleTemplate.ts
  projects/app/src/constants/flow/index.ts
  projects/app/src/pages/api/core/ai/agent/createQuestionGuide.ts
  projects/app/src/pages/api/openapi/plugin/vector.ts
  projects/app/src/pages/api/user/account/update.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/AdEdit/components/Nodes/NodeAPP.tsx
  projects/app/src/pages/app/detail/components/AdEdit/components/Provider.tsx
  projects/app/src/pages/app/detail/components/AdEdit/components/render/RenderInput.tsx
  projects/app/src/pages/app/detail/components/AdEdit/index.tsx
  projects/app/src/pages/app/detail/components/DatasetSelectModal.tsx
  projects/app/src/pages/app/detail/components/Logs.tsx
  projects/app/src/pages/app/detail/components/SelectAppModal.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/pages/chat/components/ToolMenu.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/service/events/generateQA.ts
  projects/app/src/service/moduleDispatch/agent/classifyQuestion.ts
  projects/app/src/service/moduleDispatch/agent/extract.ts
  projects/app/src/service/moduleDispatch/chat/oneapi.ts
  projects/app/src/service/moduleDispatch/index.ts
  projects/app/src/service/moduleDispatch/tools/answer.ts
  projects/app/src/service/moduleDispatch/tools/runApp.ts
  projects/app/src/service/support/outLink/auth.ts
  projects/app/src/service/utils/auth.ts
  projects/app/src/types/core/app/flow.d.ts
  projects/app/src/types/core/chat/type.d.ts
  projects/app/src/utils/adapt.ts
  projects/app/src/utils/common/adapt/message.ts
  projects/app/src/utils/common/tiktoken/index.ts
Labels: size/XXL

#378 fix: packages
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/src/constants/theme.ts
  projects/app/src/service/moduleDispatch/tools/runApp.ts
Labels: size/S

#384 Docs: update workflow for building docs image
  .github/workflows/docs-image.yml
Labels: size/S

#385 Docs: delete image cdn for vercel
  docSite/vercel.json
Labels: size/XS

#391 Docs: use docsearch
  docSite/hugo.toml
  docSite/i18n/zh-cn.toml
  docSite/layouts/partials/docs/footer/docsearch.html
Labels: size/M

#392 Update 447.md
  docSite/content/docs/installation/upgrading/447.md
Labels: size/XS

#395 Docs: add quick start and video link
  docSite/assets/imgs/create-app.png
  docSite/assets/imgs/create-app2.png
  docSite/assets/imgs/create-app3.png
  docSite/assets/imgs/create-app4.png
  docSite/assets/imgs/create-rep.png
  docSite/assets/imgs/upload-data.png
  docSite/assets/imgs/upload-data2.png
  docSite/content/docs/quick-start.md
  docSite/content/docs/use-cases/feishu.md
  docSite/content/docs/workflow/intro.md
Labels: size/M

#404 添加Baichuan2-7B-Chat模型接口文件
  files/models/Baichuan2/openai_api.py
  files/models/Baichuan2/requirements.txt
Labels: size/L

#407 Docs: update README
  README.md
  README_en.md
Labels: size/S

#416 Docs: update qr for wechat group
  docSite/assets/imgs/wechat-fastgpt.webp
  docSite/static/wechat-fastgpt.webp
Labels: size/XS

#418 Update README
  README.md
Labels: size/XS

#419 Config file to set doc baseurl
  packages/global/common/system/types/index.d.ts
  projects/app/src/components/Layout/navbar.tsx
  projects/app/src/components/support/apikey/Table.tsx
  projects/app/src/pages/account/components/Info.tsx
  projects/app/src/pages/api/system/getInitData.ts
  projects/app/src/pages/app/detail/components/AIChatSettingsModal.tsx
  projects/app/src/pages/app/detail/components/OutLink/Share.tsx
  projects/app/src/pages/components/Footer.tsx
  projects/app/src/pages/components/Navbar.tsx
  projects/app/src/pages/dataset/detail/components/Import/FileSelect.tsx
  projects/app/src/pages/login/components/LoginForm.tsx
  projects/app/src/pages/tools/index.tsx
Labels: size/S

#421 v4.5.1-2
  docSite/content/docs/installation/upgrading/451.md
  packages/service/package.json
  pnpm-lock.yaml
  projects/app/src/components/ChatBox/index.tsx
  projects/app/src/pages/_app.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/service/core/dataset/data/utils.ts
  projects/app/src/service/moduleDispatch/chat/oneapi.ts
  projects/app/src/service/moduleDispatch/tools/runApp.ts
Labels: size/M

#423 perf: btn color
  docSite/assets/imgs/getDatasetId.png
  docSite/assets/imgs/getfile_id.png
  docSite/content/docs/development/openApi.md
  docSite/content/docs/installation/upgrading/45.md
  docSite/content/docs/installation/upgrading/451.md
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/components/Icon/icons/core/app/aiFill.svg
  projects/app/src/components/Icon/icons/core/app/aiLight.svg
  projects/app/src/components/Icon/index.tsx
  projects/app/src/components/Layout/navbar.tsx
  projects/app/src/components/Layout/navbarPhone.tsx
  projects/app/src/components/MyModal/index.tsx
  projects/app/src/components/core/dataset/SelectModal.tsx
  projects/app/src/constants/flow/ModuleTemplate.ts
  projects/app/src/constants/flow/flowField.ts
  projects/app/src/pages/api/app/update.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/AIChatSettingsModal.tsx
  projects/app/src/pages/app/detail/components/AdEdit/components/Header.tsx
  projects/app/src/pages/app/detail/components/AdEdit/components/render/RenderOutput.tsx
  projects/app/src/pages/app/detail/components/BasicEdit/index.tsx
  projects/app/src/pages/app/detail/components/DatasetSelectModal.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard.tsx
  projects/app/src/pages/dataset/detail/components/DataCard.tsx
  projects/app/src/pages/dataset/detail/components/Import/Csv.tsx
  projects/app/src/pages/dataset/detail/components/Import/FileSelect.tsx
  projects/app/src/pages/dataset/detail/components/Import/ImportModal.tsx
  projects/app/src/pages/dataset/detail/components/Import/Provider.tsx
  projects/app/src/pages/dataset/detail/components/Info.tsx
  projects/app/src/pages/dataset/list/component/CreateModal.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/service/events/generateQA.ts
  projects/app/src/service/moduleDispatch/chat/oneapi.ts
  projects/app/src/service/moduleDispatch/tools/answer.ts
  projects/app/src/service/moduleDispatch/tools/http.ts
  projects/app/src/service/moduleDispatch/tools/runApp.ts
  projects/app/src/web/common/hooks/useConfirm.tsx
  projects/app/src/web/common/hooks/useEditTitle.tsx
  projects/app/src/web/core/app/basicSettings.ts
  projects/app/src/web/core/dataset/components/SelectCollections.tsx
Labels: size/XL

#427 v4.5.1-3
  README.md
  docSite/content/docs/installation/upgrading/45.md
  docSite/content/docs/workflow/examples/lab_appointment.md
  docSite/content/docs/workflow/examples/op_question.md
  projects/app/data/config.json
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/components/ChatBox/QuoteModal.tsx
  projects/app/src/components/Icon/icons/common/text/t.svg
  projects/app/src/components/Icon/icons/light/rightArrow.svg
  projects/app/src/components/Icon/index.tsx
  projects/app/src/pages/api/core/dataset/searchTest.ts
  projects/app/src/pages/app/detail/components/AdEdit/components/modules/NodeCard.tsx
  projects/app/src/pages/app/detail/components/AdEdit/components/render/RenderInput.tsx
  projects/app/src/pages/app/detail/components/BasicEdit/index.tsx
  projects/app/src/pages/dataset/detail/components/Test.tsx
  projects/app/src/service/moduleDispatch/kb/search.ts
  projects/app/src/service/pg.ts
Labels: size/L

#424 Update README.md 文档改为https://doc.fastgpt.in网站访问
  README.md
Labels: size/S

#432 Quote Modal UI and fix doc
  docSite/content/docs/development/configuration.md
  docSite/content/docs/development/intro.md
  projects/app/src/components/ChatBox/QuoteModal.tsx
  projects/app/src/global/common/string/tools.ts
  projects/app/src/pages/api/system/getInitData.ts
  projects/app/src/service/moduleDispatch/agent/classifyQuestion.ts
Labels: size/S

#445 fix: CQ module output
  packages/global/support/user/constant.ts
  packages/global/support/user/controller.d.ts
  packages/global/support/user/type.d.ts
  packages/service/support/user/schema.ts
  projects/app/src/components/core/module/Flow/components/nodes/NodeCQNode.tsx
  projects/app/src/service/moduleDispatch/agent/classifyQuestion.ts
  projects/app/src/service/moduleDispatch/agent/extract.ts
Labels: size/M
