Repository labring/FastGPT, pull requests merged in 2023-11, with the labels that each got.

#457 Create Python API
  python/api/README.md
  python/api/api.py
  python/api/dockerfile
  python/api/main.py
  python/api/requirements.txt
  python/api/services/fetch.py
  python/api/services/office2txt.py
  python/api/test/fetch_test.py
  python/api/test/office_test.py
Labels: size/L

#460 V4.6-2
  docSite/content/docs/installation/upgrading/46.md
  projects/app/src/components/ChatBox/index.tsx
Labels: size/S

#463 v4.6-3
  package.json
  packages/service/common/file/upload/multer.ts
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/components/ChatBox/index.tsx
  projects/app/src/components/Icon/icons/core/chat/recordFill.svg
  projects/app/src/components/Icon/icons/core/chat/stopSpeechFill.svg
  projects/app/src/components/Icon/index.tsx
  projects/app/src/components/Layout/index.tsx
  projects/app/src/components/common/Textarea/TagTextarea.tsx
  projects/app/src/pages/_app.tsx
  projects/app/src/pages/api/common/file/upload.ts
  projects/app/src/pages/api/core/dataset/data/exportAll.ts
  projects/app/src/pages/api/v1/audio/transcriptions.ts
  projects/app/src/web/common/hooks/useSpeech.ts
Labels: size/L

#467 add “favicon” feconfig
  packages/global/common/system/types/index.d.ts
  projects/app/src/pages/_app.tsx
  projects/app/src/pages/api/system/getInitData.ts
Labels: size/XS

#468 change default title
  projects/app/src/pages/_app.tsx
Labels: size/XS

#441 README: add "back top top" button
  README.md
  README_en.md
Labels: size/M

#473 v4.6-4
  docSite/assets/imgs/datasetSetting1.png
  docSite/content/docs/installation/upgrading/46.md
  docSite/content/docs/pricing.md
  docSite/content/docs/use-cases/datasetEngine.md
  packages/global/common/string/textSplitter.ts
  packages/global/core/dataset/type.d.ts
  packages/global/support/wallet/bill/api.d.ts
  packages/service/core/app/schema.ts
  packages/service/core/dataset/collection/schema.ts
  packages/service/core/dataset/schema.ts
  packages/service/core/dataset/training/schema.ts
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/constants/dataset.ts
  projects/app/src/global/core/api/datasetReq.d.ts
  projects/app/src/global/core/dataset/api.d.ts
  projects/app/src/global/core/prompt/agent.ts
  projects/app/src/pages/api/admin/initv46-2.ts
  projects/app/src/pages/api/admin/initv46-3.ts
  projects/app/src/pages/api/core/dataset/allDataset.ts
  projects/app/src/pages/api/core/dataset/checkExportLimit.ts
  projects/app/src/pages/api/core/dataset/create.ts
  projects/app/src/pages/api/core/dataset/data/pushData.ts
  projects/app/src/pages/api/core/dataset/detail.ts
  projects/app/src/pages/api/core/dataset/exportAll.ts
  projects/app/src/pages/api/core/dataset/list.ts
  projects/app/src/pages/api/core/dataset/update.ts
  projects/app/src/pages/api/support/wallet/bill/createTrainingBill.ts
  projects/app/src/pages/dataset/detail/components/DataCard.tsx
  projects/app/src/pages/dataset/detail/components/Import/ImportModal.tsx
  projects/app/src/pages/dataset/detail/components/Import/Provider.tsx
  projects/app/src/pages/dataset/detail/components/Import/QA.tsx
  projects/app/src/pages/dataset/detail/components/Info.tsx
  projects/app/src/pages/dataset/detail/components/InputDataModal.tsx
  projects/app/src/pages/dataset/list/component/CreateModal.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/service/events/generateQA.ts
  projects/app/src/service/support/wallet/bill/push.ts
  projects/app/src/web/core/dataset/api.ts
Labels: size/XL

#475 doc and config rerank
  docSite/content/docs/installation/upgrading/46.md
  docSite/content/docs/use-cases/ai_settings.md
  docSite/content/docs/use-cases/datasetEngine.md
  packages/global/core/module/node/type.d.ts
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/components/core/module/DatasetSelectModal.tsx
  projects/app/src/components/core/module/Flow/components/render/RenderInput.tsx
  projects/app/src/constants/flow/ModuleTemplate.ts
  projects/app/src/global/core/api/datasetReq.d.ts
  projects/app/src/pages/api/core/dataset/searchTest.ts
  projects/app/src/pages/app/detail/components/BasicEdit/index.tsx
  projects/app/src/pages/dataset/detail/components/Test.tsx
  projects/app/src/service/core/dataset/data/pg.ts
  projects/app/src/service/moduleDispatch/chat/oneapi.ts
  projects/app/src/service/moduleDispatch/dataset/search.ts
  projects/app/src/web/common/api/fetch.ts
  projects/app/src/web/core/app/basicSettings.ts
Labels: size/L

#477 Fixed the duplicate data check problem, history filter and add tts stream
  packages/global/core/ai/model.d.ts
  packages/global/core/ai/model.ts
  packages/global/core/ai/speech/api.d.ts
  packages/global/core/ai/speech/constant.ts
  packages/global/core/app/type.d.ts
  packages/global/core/chat/type.d.ts
  packages/service/common/buffer/tts/schema.ts
  packages/service/common/buffer/tts/type.d.ts
  packages/service/core/ai/audio/speech.ts
  packages/service/core/chat/chatItemSchema.ts
  projects/app/data/config.json
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/components/ChatBox/index.tsx
  projects/app/src/global/common/api/systemRes.d.ts
  projects/app/src/global/core/chat/api.d.ts
  projects/app/src/pages/api/core/chat/item/getSpeech.ts
  projects/app/src/pages/api/system/getInitData.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/TTSSelect.tsx
  projects/app/src/pages/dataset/detail/components/Import/Csv.tsx
  projects/app/src/pages/dataset/detail/components/Import/FileSelect.tsx
  projects/app/src/pages/dataset/detail/components/Import/Provider.tsx
  projects/app/src/pages/dataset/detail/components/InputDataModal.tsx
  projects/app/src/service/core/dataset/data/utils.ts
  projects/app/src/service/moduleDispatch/index.ts
  projects/app/src/types/app.d.ts
  projects/app/src/web/common/api/fetch.ts
  projects/app/src/web/common/system/staticData.ts
  projects/app/src/web/common/utils/voice.ts
  projects/app/src/web/core/chat/api.ts
Labels: size/XL

#480 fix: 46 tmbId empty
  docSite/content/docs/installation/upgrading/46.md
  projects/app/src/pages/_app.tsx
  projects/app/src/pages/api/admin/initv46-fix.ts
  projects/app/src/service/core/dataset/data/controller.ts
  projects/app/src/service/events/generateVector.ts
Labels: size/M

#484 Add whisper and tts ui
  docSite/content/docs/development/configuration.md
  packages/global/core/ai/model.d.ts
  packages/global/core/ai/model.ts
  packages/service/common/file/upload/multer.ts
  packages/service/core/ai/config.ts
  projects/app/data/config.json
  projects/app/package.json
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/components/ChatBox/MessageInput.tsx
  projects/app/src/components/ChatBox/index.tsx
  projects/app/src/components/Icon/icons/core/app/headphones.svg
  projects/app/src/components/Icon/icons/core/app/tts.svg
  projects/app/src/components/Icon/icons/core/chat/recordFill.svg
  projects/app/src/components/Icon/icons/core/chat/speaking.svg
  projects/app/src/components/Icon/icons/core/chat/stopSpeech.svg
  projects/app/src/components/Icon/icons/core/chat/stopSpeechFill.svg
  projects/app/src/components/Icon/index.tsx
  projects/app/src/components/Markdown/img/Image.tsx
  projects/app/src/components/MyModal/index.tsx
  projects/app/src/components/Select/index.tsx
  projects/app/src/global/common/api/systemRes.d.ts
  projects/app/src/global/core/chat/api.d.ts
  projects/app/src/pages/api/core/chat/item/getSpeech.ts
  projects/app/src/pages/api/system/getInitData.ts
  projects/app/src/pages/api/v1/audio/transcriptions.ts
  projects/app/src/pages/app/detail/components/TTSSelect.tsx
  projects/app/src/pages/index.tsx
  projects/app/src/service/support/wallet/bill/push.ts
  projects/app/src/types/index.d.ts
  projects/app/src/web/common/api/fetch.ts
  projects/app/src/web/common/hooks/useSpeech.ts
  projects/app/src/web/common/utils/voice.ts
  projects/app/src/web/styles/theme.ts
Labels: size/XXL

#482 Docs: add wechat case
  docSite/assets/imgs/wechat1.png
  docSite/assets/imgs/wechat10.png
  docSite/assets/imgs/wechat2.png
  docSite/assets/imgs/wechat3.png
  docSite/assets/imgs/wechat4.png
  docSite/assets/imgs/wechat5.png
  docSite/assets/imgs/wechat6.png
  docSite/assets/imgs/wechat7.png
  docSite/assets/imgs/wechat8.png
  docSite/assets/imgs/wechat9.png
  docSite/content/docs/use-cases/wechat.md
Labels: size/M

#486 add image input
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/components/ChatBox/MessageInput.tsx
  projects/app/src/components/ChatBox/index.tsx
  projects/app/src/components/Icon/icons/core/chat/fileSelect.svg
  projects/app/src/components/Icon/index.tsx
  projects/app/src/components/Markdown/chat/Image.tsx
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/web/common/hooks/useSpeech.ts
Labels: size/L

#488 reabase
  docSite/content/docs/development/configuration.md
  packages/global/common/string/tools.ts
  packages/global/core/ai/model.d.ts
  packages/global/core/ai/model.ts
  packages/global/core/ai/type.d.ts
  packages/global/core/chat/constants.ts
  packages/service/common/buffer/tts/schema.ts
  packages/service/common/file/image/schema.ts
  packages/service/core/app/schema.ts
  packages/service/core/chat/chatItemSchema.ts
  packages/service/core/chat/chatSchema.ts
  packages/service/core/chat/utils.ts
  packages/service/core/dataset/controller.ts
  packages/service/core/dataset/data/schema.ts
  packages/service/core/dataset/schema.ts
  packages/service/core/dataset/training/schema.ts
  packages/service/core/plugin/schema.ts
  packages/service/support/activity/promotion/schema.ts
  packages/service/support/openapi/schema.ts
  packages/service/support/outLink/schema.ts
  packages/service/support/permission/auth/app.ts
  packages/service/support/permission/auth/chat.ts
  packages/service/support/permission/auth/dataset.ts
  packages/service/support/user/schema.ts
  packages/service/support/wallet/bill/schema.ts
  projects/app/data/config.json
  projects/app/public/icon/speaking.gif
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/components/ChatBox/MessageInput.tsx
  projects/app/src/components/ChatBox/index.tsx
  projects/app/src/components/MyModal/index.tsx
  projects/app/src/components/support/user/team/UpdateInviteModal/index.tsx
  projects/app/src/pages/_app.tsx
  projects/app/src/pages/api/core/chat/item/getSpeech.ts
  projects/app/src/pages/api/core/dataset/allDataset.ts
  projects/app/src/pages/api/core/dataset/list.ts
  projects/app/src/pages/app/detail/components/TTSSelect.tsx
  projects/app/src/service/events/generateQA.ts
  projects/app/src/service/events/generateVector.ts
  projects/app/src/service/moduleDispatch/chat/oneapi.ts
  projects/app/src/web/common/hooks/useSpeech.ts
  projects/app/src/web/common/utils/voice.ts
  projects/app/src/web/styles/theme.ts
Labels: size/L

#489 feat: vision model
  docSite/content/docs/development/configuration.md
  docSite/content/docs/installation/upgrading/461.md
  packages/global/common/string/tools.ts
  packages/global/core/ai/model.d.ts
  packages/global/core/ai/model.ts
  packages/global/core/ai/type.d.ts
  packages/global/core/chat/constants.ts
  packages/global/core/chat/utils.ts
  packages/service/common/buffer/tts/schema.ts
  packages/service/common/file/image/controller.ts
  packages/service/common/file/image/schema.ts
  packages/service/core/app/schema.ts
  packages/service/core/chat/chatItemSchema.ts
  packages/service/core/chat/chatSchema.ts
  packages/service/core/chat/utils.ts
  packages/service/core/dataset/controller.ts
  packages/service/core/dataset/data/schema.ts
  packages/service/core/dataset/schema.ts
  packages/service/core/dataset/training/schema.ts
  packages/service/core/plugin/schema.ts
  packages/service/support/activity/promotion/schema.ts
  packages/service/support/openapi/schema.ts
  packages/service/support/outLink/schema.ts
  packages/service/support/permission/auth/app.ts
  packages/service/support/permission/auth/chat.ts
  packages/service/support/permission/auth/dataset.ts
  packages/service/support/user/schema.ts
  packages/service/support/wallet/bill/schema.ts
  projects/app/data/config.json
  projects/app/public/icon/speaking.gif
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/components/ChatBox/MessageInput.tsx
  projects/app/src/components/ChatBox/index.tsx
  projects/app/src/components/Markdown/chat/Image.tsx
  projects/app/src/components/Markdown/img/Image.tsx
  projects/app/src/components/core/module/Flow/ChatTest.tsx
  projects/app/src/components/support/user/team/UpdateInviteModal/index.tsx
  projects/app/src/pages/_app.tsx
  projects/app/src/pages/api/common/file/uploadImage.ts
  projects/app/src/pages/api/core/dataset/allDataset.ts
  projects/app/src/pages/api/core/dataset/list.ts
  projects/app/src/pages/app/detail/components/BasicEdit/index.tsx
  projects/app/src/pages/app/detail/components/TTSSelect.tsx
  projects/app/src/pages/chat/components/ChatHeader.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/service/events/generateQA.ts
  projects/app/src/service/events/generateVector.ts
  projects/app/src/service/moduleDispatch/chat/oneapi.ts
  projects/app/src/service/utils/chat/saveChat.ts
  projects/app/src/web/common/file/api.ts
  projects/app/src/web/common/file/controller.ts
  projects/app/src/web/common/file/hooks/useSelectFile.tsx
  projects/app/src/web/common/utils/voice.ts
  projects/app/src/web/core/chat/storeShareChat.ts
  projects/app/src/web/core/chat/utils.ts
  projects/app/src/web/styles/theme.ts
Labels: size/XL

#494 Docs：update wechat.md
  docSite/content/docs/use-cases/wechat.md
Labels: size/XS

#455 Docs: Add Japanese README
  README.md
  README_en.md
  README_ja.md
Labels: size/L

#493 oenapi doc
  README_ja.md
  docSite/.zhlintrc
  docSite/assets/imgs/fastgpt-api-baseurl.png
  docSite/assets/imgs/share-auth1.jpg
  docSite/assets/imgs/share-auth2.png
  docSite/assets/imgs/share-setlink.jpg
  docSite/content/docs/development/intro.md
  docSite/content/docs/development/openApi.md
  docSite/content/docs/development/openapi/_index.md
  docSite/content/docs/development/openapi/auth.md
  docSite/content/docs/development/openapi/chat.md
  docSite/content/docs/development/openapi/dataset.md
  docSite/content/docs/development/openapi/share.md
  docSite/content/docs/installation/one-api.md
  docSite/content/docs/installation/upgrading/421.md
  docSite/content/docs/installation/upgrading/43.md
  docSite/content/docs/installation/upgrading/44.md
  docSite/content/docs/installation/upgrading/442.md
  docSite/content/docs/installation/upgrading/46.md
  packages/global/common/system/types/index.d.ts
  packages/global/core/ai/model.d.ts
  packages/service/core/ai/audio/speech.ts
  packages/service/core/dataset/data/schema.ts
  projects/app/data/config.json
  projects/app/src/components/ChatBox/MessageInput.tsx
  projects/app/src/components/Layout/navbar.tsx
  projects/app/src/components/Select/index.tsx
  projects/app/src/components/core/module/AIChatSettingsModal.tsx
  projects/app/src/pages/account/components/Info.tsx
  projects/app/src/pages/api/core/chat/item/getSpeech.ts
  projects/app/src/pages/api/system/getInitData.ts
  projects/app/src/pages/app/detail/components/OutLink/Share.tsx
  projects/app/src/pages/components/Navbar.tsx
  projects/app/src/pages/login/components/LoginForm.tsx
  projects/app/src/pages/tools/index.tsx
  projects/app/src/service/moduleDispatch/chat/oneapi.ts
  projects/app/src/web/common/file/api.ts
Labels: size/XXL

#496 fix audio input infinite rendering
  projects/app/src/web/common/hooks/useSpeech.ts
Labels: size/S

#497 v4.6.1
  README.md
  README_en.md
  README_ja.md
  docSite/content/docs/installation/upgrading/43.md
  docSite/content/docs/installation/upgrading/44.md
  docSite/content/docs/installation/upgrading/441.md
  docSite/content/docs/installation/upgrading/442.md
  docSite/content/docs/installation/upgrading/445.md
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/components/ChatBox/MessageInput.tsx
  projects/app/src/components/ChatBox/QuoteModal.tsx
  projects/app/src/components/ChatBox/SelectMarkCollection.tsx
  projects/app/src/components/Icon/icons/common/pause.svg
  projects/app/src/components/Icon/icons/light/app.svg
  projects/app/src/components/Icon/index.tsx
  projects/app/src/components/MyModal/index.tsx
  projects/app/src/components/common/ParentPaths/index.tsx
  projects/app/src/components/core/dataset/SelectModal.tsx
  projects/app/src/components/core/module/DatasetSelectModal.tsx
  projects/app/src/pages/api/admin/initv46-fix.ts
  projects/app/src/pages/api/admin/initv46.ts
  projects/app/src/pages/app/detail/components/BasicEdit/index.tsx
  projects/app/src/pages/app/detail/index.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/web/common/hooks/useSticky.ts
Labels: size/XXL

#498 4.6.1 production
  packages/global/core/module/node/constant.ts
  projects/app/src/components/ChatBox/MessageInput.tsx
  projects/app/src/components/ChatBox/QuoteModal.tsx
  projects/app/src/components/ChatBox/index.tsx
  projects/app/src/components/Icon/icons/common/addCircleLight.svg
  projects/app/src/components/Icon/icons/common/courseLight.svg
  projects/app/src/components/Icon/icons/common/file/move.svg
  projects/app/src/components/Icon/icons/common/language/en.svg
  projects/app/src/components/Icon/icons/common/language/zh.svg
  projects/app/src/components/Icon/icons/common/loading.svg
  projects/app/src/components/Icon/icons/common/playFill.svg
  projects/app/src/components/Icon/icons/common/retryLight.svg
  projects/app/src/components/Icon/icons/common/rightArrowLight.svg
  projects/app/src/components/Icon/icons/common/searchLight.svg
  projects/app/src/components/Icon/icons/core/app/logsLight.svg
  projects/app/src/components/Icon/icons/core/app/markLight.svg
  projects/app/src/components/Icon/icons/core/app/questionGuide.svg
  projects/app/src/components/Icon/icons/core/chat/chatModelTag.svg
  projects/app/src/components/Icon/icons/core/chat/feedback/badLight.svg
  projects/app/src/components/Icon/icons/support/account/loginoutLight.svg
  projects/app/src/components/Icon/icons/support/account/promotionLight.svg
  projects/app/src/components/Icon/icons/support/outlink/iframeLight.svg
  projects/app/src/components/Icon/icons/support/outlink/shareLight.svg
  projects/app/src/components/Icon/icons/support/pay/payRecordLight.svg
  projects/app/src/components/Icon/index.tsx
  projects/app/src/components/Layout/navbar.tsx
  projects/app/src/components/common/ParentPaths/index.tsx
  projects/app/src/components/core/module/Flow/TemplateList.tsx
  projects/app/src/components/core/module/Flow/components/nodes/abandon/NodeVariable.tsx
  projects/app/src/components/core/module/Flow/index.tsx
  projects/app/src/components/support/user/team/TeamManageModal/index.tsx
  projects/app/src/pages/account/components/Info.tsx
  projects/app/src/pages/account/index.tsx
  projects/app/src/pages/app/detail/components/Logs.tsx
  projects/app/src/pages/app/detail/components/OutLink/index.tsx
  projects/app/src/pages/app/detail/components/QGSwitch.tsx
  projects/app/src/pages/app/detail/index.tsx
  projects/app/src/pages/chat/components/ChatHeader.tsx
  projects/app/src/pages/components/Hero.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard.tsx
  projects/app/src/pages/dataset/detail/components/DataCard.tsx
  projects/app/src/pages/dataset/detail/components/InputDataModal.tsx
  projects/app/src/pages/dataset/list/component/MoveModal.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/pages/tools/index.tsx
  projects/app/src/web/common/utils/i18n.ts
Labels: size/L

#517 4.6.2-alpha
  packages/global/common/string/tools.ts
  packages/global/core/dataset/type.d.ts
  packages/global/core/module/node/type.d.ts
  packages/global/core/module/type.d.ts
  packages/service/core/dataset/data/schema.ts
  packages/service/package.json
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/components/ChatBox/MessageInput.tsx
  projects/app/src/components/ChatBox/ResponseTags.tsx
  projects/app/src/global/core/api/datasetReq.d.ts
  projects/app/src/global/core/dataset/api.d.ts
  projects/app/src/pages/_app.tsx
  projects/app/src/pages/api/admin/initv46.ts
  projects/app/src/pages/api/admin/initv462.ts
  projects/app/src/pages/api/core/app/create.ts
  projects/app/src/pages/api/core/app/form2Modules/fastgpt-simple.ts
  projects/app/src/pages/api/core/dataset/data/insertData.ts
  projects/app/src/pages/api/core/dataset/data/pushData.ts
  projects/app/src/pages/api/core/dataset/searchTest.ts
  projects/app/src/pages/api/core/plugin/detail.ts
  projects/app/src/pages/dataset/detail/components/Info.tsx
  projects/app/src/pages/dataset/detail/components/Test.tsx
  projects/app/src/pages/dataset/list/component/CreateModal.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/pages/plugin/edit/Preview.tsx
  projects/app/src/pages/plugin/edit/index.tsx
  projects/app/src/pages/plugin/list/component/EditModal.tsx
  projects/app/src/service/core/app/module.ts
  projects/app/src/service/core/dataset/data/controller.ts
  projects/app/src/service/core/dataset/data/pg.ts
  projects/app/src/service/core/dataset/utils.ts
  projects/app/src/service/events/generateQA.ts
  projects/app/src/service/events/generateVector.ts
  projects/app/src/utils/sse.ts
  projects/app/src/web/core/dataset/api.ts
  projects/app/src/web/core/dataset/store/searchTest.ts
Labels: size/XL

#518 4.6.2-production
  docSite/content/docs/development/configuration.md
  docSite/content/docs/installation/upgrading/462.md
  packages/global/common/string/textSplitter.ts
  packages/service/common/response/index.ts
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/public/docs/versionIntro.md
  projects/app/public/imgs/modal/key.svg
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/components/ChatBox/MessageInput.tsx
  projects/app/src/components/Markdown/img/Image.tsx
  projects/app/src/components/support/user/team/TeamManageModal/EditModal.tsx
  projects/app/src/global/core/prompt/AIChat.ts
  projects/app/src/global/core/prompt/agent.ts
  projects/app/src/pages/account/components/Info.tsx
  projects/app/src/pages/app/detail/components/InfoModal.tsx
  projects/app/src/pages/app/list/component/CreateModal.tsx
  projects/app/src/pages/dataset/detail/components/Import/Chunk.tsx
  projects/app/src/pages/dataset/detail/components/Import/FileSelect.tsx
  projects/app/src/pages/dataset/detail/components/Import/ImportModal.tsx
  projects/app/src/pages/dataset/detail/components/Import/Provider.tsx
  projects/app/src/pages/dataset/detail/components/Import/QA.tsx
  projects/app/src/pages/dataset/detail/components/Info.tsx
  projects/app/src/pages/dataset/detail/components/Test.tsx
  projects/app/src/pages/dataset/list/component/CreateModal.tsx
  projects/app/src/pages/plugin/list/component/EditModal.tsx
  projects/app/src/service/events/generateQA.ts
  projects/app/src/web/common/file/controller.ts
  projects/app/src/web/common/file/utils.ts
Labels: size/XL

#519 Add mongo index
  packages/service/common/mongo/init.ts
  packages/service/core/dataset/collection/schema.ts
  packages/service/core/dataset/data/schema.ts
  projects/app/src/pages/api/core/app/form2Modules/fastgpt-universal.ts
  projects/app/src/pages/app/detail/components/SimpleEdit/index.tsx
  projects/app/src/service/core/dataset/data/pg.ts
  projects/app/src/web/core/app/templates.ts
Labels: size/M

#524 Update useSelectFile.tsx
  projects/app/src/web/common/file/hooks/useSelectFile.tsx
Labels: size/XS

#525 rerank api
  packages/global/core/ai/api.d.ts
  projects/app/src/pages/api/v1/rerank.ts
  projects/app/src/service/core/dataset/data/pg.ts
Labels: size/S

#526 system title
  packages/global/core/module/template/system/classifyQuestion.ts
  projects/app/src/components/ChatBox/MessageInput.tsx
  projects/app/src/components/common/MyRadio/index.tsx
  projects/app/src/components/core/module/DatasetParamsModal.tsx
  projects/app/src/components/core/module/Flow/components/modules/VariableEdit.tsx
  projects/app/src/components/support/permission/Radio/index.tsx
  projects/app/src/pages/_app.tsx
  projects/app/src/pages/api/common/file/uploadImage.ts
  projects/app/src/pages/app/detail/components/OutLink/index.tsx
  projects/app/src/pages/dataset/detail/components/Import/ImportModal.tsx
Labels: size/M

#529 4.6.3-alpha1
  packages/global/common/string/time.ts
  packages/global/core/app/utils.ts
  packages/global/core/chat/type.d.ts
  packages/global/core/dataset/constant.ts
  packages/global/core/dataset/controller.d.ts
  packages/global/core/dataset/type.d.ts
  packages/service/core/dataset/collection/schema.ts
  packages/service/core/dataset/data/schema.ts
  packages/service/core/dataset/training/schema.ts
  projects/app/package.json
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/components/ChatBox/WholeResponseModal.tsx
  projects/app/src/components/common/MyRadio/index.tsx
  projects/app/src/components/core/module/Flow/ModuleTemplateList.tsx
  projects/app/src/constants/dataset.ts
  projects/app/src/global/core/api/datasetReq.d.ts
  projects/app/src/global/core/dataset/type.d.ts
  projects/app/src/pages/api/admin/initv463.ts
  projects/app/src/pages/api/core/dataset/collection/create.ts
  projects/app/src/pages/api/core/dataset/collection/delById.ts
  projects/app/src/pages/api/core/dataset/collection/detail.ts
  projects/app/src/pages/api/core/dataset/collection/list.ts
  projects/app/src/pages/api/core/dataset/collection/update.ts
  projects/app/src/pages/api/core/dataset/data/insertData.ts
  projects/app/src/pages/api/core/dataset/data/list.ts
  projects/app/src/pages/api/core/dataset/data/pushData.ts
  projects/app/src/pages/api/core/dataset/delete.ts
  projects/app/src/pages/api/core/plugin/templates.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/SimpleEdit/index.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard.tsx
  projects/app/src/pages/dataset/detail/components/DataCard.tsx
  projects/app/src/pages/dataset/detail/components/Import/FileSelect.tsx
  projects/app/src/pages/dataset/detail/components/Import/ImportModal.tsx
  projects/app/src/pages/dataset/detail/components/Import/Provider.tsx
  projects/app/src/pages/dataset/detail/components/InputDataModal.tsx
  projects/app/src/service/core/dataset/data/controller.ts
  projects/app/src/service/core/dataset/data/pg.ts
  projects/app/src/service/events/generateVector.ts
  projects/app/src/service/moduleDispatch/dataset/search.ts
  projects/app/src/service/support/permission/auth/dataset.ts
  projects/app/src/web/core/dataset/api.ts
Labels: size/XL
