Repository labring/FastGPT, pull requests merged in 2023-07, with the labels that each got.

#112 修复使用代理情况下走流返回，出现的返回吞字问题
  client/src/service/utils/chat/index.ts
Labels: size/S

#121 chore: migrate c121914yu to labring
  README.md
  client/public/docs/chatProblem.md
  client/public/docs/intro.md
  client/public/docs/versionIntro.md
  client/src/components/Layout/navbar.tsx
  client/src/pages/index.tsx
  client/src/pages/tools/index.tsx
  docs/example/imgs/1.png:Zone.Identifier
  docs/example/imgs/10.png:Zone.Identifier
  docs/example/imgs/11.png:Zone.Identifier
  docs/example/imgs/12.png:Zone.Identifier
  docs/example/imgs/13.png:Zone.Identifier
  docs/example/imgs/14.png:Zone.Identifier
  docs/example/imgs/15.png:Zone.Identifier
  docs/example/imgs/16.png:Zone.Identifier
  docs/example/imgs/17.png:Zone.Identifier
  docs/example/imgs/2.png:Zone.Identifier
  docs/example/imgs/3.png:Zone.Identifier
  docs/example/imgs/4.png:Zone.Identifier
  docs/example/imgs/5.png:Zone.Identifier
  docs/example/imgs/6.png:Zone.Identifier
  docs/example/imgs/7.png:Zone.Identifier
  docs/example/imgs/8.png:Zone.Identifier
  docs/example/imgs/9.png:Zone.Identifier
Labels: size/S

#124 fix: deploy doc for macOS
  docs/deploy/mac.md
Labels: size/S

#128 Update README.md, suggest using sealos to deploy fastGPT
  README.md
Labels: size/XS

#135 修正Content-type问题
  client/src/pages/api/openapi/v1/chat/completions.ts
  client/src/service/utils/chat/index.ts
Labels: size/XS

#136 添加embedding接口
  docs/zh/examples/ChatGLM2/openai_api.py
Labels: size/M
