Repository labring/FastGPT, pull requests merged in 2023-09, with the labels that each got.

#249 增加对echarts图表的支持
  client/data/config.json
  client/package.json
  client/src/components/Markdown/img/EChartsCodeBlock.tsx
  client/src/components/Markdown/img/EChartsRenderer.tsx
  client/src/components/Markdown/index.tsx
  client/src/types/echarts-gl.d.ts
Labels: size/M

#254 修改了一些错误
  client/src/utils/sse.ts
  files/models/ChatGLM2/openai_api.py
Labels: size/L

#256 Update docs: change image width
  docSite/assets/docs/scss/custom/pages/_custom.scss
  docSite/assets/docs/scss/style.scss
  docSite/assets/jsconfig.json
  docSite/hugo.toml
  docSite/layouts/partials/docs/head/favicon.html
  docSite/layouts/partials/head/favicon.html
  docSite/resources/_gen/assets/scss/docs/scss/style.scss_b97bf3f19a5ec64d7a7c5d60f7e31818.content
  docSite/resources/_gen/assets/scss/scss/style.scss_6d90bf46f7cdc038e33af2850006d4ba.content
Labels: size/L

#259 Docs: optimize codeblock
  docSite/assets/docs/scss/custom/pages/_custom.scss
  docSite/resources/_gen/assets/scss/docs/scss/style.scss_b97bf3f19a5ec64d7a7c5d60f7e31818.content
  docSite/resources/_gen/assets/scss/scss/style.scss_6d90bf46f7cdc038e33af2850006d4ba.content
Labels: size/L

#263 Docs: fix typo
  .github/workflows/deploy-preview.yml
  docSite/content/docs/custom-models/chatglm2-m3e.md
  docSite/content/docs/custom-models/chatglm2.md
  docSite/content/docs/custom-models/m3e.md
  docSite/content/docs/installation/docker.md
  docSite/content/docs/installation/one-api.md
Labels: size/M

#264 Docs: update table style
  docSite/content/docs/custom-models/chatglm2.md
Labels: size/XS

#265 Docs: fix typo
  .github/workflows/deploy-preview.yml
  docSite/content/docs/custom-models/chatglm2.md
Labels: size/S

#266 demo
  docSite/assets/imgs/demo-fix-evidence1.png
  docSite/assets/imgs/demo-fix-evidence2.png
  docSite/assets/imgs/demo_op_question1.png
  docSite/assets/imgs/demo_op_question2.png
  docSite/assets/imgs/demo_op_question3.png
  docSite/assets/jsconfig.json
  docSite/content/docs/workflow/examples/fixingEvidence.md
  docSite/content/docs/workflow/examples/op_question.md
Labels: size/XL

#272 更新镜像通道
  docSite/content/docs/custom-models/chatglm2-m3e.md
  docSite/content/docs/custom-models/chatglm2.md
  docSite/content/docs/custom-models/m3e.md
Labels: size/S

#275 fix: file_id undefined bug
  client/src/pages/api/admin/initv44.ts
  client/src/pages/api/openapi/plugin/vector.ts
  client/src/service/pg.ts
Labels: size/S

#277 feat: move dataset
  client/public/locales/en/common.json
  client/public/locales/zh/common.json
  client/src/api/plugins/kb.ts
  client/src/api/request/kb.d.ts
  client/src/components/Icon/icons/light/move.svg
  client/src/components/Icon/icons/light/rightArrow.svg
  client/src/components/Icon/index.tsx
  client/src/components/MyMenu/index.tsx
  client/src/hooks/useEditInfo.tsx
  client/src/pages/api/plugins/kb/list.ts
  client/src/pages/api/plugins/kb/update.ts
  client/src/pages/app/detail/components/KBSelectModal.tsx
  client/src/pages/components/Hero.tsx
  client/src/pages/kb/detail/components/FileCard.tsx
  client/src/pages/kb/list/component/MoveModal.tsx
  client/src/pages/kb/list/index.tsx
  client/src/store/dataset.ts
Labels: size/L

#279 Docs: add details shortcode
  docSite/assets/jsconfig.json
  docSite/content/docs/workflow/examples/fixingEvidence.md
  docSite/content/docs/workflow/examples/google_search.md
  docSite/content/docs/workflow/examples/lab_appointment.md
  docSite/content/docs/workflow/examples/op_question.md
  docSite/layouts/shortcodes/details.html
Labels: size/M

#280 Docs: enable ‘Edit this page’
  docSite/assets/docs/scss/custom/pages/_custom.scss
  docSite/hugo.toml
  docSite/i18n/zh-cn.toml
  docSite/layouts/docs/single.html
  docSite/layouts/partials/docs/gitinfo.html
  docSite/resources/_gen/assets/scss/docs/scss/style.scss_b97bf3f19a5ec64d7a7c5d60f7e31818.content
  docSite/resources/_gen/assets/scss/scss/style.scss_6d90bf46f7cdc038e33af2850006d4ba.content
Labels: size/L

#283 Update README.md
  README.md
Labels: size/XS

#287 Docs: add pricing doc
  docSite/assets/imgs/fastgpt-price.png
  docSite/content/docs/installation/docker.md
  docSite/content/docs/installation/one-api.md
  docSite/content/docs/installation/sealos.md
  docSite/content/docs/pricing.md
  docSite/resources/_gen/assets/scss/docs/scss/style.scss_38911198a4b6e5419260ce513414dbb7.content
  docSite/resources/_gen/assets/scss/docs/scss/style.scss_38911198a4b6e5419260ce513414dbb7.json
  docSite/resources/_gen/assets/scss/scss/style.scss_455f7551fbe553ac14c8165c2aef533f.content
  docSite/resources/_gen/assets/scss/scss/style.scss_455f7551fbe553ac14c8165c2aef533f.json
  docSite/vercel.json
Labels: size/M

#289 Docs: update cdn
  docSite/vercel.json
Labels: size/XS

#290 Docs: update weight
  docSite/content/docs/custom-models/_index.md
  docSite/content/docs/custom-models/chatglm2-m3e.md
  docSite/content/docs/custom-models/chatglm2.md
  docSite/content/docs/custom-models/m3e.md
  docSite/content/docs/development/_index.md
  docSite/content/docs/development/configuration.md
  docSite/content/docs/development/intro.md
  docSite/content/docs/intro.md
  docSite/content/docs/use-cases/_index.md
  docSite/content/docs/use-cases/kb.md
  docSite/content/docs/use-cases/onwechat.md
  docSite/content/docs/use-cases/openai.md
  docSite/content/docs/use-cases/prompt.md
  docSite/content/docs/workflow/_index.md
  docSite/content/docs/workflow/examples/_index.md
  docSite/content/docs/workflow/examples/fixingEvidence.md
  docSite/content/docs/workflow/examples/google_search.md
  docSite/content/docs/workflow/examples/lab_appointment.md
  docSite/content/docs/workflow/examples/op_question.md
  docSite/content/docs/workflow/intro.md
  docSite/content/docs/workflow/modules/_index.md
  docSite/content/docs/workflow/modules/ai_chat.md
  docSite/content/docs/workflow/modules/content_extract.md
  docSite/content/docs/workflow/modules/guide.md
  docSite/content/docs/workflow/modules/history.md
  docSite/content/docs/workflow/modules/http.md
  docSite/content/docs/workflow/modules/input.md
  docSite/content/docs/workflow/modules/kb_search.md
  docSite/content/docs/workflow/modules/question.md
  docSite/content/docs/workflow/modules/reply.md
  docSite/content/docs/workflow/modules/trigger.md
  docSite/content/docs/workflow/modules/variable.md
  docSite/resources/_gen/assets/scss/docs/scss/style.scss_b97bf3f19a5ec64d7a7c5d60f7e31818.content
  docSite/resources/_gen/assets/scss/scss/style.scss_6d90bf46f7cdc038e33af2850006d4ba.content
Labels: size/L

#292 google login and power share link
  client/data/config.json
  client/public/locales/en/common.json
  client/public/locales/zh/common.json
  client/src/api/chat.ts
  client/src/api/plugins/kb.ts
  client/src/api/request/kb.d.ts
  client/src/api/service/request.ts
  client/src/api/support/outLink.ts
  client/src/api/user.ts
  client/src/components/Icon/icons/fill/google.svg
  client/src/components/Icon/index.tsx
  client/src/components/Layout/navbar.tsx
  client/src/constants/model.ts
  client/src/constants/user.ts
  client/src/pages/account/components/Info.tsx
  client/src/pages/api/openapi/v1/chat/completions.ts
  client/src/pages/api/plugins/kb/data/exportModelData.ts
  client/src/pages/api/plugins/kb/file/deleteEmptyFiles.ts
  client/src/pages/api/plugins/kb/file/list.ts
  client/src/pages/api/support/outLink/create.ts
  client/src/pages/api/support/outLink/delete.ts
  client/src/pages/api/support/outLink/init.ts
  client/src/pages/api/support/outLink/list.ts
  client/src/pages/api/support/outLink/update.ts
  client/src/pages/api/system/getInitData.ts
  client/src/pages/app/detail/components/OutLink.tsx
  client/src/pages/chat/share.tsx
  client/src/pages/kb/detail/components/DataCard.tsx
  client/src/pages/kb/detail/components/FileCard.tsx
  client/src/pages/kb/detail/components/Import/QA.tsx
  client/src/pages/login/components/LoginForm.tsx
  client/src/pages/login/provider.tsx
  client/src/service/common/ipLimit/schema.ts
  client/src/service/mongo.ts
  client/src/service/support/outLink/auth.ts
  client/src/service/support/outLink/schema.ts
  client/src/service/utils/auth.ts
  client/src/store/global.ts
  client/src/types/app.d.ts
  client/src/types/common/ipLimit.d.ts
  client/src/types/index.d.ts
  client/src/types/mongoSchema.d.ts
  client/src/types/support/outLink.d.ts
  docSite/content/docs/development/configuration.md
  files/deploy/fastgpt/config.json
Labels: size/XXL

#291 Docs: update cdn
  docSite/layouts/partials/docs/footer/footer-scripts.html
  docSite/layouts/partials/google-fonts.html
Labels: size/S

#293 Docs: add community
  docSite/assets/docs/scss/custom/pages/_custom.scss
  docSite/content/docs/commercial.md
  docSite/content/docs/community/_index.md
  docSite/content/docs/community/open-source.md
  docSite/content/docs/community/support.md
  docSite/resources/_gen/assets/scss/docs/scss/style.scss_b97bf3f19a5ec64d7a7c5d60f7e31818.content
Labels: size/L

#296 fix: share link quote
  client/public/docs/versionIntro.md
  client/src/components/ChatBox/QuoteModal.tsx
  client/src/pages/api/system/getInitData.ts
  client/src/pages/chat/share.tsx
  client/src/pages/login/components/LoginForm.tsx
  client/src/types/index.d.ts
Labels: size/L

#297 file name
  docSite/content/docs/installation/upgrading/441.md
Labels: size/XS

#299 perf: document icon and language select
  client/public/locales/en/common.json
  client/public/locales/zh/common.json
  client/src/components/Layout/navbar.tsx
  client/src/pages/account/components/Info.tsx
Labels: size/M

#301 Docs: add github badge
  docSite/assets/docs/scss/custom/pages/_custom.scss
  docSite/layouts/partials/docs/footer.html
  docSite/resources/_gen/assets/scss/docs/scss/style.scss_b97bf3f19a5ec64d7a7c5d60f7e31818.content
Labels: size/L

#303 System optimize
  client/next.config.js
  client/package.json
  client/pnpm-lock.yaml
  client/public/icon/fill/app.svg
  client/public/js/cl100k_base.json
  client/src/components/ChatBox/index.tsx
  client/src/components/Icon/index.tsx
  client/src/components/Layout/navbar.tsx
  client/src/components/MyImage/index.tsx
  client/src/pages/api/core/dataset/file/list.ts
  client/src/pages/api/openapi/kb/pushData.ts
  client/src/pages/api/openapi/text/gptMessagesSlice.ts
  client/src/pages/api/openapi/v1/chat/completions.ts
  client/src/pages/api/plugins/kb/data/insertData.ts
  client/src/pages/app/detail/components/OutLink.tsx
  client/src/pages/components/Ability.tsx
  client/src/pages/components/Choice.tsx
  client/src/pages/components/Hero.tsx
  client/src/pages/index.tsx
  client/src/pages/kb/detail/components/Import/FileSelect.tsx
  client/src/pages/kb/detail/components/Import/QA.tsx
  client/src/pages/login/index.tsx
  client/src/pages/login/provider.tsx
  client/src/service/common/tiktoken.ts
  client/src/service/events/generateQA.ts
  client/src/service/moduleDispatch/agent/classifyQuestion.ts
  client/src/service/moduleDispatch/agent/extract.ts
  client/src/service/moduleDispatch/chat/oneapi.ts
  client/src/service/mongo.ts
  client/src/types/index.d.ts
  client/src/utils/common/adapt/message.ts
  client/src/utils/common/tiktoken/cl100k_base.json
  client/src/utils/common/tiktoken/index.ts
  client/src/utils/file.ts
  client/src/utils/plugin/index.ts
  client/src/utils/plugin/openai.ts
Labels: size/XL

#304 Update deploy-docs-preview workflow
  .github/workflows/deploy-preview.yml
Labels: size/XS

#305 Docs: intergate feishu
  docSite/assets/imgs/feishu-env.png
  docSite/assets/imgs/feishu-res.png
  docSite/content/docs/use-cases/feishu.md
Labels: size/M

#307 Docs: fix typo
  docSite/assets/docs/scss/custom/pages/_custom.scss
  docSite/content/docs/use-cases/feishu.md
  docSite/content/docs/use-cases/onwechat.md
  docSite/resources/_gen/assets/scss/docs/scss/style.scss_b97bf3f19a5ec64d7a7c5d60f7e31818.content
Labels: size/M

#310 Docs: update style
  docSite/assets/images/logos/mark.svg
  docSite/layouts/docs/baseof.html
  docSite/layouts/partials/docs/gitinfo.html
  docSite/layouts/partials/docs/head.html
  docSite/layouts/partials/docs/toc.html
  docSite/resources/_gen/assets/scss/docs/scss/style.scss_b97bf3f19a5ec64d7a7c5d60f7e31818.content
  docSite/resources/_gen/assets/scss/scss/style.scss_6d90bf46f7cdc038e33af2850006d4ba.content
Labels: size/XL

#312 v4.2.2
  client/package.json
  client/pnpm-lock.yaml
  client/src/api/plugins/kb.ts
  client/src/components/ChatBox/index.tsx
  client/src/constants/user.ts
  client/src/pages/account/components/Info.tsx
  client/src/pages/account/components/PayModal.tsx
  client/src/pages/account/index.tsx
  client/src/pages/api/admin/initv442.ts
  client/src/pages/api/core/dataset/file/delById.ts
  client/src/pages/api/openapi/postKey.ts
  client/src/pages/api/openapi/v1/chat/completions.ts
  client/src/pages/api/openapi/v1/chat/getHistory.ts
  client/src/pages/api/plugins/kb/data/exportAll.ts
  client/src/pages/app/detail/components/API.tsx
  client/src/pages/app/detail/components/KBSelectModal.tsx
  client/src/pages/app/detail/index.tsx
  client/src/pages/chat/components/ChatHeader.tsx
  client/src/pages/kb/detail/components/Import/Csv.tsx
  client/src/pages/kb/detail/components/Import/FileSelect.tsx
  client/src/pages/kb/list/index.tsx
  client/src/pages/login/components/RegisterForm.tsx
  client/src/pages/login/index.tsx
  client/src/service/models/bill.ts
  client/src/types/index.d.ts
Labels: size/XL

#316 v4.4.3
  client/public/locales/en/common.json
  client/public/locales/zh/common.json
  client/src/components/ChatBox/index.tsx
  client/src/components/MyModal/index.tsx
  client/src/constants/flow/ModuleTemplate.ts
  client/src/pages/account/components/PayModal.tsx
  client/src/pages/api/admin/initv4.ts
  client/src/pages/api/openapi/v1/chat/completions.ts
  client/src/pages/app/detail/components/AIChatSettingsModal.tsx
  client/src/pages/app/detail/components/AdEdit/components/Nodes/NodeChat.tsx
  client/src/pages/app/detail/components/BasicEdit/index.tsx
  client/src/pages/app/detail/components/InfoModal.tsx
  client/src/pages/app/detail/components/OutLink.tsx
  client/src/pages/kb/detail/components/InputDataModal.tsx
  client/src/prompts/core/AIChat.ts
  client/src/service/moduleDispatch/chat/oneapi.ts
  client/src/types/core/aiChat.d.ts
  client/src/types/mongoSchema.d.ts
  client/src/utils/app.ts
  client/src/utils/common/tiktoken/index.ts
  client/src/utils/common/tools/text.ts
  docSite/assets/jsconfig.json
  docSite/content/docs/installation/upgrading/442.md
  docSite/content/docs/use-cases/prompt.md
Labels: size/XXL

#317 version
  client/package.json
  client/public/docs/versionIntro.md
Labels: size/S

#314 Feature: 高级编排自动布局
  client/package.json
  client/pnpm-lock.yaml
  client/src/pages/app/detail/components/AdEdit/index.tsx
Labels: size/XXL

#319 Revert "Feature: 高级编排自动布局"
  client/package.json
  client/pnpm-lock.yaml
  client/src/pages/app/detail/components/AdEdit/index.tsx
Labels: size/XXL

#318 fix: connected error
  client/pnpm-lock.yaml
  client/src/components/ChatBox/index.tsx
  client/src/constants/flow/ModuleTemplate.ts
  client/src/pages/app/detail/components/AdEdit/index.tsx
  client/src/service/moduleDispatch/chat/oneapi.ts
  client/src/service/response.ts
  client/src/utils/file.ts
  docSite/content/docs/installation/upgrading/442.md
Labels: size/M

#322 Optimize chat reponse data
  client/public/locales/en/common.json
  client/public/locales/zh/common.json
  client/src/api/service/plugins.ts
  client/src/components/ChatBox/ResponseTags.tsx
  client/src/components/ChatBox/WholeResponseModal.tsx
  client/src/components/Icon/index.tsx
  client/src/constants/chat.ts
  client/src/constants/flow/ModuleTemplate.ts
  client/src/pages/api/openapi/v1/chat/completions.ts
  client/src/pages/app/detail/components/AdEdit/components/modules/NodeCard.tsx
  client/src/pages/app/detail/components/AdEdit/index.tsx
  client/src/service/events/pushBill.ts
  client/src/service/models/chat.ts
  client/src/service/moduleDispatch/agent/classifyQuestion.ts
  client/src/service/moduleDispatch/agent/extract.ts
  client/src/service/moduleDispatch/chat/oneapi.ts
  client/src/service/moduleDispatch/kb/search.ts
  client/src/service/moduleDispatch/tools/http.ts
  client/src/service/response.ts
  client/src/types/chat.d.ts
  client/src/types/flow.d.ts
  client/src/utils/adapt.ts
Labels: size/L

#327 fix: mark modal cannot select folder
  client/src/components/ChatBox/SelectDataset.tsx
  client/src/components/ChatBox/index.tsx
  client/src/components/Icon/index.tsx
  client/src/components/core/dataset/SelectModal.tsx
  client/src/pages/app/detail/components/BasicEdit/index.tsx
  client/src/pages/app/detail/components/KBSelectModal.tsx
  client/src/store/dataset.ts
Labels: size/XL

#328 Docs: fix code block highlight
  .github/workflows/deploy-docs.yml
  .github/workflows/deploy-preview.yml
  docSite/go.mod
  docSite/go.sum
Labels: size/S

#329 fix: ts and default dataset
  client/src/pages/app/detail/components/AdEdit/components/Nodes/NodeKbSearch.tsx
  client/src/pages/app/detail/components/BasicEdit/index.tsx
Labels: size/M

#330 Add SSE controller; fix share page login failed
  client/package.json
  client/src/components/ChatBox/index.tsx
  client/src/pages/api/chat/chatTest.ts
  client/src/pages/api/chat/init.ts
  client/src/pages/api/core/dataset/file/update.ts
  client/src/pages/api/openapi/kb/pushData.ts
  client/src/pages/api/openapi/v1/chat/completions.ts
  client/src/pages/api/plugins/kb/data/exportAll.ts
  client/src/pages/kb/detail/components/Import/QA.tsx
  client/src/prompts/core/agent.ts
  client/src/service/common/stream.ts
  client/src/service/events/generateQA.ts
  client/src/service/moduleDispatch/chat/oneapi.ts
Labels: size/L

#331 feat: function call prompt version
  client/data/config.json
  client/public/docs/versionIntro.md
  client/src/components/ChatBox/ResponseTags.tsx
  client/src/pages/api/system/getInitData.ts
  client/src/prompts/core/agent.ts
  client/src/service/events/pushBill.ts
  client/src/service/models/bill.ts
  client/src/service/moduleDispatch/agent/classifyQuestion.ts
  client/src/service/moduleDispatch/agent/extract.ts
  client/src/service/utils/data.ts
  client/src/types/index.d.ts
  client/src/types/model.d.ts
Labels: size/L

#333 Add action for translating Non-English issues content to English
  .github/workflows/bot-issues-translator.yml
Labels: size/S

#334 Docs:add-workflow-case-全能助手
  docSite/assets/imgs/versatile_assistant_1.png
  docSite/assets/imgs/versatile_assistant_2.png
  docSite/assets/imgs/versatile_assistant_3.jpg
  docSite/assets/imgs/versatile_assistant_4.jpg
  docSite/assets/imgs/versatile_assistant_5.jpg
  docSite/assets/imgs/versatile_assistant_6.jpg
  docSite/assets/imgs/versatile_assistant_7.jpg
  docSite/content/docs/workflow/examples/versatile_assistant.md
Labels: size/XXL

#339 Add bill of training and rate of file upload
  client/data/config.json
  client/public/locales/en/common.json
  client/public/locales/zh/common.json
  client/src/api/common/bill/index.d.ts
  client/src/api/common/bill/index.ts
  client/src/api/core/dataset/data.d.ts
  client/src/api/core/dataset/file.d.ts
  client/src/api/core/dataset/file.ts
  client/src/constants/user.ts
  client/src/pages/account/components/BillDetail.tsx
  client/src/pages/account/components/BillTable.tsx
  client/src/pages/api/chat/chatTest.ts
  client/src/pages/api/common/bill/createTrainingBill.ts
  client/src/pages/api/core/dataset/data/insertData.ts
  client/src/pages/api/core/dataset/data/pushData.ts
  client/src/pages/api/core/dataset/delete.ts
  client/src/pages/api/core/dataset/file/markUsed.ts
  client/src/pages/api/openapi/plugin/vector.ts
  client/src/pages/api/openapi/v1/chat/completions.ts
  client/src/pages/api/support/file/read.ts
  client/src/pages/api/system/getInitData.ts
  client/src/pages/kb/detail/components/Import/Chunk.tsx
  client/src/pages/kb/detail/components/Import/Csv.tsx
  client/src/pages/kb/detail/components/Import/FileSelect.tsx
  client/src/pages/kb/detail/components/Import/QA.tsx
  client/src/service/common/bill/push.ts
  client/src/service/common/bill/schema.ts
  client/src/service/events/generateQA.ts
  client/src/service/events/generateVector.ts
  client/src/service/models/trainingData.ts
  client/src/service/moduleDispatch/agent/classifyQuestion.ts
  client/src/service/moduleDispatch/agent/extract.ts
  client/src/service/moduleDispatch/chat/oneapi.ts
  client/src/service/moduleDispatch/kb/search.ts
  client/src/service/mongo.ts
  client/src/service/pg.ts
  client/src/types/common/bill.d.ts
  client/src/types/mongoSchema.d.ts
  client/src/types/user.d.ts
  client/src/utils/adapt.ts
  client/src/utils/web/core/dataset.ts
Labels: size/XL

#342 perf: api key
  client/data/config.json
  client/package.json
  client/public/docs/chatProblem.md
  client/public/docs/versionIntro.md
  client/public/locales/en/common.json
  client/public/locales/zh/common.json
  client/src/api/openapi.ts
  client/src/api/support/openapi/index.d.ts
  client/src/api/support/openapi/index.ts
  client/src/components/APIKeyModal/index.tsx
  client/src/components/ChatBox/WholeResponseModal.tsx
  client/src/components/Icon/icons/fill/apikey.svg
  client/src/components/Icon/index.tsx
  client/src/components/Markdown/chat/Guide.tsx
  client/src/components/support/apikey/Table.tsx
  client/src/constants/chat.ts
  client/src/pages/account/components/ApiKeyTable.tsx
  client/src/pages/account/components/Info.tsx
  client/src/pages/account/index.tsx
  client/src/pages/api/app/getChatLogs.ts
  client/src/pages/api/chat/chatTest.ts
  client/src/pages/api/chat/init.ts
  client/src/pages/api/openapi/getKeys.ts
  client/src/pages/api/openapi/v1/chat/completions.ts
  client/src/pages/api/support/openapi/delKey.ts
  client/src/pages/api/support/openapi/getKeys.ts
  client/src/pages/api/support/openapi/postKey.ts
  client/src/pages/api/support/openapi/putKey.ts
  client/src/pages/api/system/getInitData.ts
  client/src/pages/app/detail/components/API.tsx
  client/src/pages/app/detail/components/AdEdit/components/modules/NodeCard.tsx
  client/src/pages/app/detail/components/BasicEdit/index.tsx
  client/src/pages/app/detail/components/OutLink/API.tsx
  client/src/pages/app/detail/components/OutLink/Share.tsx
  client/src/pages/app/detail/components/OutLink/index.tsx
  client/src/pages/app/detail/index.tsx
  client/src/pages/kb/list/component/EditFolderModal.tsx
  client/src/service/common/bill/push.ts
  client/src/service/errorCode.ts
  client/src/service/models/openapi.ts
  client/src/service/mongo.ts
  client/src/service/support/openapi/auth.ts
  client/src/service/support/openapi/index.ts
  client/src/service/support/openapi/schema.ts
  client/src/service/support/outLink/index.ts
  client/src/service/utils/auth.ts
  client/src/service/utils/chat/saveChat.ts
  client/src/types/index.d.ts
  client/src/types/mongoSchema.d.ts
  client/src/types/openapi.d.ts
  client/src/types/support/openapi.ts
  client/src/utils/service/core/chat/index.ts
  docSite/assets/imgs/fastgpt-api.png
  docSite/assets/jsconfig.json
  docSite/content/docs/pricing.md
  docSite/content/docs/use-cases/feishu.md
  docSite/content/docs/use-cases/onwechat.md
  docSite/content/docs/use-cases/openapi.md
  package.json
Labels: size/XXL

#348 Update intro.md
  docSite/content/docs/development/intro.md
Labels: size/XS

#346 Add OpenAPI docs;Correct the glm document
  README.md
  docSite/assets/imgs/fastgpt-api2.png
  docSite/assets/imgs/getKbId.png
  docSite/content/docs/commercial.md
  docSite/content/docs/custom-models/chatglm2-m3e.md
  docSite/content/docs/custom-models/chatglm2.md
  docSite/content/docs/custom-models/m3e.md
  docSite/content/docs/development/configuration.md
  docSite/content/docs/development/intro.md
  docSite/content/docs/development/openApi.md
  docSite/content/docs/use-cases/kb.md
  projects/app/public/docs/chatProblem.md
  projects/app/public/locales/zh/common.json
  projects/app/src/components/ChatBox/index.tsx
  projects/app/src/components/support/apikey/Table.tsx
  projects/app/src/pages/app/detail/components/OutLink/Share.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/service/support/outLink/auth.ts
  projects/app/src/store/shareChat.ts
Labels: size/XL

#352 Rename requirement.txt to requirements.txt
  files/models/ChatGLM2/requirements.txt
Labels: size/XS

#355 v4.4.5-2
  docSite/content/docs/installation/upgrading/445.md
  packages/core/aiApi/config.ts
  packages/core/aiApi/constant.ts
  packages/core/aiApi/type.d.ts
  packages/core/init.ts
  packages/core/package.json
  packages/core/types/index.d.ts
  packages/core/user/type.d.ts
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/components/ChatBox/utils.ts
  projects/app/src/components/Loading/index.tsx
  projects/app/src/components/support/apikey/Table.tsx
  projects/app/src/constants/flow/ModuleTemplate.ts
  projects/app/src/pages/api/admin/initChat.ts
  projects/app/src/pages/api/admin/initChatItem.ts
  projects/app/src/pages/api/admin/initOutlink.ts
  projects/app/src/pages/api/admin/initv445.ts
  projects/app/src/pages/api/chat/init.ts
  projects/app/src/pages/api/core/dataset/file/markUsed.ts
  projects/app/src/pages/api/openapi/plugin/vector.ts
  projects/app/src/pages/api/openapi/v1/chat/completions.ts
  projects/app/src/pages/api/support/outLink/init.ts
  projects/app/src/pages/api/user/account/update.ts
  projects/app/src/pages/app/detail/components/AdEdit/components/ChatTest.tsx
  projects/app/src/pages/app/detail/components/AdEdit/components/Nodes/NodeUserGuide.tsx
  projects/app/src/pages/app/detail/components/AdEdit/components/TemplateList.tsx
  projects/app/src/pages/app/detail/components/BasicEdit/index.tsx
  projects/app/src/pages/index.tsx
  projects/app/src/pages/kb/detail/components/Import/Chunk.tsx
  projects/app/src/pages/kb/detail/components/Import/CreateFileModal.tsx
  projects/app/src/pages/kb/detail/components/Import/QA.tsx
  projects/app/src/service/events/generateQA.ts
  projects/app/src/service/models/app.ts
  projects/app/src/service/moduleDispatch/agent/classifyQuestion.ts
  projects/app/src/service/moduleDispatch/agent/extract.ts
  projects/app/src/service/moduleDispatch/chat/oneapi.ts
  projects/app/src/service/mongo.ts
  projects/app/src/service/pg.ts
  projects/app/src/types/index.d.ts
  projects/app/src/utils/adapt.ts
  projects/app/src/utils/app.ts
  projects/app/src/utils/common/adapt/message.ts
  projects/app/src/utils/common/tiktoken/index.ts
  projects/app/src/utils/file.ts
  projects/app/tsconfig.json
Labels: size/XL

#354 Update chatglm2.md
  docSite/content/docs/custom-models/chatglm2.md
Labels: size/XS

#357 v4.4.5-3
  Dockerfile
  docSite/content/docs/installation/upgrading/445.md
  docSite/content/docs/installation/upgrading/_index.md
  projects/app/data/config.json
  projects/app/public/docs/versionIntro.md
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/api/core/ai/agent/api.ts
  projects/app/src/api/core/ai/agent/type.d.ts
  projects/app/src/api/request.ts
  projects/app/src/api/response/chat.d.ts
  projects/app/src/components/ChatBox/index.tsx
  projects/app/src/components/ChatBox/utils.ts
  projects/app/src/components/Icon/icons/app/questionGuide.svg
  projects/app/src/components/Icon/index.tsx
  projects/app/src/constants/app.ts
  projects/app/src/constants/flow/ModuleTemplate.ts
  projects/app/src/constants/flow/index.ts
  projects/app/src/pages/api/chat/init.ts
  projects/app/src/pages/api/core/ai/agent/createQuestionGuide.ts
  projects/app/src/pages/api/support/outLink/init.ts
  projects/app/src/pages/api/system/getInitData.ts
  projects/app/src/pages/app/detail/components/AdEdit/components/ChatTest.tsx
  projects/app/src/pages/app/detail/components/AdEdit/components/Nodes/NodeUserGuide.tsx
  projects/app/src/pages/app/detail/components/BasicEdit/index.tsx
  projects/app/src/pages/app/detail/components/Logs.tsx
  projects/app/src/pages/app/detail/components/OutLink/Share.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/prompts/core/agent.ts
  projects/app/src/service/common/bill/push.ts
  projects/app/src/service/moduleDispatch/tools/answer.ts
  projects/app/src/types/index.d.ts
  projects/app/src/utils/app.ts
Labels: size/L

#361 perf: completions api.fix: new chat question guide
  README.md
  docSite/content/docs/development/openApi.md
  docSite/content/docs/use-cases/onwechat.md
  docSite/content/docs/use-cases/openapi.md
  projects/app/src/api/fetch.ts
  projects/app/src/components/ChatBox/index.tsx
  projects/app/src/components/Markdown/index.module.scss
  projects/app/src/pages/api/chat/chatTest.ts
  projects/app/src/pages/api/openapi/v1/chat/completions.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/api/v1/chat/getHistory.ts
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/types/core/chat/type.d.ts
  projects/app/src/utils/adapt.ts
  projects/app/src/utils/common/adapt/message.ts
Labels: size/XXL
