Repository labring/FastGPT, pull requests merged in 2024-07, with the labels that each got.

#1874 添加AI对话时隐藏头部的功能，主要是适配移动端
  projects/app/src/pages/chat/share.tsx
Labels: size/XS

#1910 Update docker.md
  docSite/content/zh-cn/docs/development/docker.md
Labels: size/XS

#1908 Inheritance fix
  packages/service/support/permission/app/auth.ts
  projects/app/src/components/common/folder/SlideCard.tsx
  projects/app/src/components/support/permission/ConfigPerModal/index.tsx
  projects/app/src/pages/api/core/app/update.ts
  projects/app/src/pages/app/list/components/context.tsx
  projects/app/src/pages/app/list/index.tsx
Labels: size/M

#1918 fix(prompt): typo template tag
  packages/global/core/ai/prompt/agent.ts
Labels: size/XS

#1942 fix(prompt): typo extra content
  packages/global/core/ai/prompt/AIChat.ts
Labels: size/XS

#1947 perf: collection created response
  docSite/content/zh-cn/docs/development/openapi/dataset.md
  docSite/content/zh-cn/docs/development/upgrading/486.md
  packages/global/core/chat/utils.ts
  packages/plugins/src/fetchUrl/template.json
  packages/service/core/chat/controller.ts
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/collection/utils.ts
  packages/service/core/workflow/dispatch/utils.ts
  projects/app/src/components/ChatBox/hooks/useChatBox.tsx
  projects/app/src/global/core/dataset/api.d.ts
  projects/app/src/pages/api/core/app/update.ts
  projects/app/src/pages/api/core/chat/init.ts
  projects/app/src/pages/api/core/chat/outLink/init.ts
  projects/app/src/pages/api/core/chat/team/init.ts
  projects/app/src/pages/api/core/dataset/collection/create/csvTable.ts
  projects/app/src/pages/api/core/dataset/collection/create/link.ts
  projects/app/src/pages/api/core/dataset/collection/create/localFile.ts
  projects/app/src/pages/api/core/dataset/collection/create/text.ts
  projects/app/src/pages/api/core/dataset/create.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/SimpleApp/AppCard.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/EditForm.tsx
  projects/app/src/pages/chat/components/ChatHistorySlider.tsx
  projects/app/src/pages/chat/components/ToolMenu.tsx
  projects/app/src/service/core/dataset/data/controller.ts
  projects/app/src/web/core/workflow/utils.ts
Labels: size/L

#1963 4.8.6 fix
  .vscode/extensions.json
  .vscode/settings.json
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
  packages/global/tsconfig.json
  packages/service/common/buffer/rawText/schema.ts
  packages/service/common/buffer/tts/schema.ts
  packages/service/common/file/gridfs/schema.ts
  packages/service/common/file/image/schema.ts
  packages/service/common/mongo/index.ts
  packages/service/common/system/config/schema.ts
  packages/service/common/system/log.ts
  packages/service/common/system/log/constant.ts
  packages/service/common/system/log/schema.ts
  packages/service/common/system/log/type.d.ts
  packages/service/common/system/timerLock/schema.ts
  packages/service/core/app/schema.ts
  packages/service/core/app/version/schema.ts
  packages/service/core/chat/chatItemSchema.ts
  packages/service/core/chat/chatSchema.ts
  packages/service/core/chat/inputGuide/schema.ts
  packages/service/core/dataset/collection/schema.ts
  packages/service/core/dataset/data/schema.ts
  packages/service/core/dataset/schema.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/core/dataset/training/schema.ts
  packages/service/core/workflow/dispatch/agent/extract.ts
  packages/service/support/activity/promotion/schema.ts
  packages/service/support/openapi/schema.ts
  packages/service/support/outLink/schema.ts
  packages/service/support/permission/schema.ts
  packages/service/support/user/schema.ts
  packages/service/support/user/team/teamMemberSchema.ts
  packages/service/support/user/team/teamSchema.ts
  packages/service/support/user/team/teamTagsSchema.ts
  packages/service/support/wallet/sub/schema.ts
  packages/service/support/wallet/usage/schema.ts
  projects/app/.env.template
Labels: size/L

#1990 fix(env): typo template
  projects/app/.env.template
Labels: size/XS

#1970 4.8.6 fix
  docSite/content/zh-cn/docs/development/upgrading/486.md
  packages/global/core/workflow/template/output.ts
  packages/global/core/workflow/template/system/http468.ts
  packages/global/core/workflow/template/system/sandbox/index.ts
  packages/service/common/mongo/index.ts
  packages/service/common/system/log.ts
  packages/service/common/system/log/schema.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/workflow.json
  projects/app/src/components/common/folder/SelectOneResource.tsx
  projects/app/src/pages/app/detail/components/InfoModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeCode.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/chat/components/ChatHistorySlider.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/L

#2017 4.8.6 sandbox
  docSite/content/zh-cn/docs/development/openapi/dataset.md
  docSite/content/zh-cn/docs/development/upgrading/486.md
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
Labels: size/M

#2024 feat: system plugin
  packages/global/core/plugin/type.d.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/type/index.d.ts
  packages/plugins/register.ts
  packages/plugins/type.d.ts
  packages/service/core/app/plugin/controller.ts
  packages/service/core/app/plugin/utils.ts
  packages/service/core/workflow/dispatch/plugin/run.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  packages/service/support/permission/app/auth.ts
  packages/web/components/common/Avatar/index.tsx
  projects/app/src/pages/api/core/app/plugin/getSystemPluginTemplates.ts
Labels: size/L

#2032 fix: plugin runtime
  projects/app/src/components/core/chat/ChatContainer/ChatBox/PluginChatBox.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/PluginBox.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ResponseTags.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/renderPluginInput.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/constants.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderOutput.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderResponseDetail.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/context.tsx
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/Logs/index.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/ChatTest.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/app/detail/components/useChatTest.tsx
  projects/app/src/pages/chat/components/ChatHeader.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/service/utils/chat/saveChat.ts
Labels: size/XXL

#2026 feat(image): metadata support image mime type
  packages/global/common/file/image/type.d.ts
  packages/service/common/file/image/controller.ts
  projects/app/src/pages/api/system/img/[id].ts
Labels: size/S

#2058 4.8.7 test
  packages/global/core/workflow/template/system/queryExtension.ts
  packages/global/package.json
  packages/plugins/package.json
  packages/service/type.d.ts
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/src/pages/api/system/img/[id].ts
  projects/app/src/pages/app/list/components/context.tsx
  projects/app/src/service/mongo.ts
  projects/sandbox/package.json
  tsconfig.json
Labels: size/L

#2061 docs: 完善本地开发教程
  docSite/content/zh-cn/docs/development/docker.md
  docSite/content/zh-cn/docs/development/intro.md
Labels: size/M

#2076 4.8.7 fix
  packages/service/common/mongo/index.ts
  packages/service/common/mongo/init.ts
  packages/service/type.d.ts
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/src/pages/api/common/system/getInitData.ts
  projects/app/src/pages/login/provider.tsx
  projects/app/src/service/common/system/index.ts
  projects/app/src/service/common/system/volumnMongoWatch.ts
  projects/app/src/service/mongo.ts
Labels: size/XL

#2079 lock
  pnpm-lock.yaml
Labels: size/L

#2080 fix: delete plugin output node check filter
  projects/app/src/web/core/workflow/utils.ts
Labels: size/XS

#2081 Update workflow to change baseurl for cn site
  .github/workflows/docs-deploy-kubeconfig.yml
  docSite/hugo.toml
  docSite/layouts/partials/docs/gitinfo.html
Labels: size/XS

#2101 fix: markdown echarts
  packages/service/package.json
  packages/web/components/common/Radio/LeftRadio.tsx
  packages/web/hooks/useScreen.ts
  pnpm-lock.yaml
  projects/app/public/js/pdf.worker.js
  projects/app/src/components/Markdown/img/EChartsCodeBlock.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/pages/app/list/components/CreateModal.tsx
  projects/app/src/web/common/system/useSystemStore.ts
  projects/app/src/web/context/useInitApp.ts
Labels: size/L

#2115 scripts: add delete-unused-keys
  package.json
  packages/global/core/dataset/constants.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/en/chat.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/en/user.json
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/dataset.json
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderToolInput/index.tsx
  scripts/i18n/delete-unused-keys.js
Labels: size/XL

#2116 fix resource permission schema
  packages/global/support/permission/type.d.ts
  packages/service/support/permission/schema.ts
Labels: size/S

#2117 Chat-perf
  dev.md
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/chat/chevronDown.svg
  packages/web/components/common/Icon/icons/core/chat/chevronUp.svg
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ResponseTags.tsx
Labels: size/L

#2124 update: i18n common.json keys
  packages/web/components/common/Textarea/CodeEditor/index.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/common.json
  projects/app/src/components/core/app/InputGuideConfig.tsx
  projects/app/src/components/support/apikey/Table.tsx
  projects/app/src/components/support/permission/ResumeInheritText/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeExtract/ExtractFieldModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderToolInput/index.tsx
  projects/app/src/pages/dataset/detail/components/Import/diffSource/ExternalFile.tsx
Labels: size/M

#2126 Perf system plugin and worker
  docSite/content/zh-cn/docs/development/upgrading/488.md
  packages/plugins/package.json
  packages/plugins/register.ts
  packages/plugins/runtime/worker.ts
  packages/plugins/src/duckduckgo/search/index.ts
  packages/plugins/src/duckduckgo/searchImg/index.ts
  packages/plugins/src/duckduckgo/searchNews/index.ts
  packages/plugins/src/duckduckgo/searchVideo/index.ts
  packages/plugins/src/mathExprVal/index.ts
  packages/service/common/file/read/utils.ts
  packages/service/common/string/tiktoken/index.ts
  packages/service/common/system/log.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/type.d.ts
  packages/service/worker/countGptMessagesTokens/cl100k_base.json
  packages/service/worker/countGptMessagesTokens/index.ts
  packages/service/worker/readFile/extension/csv.ts
  packages/service/worker/readFile/extension/docx.ts
  packages/service/worker/readFile/extension/html.ts
  packages/service/worker/readFile/extension/pdf.ts
  packages/service/worker/readFile/extension/pptx.ts
  packages/service/worker/readFile/extension/rawText.ts
  packages/service/worker/readFile/extension/xlsx.ts
  packages/service/worker/readFile/index.ts
  packages/service/worker/readFile/parseOffice.ts
  packages/service/worker/readFile/type.d.ts
  packages/service/worker/utils.ts
  packages/web/components/common/Icon/icons/core/chat/chevronUp.svg
  pnpm-lock.yaml
  projects/app/next.config.js
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ResponseTags.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/ChatTest.tsx
Labels: size/XL

#2118 purge old permission
  packages/global/support/user/team/constant.ts
  packages/service/support/permission/app/auth.ts
  packages/service/support/permission/auth/common.ts
  packages/service/support/permission/auth/file.ts
  packages/service/support/permission/auth/openapi.ts
  packages/service/support/permission/dataset/auth.ts
  packages/service/support/permission/publish/authLink.ts
  packages/service/support/permission/type.d.ts
  packages/service/support/permission/type/auth.d.ts
  packages/service/support/permission/user/auth.ts
  packages/service/support/user/team/teamMemberSchema.ts
  projects/app/src/pages/api/core/chat/delHistory.ts
  projects/app/src/pages/api/core/chat/feedback/adminUpdate.ts
  projects/app/src/pages/api/core/chat/feedback/closeCustom.ts
  projects/app/src/pages/api/core/chat/feedback/updateUserFeedback.ts
  projects/app/src/pages/api/core/chat/item/delete.ts
  projects/app/src/pages/api/core/chat/updateHistory.ts
  projects/app/src/pages/api/support/openapi/delete.ts
  projects/app/src/pages/api/support/openapi/update.ts
  projects/app/src/service/support/permission/auth/chat.ts
Labels: size/L

#2135 perf: variable label picker scroll & focus disappear
  packages/global/core/workflow/utils.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  packages/web/components/common/Textarea/PromptEditor/Editor.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/VariableLabelPickerPlugin/index.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/VariableLabelPlugin/utils.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Provider.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariableInput.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/pages/app/detail/components/useChatTest.tsx
  projects/app/src/pages/app/list/index.tsx
Labels: size/M

#2131 perf: switch perf
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/chat/chevronSelector.svg
  packages/web/components/common/Icon/icons/core/chat/sideLine.svg
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/common.json
  projects/app/src/pages/chat/components/ChatHeader.tsx
  projects/app/src/pages/chat/components/ChatHistorySlider.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/team.tsx
Labels: size/XL

#2142 fix: variable dynamic refresh & space match
  packages/web/components/common/Textarea/PromptEditor/Editor.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/VariableLabelPickerPlugin/index.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/VariableLabelPlugin/index.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/VariableLabelPlugin/utils.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Textarea.tsx
Labels: size/M

#2097 添加插件：Doc2X 图片/文档识别
  packages/plugins/register.ts
  packages/plugins/src/Doc2X/URLImg2text/index.ts
  packages/plugins/src/Doc2X/URLImg2text/template.json
  packages/plugins/src/Doc2X/URLPDF2text/index.ts
  packages/plugins/src/Doc2X/URLPDF2text/template.json
  packages/plugins/src/Doc2X/template.json
Labels: size/XXL

#2146 fix: change variable matching with any content
  packages/web/components/common/Textarea/PromptEditor/plugins/VariableLabelPlugin/utils.ts
  packages/web/components/common/Textarea/PromptEditor/plugins/VariablePlugin/utils.ts
Labels: size/L

#2134 refactor openapikey and outlink apis
  packages/global/common/error/code/openapi.ts
  packages/global/support/permission/type.d.ts
  packages/service/support/permission/auth/openapi.ts
  projects/app/src/pages/api/core/dataset/folder/create.ts
  projects/app/src/pages/api/support/openapi/create.ts
  projects/app/src/pages/api/support/openapi/delete.ts
  projects/app/src/pages/api/support/openapi/list.ts
  projects/app/src/pages/api/support/openapi/update.ts
  projects/app/src/pages/api/support/outLink/create.ts
  projects/app/src/pages/api/support/outLink/delete.ts
  projects/app/src/pages/api/support/outLink/list.ts
  projects/app/src/pages/api/support/outLink/update.ts
Labels: size/XL

#2143 4.8.8 test fix
  .prettierignore
  .vscode/settings.json
  docSite/content/zh-cn/docs/development/upgrading/488.md
  packages/global/package.json
  packages/plugins/register.ts
  packages/plugins/src/Doc2X/URLImg2text/template.json
  packages/plugins/src/Doc2X/URLPDF2text/template.json
  packages/plugins/src/Doc2X/template.json
  packages/service/core/ai/audio/transcriptions.ts
  packages/service/core/ai/config.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/package.json
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/info.svg
  packages/web/components/common/Icon/icons/core/chat/chevronSelector.svg
  packages/web/components/common/Icon/icons/plugins/doc2x.svg
  packages/web/components/common/Tabs/LightRowTabs.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/VariableLabelPickerPlugin/index.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/VariableLabelPlugin/components/VariableLabel.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/workflow.json
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/src/components/common/Textarea/MyTextarea/VariableTip.tsx
  projects/app/src/components/core/app/DatasetParamsModal.tsx
  projects/app/src/components/core/app/VariableEdit.tsx
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/pages/api/v1/audio/transcriptions.ts
  projects/app/src/pages/app/detail/components/SimpleApp/EditForm.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeHttp/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/Label.tsx
  projects/app/src/pages/chat/components/ChatHeader.tsx
  projects/app/src/pages/chat/components/ChatHistorySlider.tsx
  projects/app/src/pages/chat/components/ToolMenu.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/pages/login/index.tsx
  projects/app/src/web/core/app/templates.ts
  projects/sandbox/package.json
  projects/sandbox/src/sandbox/jsFn/delay.ts
  projects/sandbox/src/sandbox/jsFn/tiktoken/index.ts
  projects/sandbox/src/sandbox/sandbox.controller.ts
  projects/sandbox/src/sandbox/sandbox.service.ts
  projects/sandbox/src/sandbox/utils.ts
  projects/sandbox/src/worker/runJs.ts
  projects/sandbox/src/worker/utils.ts
Labels: size/XXL

#2158 fix: outlink manage can delete/update others
  packages/service/support/permission/auth/openapi.ts
  packages/service/support/permission/publish/authLink.ts
  packages/service/support/user/team/teamMemberSchema.ts
  projects/app/src/pages/api/support/openapi/delete.ts
Labels: size/M

#2159 enable importing httpPlugin via http request
  projects/app/src/pages/app/list/components/HttpPluginEditModal.tsx
Labels: size/XS

#2151 dataset inheritance permission
  packages/global/common/error/code/dataset.ts
  packages/global/core/dataset/api.d.ts
  packages/global/core/dataset/type.d.ts
  packages/service/core/dataset/schema.ts
  packages/service/support/permission/dataset/auth.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/common.json
  projects/app/src/components/core/dataset/DatasetTypeTag.tsx
  projects/app/src/global/core/dataset/api.d.ts
  projects/app/src/pages/api/core/dataset/create.ts
  projects/app/src/pages/api/core/dataset/list.ts
  projects/app/src/pages/api/core/dataset/resumeInheritPermission.ts
  projects/app/src/pages/api/core/dataset/update.ts
  projects/app/src/pages/dataset/list/component/CreateModal.tsx
  projects/app/src/pages/dataset/list/component/List.tsx
  projects/app/src/pages/dataset/list/context.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/web/core/dataset/api.ts
  projects/app/src/web/core/dataset/constants.ts
  projects/app/src/web/core/dataset/store/dataset.ts
Labels: size/XL

#2166 fix: editor focus & picker highlight & ui
  packages/web/components/common/Textarea/PromptEditor/Editor.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/VariableLabelPickerPlugin/index.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/VariableLabelPlugin/index.tsx
Labels: size/M

#2169 fix: app get readable team plugin error
  projects/app/src/pages/api/core/app/plugin/getPreviewNode.ts
Labels: size/XS

#2171 fix: plugin input default value & validate
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderInput.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/renderPluginInput.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/components/ToolSelectModal.tsx
Labels: size/L

#2172 Add img extension
  .vscode/settings.json
  docSite/content/zh-cn/docs/development/upgrading/488.md
  packages/service/common/file/gridfs/controller.ts
  packages/service/common/file/image/controller.ts
  packages/service/common/file/read/utils.ts
  packages/service/common/mongo/init.ts
  packages/service/core/chat/chatSchema.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/logLight.svg
  projects/app/src/pages/api/common/file/previewContent.ts
  projects/app/src/pages/api/system/img/[id].ts
Labels: size/M

#2174 Add mongo forward read. Fix markdown code block.
  packages/service/common/file/image/controller.ts
  packages/service/common/mongo/utils.ts
  pnpm-lock.yaml
  projects/app/src/components/Markdown/CodeLight.tsx
  projects/app/src/components/Markdown/index.module.scss
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/pages/api/core/app/getChatLogs.ts
  projects/app/src/pages/api/core/dataset/exportAll.ts
  projects/app/src/pages/api/core/dataset/training/getDatasetTrainingQueue.ts
  projects/app/src/pages/api/core/dataset/training/getQueueLen.ts
Labels: size/L

#2185 fix: app type
  projects/app/src/pages/chat/components/ChatHeader.tsx
Labels: size/XS

#2187 perf: markdown code css
  packages/plugins/src/duckduckgo/search/index.ts
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/pages/api/proApi/[...path].ts
Labels: size/S

#2188 feat: 4.8.8 doc
  docSite/content/zh-cn/docs/development/upgrading/488.md
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
Labels: size/S

#2190 fix: plugin revert
  projects/app/src/pages/api/core/app/version/revert.ts
Labels: size/XS

#2195 docs: add subtitle translation example
  docSite/assets/imgs/ai-translate-1.png
  docSite/assets/imgs/ai-translate-2.png
  docSite/assets/imgs/ai-translate-3.png
  docSite/assets/imgs/combine-subtitle.png
  docSite/assets/imgs/cut-text.png
  docSite/assets/imgs/extract-subtitle.png
  docSite/assets/imgs/format-original-text.png
  docSite/assets/imgs/gpt-translate-example.png
  docSite/assets/imgs/loop-execution.png
  docSite/content/zh-cn/docs/workflow/examples/dalle3.md
  docSite/content/zh-cn/docs/workflow/examples/feishu_webhook.md
  docSite/content/zh-cn/docs/workflow/examples/fixingEvidence.md
  docSite/content/zh-cn/docs/workflow/examples/google_search.md
  docSite/content/zh-cn/docs/workflow/examples/lab_appointment.md
  docSite/content/zh-cn/docs/workflow/examples/translate-subtitle-using-gpt.md
Labels: size/XXL

#2191 perf: dataset upload process render
  projects/app/src/pages/dataset/detail/components/Import/components/FileSelector.tsx
  projects/app/src/pages/dataset/detail/components/Import/diffSource/FileLocal.tsx
Labels: size/XS

#2197 Update README.md
  README.md
Labels: size/XS

#2192 perf: 运行详情弹窗优化
  projects/app/public/imgs/modal/wholeRecord.svg
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderResponseDetail.tsx
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/chat/components/ChatHeader.tsx
  projects/app/src/pages/chat/components/CustomPluginRunBox.tsx
Labels: size/L

#2203 style: Optimize detail popup style
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
Labels: size/S

#2210 fix: dataset params default error
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SelectDatasetParams.tsx
Labels: size/XS

#2211 feat: collection metadata filter
  packages/service/common/vectorStore/controller.d.ts
  packages/service/common/vectorStore/milvus/class.ts
  packages/service/common/vectorStore/pg/class.ts
  packages/service/core/dataset/collection/schema.ts
  packages/service/core/dataset/search/controller.ts
Labels: size/L

#2199 fix: the helm release failed due to version handle
  .github/workflows/helm-release.yaml
  bin/fastgpt-v1.0.0-helm.tgz
Labels: size/XS

#2222 fix: oneapi image
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
Labels: size/XS

#2221 Fix Switch state inconsistency for Scheduled Trigger
  projects/app/src/components/core/app/ScheduledTriggerConfig.tsx
Labels: size/XS

#2226 fix: add check for reset
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderInput.tsx
Labels: size/S

#2227 perf: remove unuse code
  packages/web/components/common/Input/HttpInput/index.tsx
  packages/web/components/common/Textarea/PromptEditor/Editor.tsx
  packages/web/components/common/Textarea/PromptEditor/index.tsx
  pnpm-lock.yaml
  projects/app/src/components/core/app/WelcomeTextConfig.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/pages/app/detail/components/Plugin/Header.tsx
  projects/app/src/pages/app/detail/components/Plugin/index.tsx
  projects/app/src/pages/app/detail/components/Workflow/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/ChatTest.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeHttp/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
  projects/app/src/pages/app/detail/components/useChatTest.tsx
  projects/app/src/pages/app/detail/index.tsx
Labels: size/L

#2228 fix: response modal
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
Labels: size/L

#2230 yml version
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
Labels: size/S
