Repository labring/FastGPT, pull requests merged in 2024-06, with the labels that each got.

#1648 4.8.3 test and fix
  docSite/content/zh-cn/docs/development/upgrading/483.md
  packages/global/common/error/code/plugin.ts
  packages/global/common/error/code/system.ts
  packages/global/common/error/errorCode.ts
  packages/global/common/error/utils.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/template/system/sandbox/index.ts
  packages/global/core/workflow/type/io.d.ts
  packages/service/common/mongo/sessionRun.ts
  packages/service/common/vectorStore/milvus/class.ts
  packages/service/core/workflow/dispatch/code/run.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/service/support/permission/teamLimit.ts
  packages/web/components/common/MySelect/MultipleRowSelect.tsx
  packages/web/styles/theme.ts
  projects/app/i18n/en/workflow.json
  projects/app/i18n/zh/common.json
  projects/app/i18n/zh/workflow.json
  projects/app/src/components/ChatBox/Input/ChatInput.tsx
  projects/app/src/components/ChatBox/Input/InputGuideBox.tsx
  projects/app/src/components/ChatBox/Provider.tsx
  projects/app/src/components/ChatBox/components/WholeResponseModal.tsx
  projects/app/src/components/common/NextHead/index.tsx
  projects/app/src/components/core/workflow/Flow/hooks/useDebug.tsx
  projects/app/src/components/core/workflow/Flow/nodes/render/RenderInput/templates/Reference.tsx
  projects/app/src/components/core/workflow/Flow/nodes/render/RenderOutput/index.tsx
  projects/app/src/pages/api/core/app/questionGuides/import.ts
  projects/app/src/pages/api/core/chat/inputGuide/query.ts
  projects/app/src/pages/app/detail/components/SimpleEdit/EditForm.tsx
  projects/app/src/pages/chat/components/ChatHeader.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/dataset/detail/components/Import/commonProgress/DataProcess.tsx
  projects/app/src/pages/dataset/list/component/CreateModal.tsx
  projects/app/src/web/core/app/templates.ts
  projects/app/src/web/core/app/utils.ts
  projects/app/src/web/core/chat/inputGuide/api.ts
  projects/app/src/web/core/workflow/adapt.ts
  projects/app/src/web/core/workflow/api.ts
  projects/sandbox/package.json
  projects/sandbox/src/http-exception.filter.ts
  projects/sandbox/src/sandbox/dto/create-sandbox.dto.ts
  projects/sandbox/src/sandbox/sandbox.controller.ts
  projects/sandbox/src/worker/runJs.ts
Labels: size/XL

#1655 Fix doc
  docSite/content/zh-cn/docs/development/docker.md
  docSite/content/zh-cn/docs/development/upgrading/483.md
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
Labels: size/M

#1650 App Permission
  packages/global/core/app/collaborator.d.ts
  packages/global/core/app/type.d.ts
  packages/global/support/permission/type.d.ts
  packages/service/core/app/schema.ts
  packages/service/support/permission/app/permission.ts
  packages/service/support/permission/app/type.d.ts
  packages/service/support/permission/auth/app.ts
  packages/service/support/permission/resourcePermission/controller.ts
  packages/service/support/permission/resourcePermission/permisson.ts
  packages/service/support/permission/resourcePermission/schema.ts
  packages/service/support/permission/type.d.ts
  packages/web/components/common/Icon/icons/support/permission/collaborator.svg
  pnpm-lock.yaml
  projects/app/public/imgs/modal/edit.svg
  projects/app/src/components/support/permission/IconText/index.tsx
  projects/app/src/components/support/permission/MemberManager/AddMemberModal.tsx
  projects/app/src/components/support/permission/MemberManager/ManageModal.tsx
  projects/app/src/components/support/permission/MemberManager/PermissionSelect.tsx
  projects/app/src/components/support/permission/MemberManager/PermissionTags.tsx
  projects/app/src/components/support/permission/MemberManager/index.tsx
  projects/app/src/global/core/app/api.d.ts
  projects/app/src/pages/api/core/app/detail.ts
  projects/app/src/pages/api/core/app/list.ts
  projects/app/src/pages/api/core/app/update.ts
  projects/app/src/pages/app/detail/components/InfoModal.tsx
  projects/app/src/pages/app/detail/components/SimpleEdit/AppCard.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/web/core/app/collaborator.ts
  projects/app/src/web/core/app/constants.ts
Labels: size/XXL

#1748 perf: vector generate
  projects/app/src/pages/api/core/dataset/training/rebuildEmbedding.ts
  projects/app/src/service/events/generateVector.ts
Labels: size/L

#1754 fix: system plugin run time error
  docSite/content/zh-cn/docs/development/upgrading/484.md
  packages/service/core/plugin/controller.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  packages/service/package.json
  pnpm-lock.yaml
Labels: size/S

#1759 feat: chat slider support folder
  docSite/content/zh-cn/docs/development/upgrading/484.md
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/select.svg
  packages/web/components/common/MyMenu/index.tsx
  packages/web/components/common/MyPopover/index.tsx
  projects/app/i18n/en/common.json
  projects/app/i18n/zh/common.json
  projects/app/public/docs/versionIntro.md
  projects/app/src/components/Avatar/index.tsx
  projects/app/src/components/common/folder/SelectOneResource.tsx
  projects/app/src/pages/api/core/app/list.ts
  projects/app/src/pages/chat/components/ChatHistorySlider.tsx
  projects/app/src/pages/chat/components/SliderApps.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/web/core/app/store/useAppStore.ts
  projects/sandbox/src/main.ts
Labels: size/L

#1764 fix: simple bot dataset load error
  projects/app/src/components/core/app/DatasetSelectModal.tsx
  projects/app/src/pages/app/detail/components/SimpleEdit/EditForm.tsx
  projects/app/src/pages/dataset/list/index.tsx
Labels: size/S

#1791 doc: update wechat
  docSite/assets/imgs/wechat6.png
  docSite/content/zh-cn/docs/use-cases/wechat.md
  docSite/content/zh-cn/docs/workflow/intro.md
Labels: size/S

#1800 Fixed a typo in license
  LICENSE
Labels: size/XS

#1805 4.8.5 test
  .vscode/settings.json
  docSite/content/zh-cn/docs/development/upgrading/485.md
  package.json
  packages/global/common/string/textSplitter.ts
  packages/global/core/dataset/type.d.ts
  packages/global/package.json
  packages/plugins/package.json
  packages/service/common/file/gridfs/controller.ts
  packages/service/common/file/gridfs/utils.ts
  packages/service/package.json
  packages/web/components/common/MyMenu/index.tsx
  packages/web/components/common/MyPopover/PopoverConfirm.tsx
  packages/web/i18n/en/app.json
  packages/web/i18n/en/chat.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/en/file.json
  packages/web/i18n/en/publish.json
  packages/web/i18n/en/user.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/chat.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/dataset.json
  packages/web/i18n/zh/file.json
  packages/web/i18n/zh/publish.json
  packages/web/i18n/zh/user.json
  packages/web/i18n/zh/workflow.json
  pnpm-lock.yaml
  projects/app/next-i18next.config.js
  projects/app/package.json
  projects/app/public/docs/versionIntro.md
  projects/app/src/pages/api/common/file/read.ts
  projects/app/src/pages/api/core/app/copy.ts
  projects/app/src/pages/api/core/app/update.ts
  projects/app/src/pages/api/core/chat/delHistory.ts
  projects/app/src/pages/api/core/chat/initLocalShareHistoryV464.ts
  projects/app/src/pages/api/core/chat/item/delete.ts
  projects/app/src/pages/api/core/chat/updateHistory.ts
  projects/app/src/pages/app/detail/components/PublishHistoriesSlider.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/AppCard.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Header.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/index.tsx
  projects/app/src/pages/app/detail/components/Workflow/Header.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
  projects/app/src/pages/app/detail/components/context.tsx
  projects/app/src/pages/app/list/components/List.tsx
  projects/app/src/pages/chat/components/ChatHistorySlider.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/pages/dataset/detail/components/Import/components/FileSelector.tsx
  projects/app/src/service/core/dataset/data/controller.ts
  projects/app/src/service/support/permission/auth/chat.ts
  projects/app/src/types/i18n.d.ts
  projects/app/src/web/common/file/api.ts
  projects/app/src/web/core/app/api/app.ts
  projects/sandbox/package.json
Labels: size/XXL

#1819 4.8.5 test
  .github/workflows/build-sandbox-image.yml
  .github/workflows/fastgpt-image.yml
  docSite/content/zh-cn/docs/development/faq.md
  docSite/content/zh-cn/docs/development/upgrading/485.md
  packages/global/core/dataset/utils.ts
  packages/web/components/common/Tabs/FillRowTabs.tsx
  packages/web/components/common/Tabs/LightRowTabs.tsx
  packages/web/styles/theme.ts
  projects/app/src/components/ChatBox/Input/ChatInput.tsx
  projects/app/src/components/ChatBox/components/WholeResponseModal.tsx
  projects/app/src/components/ChatBox/index.tsx
  projects/app/src/components/Layout/navbar.tsx
  projects/app/src/components/Layout/navbarPhone.tsx
  projects/app/src/components/SideTabs/index.tsx
  projects/app/src/components/common/folder/SelectOneResource.tsx
  projects/app/src/components/core/app/DatasetParamsModal.tsx
  projects/app/src/components/support/user/team/TeamManageModal/TeamCard.tsx
  projects/app/src/global/core/chat/api.d.ts
  projects/app/src/pages/account/index.tsx
  projects/app/src/pages/api/core/chat/updateHistory.ts
  projects/app/src/pages/app/detail/components/SimpleApp/components/ToolSelectModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeHttp/index.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/pages/chat/components/ChatHeader.tsx
  projects/app/src/pages/chat/components/ChatHistorySlider.tsx
  projects/app/src/pages/chat/components/SliderApps.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/pages/dataset/detail/components/InputDataModal.tsx
  projects/app/src/pages/dataset/detail/components/Slider.tsx
  projects/app/src/pages/login/fastlogin.tsx
  projects/app/src/pages/login/index.tsx
  projects/app/src/pages/login/provider.tsx
  projects/app/src/web/core/chat/api.ts
  projects/app/src/web/core/chat/context/chatContext.tsx
  projects/app/src/web/core/chat/context/storeChat.ts
  projects/app/src/web/core/chat/storeChat.ts
  projects/app/src/web/core/chat/storeShareChat.ts
Labels: size/XXL

#1825 4.8.5 test
  .vscode/settings.json
  docSite/content/zh-cn/docs/development/configuration.md
  packages/global/common/string/tools.ts
  packages/web/components/common/MyMenu/index.tsx
  projects/app/public/imgs/model/deepseek.svg
  projects/app/public/imgs/model/minimax.svg
  projects/app/src/components/common/folder/SlideCard.tsx
  projects/app/src/components/support/permission/MemberManager/AddMemberModal.tsx
  projects/app/src/components/support/permission/MemberManager/context.tsx
  projects/app/src/pages/dataset/list/component/List.tsx
Labels: size/L

#1820 Dataset frontend style adjusting
  package.json
  packages/global/core/dataset/api.d.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/common.json
  pnpm-lock.yaml
  projects/app/src/pages/api/core/dataset/list.ts
  projects/app/src/pages/dataset/detail/index.tsx
  projects/app/src/pages/dataset/list/component/List.tsx
  projects/app/src/pages/dataset/list/context.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/web/core/dataset/api.ts
Labels: size/XXL

#1833 Dataset frontend adjusting (again
  projects/app/src/pages/api/core/dataset/list.ts
  projects/app/src/pages/dataset/list/component/List.tsx
  projects/app/src/pages/dataset/list/context.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/web/core/dataset/api.ts
Labels: size/XL

#1827 i18n: update Chinese (zh) localization strings
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/chat.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/dataset.json
  packages/web/i18n/zh/file.json
  packages/web/i18n/zh/publish.json
  packages/web/i18n/zh/workflow.json
Labels: size/L

#1838 feat: app template;fix: chat test reset
  docSite/content/zh-cn/docs/development/upgrading/485.md
  docSite/content/zh-cn/docs/workflow/examples/dalle3.md
  docSite/content/zh-cn/docs/workflow/examples/feishu_webhook.md
  packages/service/core/workflow/dispatch/code/run.ts
  projects/app/public/imgs/app/templates/dalle.svg
  projects/app/public/imgs/app/templates/feishu.svg
  projects/app/public/imgs/app/templates/google.svg
  projects/app/public/imgs/app/templates/translate.svg
  projects/app/src/components/ChatBox/components/WholeResponseModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/ChatTest.tsx
  projects/app/src/web/core/app/templates.ts
Labels: size/XXL

#1845 4.8.5 perf app ui
  packages/service/common/vectorStore/pg/index.ts
  packages/service/support/permission/controller.ts
  packages/web/components/common/Icon/icons/core/app/type/simple.svg
  pnpm-lock.yaml
  projects/app/src/components/Layout/index.tsx
  projects/app/src/components/Layout/navbar.tsx
  projects/app/src/components/support/permission/IconText/index.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/AppCard.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/ChatTest.tsx
  projects/app/src/pages/app/list/components/List.tsx
  projects/app/src/pages/app/list/components/TypeTag.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/pages/login/index.tsx
  projects/app/src/pages/login/provider.tsx
  projects/app/src/web/styles/default.scss
Labels: size/XXL

#1853 fix error toast
  projects/app/src/pages/app/list/components/List.tsx
Labels: size/XS

#1854 4.8.5 perf
  docSite/content/zh-cn/docs/development/upgrading/485.md
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
  packages/web/i18n/zh/common.json
  projects/app/src/components/common/folder/SelectOneResource.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/AppCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useKeyboard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useUtils.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/app/list/components/List.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/pages/chat/components/ChatHistorySlider.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/L

#1857 添加移动端手势放大图片的功能
  projects/app/src/components/Markdown/img/Image.tsx
Labels: size/L

#1862 4.8.5 test fix
  docSite/content/zh-cn/docs/development/upgrading/485.md
  packages/service/common/middle/entry.ts
  packages/service/common/mongo/index.ts
  packages/service/common/mongo/init.ts
  packages/web/components/common/Icon/icons/core/chat/fileSelect.svg
  packages/web/components/common/Image/PhotoView.tsx
  packages/web/i18n/zh/common.json
  packages/web/package.json
  pnpm-lock.yaml
  projects/app/public/imgs/app/avatar/httpPlugin.svg
  projects/app/public/imgs/app/avatar/plugin.svg
  projects/app/public/imgs/app/avatar/simple.svg
  projects/app/public/imgs/app/avatar/workflow.svg
  projects/app/src/components/Markdown/img/Image.tsx
  projects/app/src/components/core/app/InputGuideConfig.tsx
  projects/app/src/components/support/permission/IconText/index.tsx
  projects/app/src/pages/api/core/dataset/collection/create/csvTable.ts
  projects/app/src/pages/app/detail/components/SimpleApp/AppCard.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Edit.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/EditForm.tsx
  projects/app/src/pages/app/detail/components/Workflow/Header.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/SelectAppModal.tsx
  projects/app/src/pages/app/list/components/CreateModal.tsx
  projects/app/src/pages/app/list/components/List.tsx
  projects/app/src/pages/chat/components/ChatHistorySlider.tsx
  projects/app/src/pages/chat/components/SliderApps.tsx
  projects/app/src/pages/login/components/RegisterForm.tsx
  projects/app/src/service/mongo.ts
  projects/app/src/web/core/app/templates.ts
  projects/app/src/web/core/app/utils.ts
  projects/app/src/web/core/dataset/store/dataset.ts
Labels: size/XXL

#1869 4.8.5 test
  docSite/content/zh-cn/docs/development/upgrading/485.md
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
Labels: size/M

#1883 Dataset collection forbid
  .github/ISSUE_TEMPLATE/config.yml
  README.md
  docSite/content/zh-cn/docs/development/upgrading/484.md
  docSite/content/zh-cn/docs/development/upgrading/485.md
  docSite/content/zh-cn/docs/development/upgrading/486.md
  packages/global/core/dataset/collection/utils.ts
  packages/global/core/dataset/type.d.ts
  packages/service/common/vectorStore/controller.d.ts
  packages/service/common/vectorStore/milvus/class.ts
  packages/service/common/vectorStore/pg/class.ts
  packages/service/core/dataset/collection/schema.ts
  packages/service/core/dataset/data/schema.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/web/components/common/Tag/index.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/dataset.json
  projects/app/src/components/CommunityModal/index.tsx
  projects/app/src/components/common/folder/useFolderDrag.tsx
  projects/app/src/global/core/api/datasetReq.d.ts
  projects/app/src/global/core/dataset/api.d.ts
  projects/app/src/global/core/dataset/type.d.ts
  projects/app/src/pages/account/components/Info.tsx
  projects/app/src/pages/api/core/dataset/collection/list.ts
  projects/app/src/pages/api/core/dataset/collection/update.ts
  projects/app/src/pages/api/core/dataset/data/list.ts
  projects/app/src/pages/api/core/dataset/data/update.ts
  projects/app/src/pages/app/list/components/List.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/index.tsx
  projects/app/src/pages/dataset/detail/components/DataCard.tsx
  projects/app/src/pages/dataset/detail/components/InputDataModal.tsx
  projects/app/src/service/core/dataset/data/controller.ts
  projects/app/src/web/common/hooks/useDrag.tsx
  projects/app/src/web/common/hooks/useEditTitle.tsx
  projects/app/src/web/core/dataset/api.ts
Labels: size/XXL

#1885 Dataset collection forbid
  docSite/content/zh-cn/docs/development/upgrading/486.md
  packages/global/core/dataset/collection/utils.ts
  packages/global/core/dataset/type.d.ts
  packages/service/common/vectorStore/controller.d.ts
  packages/service/common/vectorStore/milvus/class.ts
  packages/service/common/vectorStore/pg/class.ts
  packages/service/core/dataset/collection/schema.ts
  packages/service/core/dataset/data/schema.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/web/components/common/Tag/index.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/dataset.json
  projects/app/src/components/CommunityModal/index.tsx
  projects/app/src/components/common/folder/useFolderDrag.tsx
  projects/app/src/global/core/api/datasetReq.d.ts
  projects/app/src/global/core/dataset/api.d.ts
  projects/app/src/global/core/dataset/type.d.ts
  projects/app/src/pages/account/components/Info.tsx
  projects/app/src/pages/api/core/dataset/collection/list.ts
  projects/app/src/pages/api/core/dataset/collection/update.ts
  projects/app/src/pages/api/core/dataset/data/list.ts
  projects/app/src/pages/api/core/dataset/data/update.ts
  projects/app/src/pages/app/list/components/List.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/index.tsx
  projects/app/src/pages/dataset/detail/components/DataCard.tsx
  projects/app/src/pages/dataset/detail/components/InputDataModal.tsx
  projects/app/src/service/core/dataset/data/controller.ts
  projects/app/src/web/common/hooks/useDrag.tsx
  projects/app/src/web/common/hooks/useEditTitle.tsx
  projects/app/src/web/core/dataset/api.ts
Labels: size/XXL
