Repository labring/FastGPT, pull requests merged in 2024-02, with the labels that each got.

#807 Add IPv6 support for hostnames
  packages/service/support/permission/auth/common.ts
  projects/app/src/service/common/api/request.ts
  projects/app/src/service/moduleDispatch/tools/http.ts
Labels: size/S

#814 change gpt-4-turbo maxResponse configuration template
  docSite/content/docs/development/configuration.md
Labels: size/XS

#853 Fix: pdf version
  docSite/content/docs/development/sealos.md
  packages/service/core/chat/chatItemSchema.ts
  packages/service/core/chat/chatSchema.ts
  packages/service/core/chat/controller.ts
  packages/service/core/dataset/training/schema.ts
  packages/service/support/user/team/teamMemberSchema.ts
  packages/service/support/user/team/teamSchema.ts
  packages/web/package.json
  pnpm-lock.yaml
  projects/app/src/pages/api/core/app/del.ts
  projects/app/src/pages/api/core/chat/clearHistories.ts
  projects/app/src/service/events/generateQA.ts
  projects/app/src/service/events/generateVector.ts
  projects/app/src/service/utils/chat/saveChat.ts
Labels: size/XL

#855 perf: mongo doc
  docSite/content/docs/development/docker.md
  docSite/content/docs/development/upgrading/468.md
Labels: size/XS

#866 docs:Update chatglm2.md and reranker.md the 'requirements' the word error
  docSite/content/docs/development/custom-models/chatglm2.md
  docSite/content/docs/development/custom-models/reranker.md
Labels: size/XS

#898 docs: fix types
  docSite/content/docs/development/faq.md
Labels: size/XS
