Repository labring/FastGPT, pull requests merged in 2024-10, with the labels that each got.

#2849 fix: variables check
  packages/global/core/workflow/utils.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
Labels: size/S

#2850 4.8.11 test
  projects/app/src/components/support/user/team/TeamMenu/index.tsx
  projects/app/src/pages/account/components/InformTable.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/ButtonEdge.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeHttp/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeVariableUpdate.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Textarea.tsx
Labels: size/L

#2833 docs: add FAQ
  docSite/content/zh-cn/docs/FAQ.md
Labels: size/M

#2856 Optimize base64 storage in files to support concurrent storage
  docSite/content/zh-cn/docs/FAQ.md
  docSite/content/zh-cn/docs/commercial/_index.md
  docSite/content/zh-cn/docs/commercial/saas.md
  docSite/content/zh-cn/docs/faq/_index.md
  docSite/content/zh-cn/docs/faq/app.md
  docSite/content/zh-cn/docs/faq/chat.md
  docSite/content/zh-cn/docs/faq/dataset.md
  docSite/content/zh-cn/docs/faq/docker.md
  docSite/content/zh-cn/docs/faq/error.md
  docSite/content/zh-cn/docs/faq/other.md
  docSite/content/zh-cn/docs/faq/privateDeploy.md
  packages/global/common/fn/utils.ts
  packages/global/common/string/markdown.ts
  packages/service/common/file/image/schema.ts
  packages/service/common/file/multer.ts
  packages/service/worker/htmlStr2Md/utils.ts
  projects/app/src/pages/api/core/dataset/collection/create/localFile.ts
  projects/app/src/service/core/app/plugin.ts
  projects/app/src/service/mongo.ts
Labels: size/L

#2860 pref: trim the input of outlink
  projects/app/src/pages/app/detail/components/Publish/FeiShu/FeiShuEditModal.tsx
  projects/app/src/pages/app/detail/components/Publish/OffiAccount/OffiAccountEditModal.tsx
Labels: size/M

#2858 fix: customize flow remove change
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/FlowController.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/index.tsx
Labels: size/M

#2865 Perf: delete app tip; fix: can't stop debug.
  README.md
  docSite/content/zh-cn/docs/development/upgrading/4810.md
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/workflow.json
  projects/app/package.json
  projects/app/public/docs/versionIntro.md
  projects/app/src/components/support/apikey/Table.tsx
  projects/app/src/pages/account/index.tsx
  projects/app/src/pages/api/admin/initv4811.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/app/detail/components/context.tsx
  projects/app/src/pages/app/list/components/List.tsx
  projects/app/src/pages/dataset/list/index.tsx
Labels: size/L

#2868 fix: form-data not display in http node log
  packages/service/core/workflow/dispatch/tools/http468.ts
Labels: size/S

#2870 IOS safari whisper support
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  packages/service/core/workflow/dispatch/tools/http468.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/Handle/ToolHandle.tsx
  projects/app/src/web/common/hooks/useSpeech.ts
Labels: size/M

#2871 4.8.11 test
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  docSite/content/zh-cn/docs/development/upgrading/4812.md
Labels: size/M

#2872 action
  .github/workflows/docs-deploy-kubeconfig.yml
  .github/workflows/docs-deploy-vercel.yml
  .github/workflows/preview-fastgpt-image.yml
Labels: size/XS

#2873 fix: o1 model cannot run in simpleApp
  projects/app/src/web/core/app/utils.ts
Labels: size/XS

#2874 update o1 config
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
  projects/app/data/config.json
Labels: size/M

#2875 Update README.md
  README.md
Labels: size/XS

#2876 fix: file extension check
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  docSite/content/zh-cn/docs/development/upgrading/4812.md
  packages/global/common/string/tools.ts
  packages/service/common/file/gridfs/controller.ts
  packages/service/core/dataset/read.ts
  packages/service/core/workflow/dispatch/tools/readFiles.ts
Labels: size/M

#2879 fix: workflow delete error
  projects/app/src/pages/api/core/chat/getPaginationRecords.ts
  projects/app/src/pages/api/core/chat/init.ts
  projects/app/src/pages/api/core/chat/outLink/init.ts
  projects/app/src/pages/api/core/chat/team/init.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/index.tsx
  projects/app/src/service/support/permission/auth/chat.ts
Labels: size/L

#2880 Update 469.md
  docSite/content/zh-cn/docs/development/upgrading/469.md
Labels: size/XS

#2882 fix:fastgpt-sandbox image version
  files/docker/docker-compose-pgvector.yml
Labels: size/XS

#2887 fix: not delete edges when deleting non-deletable nodes
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
Labels: size/S

#2863 perf: optimize global variables
  packages/global/core/app/type.d.ts
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/utils.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/drag.svg
  packages/web/i18n/en/common.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/workflow.json
  projects/app/src/components/core/app/VariableEdit.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariableInput.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useDebug.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/Loop/NodeLoopStart.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeFormInput/InputFormEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/VariableTable.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
Labels: size/XXL

#2893 change app template default author
  projects/app/public/appMarketTemplates/CQ/template.json
  projects/app/public/appMarketTemplates/TranslateRobot/template.json
  projects/app/public/appMarketTemplates/chatGuide/template.json
  projects/app/public/appMarketTemplates/flux/template.json
  projects/app/public/appMarketTemplates/google/template.json
  projects/app/public/appMarketTemplates/plugin-dalle/template.json
  projects/app/public/appMarketTemplates/plugin-feishu/template.json
  projects/app/public/appMarketTemplates/simpleDatasetChat/template.json
  projects/app/public/appMarketTemplates/srt-translate/template.json
  projects/app/public/appMarketTemplates/timeBot/template.json
  projects/app/src/pages/app/detail/components/SimpleApp/components/ToolSelectModal.tsx
  projects/app/src/pages/app/list/components/CreateModal.tsx
  projects/app/src/pages/app/list/components/TemplateMarketModal.tsx
Labels: size/S

#2890 fix: resource permission indexes
  packages/service/support/permission/controller.ts
  packages/service/support/permission/schema.ts
Labels: size/M

#2886 plugins: add wiki search
  packages/plugins/package.json
  packages/plugins/register.ts
  packages/plugins/src/wiki/index.ts
  packages/plugins/src/wiki/template.json
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/workflow/template/wiki.svg
  pnpm-lock.yaml
Labels: size/XL

#2891 feat: http node url support variables
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeHttp/index.tsx
Labels: size/M

#2892 fix: global variables
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/utils.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/workflow.json
  projects/app/src/components/core/app/VariableEdit.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariableInput.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useDebug.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeFormInput/InputFormEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
Labels: size/L

#2907 Updated readme english
  .github/imgs/image.png
  README_en.md
Labels: size/L

#2908 feat: add app chat openapi
  docSite/content/zh-cn/docs/development/openapi/chat.md
  docSite/content/zh-cn/docs/development/openapi/dataset.md
  projects/app/src/pages/api/core/ai/agent/createQuestionGuide.ts
  projects/app/src/pages/api/core/chat/clearHistories.ts
  projects/app/src/pages/api/core/chat/delHistory.ts
  projects/app/src/pages/api/core/chat/getHistories.ts
  projects/app/src/pages/api/core/chat/getPaginationRecords.ts
  projects/app/src/pages/api/core/chat/init.ts
  projects/app/src/pages/api/core/chat/item/delete.ts
  projects/app/src/pages/api/core/chat/updateHistory.ts
Labels: size/XL

#2910 Doc
  README.md
  docSite/content/zh-cn/docs/development/configuration.md
  docSite/content/zh-cn/docs/development/openapi/chat.md
  docSite/content/zh-cn/docs/development/openapi/dataset.md
  packages/global/core/chat/api.d.ts
  packages/global/core/chat/type.d.ts
  packages/service/core/chat/controller.ts
  packages/service/core/workflow/dispatch/tools/customFeedback.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/FeedbackModal.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/SelectMarkCollection.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/global/core/chat/api.d.ts
  projects/app/src/pages/api/core/ai/agent/createQuestionGuide.ts
  projects/app/src/pages/api/core/chat/clearHistories.ts
  projects/app/src/pages/api/core/chat/delHistory.ts
  projects/app/src/pages/api/core/chat/feedback/adminUpdate.ts
  projects/app/src/pages/api/core/chat/feedback/closeCustom.ts
  projects/app/src/pages/api/core/chat/feedback/updateUserFeedback.ts
  projects/app/src/pages/api/core/chat/getHistories.ts
  projects/app/src/pages/api/core/chat/getPaginationRecords.ts
  projects/app/src/pages/api/core/chat/getResData.ts
  projects/app/src/pages/api/core/chat/init.ts
  projects/app/src/pages/api/core/chat/item/delete.ts
  projects/app/src/pages/api/core/chat/item/getSpeech.ts
  projects/app/src/pages/api/core/chat/updateHistory.ts
  projects/app/src/pages/api/plugins/customFeedback/index.ts
  projects/app/src/pages/api/plugins/customFeedback/v2/index.ts
  projects/app/src/web/core/dataset/store/markdata.ts
Labels: size/XL

#2914 update feishu-img
  .github/ISSUE_TEMPLATE/config.yml
  README.md
Labels: size/XS

#2916 Doc
  docSite/assets/images/social/lark.svg
  docSite/content/zh-cn/docs/community.md
  docSite/content/zh-cn/docs/development/intro.md
  docSite/hugo.toml
  docSite/layouts/docs/baseof.html
  docSite/layouts/partials/docs/top-header.html
  projects/app/public/docs/chatProblem.md
  projects/app/src/service/common/system/index.ts
Labels: size/S

#2913 feat: remove style tag when fetching url
  packages/service/common/string/cheerio.ts
Labels: size/XS

#2903 Tool call support interactive node
  docSite/content/zh-cn/docs/development/upgrading/4812.md
  packages/global/common/string/markdown.ts
  packages/global/core/ai/type.d.ts
  packages/global/core/chat/adapt.ts
  packages/global/core/chat/type.d.ts
  packages/global/core/chat/utils.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/global/core/workflow/template/system/interactive/formInput.ts
  packages/global/core/workflow/template/system/interactive/type.d.ts
  packages/global/core/workflow/template/system/interactive/userSelect.ts
  packages/service/core/chat/saveChat.ts
  packages/service/core/chat/utils.ts
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/agent/runTool/type.d.ts
  packages/service/core/workflow/dispatch/agent/runTool/utils.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/interactive/formInput.ts
  packages/service/core/workflow/dispatch/interactive/userSelect.ts
  packages/service/core/workflow/dispatch/type.d.ts
  packages/web/i18n/zh/chat.json
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/ChatContainer/type.d.ts
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/pages/api/core/chat/chatTest.ts
Labels: size/XXL

#2923 perf: variable replace rang
  packages/global/common/string/tools.ts
  packages/global/core/workflow/utils.ts
Labels: size/S

#2927 fix: add dataset tags not update render
  projects/app/src/pages/dataset/detail/components/CollectionCard/TagManageModal.tsx
Labels: size/XS

#2926 fix: global var default value & wrap variable form
  projects/app/src/components/core/app/VariableEdit.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariableInput.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useDebug.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
Labels: size/M

#2930 feat: add AI Icon Svg Logo
  docSite/content/zh-cn/docs/development/configuration.md
  projects/app/public/imgs/model/doubao.svg
Labels: size/S

#2931 fix: quote settings default value & zindex & i18n
  packages/web/components/common/Textarea/PromptEditor/plugins/VariableLabelPickerPlugin/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/ButtonEdge.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SettingQuotePrompt.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/utils.tsx
Labels: size/S

#2933 fix: variable label i18n & create question guide language
  packages/service/core/ai/functions/createQuestionGuide.ts
  packages/web/components/common/Textarea/PromptEditor/plugins/VariableLabelPlugin/index.tsx
Labels: size/S

#2898 feat: app/dataset support group
  packages/global/core/app/collaborator.d.ts
  packages/global/core/app/type.d.ts
  packages/global/core/dataset/collaborator.d.ts
  packages/global/core/dataset/type.d.ts
  packages/global/support/permission/collaborator.d.ts
  packages/global/support/permission/constant.ts
  packages/global/support/permission/type.d.ts
  packages/service/core/app/schema.ts
  packages/service/core/dataset/schema.ts
  packages/service/support/permission/app/auth.ts
  packages/service/support/permission/controller.ts
  packages/service/support/permission/dataset/auth.ts
  packages/service/support/permission/inheritPermission.ts
  packages/service/support/permission/memberGroup/controllers.ts
  packages/service/support/permission/type.d.ts
  packages/service/support/permission/user/auth.ts
  packages/web/i18n/zh/common.json
  pnpm-lock.yaml
  projects/app/jest.config.js
  projects/app/package.json
  projects/app/src/components/common/folder/SlideCard.tsx
  projects/app/src/components/support/permission/ConfigPerModal/index.tsx
  projects/app/src/components/support/permission/IconText/index.tsx
  projects/app/src/components/support/permission/MemberManager/AddMemberModal.tsx
  projects/app/src/components/support/permission/MemberManager/ManageModal.tsx
  projects/app/src/components/support/permission/MemberManager/MemberListCard.tsx
  projects/app/src/components/support/permission/MemberManager/context.tsx
  projects/app/src/components/support/user/team/TeamManageModal/components/SelectMember.tsx
  projects/app/src/global/core/app/api.d.ts
  projects/app/src/pages/api/__mocks__/base.ts
  projects/app/src/pages/api/__mocks__/db/init.ts
  projects/app/src/pages/api/__mocks__/type.d.ts
  projects/app/src/pages/api/core/app/folder/create.ts
  projects/app/src/pages/api/core/app/list.ts
  projects/app/src/pages/api/core/app/update.ts
  projects/app/src/pages/api/core/dataset/allDataset.ts
  projects/app/src/pages/api/core/dataset/folder/create.ts
  projects/app/src/pages/api/core/dataset/list.ts
  projects/app/src/pages/api/core/dataset/update.ts
  projects/app/src/pages/api/support/outLink/update.test.ts
  projects/app/src/pages/app/detail/components/InfoModal.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/AppCard.tsx
  projects/app/src/pages/app/detail/components/context.tsx
  projects/app/src/pages/app/list/components/List.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/pages/dataset/detail/components/Info.tsx
  projects/app/src/pages/dataset/list/component/List.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/test/utils.ts
  projects/app/src/web/core/app/constants.ts
  projects/app/src/web/core/dataset/api/collaborator.ts
  projects/app/src/web/core/dataset/constants.ts
  projects/app/src/web/support/user/useUserStore.ts
Labels: size/XXL

#2948 在“发布成功”通知中，显示关闭按钮
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/SaveAndPublish.tsx
Labels: size/XS

#2936 4.8.12 test
  docSite/content/zh-cn/docs/development/upgrading/4812.md
  packages/plugins/src/drawing/template.json
  packages/service/core/workflow/dispatch/agent/extract.ts
  packages/web/components/common/Textarea/PromptEditor/Editor.tsx
  projects/app/data/config.json
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SettingQuotePrompt.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/utils.tsx
  projects/app/src/pages/login/index.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/L

#2953 chore: adjust toast top distance
  packages/web/hooks/useToast.ts
  projects/app/src/pages/app/detail/components/Workflow/components/SaveButton.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/SaveAndPublish.tsx
Labels: size/S

#2958 新增数据源配置：可以直接执行sql,支持MySQL，PG数据库
  packages/plugins/package.json
  packages/plugins/register.ts
  packages/plugins/src/databaseConnection/index.ts
  packages/plugins/src/databaseConnection/template.json
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/workflow/template/datasource.svg
Labels: size/XL

#2947 add google search plugin
  packages/plugins/register.ts
  packages/plugins/src/google/template.json
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/workflow/template/google.svg
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useDebug.tsx
Labels: size/XL

#2951 typofix:laf函数调用时，弹出文字错误
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderOutput/FieldEditModal.tsx
Labels: size/XS

#2950 perf: all plugin variables type support referense & replace input and textarea with prompt editor
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/node/constant.ts
  packages/global/core/workflow/utils.ts
  packages/web/components/core/workflow/NodeInputSelect.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/workflow.json
  projects/app/src/components/core/app/VariableEdit.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariableInput.tsx
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useDebug.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeFormInput/InputFormEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/TextInput.tsx
Labels: size/L

#2963 Concat textinput to input type
  docSite/content/zh-cn/docs/development/upgrading/4812.md
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/node/constant.ts
  packages/global/core/workflow/utils.ts
  packages/plugins/src/databaseConnection/index.ts
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/web/components/core/workflow/NodeInputSelect.tsx
  projects/app/src/components/core/app/VariableEdit.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariableInput.tsx
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/pages/app/detail/components/Workflow/components/SaveButton.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/SaveAndPublish.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeFormInput/InputFormEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/TextInput.tsx
Labels: size/L

#2965 System plugin adapt reference type in plugin input
  packages/plugins/src/databaseConnection/template.json
  packages/plugins/src/drawing/baseChart/template.json
  packages/plugins/src/duckduckgo/search/template.json
  packages/plugins/src/duckduckgo/searchImg/template.json
  packages/plugins/src/duckduckgo/searchNews/template.json
  packages/plugins/src/duckduckgo/searchVideo/template.json
  packages/plugins/src/duckduckgo/template.json
  packages/plugins/src/google/template.json
  packages/plugins/src/wiki/template.json
  packages/web/components/common/Textarea/PromptEditor/Editor.tsx
  packages/web/components/common/Textarea/PromptEditor/index.module.scss
  packages/web/components/common/Textarea/PromptEditor/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/TextInput.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Textarea.tsx
Labels: size/L

#2967 perf:textarea auto height
  packages/web/components/common/Textarea/PromptEditor/Editor.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/VariableLabelPlugin/components/VariableLabel.tsx
  projects/app/package.json
  projects/app/src/components/common/Textarea/MyTextarea/index.tsx
  projects/app/src/components/core/app/DatasetParamsModal.tsx
  projects/app/src/components/core/app/WelcomeTextConfig.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariableInput.tsx
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useDebug.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/NodePluginConfig.tsx
Labels: size/L

#2968 fix: milvus
  packages/service/common/vectorStore/milvus/class.ts
Labels: size/S

#2969 HTTP support jsonPath; System plugin support save file.
  docSite/content/zh-cn/docs/development/docker.md
  docSite/content/zh-cn/docs/development/upgrading/4812.md
  docSite/content/zh-cn/docs/workflow/modules/http.md
  packages/global/core/workflow/template/system/http468.ts
  packages/plugins/package.json
  packages/plugins/src/drawing/baseChart/index.ts
  packages/plugins/src/drawing/baseChart/template.json
  packages/plugins/type.d.ts
  packages/plugins/utils.ts
  packages/service/common/string/tiktoken/index.ts
  packages/service/common/vectorStore/milvus/class.ts
  packages/service/core/chat/utils.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  packages/service/package.json
  packages/web/hooks/useI18n.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/workflow.json
  pnpm-lock.yaml
  projects/app/data/config.json
  projects/app/src/components/common/Textarea/MyTextarea/index.tsx
  projects/app/src/components/core/app/DatasetParamsModal.tsx
  projects/app/src/components/core/app/VariableEdit.tsx
  projects/app/src/components/core/app/WelcomeTextConfig.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariableInput.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useDebug.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderOutput/FieldEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderOutput/index.tsx
  projects/app/src/pages/app/detail/components/context.tsx
Labels: size/XL

#2952 Pref: app move
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/dataset.json
  projects/app/src/components/common/folder/MoveModal.tsx
  projects/app/src/pages/api/core/app/update.ts
  projects/app/src/pages/api/core/dataset/update.ts
  projects/app/src/pages/app/list/components/List.tsx
  projects/app/src/pages/app/list/components/context.tsx
  projects/app/src/pages/dataset/list/component/List.tsx
  projects/app/src/pages/dataset/list/component/MoveModal.tsx
  projects/app/src/pages/dataset/list/context.tsx
Labels: size/L

#2956 feat: QPS Limit middleware
  packages/global/common/error/errorCode.ts
  packages/service/common/middle/qpsLimit.ts
  packages/service/common/system/frequencyLimit/schema.ts
  packages/service/common/system/frequencyLimit/type.d.ts
  packages/service/common/system/frequencyLimit/utils.ts
  packages/service/package.json
  packages/web/i18n/zh/common.json
  pnpm-lock.yaml
Labels: size/L

#2981 fix: http raw response undefined
  packages/service/core/workflow/dispatch/tools/http468.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/utils.tsx
Labels: size/S

#2988 4.8.12 test fix
  packages/global/common/error/errorCode.ts
  packages/plugins/src/bing/template.json
  packages/service/common/middle/entry.ts
  packages/service/common/middle/qpsLimit.ts
  packages/service/common/middle/reqFrequencyLimit.ts
  packages/service/common/system/frequencyLimit/schema.ts
  packages/service/common/system/frequencyLimit/utils.ts
  packages/service/core/workflow/dispatch/loop/runLoop.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  projects/app/.env.template
  projects/app/src/components/core/app/ScheduledTriggerConfig.tsx
  projects/app/src/pages/api/core/dataset/searchTest.ts
  projects/app/src/web/common/system/doc.ts
  projects/app/src/web/core/workflow/utils.ts
Labels: size/L

#2993 Group role
  docSite/content/zh-cn/docs/development/upgrading/4812.md
  packages/global/core/app/collaborator.d.ts
  packages/global/core/app/type.d.ts
  packages/global/core/dataset/collaborator.d.ts
  packages/global/core/dataset/type.d.ts
  packages/global/support/permission/collaborator.d.ts
  packages/global/support/permission/constant.ts
  packages/global/support/permission/type.d.ts
  packages/service/core/app/schema.ts
  packages/service/core/dataset/schema.ts
  packages/service/support/permission/app/auth.ts
  packages/service/support/permission/controller.ts
  packages/service/support/permission/dataset/auth.ts
  packages/service/support/permission/inheritPermission.ts
  packages/service/support/permission/memberGroup/controllers.ts
  packages/service/support/permission/type.d.ts
  packages/service/support/permission/user/auth.ts
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/dataset.json
  pnpm-lock.yaml
  projects/app/jest.config.js
  projects/app/package.json
  projects/app/src/components/common/folder/MoveModal.tsx
  projects/app/src/components/common/folder/SlideCard.tsx
  projects/app/src/components/support/permission/ConfigPerModal/index.tsx
  projects/app/src/components/support/permission/IconText/index.tsx
  projects/app/src/components/support/permission/MemberManager/AddMemberModal.tsx
  projects/app/src/components/support/permission/MemberManager/ManageModal.tsx
  projects/app/src/components/support/permission/MemberManager/MemberListCard.tsx
  projects/app/src/components/support/permission/MemberManager/context.tsx
  projects/app/src/components/support/user/team/TeamManageModal/components/SelectMember.tsx
  projects/app/src/global/core/app/api.d.ts
  projects/app/src/pages/api/__mocks__/base.ts
  projects/app/src/pages/api/__mocks__/db/init.ts
  projects/app/src/pages/api/__mocks__/type.d.ts
  projects/app/src/pages/api/core/app/folder/create.ts
  projects/app/src/pages/api/core/app/list.ts
  projects/app/src/pages/api/core/app/update.ts
  projects/app/src/pages/api/core/dataset/allDataset.ts
  projects/app/src/pages/api/core/dataset/folder/create.ts
  projects/app/src/pages/api/core/dataset/list.ts
  projects/app/src/pages/api/core/dataset/update.ts
  projects/app/src/pages/api/support/outLink/update.test.ts
  projects/app/src/pages/app/detail/components/InfoModal.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/AppCard.tsx
  projects/app/src/pages/app/detail/components/context.tsx
  projects/app/src/pages/app/list/components/List.tsx
  projects/app/src/pages/app/list/components/context.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/pages/dataset/detail/components/Info.tsx
  projects/app/src/pages/dataset/list/component/List.tsx
  projects/app/src/pages/dataset/list/component/MoveModal.tsx
  projects/app/src/pages/dataset/list/context.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/test/utils.ts
  projects/app/src/web/core/app/constants.ts
  projects/app/src/web/core/dataset/api/collaborator.ts
  projects/app/src/web/core/dataset/constants.ts
  projects/app/src/web/support/user/useUserStore.ts
Labels: size/XXL

#2994 4.8.12 test
  docSite/content/zh-cn/docs/development/upgrading/4812.md
  packages/global/core/workflow/template/system/variableUpdate/index.tsx
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/loop/runLoop.ts
  packages/service/core/workflow/dispatch/plugin/run.ts
  packages/service/core/workflow/dispatch/plugin/runApp.ts
  projects/app/.env.template
  projects/app/package.json
  projects/app/src/components/common/folder/MoveModal.tsx
  projects/app/src/pages/app/detail/components/Workflow/Header.tsx
Labels: size/L

#2995 Add RAG documentation and images
  docSite/assets/imgs/RAG1.png
  docSite/assets/imgs/RAG2.png
  docSite/assets/imgs/RAG3.png
  docSite/content/zh-cn/docs/course/RAG.md
Labels: size/L

#2996 Update chat.md
  docSite/content/zh-cn/docs/development/openapi/chat.md
Labels: size/XS

#3002 fix: optimize tool node check in workflow
  projects/app/src/web/core/workflow/utils.ts
Labels: size/S

#3004 fix: milvus
  packages/service/common/vectorStore/milvus/class.ts
Labels: size/S

#2992 fix: upload file
  packages/service/common/file/gridfs/controller.ts
  packages/service/common/file/read/utils.ts
  packages/service/worker/htmlStr2Md/utils.ts
  packages/service/worker/readFile/extension/docx.ts
  packages/service/worker/readFile/extension/html.ts
  packages/service/worker/readFile/type.d.ts
  pnpm-lock.yaml
  projects/app/src/pages/api/core/dataset/collection/create/fileId.ts
Labels: size/XL

#3012 fix/group
  packages/service/support/permission/app/auth.ts
  packages/service/support/permission/dataset/auth.ts
  projects/app/src/pages/api/core/app/list.ts
  projects/app/src/pages/api/core/dataset/list.ts
Labels: size/M

#3011 app list open-api & completion with appid & get history source
  docSite/content/zh-cn/docs/development/openapi/chat.md
  projects/app/src/global/core/chat/api.d.ts
  projects/app/src/pages/api/core/app/list.ts
  projects/app/src/pages/api/core/chat/getHistories.ts
  projects/app/src/pages/api/v1/chat/completions.ts
Labels: size/S

#3013 feat: reset milvus
  docSite/content/zh-cn/docs/development/upgrading/4812.md
  packages/service/core/dataset/training/schema.ts
  pnpm-lock.yaml
  projects/app/src/pages/api/admin/resetMilvus.ts
  projects/app/src/pages/api/core/dataset/collection/scrollList.ts
  projects/app/src/pages/api/core/dataset/training/rebuildEmbedding.ts
  projects/app/src/service/events/generateVector.ts
Labels: size/L

#3015 perf: dataset data auth
  packages/global/core/dataset/type.d.ts
  packages/service/support/permission/dataset/auth.ts
  projects/app/src/pages/api/core/dataset/data/update.ts
Labels: size/M

#3020 update text splitter
  docSite/content/zh-cn/docs/development/upgrading/4812.md
  packages/global/common/string/textSplitter.ts
  packages/service/common/string/utils.ts
  packages/service/package.json
  packages/service/worker/utils.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/common.json
  pnpm-lock.yaml
  projects/app/src/pages/api/admin/resetMilvus.ts
  projects/app/src/pages/api/core/dataset/file/getPreviewChunks.ts
  projects/app/src/web/common/hooks/useSpeech.ts
  projects/sandbox/package.json
Labels: size/L

#3021 fix/group
  projects/app/src/pages/api/core/app/list.ts
  projects/app/src/pages/api/core/dataset/list.ts
Labels: size/M

#3023 perf: app list permission
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/common.json
  projects/app/src/pages/api/core/app/list.ts
  projects/app/src/pages/api/core/dataset/list.ts
  projects/app/src/pages/dataset/list/index.tsx
Labels: size/S

#3026 4.8.12 test
  projects/app/src/pages/dataset/list/index.tsx
Labels: size/XS

#3016 feat: add baidu conversion tracking
  projects/app/src/pages/login/components/RegisterForm.tsx
  projects/app/src/web/context/useInitApp.ts
  projects/app/src/web/support/user/api.ts
Labels: size/S

#3030 add more market template
  projects/app/public/appMarketTemplates/Chinese/avatar.svg
  projects/app/public/appMarketTemplates/Chinese/template.json
  projects/app/public/appMarketTemplates/animalLife/avatar.svg
  projects/app/public/appMarketTemplates/animalLife/template.json
  projects/app/public/appMarketTemplates/divination/avatar.svg
  projects/app/public/appMarketTemplates/divination/template.json
  projects/app/public/appMarketTemplates/githubIssue/avatar.svg
  projects/app/public/appMarketTemplates/githubIssue/template.json
  projects/app/public/appMarketTemplates/longTranslate/template.json
  projects/app/public/appMarketTemplates/stock/avatar.svg
  projects/app/public/appMarketTemplates/stock/template.json
Labels: size/XXL

#3031 fix: allDataset
  projects/app/src/pages/api/core/dataset/allDataset.ts
Labels: size/M

#3028 add goole tag manager
  docSite/layouts/docs/baseof.html
Labels: size/S

#3033 fix: only owner or team owner can change app's owner
  projects/app/src/pages/app/list/components/List.tsx
Labels: size/S

#3032 fix: dataset select cannot refresh
  projects/app/src/pages/api/core/app/list.ts
  projects/app/src/pages/api/core/chat/feedback/updateUserFeedback.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SettingQuotePrompt.tsx
  projects/app/src/pages/dataset/list/component/List.tsx
Labels: size/S

#3036 Update 4812.md
  docSite/content/zh-cn/docs/development/upgrading/4812.md
Labels: size/XS

#3040 Update i18n files and Upload component
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/common.json
  projects/app/src/pages/dataset/detail/components/Import/commonProgress/Upload.tsx
Labels: size/L

#3047 fix: alldataset get dataset without folders. omit the permission check
  projects/app/src/pages/api/core/dataset/allDataset.ts
Labels: size/M

#3048 fix: dataset select check
  projects/app/src/components/core/app/DatasetSelectModal.tsx
Labels: size/S
