Repository labring/FastGPT, pull requests merged in 2024-03, with the labels that each got.

#903 Update http468.ts
  projects/app/src/service/moduleDispatch/tools/http468.ts
Labels: size/S

#921 Global variables support external variable; Extract module support default value
  docSite/content/docs/agreement/privacy.md
  docSite/content/docs/development/openapi/share.md
  docSite/content/docs/development/upgrading/469.md
  packages/global/core/module/constants.ts
  packages/global/core/module/template/system/contextExtract.ts
  packages/global/core/module/type.d.ts
  packages/service/common/vectorStore/pg/index.ts
  packages/web/components/common/CustomModal/index.tsx
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/app/variable/external.svg
  packages/web/components/common/Textarea/PromptEditor/index.tsx
  packages/web/styles/theme.ts
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/public/docs/versionIntro.md
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/components/ChatBox/index.tsx
  projects/app/src/components/MyModal/index.tsx
  projects/app/src/components/core/module/Flow/FlowProvider.tsx
  projects/app/src/components/core/module/Flow/components/modules/VariableEdit.tsx
  projects/app/src/components/core/module/Flow/components/nodes/NodeExtract/ExtractFieldModal.tsx
  projects/app/src/components/core/module/Flow/components/nodes/NodeExtract/index.tsx
  projects/app/src/global/core/prompt/agent.ts
  projects/app/src/pages/_app.tsx
  projects/app/src/pages/app/detail/components/SimpleEdit/EditForm.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/login/components/RegisterForm.tsx
  projects/app/src/pages/login/index.tsx
  projects/app/src/service/moduleDispatch/agent/extract.ts
Labels: size/XL

#936 reranker.md优化docker启动命令，并增加docker-compose.yml示例
  docSite/content/docs/development/custom-models/reranker.md
Labels: size/S

#950 fix: 知识库QA生成，答案中有“Q”会导致提前截断。
  projects/app/src/service/events/generateQA.ts
Labels: size/XS

#968 Docs: update workflow for building docs image
  .github/workflows/docs-image.yml
Labels: size/L

#970 move components to web package (#37)
  docSite/content/docs/development/upgrading/469.md
Labels: size/XS

#977 Docs: fix HomePage
  docSite/hugo.toml
Labels: size/XS

#992 docs: Fixed misspelled key "usedInToolCall"
  docSite/content/docs/development/configuration.md
  docSite/content/docs/development/one-api.md
  projects/app/data/config.json
Labels: size/S

#994 docs: Fixed misspelled word "v"
  docSite/content/docs/development/docker.md
Labels: size/XS

#1000 Update ai_settings.md
  docSite/content/docs/use-cases/ai_settings.md
Labels: size/XS

#1012 Fix history in classifyQuestion and extract modules
  projects/app/src/service/moduleDispatch/agent/classifyQuestion.ts
  projects/app/src/service/moduleDispatch/agent/extract.ts
Labels: size/S

#1043 优化建议模式；修复多索引训练失败问题
  .github/ISSUE_TEMPLATE/config.yml
  packages/service/core/dataset/training/controller.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/pages/account/components/Info.tsx
  projects/app/src/pages/account/components/InformTable.tsx
  projects/app/src/pages/app/detail/components/SimpleEdit/ToolSelectModal.tsx
  projects/app/src/service/core/dataset/data/controller.ts
  projects/app/src/web/core/app/utils.ts
Labels: size/L

#1040 fix: claude3 image type verification failed (#1038)
  packages/service/common/file/utils.ts
  projects/app/src/pages/api/system/img/[id].ts
Labels: size/S

#1023 feat: support to install fastgpt via helm chart
  .github/workflows/helm-release.yaml
  .github/workflows/preview-image.yml
  .gitignore
  files/helm/fastgpt/.helmignore
  files/helm/fastgpt/Chart.lock
  files/helm/fastgpt/Chart.yaml
  files/helm/fastgpt/templates/NOTES.txt
  files/helm/fastgpt/templates/_helpers.tpl
  files/helm/fastgpt/templates/configmap-config.yaml
  files/helm/fastgpt/templates/deployment.yaml
  files/helm/fastgpt/templates/hpa.yaml
  files/helm/fastgpt/templates/ingress.yaml
  files/helm/fastgpt/templates/secret-env.yaml
  files/helm/fastgpt/templates/service.yaml
  files/helm/fastgpt/templates/serviceaccount.yaml
  files/helm/fastgpt/templates/tests/test-connection.yaml
  files/helm/fastgpt/values.yaml
Labels: size/XL

#1075 调整更新文档，不要挂载持久化
  docSite/content/docs/development/upgrading/47.md
  packages/service/common/file/multer.ts
Labels: size/M

#1080 Fix: HTTP组件中文错别字修复
  projects/app/public/locales/zh/common.json
Labels: size/XS

#1082 update reranker source code
  python/reranker/bge-reranker-base/Dockerfile
  python/reranker/bge-reranker-base/README.md
  python/reranker/bge-reranker-base/app.py
  python/reranker/bge-reranker-base/requirements.txt
Labels: size/M

#1083 fix doc images
  docSite/assets/imgs/gapierTool13.webp
  files/deploy/fastgpt/docker-compose.yml
  packages/service/common/file/utils.ts
  packages/service/common/system/constants.ts
  projects/app/src/pages/api/common/file/upload.ts
  projects/app/src/service/common/system/cron.ts
Labels: size/M

#1089 chore: avoid trigger the helm release in main branch
  .github/workflows/helm-release.yaml
Labels: size/XS

#1095 doc: add readme file of the helm chart
  files/helm/fastgpt/Chart.yaml
  files/helm/fastgpt/README.md
  files/helm/fastgpt/values.yaml
Labels: size/M
