Repository labring/FastGPT, pull requests merged in 2024-01, with the labels that each got.

#675 doc
  docSite/content/docs/development/configuration.md
  docSite/content/docs/development/docker.md
  docSite/content/docs/development/intro.md
  packages/service/common/vectorStore/pg/controller.ts
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/pages/components/Ability.tsx
  projects/app/src/pages/components/Choice.tsx
  projects/app/src/pages/components/Footer.tsx
  projects/app/src/pages/components/Hero.tsx
  projects/app/src/pages/components/Navbar.tsx
  projects/app/src/pages/index.tsx
  projects/app/src/pages/login/provider.tsx
Labels: size/XL

#679 add reranker
  python/reranker/bge-reranker-base/Dockerfile
  python/reranker/bge-reranker-base/README.md
  python/reranker/bge-reranker-base/app.py
  python/reranker/bge-reranker-base/requirement.txt
Labels: size/L

#684 fix: init pg error error: CREATE INDEX CONCURRENTLY cannot run inside…
  packages/service/common/vectorStore/pg/controller.ts
Labels: size/XS

#693 修复向量模型无法正常处理字符串的问题
  packages/service/core/ai/embedding/index.ts
Labels: size/XS

#694 Update docs and response tag in share page
  docSite/content/docs/commercial/intro.md
  docSite/content/docs/development/openapi/auth.md
  packages/global/common/file/constants.ts
  packages/global/common/file/read/index.ts
  packages/service/common/file/upload/multer.ts
  packages/service/common/vectorStore/controller.ts
  packages/service/core/ai/embedding/index.ts
  packages/service/core/dataset/training/schema.ts
  packages/web/common/system/utils.ts
  packages/web/package.json
  pnpm-lock.yaml
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/components/ChatBox/ResponseTags.tsx
  projects/app/src/components/core/dataset/QuoteItem.tsx
  projects/app/src/global/core/dataset/type.d.ts
  projects/app/src/pages/api/core/dataset/data/list.ts
  projects/app/src/pages/api/v1/embeddings.ts
  projects/app/src/pages/app/detail/components/OutLink/Share.tsx
  projects/app/src/pages/dataset/detail/components/DataCard.tsx
  projects/app/src/service/core/dataset/data/controller.ts
  projects/app/src/service/events/generateVector.ts
  projects/app/src/utils/service/core/chat/index.ts
Labels: size/L

#696 docs: update font and cdn
  .github/workflows/deploy-docs.yml
  .imgbotconfig
  docSite/assets/docs/scss/custom/pages/_custom.scss
  docSite/assets/imgs/functional-arch.webp
  docSite/assets/imgs/sealos-fastgpt.webp
  docSite/hugo.toml
  docSite/layouts/partials/docs/footer/footer-scripts.html
  docSite/layouts/partials/docs/head.html
  docSite/static/js/jsdelivr-auto-fallback.js
Labels: size/L

#698 docs: update cdn link
  .github/sync_imgs.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/deploy-preview.yml
  .github/workflows/sync_imgs.yml
  docSite/assets/imgs/sealos_price.jpg
  docSite/content/docs/commercial/intro.md
  docSite/content/docs/course/websync.md
  docSite/layouts/docs/_markup/render-image.html
  docSite/layouts/partials/docs/footer/footer-scripts.html
  docSite/layouts/partials/docs/head.html
  docSite/static/js/jsdelivr-auto-fallback.js
Labels: size/M

#699 Update workflow deploy-docs-preview
  .github/workflows/deploy-preview.yml
Labels: size/XS

#697 Commercial baseurl
  README.md
  docSite/assets/imgs/KBProcess.jpg
  docSite/assets/imgs/chatmodels1.png
  docSite/assets/imgs/data_search1.png
  docSite/assets/imgs/onsealos10.png
  docSite/assets/imgs/onsealos12.png
  docSite/assets/imgs/onsealosl11.PNG
  docSite/assets/imgs/sealos13.png
  docSite/content/docs/development/configuration.md
  docSite/content/docs/development/docker.md
  docSite/content/docs/development/openapi/dataset.md
  docSite/content/docs/development/openapi/share.md
  docSite/content/docs/development/sealos.md
  docSite/content/docs/development/upgrading/45.md
  docSite/content/docs/development/upgrading/466.md
  docSite/content/docs/development/upgrading/intro.md
  docSite/content/docs/use-cases/ai_settings.md
  docSite/content/docs/use-cases/datasetEngine.md
  docSite/content/docs/workflow/examples/lab_appointment.md
  docSite/content/docs/workflow/examples/versatile_assistant.md
  packages/global/common/system/types/index.d.ts
  packages/global/support/user/inform/constants.ts
  packages/global/support/user/inform/type.d.ts
  packages/service/common/api/plusRequest.ts
  packages/service/common/string/markdown.ts
  packages/service/common/system/config/controller.ts
  packages/service/common/system/constants.ts
  packages/service/support/outLink/tools.ts
  projects/app/.env.template
  projects/app/data/config.json
  projects/app/src/components/ChatBox/ResponseTags.tsx
  projects/app/src/pages/api/admin/initv46.ts
  projects/app/src/pages/api/common/system/getInitData.ts
  projects/app/src/pages/api/common/system/refreshConfig.ts
  projects/app/src/pages/api/core/dataset/data/pushData.ts
  projects/app/src/pages/api/core/plugin/templates.ts
  projects/app/src/pages/api/plusApi/[...path].ts
  projects/app/src/service/core/app/utils.ts
  projects/app/src/service/core/dataset/utils.ts
  projects/app/src/service/events/generateQA.ts
  projects/app/src/service/moduleDispatch/chat/oneapi.ts
  projects/app/src/service/support/permission/auth/bill.ts
  projects/app/src/service/support/user/inform/api.ts
  projects/app/src/service/support/wallet/bill/controller.ts
Labels: size/L

#700 docs: optimize css style
  docSite/assets/docs/scss/custom/pages/_custom.scss
  docSite/content/docs/community.md
  docSite/content/docs/development/docker.md
  docSite/content/docs/development/intro.md
  docSite/content/docs/development/one-api.md
  docSite/content/docs/development/sealos.md
  docSite/layouts/docs/_markup/render-image.html
  docSite/layouts/partials/docs/footer/footer-scripts.html
  docSite/layouts/partials/docs/head.html
  docSite/static/js/jsdelivr-auto-fallback.js
Labels: size/M

#717 Update rearanker code url. Add chat storage ip address
  docSite/content/docs/development/custom-models/reranker.md
  packages/global/core/chat/type.d.ts
  packages/service/core/chat/chatSchema.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/service/utils/chat/saveChat.ts
Labels: size/M

#711 Ignore .idea directory
  .gitignore
Labels: size/XS

#719 Improve the i18n configuration of the chat page
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/pages/chat/components/ChatHeader.tsx
  projects/app/src/pages/chat/components/ChatHistorySlider.tsx
  projects/app/src/pages/chat/components/ToolMenu.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
Labels: size/M

#745 Update data_search.md
  docSite/content/docs/course/data_search.md
Labels: size/XS

#752 4.6.7 fix
  docSite/content/docs/development/docker.md
  docSite/content/docs/development/qa.md
  packages/global/common/file/icon.ts
  packages/global/common/string/markdown.ts
  packages/global/core/dataset/api.d.ts
  packages/global/core/dataset/controller.d.ts
  packages/service/common/file/image/controller.ts
  packages/service/common/file/image/schema.ts
  packages/service/common/file/multer.ts
  packages/service/common/vectorStore/pg/controller.ts
  packages/service/core/chat/chatItemSchema.ts
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/training/controller.ts
  packages/service/support/wallet/bill/schema.ts
  packages/web/common/file/read/csv.ts
  packages/web/common/file/read/index.ts
  packages/web/components/common/Textarea/JsonEditor/index.tsx
  packages/web/package.json
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/public/locales/zh/common.json
  projects/app/src/components/core/module/Flow/components/modules/ButtonEdge.tsx
  projects/app/src/global/core/api/datasetRes.d.ts
  projects/app/src/global/core/dataset/api.d.ts
  projects/app/src/pages/api/core/dataset/collection/create/text.ts
  projects/app/src/pages/api/core/dataset/data/pushData.ts
  projects/app/src/pages/api/plusApi/[...path].ts
  projects/app/src/pages/dataset/detail/components/Import/diffSource/FileLocal.tsx
  projects/app/src/pages/dataset/detail/components/Import/diffSource/TableLocal.tsx
  projects/app/src/pages/dataset/detail/components/InputDataModal.tsx
  projects/app/src/pages/dataset/detail/components/Test.tsx
  projects/app/src/service/common/system/cron.ts
  projects/app/src/service/core/dataset/data/controller.ts
  projects/app/src/service/mongo.ts
  projects/app/src/web/common/file/controller.ts
  projects/app/src/web/common/file/utils.ts
  projects/app/src/web/core/dataset/api.ts
Labels: size/XL

#754 bugfix: 修复训练任务过早过期的问题
  packages/service/core/dataset/training/schema.ts
Labels: size/XS

#759 V4.6.7-production
  README.md
  README_en.md
  docSite/content/docs/development/openapi/chat.md
  docSite/content/docs/development/openapi/dataset.md
  docSite/content/docs/development/upgrading/467.md
  packages/global/common/error/utils.ts
  packages/global/common/string/tools.ts
  packages/service/common/file/utils.ts
  packages/service/common/response/index.ts
  packages/service/support/permission/controller.ts
  packages/web/components/common/Icon/icons/support/account/loginoutLight.svg
  projects/app/public/docs/versionIntro.md
  projects/app/public/locales/zh/common.json
  projects/app/src/components/ChatBox/MessageInput.tsx
  projects/app/src/components/ChatBox/index.tsx
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/components/common/Textarea/TagTextarea.tsx
  projects/app/src/components/core/module/AIChatSettingsModal.tsx
  projects/app/src/components/support/user/team/TeamManageModal/InviteModal.tsx
  projects/app/src/components/support/user/team/TeamManageModal/index.tsx
  projects/app/src/pages/account/components/Info.tsx
  projects/app/src/pages/api/core/dataset/collection/create/file.ts
  projects/app/src/pages/api/core/dataset/collection/create/link.ts
  projects/app/src/pages/api/core/dataset/collection/create/text.ts
  projects/app/src/pages/api/core/dataset/create.ts
  projects/app/src/pages/api/core/dataset/delete.ts
  projects/app/src/pages/api/plusApi/[...path].ts
  projects/app/src/pages/api/proApi/[...path].ts
  projects/app/src/pages/dataset/detail/index.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/pages/login/provider.tsx
  projects/app/src/web/common/hooks/useConfirm.tsx
  projects/app/src/web/core/dataset/api.ts
  projects/app/src/web/core/dataset/utils.ts
  projects/app/src/web/support/activity/promotion/api.ts
  projects/app/src/web/support/user/api.ts
  projects/app/src/web/support/user/inform/api.ts
  projects/app/src/web/support/user/team/api.ts
  projects/app/src/web/support/wallet/bill/api.ts
  projects/app/src/web/support/wallet/pay/api.ts
  projects/app/src/web/support/wallet/sub/api.ts
Labels: size/XXL

#768 dataset api
  docSite/content/docs/development/openapi/dataset.md
  projects/app/src/pages/api/core/dataset/collection/create/link.ts
  projects/app/src/pages/api/core/dataset/collection/create/text.ts
  projects/app/src/web/core/dataset/api.ts
Labels: size/L

#785 fix: retry input and whisper
  projects/app/src/components/ChatBox/index.tsx
  projects/app/src/web/common/hooks/useSpeech.ts
Labels: size/M

#797 Fixes: Fix logic error when extraction result is "false".
  projects/app/src/service/moduleDispatch/agent/extract.ts
Labels: size/XS

#786 feat: add localization editor and ide extension
  .vscode/extensions.json
  README.md
  project.inlang/project_id
  project.inlang/settings.json
Labels: size/M

#799 fix: badge points to right repo now
  README.md
Labels: size/XS
