Repository labring/FastGPT, pull requests merged in 2024-05, with the labels that each got.

#1348 Enhance English language support in i18n
  projects/app/i18n/en/common.json
Labels: size/XXL

#1345 fix: leave user will can not login
  packages/service/support/user/controller.ts
Labels: size/XS

#1365 feat: custom feedback plugin
  packages/service/core/workflow/dispatch/index.ts
  projects/app/data/pluginTemplates/customFeedback.json
  projects/app/src/service/support/wallet/usage/push.ts
Labels: size/L

#1362 feat: add update variable node
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/node/constant.ts
  packages/global/core/workflow/runtime/constants.ts
  packages/global/core/workflow/template/constants.ts
  packages/global/core/workflow/template/system/variableUpdate/index.tsx
  packages/global/core/workflow/template/system/variableUpdate/type.d.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/init/systemConfig.tsx
  packages/service/core/workflow/dispatch/init/systemConfiig.tsx
  packages/service/core/workflow/dispatch/tools/runUpdateVar.ts
  packages/service/core/workflow/dispatch/type.d.ts
  packages/service/core/workflow/dispatchV1/type.d.ts
  projects/app/i18n/en/common.json
  projects/app/i18n/zh/common.json
  projects/app/src/components/ChatBox/index.tsx
  projects/app/src/components/core/workflow/Flow/ChatTest.tsx
  projects/app/src/components/core/workflow/Flow/index.tsx
  projects/app/src/components/core/workflow/Flow/nodes/NodeVariableUpdate.tsx
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/service/utils/chat/saveChat.ts
  projects/app/src/web/common/api/fetch.ts
Labels: size/XL

#1367 fix: reference input of updateVariable node
  packages/global/core/workflow/runtime/constants.ts
  packages/global/core/workflow/template/constants.ts
  packages/global/core/workflow/template/system/ifElse/index.ts
  packages/global/core/workflow/template/system/laf.ts
  packages/global/core/workflow/template/system/variableUpdate/index.tsx
  packages/global/core/workflow/template/system/variableUpdate/type.d.ts
  projects/app/src/components/core/workflow/Flow/nodes/NodeVariableUpdate.tsx
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/web/common/api/fetch.ts
Labels: size/M

#1369 fix: add judge to update variable node input
  projects/app/src/components/core/workflow/Flow/nodes/NodeVariableUpdate.tsx
Labels: size/S

#1370 Fix 4.8 node
  packages/global/core/chat/type.d.ts
  packages/global/core/chat/utils.ts
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/global/core/workflow/template/system/assignedAnswer.ts
  packages/global/core/workflow/template/system/pluginInput.ts
  packages/global/core/workflow/template/system/pluginOutput.ts
  packages/global/core/workflow/template/system/variableUpdate/index.tsx
  packages/global/core/workflow/template/system/variableUpdate/type.d.ts
  packages/global/core/workflow/type/index.d.ts
  packages/global/core/workflow/utils.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/init/workflowStart.tsx
  packages/service/core/workflow/dispatch/plugin/run.ts
  packages/service/core/workflow/dispatch/tools/runApp.ts
  packages/service/core/workflow/dispatch/tools/runUpdateVar.ts
  projects/app/data/pluginTemplates/customFeedback.json
  projects/app/data/pluginTemplates/getCurrentTime.json
  projects/app/data/pluginTemplates/textEditor.json
  projects/app/data/pluginTemplates/v1/customFeedback.json
  projects/app/data/pluginTemplates/v1/getCurrentTime.json
  projects/app/data/pluginTemplates/v1/textEditor.json
  projects/app/data/pluginTemplates/v1/tfSwitch.json
  projects/app/i18n/en/common.json
  projects/app/i18n/zh/common.json
  projects/app/src/components/ChatBox/index.tsx
  projects/app/src/components/core/app/VariableEdit.tsx
  projects/app/src/components/core/workflow/Flow/nodes/NodeVariableUpdate.tsx
  projects/app/src/components/core/workflow/Flow/nodes/render/RenderInput/templates/Reference.tsx
  projects/app/src/components/core/workflow/context.tsx
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/core/workflow/debug.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/plugin/list/component/EditModal.tsx
  projects/app/src/service/core/app/utils.ts
  projects/app/src/web/core/workflow/utils.ts
Labels: size/XL

#1376 Ai histories
  .vscode/settings.json
  packages/global/core/workflow/template/system/globalVariable.ts
  packages/global/core/workflow/template/system/tools.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/web/hooks/useBeforeunload.ts
  packages/web/hooks/useEditTextarea.tsx
  projects/app/i18n/en/common.json
  projects/app/i18n/zh/common.json
  projects/app/src/components/core/workflow/Flow/ChatTest.tsx
  projects/app/src/components/core/workflow/Flow/nodes/NodeDatasetConcat.tsx
  projects/app/src/components/core/workflow/Flow/nodes/render/NodeCard.tsx
  projects/app/src/components/core/workflow/context.tsx
  projects/app/src/pages/app/detail/components/FlowEdit/Header.tsx
Labels: size/L

#1378 feat: add elseif to ifelse node
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/template/system/ifElse/index.ts
  packages/global/core/workflow/template/system/ifElse/type.d.ts
  packages/service/core/workflow/dispatch/tools/runIfElse.ts
  pnpm-lock.yaml
  projects/app/i18n/en/common.json
  projects/app/i18n/zh/common.json
  projects/app/package.json
  projects/app/src/components/core/workflow/Flow/nodes/NodeIfElse.tsx
  projects/app/src/components/core/workflow/Flow/nodes/NodeIfElse/ListItem.tsx
  projects/app/src/components/core/workflow/Flow/nodes/NodeIfElse/index.tsx
Labels: size/XXL

#1382 4.8 test
  packages/global/core/workflow/template/system/ifElse/index.ts
  packages/global/core/workflow/type/index.d.ts
  packages/service/core/ai/rerank/index.ts
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/init/workflowStart.tsx
  packages/service/core/workflow/dispatch/tools/http468.ts
  packages/service/core/workflow/dispatch/tools/runIfElse.ts
  packages/web/hooks/useBeforeunload.ts
  pnpm-lock.yaml
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/components/core/workflow/Flow/ChatTest.tsx
  projects/app/src/components/core/workflow/Flow/nodes/NodeIfElse/ListItem.tsx
  projects/app/src/components/core/workflow/Flow/nodes/NodeVariableUpdate.tsx
  projects/app/src/components/core/workflow/Flow/nodes/render/NodeCard.tsx
  projects/app/src/components/core/workflow/context.tsx
  projects/app/src/pages/api/core/workflow/debug.ts
  projects/app/src/pages/app/detail/components/FlowEdit/Header.tsx
  projects/app/src/pages/app/detail/components/SimpleEdit/ChatTest.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/L

#1383 fix: if else node
  packages/global/core/workflow/template/system/ifElse/constant.ts
  packages/global/core/workflow/utils.ts
  packages/service/core/workflow/dispatch/tools/runIfElse.ts
  projects/app/src/components/core/workflow/Flow/nodes/NodeIfElse/ListItem.tsx
  projects/app/src/components/core/workflow/Flow/nodes/NodeIfElse/index.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/L

#1385 4.8 test fix
  docSite/content/docs/development/upgrading/48.md
  packages/global/common/string/tools.ts
  packages/global/core/workflow/template/input.ts
  packages/web/components/common/DndDrag/DragIcon.tsx
  packages/web/components/common/DndDrag/index.tsx
  packages/web/package.json
  pnpm-lock.yaml
  projects/app/i18n/zh/common.json
  projects/app/package.json
  projects/app/src/components/ChatBox/components/VariableInput.tsx
  projects/app/src/components/ChatBox/index.tsx
  projects/app/src/components/core/workflow/Flow/nodes/NodeIfElse/ListItem.tsx
  projects/app/src/components/core/workflow/Flow/nodes/NodeIfElse/index.tsx
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/FlowEdit/index.tsx
  projects/app/src/pages/chat/share.tsx
Labels: size/L

#1387 perf: global variable any type
  docSite/content/docs/development/faq.md
  projects/app/src/web/core/workflow/utils.ts
Labels: size/XS

#1386 4.8 test fix
  packages/service/core/workflow/dispatch/tools/runIfElse.ts
  projects/app/src/components/core/workflow/Flow/nodes/NodeIfElse/ListItem.tsx
  projects/app/src/components/core/workflow/Flow/nodes/NodeLaf.tsx
  projects/app/src/components/support/laf/LafAccountModal.tsx
Labels: size/L

#1393 fix: add pptx encoding try catch
  packages/service/common/buffer/rawText/schema.ts
  packages/service/common/file/gridfs/controller.ts
  packages/service/worker/file/parseOffice.ts
Labels: size/M

#1394 4.8 test
  packages/global/core/app/utils.ts
  packages/global/core/chat/type.d.ts
  packages/global/core/workflow/utils.ts
  packages/service/core/ai/rerank/index.ts
  packages/service/core/chat/chatSchema.ts
  projects/app/src/components/ChatBox/Provider.tsx
  projects/app/src/components/ChatBox/components/VariableInput.tsx
  projects/app/src/components/ChatBox/index.tsx
  projects/app/src/components/core/workflow/Flow/ChatTest.tsx
  projects/app/src/components/core/workflow/Flow/nodes/render/Handle/ToolHandle.tsx
  projects/app/src/components/core/workflow/Flow/nodes/render/Handle/index.tsx
  projects/app/src/pages/api/core/chat/init.ts
  projects/app/src/pages/api/core/chat/outLink/init.ts
  projects/app/src/pages/api/core/chat/team/init.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/FlowEdit/Header.tsx
  projects/app/src/pages/app/detail/components/SimpleEdit/EditForm.tsx
  projects/app/src/pages/app/detail/components/SimpleEdit/index.tsx
  projects/app/src/service/utils/chat/saveChat.ts
  projects/app/src/web/core/workflow/utils.ts
Labels: size/XL

#1397 4.8 test fix
  packages/global/common/error/code/app.ts
  packages/global/common/error/code/openapi.ts
  packages/global/common/error/code/outLink.ts
  packages/global/common/error/code/plugin.ts
  packages/global/core/workflow/template/system/variableUpdate/index.tsx
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  projects/app/data/pluginTemplates/customFeedback.json
  projects/app/src/components/ChatBox/MessageInput.tsx
  projects/app/src/components/core/workflow/context.tsx
  projects/app/src/pages/api/core/chat/init.ts
  projects/app/src/pages/api/core/workflow/debug.ts
  projects/app/src/pages/api/plugins/customFeedback/v2/index.ts
Labels: size/L

#1391 Doc: update doc
  docSite/assets/imgs/aichat.png
  docSite/assets/imgs/aichat02.png
  docSite/assets/imgs/aichat2.png
  docSite/assets/imgs/chatinput.png
  docSite/assets/imgs/coreferenceResolution1.jpg
  docSite/assets/imgs/cq1.png
  docSite/assets/imgs/customfeedback1.jpg
  docSite/assets/imgs/customfeedback2.jpg
  docSite/assets/imgs/customfeedback3.jpg
  docSite/assets/imgs/customfeedback4.jpg
  docSite/assets/imgs/demo-appointment1.webp
  docSite/assets/imgs/demo-appointment2.webp
  docSite/assets/imgs/demo-appointment3.webp
  docSite/assets/imgs/demo-appointment4.webp
  docSite/assets/imgs/demo-appointment5.png
  docSite/assets/imgs/demo-appointment6.jpg
  docSite/assets/imgs/extract1.png
  docSite/assets/imgs/flow-dataset1.png
  docSite/assets/imgs/flow-intro1.png
  docSite/assets/imgs/flow-intro2.png
  docSite/assets/imgs/flow-intro3.png
  docSite/assets/imgs/flow-tool1.png
  docSite/assets/imgs/flow-tool3.png
  docSite/assets/imgs/flow-tool4.png
  docSite/assets/imgs/http1.jpg
  docSite/assets/imgs/judgement1.png
  docSite/assets/imgs/specialreply.png
  docSite/assets/imgs/string.png
  docSite/content/docs/course/quick-start.md
  docSite/content/docs/workflow/intro.md
  docSite/content/docs/workflow/modules/ai_chat.md
  docSite/content/docs/workflow/modules/content_extract.md
  docSite/content/docs/workflow/modules/dataset_search.md
  docSite/content/docs/workflow/modules/http.md
  docSite/content/docs/workflow/modules/input.md
  docSite/content/docs/workflow/modules/reply.md
  docSite/content/docs/workflow/modules/text_editor.md
  docSite/content/docs/workflow/modules/tfswitch.md
  docSite/content/docs/workflow/modules/tool.md
Labels: size/L

#1415 fix: embedding recall drop-dead halt
  packages/service/common/vectorStore/controller.d.ts
  packages/service/common/vectorStore/pg/controller.ts
  packages/service/core/dataset/search/controller.ts
Labels: size/S

#1416 fix: change photo max size
  projects/app/src/components/ChatBox/MessageInput.tsx
Labels: size/XS

#1419 perf: detail=false, not response variable update
  packages/service/core/ai/embedding/index.ts
  projects/app/src/pages/api/v1/chat/completions.ts
Labels: size/S

#1424 4.8-alpha fix
  packages/global/common/string/textSplitter.ts
  packages/service/common/string/tiktoken/index.ts
  packages/service/common/vectorStore/controller.d.ts
  packages/service/common/vectorStore/pg/controller.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/core/workflow/dispatch/agent/classifyQuestion.ts
  packages/service/worker/file/extension/csv.ts
  packages/service/worker/file/extension/xlsx.ts
  packages/service/worker/file/read.ts
  packages/service/worker/htmlStr2Md/index.ts
  packages/service/worker/tiktoken/countGptMessagesTokens.ts
  packages/service/worker/utils.ts
  projects/app/public/docs/versionIntro.md
  projects/app/src/components/ChatBox/MessageInput.tsx
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/pages/api/plugins/textEditor/v2/index.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/dataset/detail/components/Import/diffSource/TableLocal.tsx
  projects/app/src/web/core/dataset/store/searchTest.ts
Labels: size/L

#1428 Change embedding
  files/helm/fastgpt/templates/configmap-config.yaml
  packages/global/common/string/textSplitter.ts
  packages/global/core/ai/model.ts
  packages/service/core/dataset/schema.ts
  projects/app/data/config.json
  projects/app/src/pages/api/core/dataset/file/getPreviewChunks.ts
Labels: size/L

#1426 Create mongodump跨环境迁移数据库.md
  docSite/content/docs/development/mongodump跨环境迁移数据库.md
Labels: size/L

#1430 Update doc
  docSite/content/docs/development/faq.md
  docSite/content/docs/development/migration/ docker_mongo.md
  docSite/content/docs/development/migration/_index.md
  docSite/content/docs/development/migration/docker_db.md
  packages/service/core/ai/embedding/index.ts
Labels: size/M

#1431 README: update wechat qr code
  README.md
Labels: size/XS

#1336 feat: i18n modify;
  projects/app/i18n/en/common.json
  projects/app/i18n/zh/common.json
Labels: size/XS

#1439 fix: openapi integer & array type
  packages/global/core/plugin/httpPlugin/utils.ts
  projects/app/src/components/core/workflow/Flow/nodes/NodeLaf.tsx
Labels: size/M

#1441 Perf: i18n ns
  .vscode/i18n-ally-custom-framework.yml
  packages/web/package.json
  pnpm-lock.yaml
  projects/app/i18n/en/app.json
  projects/app/i18n/en/common.json
  projects/app/i18n/en/dataset.json
  projects/app/i18n/zh/app.json
  projects/app/i18n/zh/common.json
  projects/app/i18n/zh/dataset.json
  projects/app/src/components/core/workflow/Flow/ImportSettings.tsx
  projects/app/src/components/core/workflow/Flow/NodeTemplatesModal.tsx
  projects/app/src/components/core/workflow/Flow/nodes/render/Handle/index.tsx
  projects/app/src/components/core/workflow/Flow/nodes/render/NodeCard.tsx
  projects/app/src/components/support/apikey/Table.tsx
  projects/app/src/pages/_app.tsx
  projects/app/src/pages/app/detail/components/FlowEdit/Header.tsx
  projects/app/src/pages/app/detail/components/Logs.tsx
  projects/app/src/pages/app/detail/components/SimpleEdit/AppCard.tsx
  projects/app/src/pages/app/detail/components/SimpleEdit/ChatTest.tsx
  projects/app/src/pages/app/detail/components/SimpleEdit/EditForm.tsx
  projects/app/src/pages/app/detail/index.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/pages/chat/components/ChatHistorySlider.tsx
  projects/app/src/pages/plugin/edit/Header.tsx
  projects/app/src/types/i18n.d.ts
  projects/app/src/web/common/utils/i18n.ts
  projects/app/src/web/context/I18n.tsx
Labels: size/XXL

#1443 adapt not input type
  projects/app/src/web/core/workflow/adapt.ts
Labels: size/XS

#1444 i18n
  .vscode/i18n-ally-custom-framework.yml
  packages/global/common/file/constants.ts
  packages/global/common/file/image/constants.ts
  projects/app/i18n/en/common.json
  projects/app/i18n/en/file.json
  projects/app/i18n/en/publish.json
  projects/app/i18n/zh/common.json
  projects/app/i18n/zh/file.json
  projects/app/i18n/zh/publish.json
  projects/app/src/components/ChatBox/ResponseTags.tsx
  projects/app/src/components/core/dataset/RawSourceBox.tsx
  projects/app/src/components/support/apikey/Table.tsx
  projects/app/src/pages/account/components/ApiKeyTable.tsx
  projects/app/src/pages/account/index.tsx
  projects/app/src/pages/app/detail/components/Publish/API/index.tsx
  projects/app/src/pages/app/detail/components/Publish/FeiShu/FeiShuEditModal.tsx
  projects/app/src/pages/app/detail/components/Publish/Link/index.tsx
  projects/app/src/pages/app/detail/index.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/pages/dataset/detail/components/Import/commonProgress/Upload.tsx
  projects/app/src/pages/dataset/detail/components/Import/components/FileSelector.tsx
  projects/app/src/pages/dataset/detail/components/Import/components/RenderFiles.tsx
  projects/app/src/pages/dataset/detail/index.tsx
  projects/app/src/types/i18n.d.ts
  projects/app/src/web/common/file/hooks/useSelectFile.tsx
  projects/app/src/web/context/I18n.tsx
Labels: size/XXL

#1455 fix: session
  docSite/content/docs/development/docker.md
  files/deploy/fastgpt/docker-compose.yml
  packages/service/common/mongo/sessionRun.ts
  projects/app/i18n/en/common.json
  projects/app/i18n/zh/common.json
  projects/app/src/pages/login/components/LoginForm/LoginForm.tsx
Labels: size/M

#1463 Change embedding
  .vscode/nextapi.code-snippets
  .vscode/settings.json
  docSite/content/docs/development/upgrading/48.md
  docSite/content/docs/development/upgrading/481.md
  packages/global/core/dataset/type.d.ts
  packages/global/support/user/team/constant.ts
  packages/service/common/buffer/rawText/schema.ts
  packages/service/common/buffer/tts/schema.ts
  packages/service/common/mongo/sessionRun.ts
  packages/service/common/vectorStore/pg/controller.ts
  packages/service/core/app/versionSchema.ts
  packages/service/core/dataset/collection/schema.ts
  packages/service/core/dataset/data/schema.ts
  packages/service/core/dataset/training/schema.ts
  packages/service/type/next.d.ts
  packages/web/components/common/MyDivider/index.tsx
  packages/web/components/common/MyTooltip/index.tsx
  projects/app/.eslintrc.json
  projects/app/i18n/en/dataset.json
  projects/app/i18n/zh/dataset.json
  projects/app/src/components/Select/AIModelSelector.tsx
  projects/app/src/global/core/dataset/api.d.ts
  projects/app/src/pages/api/admin/initv481.ts
  projects/app/src/pages/api/core/dataset/training/getDatasetTrainingQueue.ts
  projects/app/src/pages/api/core/dataset/training/rebuildEmbedding.ts
  projects/app/src/pages/dataset/detail/components/Info.tsx
  projects/app/src/pages/dataset/detail/components/Slider.tsx
  projects/app/src/pages/dataset/detail/index.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/service/common/system/cron.ts
  projects/app/src/service/core/dataset/data/controller.ts
  projects/app/src/service/events/generateQA.ts
  projects/app/src/service/events/generateVector.ts
  projects/app/src/service/middle/entry.ts
  projects/app/src/web/core/dataset/api.ts
  projects/app/src/web/core/dataset/context/datasetPageContext.tsx
  projects/app/src/web/core/dataset/context/useDatasetContext.tsx
Labels: size/XXL

#1466 Dir tree doc and move some code
  docSite/content/docs/development/intro.md
  packages/global/common/string/time.ts
  project.inlang/project_id
  project.inlang/settings.json
  projects/app/src/components/ChatBox/hooks/useChatBox.tsx
  projects/app/src/components/core/app/TTSSelect.tsx
  projects/app/src/components/core/workflow/Flow/nodes/NodeSystemConfig.tsx
  projects/app/src/constants/dataset.ts
  projects/app/src/pages/_error.tsx
  projects/app/src/pages/account/components/InformTable.tsx
  projects/app/src/pages/app/detail/components/Publish/FeiShu/index.tsx
  projects/app/src/pages/app/detail/components/Publish/Link/index.tsx
  projects/app/src/pages/app/detail/components/SimpleEdit/EditForm.tsx
  projects/app/src/pages/dataset/detail/components/InputDataModal.tsx
  projects/app/src/pages/dataset/detail/components/Test.tsx
  projects/app/src/pages/login/components/ForgetPasswordForm.tsx
  projects/app/src/pages/login/components/LoginForm/LoginForm.tsx
  projects/app/src/pages/login/components/LoginForm/WechatForm.tsx
  projects/app/src/pages/login/components/LoginForm/components/FormLayout.tsx
  projects/app/src/pages/login/components/RegisterForm.tsx
  projects/app/src/pages/login/index.tsx
  projects/app/src/types/index.d.ts
  projects/app/src/utils/tools.ts
  projects/app/src/web/common/system/constants.ts
  projects/app/src/web/common/utils/voice.ts
  projects/app/src/web/context/useInitApp.ts
  projects/app/src/web/core/app/constants.ts
  projects/app/src/web/core/app/store/useAppStore.ts
  projects/app/src/web/core/chat/constants.ts
  projects/app/src/web/core/dataset/constants.ts
  projects/app/src/web/core/dataset/store/dataset.ts
  projects/app/src/web/support/user/login/constants.ts
Labels: size/L

#1471 Fixes: fix edge handler with onDelEdge
  projects/app/src/components/core/workflow/context.tsx
Labels: size/XS

#1475 fix doc
  docSite/content/docs/development/migration/ docker_mongo.md
  docSite/content/docs/development/upgrading/481.md
Labels: size/XS

#1484 feat: node version
  packages/global/core/app/utils.ts
  packages/global/core/plugin/httpPlugin/utils.ts
  packages/global/core/workflow/template/system/aiChat.ts
  packages/global/core/workflow/template/system/assignedAnswer.ts
  packages/global/core/workflow/template/system/classifyQuestion.ts
  packages/global/core/workflow/template/system/contextExtract.ts
  packages/global/core/workflow/template/system/datasetConcat.ts
  packages/global/core/workflow/template/system/datasetSearch.ts
  packages/global/core/workflow/template/system/emptyNode.ts
  packages/global/core/workflow/template/system/globalVariable.ts
  packages/global/core/workflow/template/system/http468.ts
  packages/global/core/workflow/template/system/ifElse/index.ts
  packages/global/core/workflow/template/system/laf.ts
  packages/global/core/workflow/template/system/pluginInput.ts
  packages/global/core/workflow/template/system/pluginOutput.ts
  packages/global/core/workflow/template/system/queryExtension.ts
  packages/global/core/workflow/template/system/runApp.ts
  packages/global/core/workflow/template/system/runPlugin.ts
  packages/global/core/workflow/template/system/stopTool.ts
  packages/global/core/workflow/template/system/systemConfig.ts
  packages/global/core/workflow/template/system/tools.ts
  packages/global/core/workflow/template/system/variableUpdate/index.tsx
  packages/global/core/workflow/template/system/workflowStart.ts
  packages/global/core/workflow/type/index.d.ts
  packages/service/core/plugin/controller.ts
  packages/web/styles/theme.ts
  projects/app/i18n/en/app.json
  projects/app/i18n/zh/app.json
  projects/app/src/components/core/workflow/Flow/nodes/render/NodeCard.tsx
  projects/app/src/components/core/workflow/utils.ts
  projects/app/src/pages/api/core/plugin/pluginTemplate/getSystemPluginTemplates.ts
  projects/app/src/pages/api/core/plugin/pluginTemplate/getTeamPluginTemplates.ts
  projects/app/src/pages/plugin/list/component/EditModal.tsx
  projects/app/src/web/core/app/templates.ts
  projects/app/src/web/core/app/utils.ts
  projects/app/src/web/core/workflow/adapt.ts
  projects/app/src/web/core/workflow/utils.ts
Labels: size/L

#1492 Perf workflow
  .vscode/i18n-ally-custom-framework.yml
  docSite/content/docs/development/openapi/share.md
  docSite/content/docs/development/upgrading/481.md
  packages/global/core/chat/type.d.ts
  packages/global/core/workflow/api.d.ts
  packages/global/core/workflow/template/system/datasetSearch.ts
  packages/global/core/workflow/type/index.d.ts
  packages/global/core/workflow/utils.ts
  packages/service/core/workflow/dispatch/dataset/search.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/web/components/common/Input/NumberInput/index.tsx
  packages/web/components/common/MyDrawer/MyRightDrawer.tsx
  projects/app/i18n/en/dataset.json
  projects/app/i18n/en/workflow.json
  projects/app/i18n/zh/dataset.json
  projects/app/i18n/zh/workflow.json
  projects/app/src/components/core/app/DatasetSelectModal.tsx
  projects/app/src/components/core/workflow/Flow/hooks/useDebug.tsx
  projects/app/src/components/core/workflow/Flow/index.tsx
  projects/app/src/components/core/workflow/Flow/nodes/NodePluginInput.tsx
  projects/app/src/components/core/workflow/Flow/nodes/render/FieldEditModal.tsx
  projects/app/src/components/core/workflow/Flow/nodes/render/NodeCard.tsx
  projects/app/src/components/core/workflow/Flow/nodes/render/RenderInput/Label.tsx
  projects/app/src/components/core/workflow/Flow/nodes/render/VariableTable.tsx
  projects/app/src/components/core/workflow/context.tsx
  projects/app/src/components/core/workflow/utils.ts
  projects/app/src/pages/app/detail/components/FlowEdit/Header.tsx
  projects/app/src/pages/app/detail/index.tsx
  projects/app/src/pages/plugin/edit/index.tsx
  projects/app/src/pages/plugin/list/component/EditModal.tsx
  projects/app/src/types/i18n.d.ts
  projects/app/src/web/context/I18n.tsx
  projects/app/src/web/core/app/templates.ts
  projects/app/src/web/core/app/utils.ts
  projects/app/src/web/core/workflow/constants/dataType.ts
  projects/app/src/web/core/workflow/utils.ts
Labels: size/L

#1493 perf:change plugin version update position
  packages/global/core/plugin/type.d.ts
  packages/global/core/workflow/type/index.d.ts
  packages/service/core/plugin/controller.ts
  packages/service/core/plugin/schema.ts
  packages/service/core/workflow/dispatch/utils.ts
  projects/app/i18n/en/app.json
  projects/app/i18n/zh/app.json
  projects/app/src/components/core/workflow/Flow/nodes/render/NodeCard.tsx
  projects/app/src/components/core/workflow/utils.ts
  projects/app/src/pages/api/core/plugin/update.ts
Labels: size/L

#1497 External dataset
  .vscode/nextapi.code-snippets
  packages/global/common/string/textSplitter.ts
  packages/global/common/system/types/index.d.ts
  packages/global/core/dataset/constants.ts
  packages/global/core/dataset/read.ts
  packages/service/common/file/gridfs/controller.ts
  packages/service/common/file/read/utils.ts
  packages/service/common/string/cheerio.ts
  packages/service/common/string/tiktoken/index.ts
  packages/service/core/dataset/read.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/service/package.json
  packages/service/type.d.ts
  packages/service/worker/file/extension/pdf.ts
  packages/service/worker/file/read.ts
  packages/service/worker/file/type.d.ts
  packages/service/worker/tiktoken/countGptMessagesTokens.ts
  pnpm-lock.yaml
  projects/app/data/config.json
  projects/app/src/global/core/dataset/api.d.ts
  projects/app/src/middleware.ts
  projects/app/src/pages/api/common/file/previewContent.ts
  projects/app/src/pages/api/core/ai/token.ts
  projects/app/src/pages/api/core/dataset/collection/create/csvTable.ts
  projects/app/src/pages/api/core/dataset/collection/create/file.ts
  projects/app/src/pages/api/core/dataset/file/getPreviewChunks.ts
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/pages/dataset/detail/components/Import/components/PreviewChunks.tsx
  projects/app/src/pages/dataset/detail/components/Import/components/PreviewRawText.tsx
  projects/app/src/pages/dataset/detail/components/Import/diffSource/ExternalFile.tsx
  projects/app/src/pages/dataset/detail/components/Import/diffSource/FileLink.tsx
  projects/app/src/pages/dataset/detail/components/Import/diffSource/TableLocal.tsx
  projects/app/src/service/common/system/cronTask.ts
  projects/app/src/web/common/file/api.ts
  projects/app/src/web/core/dataset/api.ts
Labels: size/XL

#1507 perf: tiktoken count
  .npmrc
  Dockerfile
  packages/service/common/string/tiktoken/index.ts
  packages/service/core/dataset/search/utils.ts
  packages/service/package.json
  packages/service/worker/tiktoken/countGptMessagesTokens.ts
  pnpm-lock.yaml
  projects/app/next.config.js
Labels: size/L

#1509 perf: token count
  packages/service/common/string/tiktoken/index.ts
  packages/service/worker/tiktoken/countGptMessagesTokens.ts
  projects/app/src/middleware.ts
  projects/app/src/pages/api/core/ai/token.ts
Labels: size/S

#1442 Permission
  packages/global/support/permission/constant.ts
  packages/global/support/permission/type.d.ts
  packages/global/support/user/team/controller.d.ts
  packages/global/support/user/team/type.d.ts
  packages/service/support/permission/resourcePermission/controller.ts
  packages/service/support/permission/resourcePermission/permisson.ts
  packages/service/support/permission/resourcePermission/schema.ts
  packages/service/support/user/team/controller.ts
  packages/service/support/user/team/teamSchema.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/trash.svg
  packages/web/components/common/Icon/icons/support/team/key.svg
  packages/web/components/common/Icon/icons/support/team/memberLight.svg
  pnpm-lock.yaml
  projects/app/i18n/zh/common.json
  projects/app/src/components/common/Rowtabs/index.tsx
  projects/app/src/components/support/user/team/TeamManageModal/AddManager.tsx
  projects/app/src/components/support/user/team/TeamManageModal/MemberTable.tsx
  projects/app/src/components/support/user/team/TeamManageModal/PermissionManage.tsx
  projects/app/src/components/support/user/team/TeamManageModal/TeamCard.tsx
  projects/app/src/components/support/user/team/TeamManageModal/TeamList.tsx
  projects/app/src/components/support/user/team/TeamManageModal/index.tsx
  projects/app/src/web/support/user/team/api.ts
Labels: size/XXL

#1522 Update permission
  .vscode/i18n-ally-custom-framework.yml
  packages/global/support/permission/constant.ts
  packages/global/support/permission/type.d.ts
  packages/global/support/user/team/controller.d.ts
  packages/global/support/user/team/type.d.ts
  packages/service/support/permission/resourcePermission/controller.ts
  packages/service/support/permission/resourcePermission/permisson.ts
  packages/service/support/permission/resourcePermission/schema.ts
  packages/service/support/user/team/controller.ts
  packages/service/support/user/team/teamSchema.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/trash.svg
  packages/web/components/common/Icon/icons/support/permission/collaborator.svg
  packages/web/components/common/Icon/icons/support/team/key.svg
  packages/web/components/common/Icon/icons/support/team/memberLight.svg
  projects/app/i18n/en/common.json
  projects/app/i18n/en/user.json
  projects/app/i18n/zh/common.json
  projects/app/i18n/zh/user.json
  projects/app/src/components/common/Rowtabs/index.tsx
  projects/app/src/components/support/user/team/TeamManageModal/AddManager.tsx
  projects/app/src/components/support/user/team/TeamManageModal/MemberTable.tsx
  projects/app/src/components/support/user/team/TeamManageModal/PermissionManage.tsx
  projects/app/src/components/support/user/team/TeamManageModal/TeamCard.tsx
  projects/app/src/components/support/user/team/TeamManageModal/TeamList.tsx
  projects/app/src/components/support/user/team/TeamManageModal/index.tsx
  projects/app/src/pages/account/index.tsx
  projects/app/src/types/i18n.d.ts
  projects/app/src/web/context/I18n.tsx
  projects/app/src/web/support/user/team/api.ts
Labels: size/XXL

#1524 fix: api key delete bug
  packages/web/hooks/useConfirm.tsx
  projects/app/src/components/support/apikey/Table.tsx
Labels: size/L

#1527 feat: fix admin role
  packages/service/support/permission/auth/app.ts
Labels: size/XS

#1508 feat: question guide
  docSite/assets/imgs/questionGuide.png
  docSite/content/docs/course/custom_link.md
  packages/global/core/app/constants.ts
  packages/global/core/app/type.d.ts
  packages/global/core/app/utils.ts
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/template/system/systemConfig.ts
  packages/global/core/workflow/utils.ts
  packages/service/core/app/qGuideSchema.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/book.svg
  packages/web/components/common/Icon/icons/core/app/inputGuides.svg
  packages/web/components/common/Icon/icons/union.svg
  packages/web/hooks/useScrollPagination.tsx
  projects/app/i18n/en/app.json
  projects/app/i18n/en/common.json
  projects/app/i18n/zh/app.json
  projects/app/i18n/zh/common.json
  projects/app/src/components/ChatBox/MessageInput.tsx
  projects/app/src/components/ChatBox/components/QustionGuide.tsx
  projects/app/src/components/ChatBox/index.tsx
  projects/app/src/components/core/app/QGuidesConfig.tsx
  projects/app/src/components/core/workflow/Flow/ChatTest.tsx
  projects/app/src/components/core/workflow/Flow/nodes/NodeSystemConfig.tsx
  projects/app/src/pages/api/core/app/del.ts
  projects/app/src/pages/api/core/app/questionGuides/import.ts
  projects/app/src/pages/api/core/app/questionGuides/list.ts
  projects/app/src/pages/app/detail/components/FlowEdit/Header.tsx
  projects/app/src/pages/app/detail/components/FlowEdit/index.tsx
  projects/app/src/pages/app/detail/components/SimpleEdit/ChatTest.tsx
  projects/app/src/pages/app/detail/components/SimpleEdit/EditForm.tsx
  projects/app/src/pages/app/detail/components/SimpleEdit/ToolSelectModal.tsx
  projects/app/src/pages/app/detail/index.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/web/core/app/api.ts
  projects/app/src/web/core/app/store/useAppStore.ts
  projects/app/src/web/core/app/utils.ts
  projects/app/src/web/core/chat/utils.ts
Labels: size/XXL

#1531 Add request log and uncatch error tip.
  Dockerfile
  packages/global/core/workflow/runtime/utils.ts
  packages/service/common/middle/entry.ts
  packages/service/common/system/tools.ts
  packages/service/core/chat/controller.ts
  projects/app/src/components/core/workflow/Flow/ChatTest.tsx
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/SimpleEdit/ChatTest.tsx
  projects/app/src/service/mongo.ts
Labels: size/M

#1558 perf: input guide
  docSite/content/docs/course/chat_input_guide.md
  packages/global/core/workflow/utils.ts
Labels: size/XS

#1539 fix: chunk preview drawer can not scroll
  packages/web/components/common/MyDrawer/MyRightDrawer.tsx
  projects/app/src/components/core/workflow/Flow/hooks/useDebug.tsx
  projects/app/src/pages/dataset/detail/components/Import/components/PreviewChunks.tsx
Labels: size/M

#1570 更新Nextjs配置，更新服务端组件的声明
  projects/app/next.config.js
Labels: size/XS

#1576 perf: tool promot and reg slice;query extension prompt
  packages/global/common/string/tools.ts
  packages/global/core/workflow/template/system/runApp.ts
  packages/service/core/ai/functions/queryExtension.ts
  packages/service/core/workflow/dispatch/agent/extract.ts
  packages/service/core/workflow/dispatch/agent/runTool/constants.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
Labels: size/L

#1583 Fix: embedding model names in config.json
  projects/app/data/config.json
Labels: size/XS

#1580 Release update
  docSite/content/docs/development/openapi/chat.md
  docSite/content/docs/development/upgrading/481.md
  files/deploy/fastgpt/docker-compose.yml
  packages/global/common/string/tools.ts
  packages/global/core/workflow/template/system/variableUpdate/index.tsx
  packages/service/core/ai/functions/queryExtension.ts
  packages/service/core/workflow/dispatch/agent/runTool/constants.ts
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/tools/runUpdateVar.ts
  packages/service/core/workflow/dispatch/utils.ts
  projects/app/data/config.json
  projects/app/src/components/ChatBox/index.tsx
  projects/app/src/components/ChatBox/type.d.ts
  projects/app/src/components/core/workflow/Flow/ChatTest.tsx
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/web/common/api/fetch.ts
Labels: size/L

#1589 Update README
  README_en.md
Labels: size/S

#1612 4.8.2-fix
  .github/workflows/build-sandbox-image.yml
  .github/workflows/fastgpt-image.yml
  .github/workflows/preview-image.yml
  docSite/content/docs/development/upgrading/482.md
  files/deploy/fastgpt/docker-compose.yml
  projects/app/public/docs/versionIntro.md
  projects/app/src/components/core/app/ScheduledTriggerConfig.tsx
  projects/app/src/components/core/workflow/Flow/components/ButtonEdge.tsx
  projects/app/src/components/core/workflow/Flow/index.tsx
  projects/app/src/components/core/workflow/context.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/Context.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/index.tsx
  projects/app/src/service/core/app/workflow.ts
Labels: size/L

#1626 Docs: add umami analytics
  docSite/hugo.toml
  docSite/layouts/partials/docs/analytics/umami.html
  docSite/layouts/partials/docs/head.html
Labels: size/S

#1629 Docs: add google analytics, baidu and clarity
  docSite/hugo.toml
  docSite/layouts/partials/docs/analytics/baidu.html
  docSite/layouts/partials/docs/analytics/clarity.html
  docSite/layouts/partials/docs/analytics/google.html
  docSite/layouts/partials/docs/head.html
Labels: size/M

#1630 Docs: fix base url
  docSite/hugo.toml
Labels: size/XS

#1635 Add icon for Google Gemini
  projects/app/public/imgs/model/gemini.svg
Labels: size/S
