Repository labring/FastGPT, pull requests merged in 2024-04, with the labels that each got.

#1114 fix name from originBucekerName to originBucketName
  packages/service/common/file/multer.ts
Labels: size/XS

#1131 doc
  docSite/content/docs/development/docker.md
  docSite/content/docs/development/upgrading/471.md
  packages/service/core/dataset/training/controller.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  projects/app/src/components/ChatBox/components/ChatItem.tsx
  projects/app/src/web/core/dataset/api.ts
Labels: size/S

#1134 Update docker-compose.yml
  files/deploy/fastgpt/docker-compose.yml
Labels: size/XS

#1161 Fix share page whisper auth
  docSite/content/docs/development/configuration.md
  docSite/content/docs/development/custom-models/bge-rerank.md
  docSite/content/docs/development/upgrading/471.md
  docSite/content/docs/workflow/examples/dalle3.md
  docSite/content/docs/workflow/examples/feishu_webhook.md
  docSite/content/docs/workflow/examples/google_search.md
  docSite/content/docs/workflow/modules/laf.md
  packages/global/common/string/textSplitter.ts
  packages/global/common/string/tools.ts
  packages/global/core/module/template/system/userGuide.ts
  packages/global/core/module/template/tip.ts
  packages/global/support/user/team/type.d.ts
  packages/global/support/wallet/bill/type.d.ts
  packages/service/common/file/image/schema.ts
  packages/service/common/vectorStore/controller.d.ts
  packages/service/common/vectorStore/pg/controller.ts
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/controller.ts
  packages/service/core/dataset/data/controller.ts
  packages/service/core/dataset/data/schema.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/core/dataset/training/controller.ts
  packages/service/core/dataset/training/schema.ts
  packages/service/support/user/team/teamSchema.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/modules/fixview.svg
  projects/app/public/docs/versionIntro.md
  projects/app/public/js/iframe.js
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/components/ChatBox/components/ChatItem.tsx
  projects/app/src/components/core/module/Flow/ChatTest.tsx
  projects/app/src/components/core/module/Flow/FlowProvider.tsx
  projects/app/src/components/core/module/Flow/components/nodes/NodeUserGuide.tsx
  projects/app/src/components/core/module/Flow/components/render/NodeCard.tsx
  projects/app/src/components/core/module/Flow/index.tsx
  projects/app/src/components/support/laf/LafAccountModal.tsx
  projects/app/src/pages/api/admin/initv471.ts
  projects/app/src/pages/api/core/dataset/collection/delete.ts
  projects/app/src/pages/api/core/dataset/data/insertData.ts
  projects/app/src/pages/api/core/dataset/data/list.ts
  projects/app/src/pages/api/v1/audio/transcriptions.ts
  projects/app/src/pages/app/detail/components/FlowEdit/Header.tsx
  projects/app/src/pages/app/detail/components/OutLink/SelectUsingWayModal.tsx
  projects/app/src/pages/chat/components/ToolMenu.tsx
  projects/app/src/pages/plugin/edit/Header.tsx
  projects/app/src/service/common/system/cronTask.ts
  projects/app/src/service/core/dataset/data/utils.ts
  projects/app/src/web/common/api/lafRequest.ts
  projects/app/src/web/common/hooks/useSpeech.ts
  projects/app/src/web/core/app/templates.ts
  projects/app/src/web/core/app/utils.ts
  projects/app/src/web/styles/reactflow.scss
  projects/app/src/web/support/laf/api.ts
  python/bge-rerank/README.md
Labels: size/XL

#1182 fix the problem that no permission to exported knowledge
  projects/app/src/pages/dataset/list/index.tsx
Labels: size/M

#1173 4.7.1 production
  docSite/content/docs/development/upgrading/471.md
  packages/global/common/file/tools.ts
  packages/service/common/file/gridfs/controller.ts
  packages/service/common/file/read/pptx.ts
  packages/service/common/file/read/rawText.ts
  packages/service/common/file/read/type.d.ts
  packages/service/common/vectorStore/pg/controller.ts
  packages/service/common/vectorStore/pg/index.ts
  packages/service/package.json
  packages/web/components/common/Textarea/PromptEditor/utils.ts
  pnpm-lock.yaml
  projects/app/src/components/ChatBox/components/ChatItem.tsx
  projects/app/src/components/core/module/Flow/components/nodes/NodeLaf.tsx
  projects/app/src/pages/api/common/file/read.ts
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/service/support/permission/auth/dataset.ts
  projects/app/src/web/common/api/xmlFetch.ts
  projects/app/src/web/common/hooks/useSpeech.ts
Labels: size/L

#1194 修复拖动聊天图标容易中断问题
  projects/app/public/js/iframe.js
Labels: size/XS

#1215 Docs: fix README.md style
  README.md
Labels: size/XS

#1231 fix: base64 image undefined
  packages/service/core/chat/utils.ts
Labels: size/XS

#1225 Fix: websync doc and export dataset ux
  docSite/content/docs/course/websync.md
  packages/global/core/module/template/system/userGuide.ts
  projects/app/public/locales/en/common.json
  projects/app/public/locales/zh/common.json
  projects/app/src/pages/api/core/dataset/exportAll.ts
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/web/common/api/xmlFetch.ts
Labels: size/L

#1266 docs: Add doc for Xinference
  docSite/assets/docs/scss/custom/pages/_custom.scss
  docSite/assets/docs/scss/custom/plugins/prism/themes/_lotusdocs.scss
  docSite/assets/imgs/fastgpt-list-models.png
  docSite/assets/imgs/one-api-add-xinference-models.jpg
  docSite/assets/imgs/xinference-launch-model.png
  docSite/content/docs/development/custom-models/bge-rerank.md
  docSite/content/docs/development/custom-models/chatglm2-m3e.md
  docSite/content/docs/development/custom-models/chatglm2.md
  docSite/content/docs/development/custom-models/m3e.md
  docSite/content/docs/development/custom-models/xinference.md
  docSite/content/docs/development/one-api.md
  docSite/content/docs/pricing.md
  docSite/layouts/redirect/single.html
Labels: size/L

#1291 perf: tool value type and complections body size
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  projects/app/src/pages/api/common/file/uploadImage.ts
Labels: size/M

#1297 pnpm lock
  .github/workflows/fastgpt-image.yml
  pnpm-lock.yaml
Labels: size/L

#1298 package
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/src/components/Markdown/img/MermaidCodeBlock.tsx
Labels: size/L

#1299 remove isolate vm
  packages/service/core/workflow/dispatch/code/isolatedvm.ts
  packages/service/package.json
  pnpm-lock.yaml
Labels: size/L

#1295 chatbot url没有配置时，不显示chatbot界面，改善页面一致性
  projects/app/src/pages/account/components/Info.tsx
Labels: size/M

#1313 fix @node-rs/jieba and window not found
  packages/web/common/system/utils.ts
  packages/web/hooks/useBeforeunload.ts
  packages/web/package.json
  pnpm-lock.yaml
  projects/app/next.config.js
  projects/app/package.json
  projects/app/src/components/ChatBox/components/Empty.tsx
  projects/app/src/components/Layout/index.tsx
  projects/app/src/components/support/user/inform/ImportantInform.tsx
  projects/app/src/components/support/user/inform/SystemMsgModal.tsx
  projects/app/src/pages/_app.tsx
  projects/app/src/pages/chat/components/Empty.tsx
  projects/app/src/pages/login/index.tsx
  projects/app/src/web/context/ChakraUI.tsx
  projects/app/src/web/context/QueryClient.tsx
  projects/app/src/web/context/useInitApp.ts
Labels: size/XL

#1246 feat: 增加自定义 meta description;
  docSite/content/docs/development/sealos.md
  packages/global/common/system/types/index.d.ts
  projects/app/src/pages/_app.tsx
  projects/app/src/web/common/system/api.ts
Labels: size/S

#1331 Publish histories
  .vscode/nextapi.code-snippets
  .vscode/settings.json
  packages/global/core/app/version.d.ts
  packages/global/core/plugin/httpPlugin/utils.ts
  packages/global/core/workflow/template/constants.ts
  packages/web/common/fetch/type.d.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/publishFill.svg
  packages/web/components/common/Icon/icons/core/workflow/revertVersion.svg
  packages/web/components/common/Icon/icons/core/workflow/versionHistories.svg
  packages/web/components/common/Icon/icons/history.svg
  packages/web/components/common/MyBox/index.tsx
  packages/web/components/common/MyDrawer/CustomRightDrawer.tsx
  packages/web/core/workflow/constants.ts
  packages/web/hooks/useScrollPagination.tsx
  packages/web/package.json
  pnpm-lock.yaml
  project.inlang/settings.json
  projects/app/i18n/en/common.json
  projects/app/i18n/zh/common.json
  projects/app/next-i18next.config.js
  projects/app/src/components/PageContainer/index.tsx
  projects/app/src/components/common/MyBox/index.tsx
  projects/app/src/components/core/dataset/QuoteItem.tsx
  projects/app/src/components/core/dataset/SelectModal.tsx
  projects/app/src/components/core/workflow/Flow/NodeTemplatesModal.tsx
  projects/app/src/components/core/workflow/components/PublishHistoriesSlider.tsx
  projects/app/src/components/core/workflow/context.tsx
  projects/app/src/global/core/app/api.d.ts
  projects/app/src/pages/account/components/BillTable.tsx
  projects/app/src/pages/api/core/app/version/list.ts
  projects/app/src/pages/api/core/app/version/revert.ts
  projects/app/src/pages/app/detail/components/FlowEdit/Header.tsx
  projects/app/src/pages/app/detail/components/Logs.tsx
  projects/app/src/pages/app/detail/components/SimpleEdit/EditForm.tsx
  projects/app/src/pages/app/detail/components/SimpleEdit/ToolSelectModal.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard.tsx
  projects/app/src/pages/dataset/detail/components/Import/components/FileSelector.tsx
  projects/app/src/pages/dataset/detail/components/InputDataModal.tsx
  projects/app/src/pages/dataset/detail/index.tsx
  projects/app/src/types/i18n.d.ts
  projects/app/src/web/core/app/store/useAppStore.ts
  projects/app/src/web/core/app/versionApi.ts
Labels: size/XL

#1338 fix: issues/1334 useTransition 导致光标刷新后移问题;
  projects/app/src/components/core/workflow/Flow/nodes/NodeHttp/index.tsx
Labels: size/S

#1337 Perf: read file woker
  .github/ISSUE_TEMPLATE/bugs.md
  packages/global/core/workflow/template/system/tools.ts
  packages/service/common/file/gridfs/controller.ts
  packages/service/common/file/read/html.ts
  packages/service/common/file/read/markdown.ts
  packages/service/common/file/read/type.d.ts
  packages/service/common/file/read/utils.ts
  packages/service/common/file/read/word.ts
  packages/service/common/string/cheerio.ts
  packages/service/common/string/markdown.ts
  packages/service/common/vectorStore/pg/controller.ts
  packages/service/core/workflow/dispatch/agent/classifyQuestion.ts
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/tools/answer.ts
  packages/service/worker/file/extension/csv.ts
  packages/service/worker/file/extension/docx.ts
  packages/service/worker/file/extension/html.ts
  packages/service/worker/file/extension/pdf.ts
  packages/service/worker/file/extension/pptx.ts
  packages/service/worker/file/extension/rawText.ts
  packages/service/worker/file/extension/xlsx.ts
  packages/service/worker/file/parseOffice.ts
  packages/service/worker/file/read.ts
  packages/service/worker/file/type.d.ts
  packages/service/worker/htmlStr2Md.ts
  packages/service/worker/htmlStr2Md/index.ts
  packages/service/worker/htmlStr2Md/utils.ts
  packages/service/worker/utils.ts
  packages/web/hooks/useScrollPagination.tsx
  projects/app/next.config.js
  projects/app/package.json
  projects/app/src/components/core/workflow/Flow/nodes/NodeHttp/index.tsx
  projects/app/src/components/core/workflow/Flow/nodes/NodeTools.tsx
  projects/app/src/components/core/workflow/Flow/nodes/render/RenderInput/Label.tsx
Labels: size/XL
