Repository labring/FastGPT, pull requests merged in 2024-12, with the labels that each got.

#3284 Fix share page feedback auth
  packages/global/core/chat/api.d.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/FeedbackModal.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/pages/app/detail/components/Publish/Link/SelectUsingWayModal.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/web/common/utils/i18n.ts
  projects/app/src/web/core/chat/context/chatRecordContext.tsx
Labels: size/L

#3281 refactor: 页面拆分&i18n拆分
  package.json
  packages/web/i18n/en/account.json
  packages/web/i18n/en/account_apikey.json
  packages/web/i18n/en/account_bill.json
  packages/web/i18n/en/account_individuation.json
  packages/web/i18n/en/account_info.json
  packages/web/i18n/en/account_inform.json
  packages/web/i18n/en/account_promotion.json
  packages/web/i18n/en/account_usage.json
  packages/web/i18n/en/app.json
  packages/web/i18n/zh-CN/account.json
  packages/web/i18n/zh-CN/account_apikey.json
  packages/web/i18n/zh-CN/account_bill.json
  packages/web/i18n/zh-CN/account_individuation.json
  packages/web/i18n/zh-CN/account_info.json
  packages/web/i18n/zh-CN/account_inform.json
  packages/web/i18n/zh-CN/account_promotion.json
  packages/web/i18n/zh-CN/account_usage.json
  packages/web/i18n/zh-CN/user.json
  packages/web/i18n/zh-Hant/account.json
  packages/web/i18n/zh-Hant/account_apikey.json
  packages/web/i18n/zh-Hant/account_bill.json
  packages/web/i18n/zh-Hant/account_individuation.json
  packages/web/i18n/zh-Hant/account_info.json
  packages/web/i18n/zh-Hant/account_inform.json
  packages/web/i18n/zh-Hant/account_promotion.json
  packages/web/i18n/zh-Hant/account_usage.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/chat.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/types/i18next.d.ts
  projects/app/src/components/Layout/navbar.tsx
  projects/app/src/pages/account/apikey.tsx
  projects/app/src/pages/account/bill/components/ApplyInvoiceModal.tsx
  projects/app/src/pages/account/bill/components/BillTable.tsx
  projects/app/src/pages/account/bill/components/InvoiceHeaderForm.tsx
  projects/app/src/pages/account/bill/components/InvoiceTable.tsx
  projects/app/src/pages/account/bill/index.tsx
  projects/app/src/pages/account/components/AccountContainer.tsx
  projects/app/src/pages/account/components/ApiKeyTable.tsx
  projects/app/src/pages/account/components/Individuation.tsx
  projects/app/src/pages/account/components/InformTable.tsx
  projects/app/src/pages/account/components/Promotion.tsx
  projects/app/src/pages/account/components/UsageDetail.tsx
  projects/app/src/pages/account/components/UsageTable.tsx
  projects/app/src/pages/account/individuation.tsx
  projects/app/src/pages/account/info/components/ConversionModal.tsx
  projects/app/src/pages/account/info/components/OpenAIAccountModal.tsx
  projects/app/src/pages/account/info/components/UpdateNotificationModal.tsx
  projects/app/src/pages/account/info/components/UpdatePswModal.tsx
  projects/app/src/pages/account/info/components/standardDetailModal.tsx
  projects/app/src/pages/account/info/index.tsx
  projects/app/src/pages/account/inform.tsx
  projects/app/src/pages/account/promotion.tsx
  projects/app/src/pages/account/usage.tsx
  scripts/i18n/index.js
Labels: size/XXL

#3290 fix(plugin): use intro instead of userguide
  packages/global/core/workflow/type/node.d.ts
  packages/plugins/register.ts
  projects/app/src/pages/api/core/app/plugin/getSystemPluginTemplates.ts
  projects/app/src/pages/app/detail/components/SimpleApp/components/ToolSelectModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pages/toolkit/components/PluginCard.tsx
Labels: size/M

#3293 fix simple snapshot init & auto excute when change app
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Edit.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Header.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/index.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/useSnapshots.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
Labels: size/M

#3295 fix: auto send prompt runtime
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Provider.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/pages/chat/components/ChatHeader.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/web/core/chat/context/chatItemContext.tsx
  projects/app/src/web/core/chat/context/chatRecordContext.tsx
Labels: size/L

#3296 fix: ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/pages/app/detail/components/Logs/DetailLogsModal.tsx
  projects/app/src/pages/app/detail/components/useChatTest.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
Labels: size/S

#3272 feat: add api dataset
  docSite/assets/imgs/api-dataset-1.png
  docSite/content/zh-cn/docs/guide/knowledge_base/api_dataset.md
  docSite/content/zh-cn/docs/guide/knowledge_base/externalFile.md
  packages/global/core/dataset/api.d.ts
  packages/global/core/dataset/apiDataset.d.ts
  packages/global/core/dataset/collection/utils.ts
  packages/global/core/dataset/constants.ts
  packages/global/core/dataset/read.ts
  packages/global/core/dataset/type.d.ts
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/collection/schema.ts
  packages/service/core/dataset/read.ts
  packages/service/core/dataset/schema.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/global/core/dataset/api.d.ts
  projects/app/src/pages/api/common/file/previewContent.ts
  projects/app/src/pages/api/core/dataset/apiDataset/list.ts
  projects/app/src/pages/api/core/dataset/collection/create/apiCollection.ts
  projects/app/src/pages/api/core/dataset/collection/read.ts
  projects/app/src/pages/api/core/dataset/create.ts
  projects/app/src/pages/api/core/dataset/file/getPreviewChunks.ts
  projects/app/src/pages/dataset/detail/components/CollectionCard/Header.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/index.tsx
  projects/app/src/pages/dataset/detail/components/Import/Context.tsx
  projects/app/src/pages/dataset/detail/components/Import/commonProgress/Upload.tsx
  projects/app/src/pages/dataset/detail/components/Import/components/PreviewChunks.tsx
  projects/app/src/pages/dataset/detail/components/Import/components/PreviewRawText.tsx
  projects/app/src/pages/dataset/detail/components/Import/diffSource/APIDataset.tsx
  projects/app/src/pages/dataset/detail/components/Import/diffSource/ExternalFile.tsx
  projects/app/src/pages/dataset/detail/components/Import/index.tsx
  projects/app/src/pages/dataset/list/component/CreateModal.tsx
  projects/app/src/pages/dataset/list/component/List.tsx
  projects/app/src/pages/dataset/list/component/SideTag.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/service/core/dataset/data/utils.ts
  projects/app/src/web/core/dataset/api.ts
  projects/app/src/web/core/dataset/type.d.ts
Labels: size/XXL

#3301 perf: create collection code
  docSite/content/zh-cn/docs/development/upgrading/4815.md
  packages/global/core/dataset/apiDataset.d.ts
  packages/service/common/api/serverRequest.ts
  packages/service/core/dataset/apiDataset/api.ts
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/read.ts
  packages/web/hooks/useI18n.ts
  projects/app/src/components/Layout/navbar.tsx
  projects/app/src/components/Layout/navbarPhone.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/global/core/ai/api.d.ts
  projects/app/src/global/core/dataset/api.d.ts
  projects/app/src/pages/account/individuation.tsx
  projects/app/src/pages/api/common/file/previewContent.ts
  projects/app/src/pages/api/core/ai/agent/createQuestionGuide.ts
  projects/app/src/pages/api/core/ai/agent/v2/createQuestionGuide.ts
  projects/app/src/pages/api/core/dataset/apiDataset/list.ts
  projects/app/src/pages/api/core/dataset/collection/create/apiCollection.ts
  projects/app/src/pages/api/core/dataset/collection/create/csvTable.ts
  projects/app/src/pages/api/core/dataset/collection/create/fileId.ts
  projects/app/src/pages/api/core/dataset/collection/create/localFile.ts
  projects/app/src/pages/api/core/dataset/collection/create/text.ts
  projects/app/src/pages/api/core/dataset/collection/read.ts
  projects/app/src/pages/api/core/dataset/file/getPreviewChunks.ts
  projects/app/src/pages/dataset/detail/components/Import/components/PreviewChunks.tsx
  projects/app/src/pages/dataset/detail/components/Import/components/PreviewRawText.tsx
  projects/app/src/service/core/dataset/data/utils.ts
  projects/app/src/service/support/permission/auth/chat.ts
  projects/app/src/web/common/api/request.ts
  projects/app/src/web/common/utils/i18n.ts
  projects/app/src/web/core/ai/api.ts
Labels: size/XXL

#3300 microsoft oauth tenantId & custom button name
  packages/global/common/system/types/index.d.ts
  projects/app/src/pages/login/components/LoginForm/components/FormLayout.tsx
Labels: size/S

#3303 fix: tts auth and response type
  docSite/content/zh-cn/docs/development/upgrading/4815.md
  packages/global/common/string/textSplitter.ts
  projects/app/src/components/core/app/TTSSelect.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Provider.tsx
  projects/app/src/pages/api/core/chat/item/getSpeech.ts
  projects/app/src/service/support/wallet/usage/push.ts
  projects/app/src/web/common/utils/voice.ts
Labels: size/M

#3314 perf: sync collection and ui check
  packages/global/common/error/code/dataset.ts
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/collection/utils.ts
  packages/web/components/common/MySelect/index.tsx
  packages/web/i18n/en/account.json
  packages/web/i18n/en/account_info.json
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/en/user.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-CN/user.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/dataset.json
  packages/web/i18n/zh-Hant/user.json
  projects/app/src/components/Layout/navbar.tsx
  projects/app/src/components/Layout/navbarPhone.tsx
  projects/app/src/components/support/user/team/TeamMenu/index.tsx
  projects/app/src/pages/account/components/AccountContainer.tsx
  projects/app/src/pages/account/components/TeamSelector.tsx
  projects/app/src/pages/account/info/index.tsx
  projects/app/src/pages/account/team/components/GroupManage/GroupManageMember.tsx
  projects/app/src/pages/account/team/index.tsx
  projects/app/src/pages/api/core/dataset/collection/create/apiCollection.ts
  projects/app/src/pages/api/core/dataset/collection/create/fileId.ts
  projects/app/src/pages/api/core/dataset/collection/create/link.ts
  projects/app/src/pages/api/core/dataset/collection/create/localFile.ts
  projects/app/src/pages/api/core/dataset/collection/create/text.ts
  projects/app/src/pages/api/core/dataset/collection/delete.ts
  projects/app/src/pages/api/core/dataset/collection/sync.ts
  projects/app/src/pages/api/core/dataset/collection/sync/link.ts
  projects/app/src/pages/api/core/dataset/update.ts
  projects/app/src/pages/app/list/components/TemplateMarketModal.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/Context.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/index.tsx
  projects/app/src/pages/dataset/detail/components/Import/diffSource/APIDataset.tsx
  projects/app/src/pages/dataset/detail/components/MetaDataCard.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/pages/login/components/LoginForm/components/FormLayout.tsx
  projects/app/src/service/common/system/volumnMongoWatch.ts
  projects/app/src/web/core/dataset/api.ts
  projects/app/src/web/core/dataset/context/datasetPageContext.tsx
  scripts/i18n/delete-unused-keys.js
Labels: size/XXL

#3315 fix: debug variables & cronjob & system plugin callback load
  packages/web/components/common/MySelect/CronSelector.tsx
  packages/web/components/common/MySelect/MultipleRowSelect.tsx
  packages/web/components/common/MySelect/type.d.ts
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/core/app/ScheduledTriggerConfig.tsx
  projects/app/src/pages/api/core/app/plugin/getSystemPluginTemplates.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useDebug.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/XL

#3318 perf: node templates ui;fix: dataset import ui
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pages/dataset/detail/components/Import/components/Preview.tsx
  projects/app/src/pages/dataset/detail/components/Import/index.tsx
Labels: size/L

#3309 feat:套餐改名和套餐跳转配置
  packages/global/common/system/types/index.d.ts
  packages/global/support/wallet/sub/api.d.ts
  packages/global/support/wallet/sub/type.d.ts
  projects/app/src/components/Layout/navbar.tsx
  projects/app/src/components/support/wallet/StandardPlanContentList.tsx
  projects/app/src/pages/account/info/index.tsx
  projects/app/src/pages/more/index.tsx
  projects/app/src/pages/price/components/Standard.tsx
Labels: size/M

#3319 4.8.15 test
  packages/service/common/response/index.ts
  packages/service/core/ai/functions/queryExtension.ts
  packages/service/core/ai/rerank/index.ts
  packages/service/core/dataset/training/utils.ts
  packages/service/core/workflow/dispatch/tools/readFiles.ts
  packages/web/i18n/en/account_info.json
  packages/web/i18n/zh-CN/account_bill.json
  packages/web/i18n/zh-CN/account_info.json
  packages/web/i18n/zh-Hant/account_info.json
  projects/app/src/components/Layout/navbar.tsx
  projects/app/src/components/Select/AIModelSelector.tsx
  projects/app/src/components/support/wallet/StandardPlanContentList.tsx
  projects/app/src/pages/account/info/index.tsx
  projects/app/src/pages/api/core/dataset/data/pushData.ts
  projects/app/src/pages/api/core/dataset/update.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pages/price/components/Points.tsx
  projects/app/src/pages/price/components/Standard.tsx
  projects/app/src/service/events/utils.ts
  projects/app/src/web/support/wallet/sub/constants.ts
Labels: size/XL

#3270 html渲染文档
  docSite/assets/imgs/htmlRendering1.png
  docSite/assets/imgs/htmlRendering2.png
  docSite/assets/imgs/htmlRendering3.png
  docSite/content/zh-cn/docs/guide/DialogBoxes/_index.md
  docSite/content/zh-cn/docs/guide/DialogBoxes/htmlRendering.md
Labels: size/L

#3322 feat: doc
  docSite/assets/imgs/image-10.png
  docSite/assets/imgs/image-11.png
  docSite/assets/imgs/image-12.png
  docSite/assets/imgs/image-13.png
  docSite/assets/imgs/image-14.png
  docSite/assets/imgs/image-15.png
  docSite/assets/imgs/image-16.png
  docSite/content/zh-cn/docs/development/custom-models/maker.md
  docSite/content/zh-cn/docs/guide/DialogBoxes/htmlRendering.md
  packages/service/common/file/read/utils.ts
  packages/service/core/workflow/dispatch/utils.ts
  projects/app/src/pages/api/v1/embeddings.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
Labels: size/L

#3282 集合重训练
  packages/global/core/dataset/api.d.ts
  packages/global/core/dataset/constants.ts
  packages/service/core/dataset/collection/controller.ts
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/dataset.json
  projects/app/src/pages/api/core/dataset/collection/create/reTrainingCollection.ts
  projects/app/src/pages/dataset/detail/components/DataCard.tsx
  projects/app/src/pages/dataset/detail/components/Import/Context.tsx
  projects/app/src/pages/dataset/detail/components/Import/commonProgress/DataProcess.tsx
  projects/app/src/pages/dataset/detail/components/Import/commonProgress/Upload.tsx
  projects/app/src/pages/dataset/detail/components/Import/components/PreviewChunks.tsx
  projects/app/src/pages/dataset/detail/components/Import/components/PreviewRawText.tsx
  projects/app/src/pages/dataset/detail/components/Import/diffSource/ReTraining.tsx
  projects/app/src/pages/dataset/detail/components/Import/index.tsx
  projects/app/src/web/core/dataset/api.ts
Labels: size/L

#3329 perf: custom navbar code;perf: retraining code;feat: api dataset and dataset api doc
  docSite/assets/imgs/image-17.png
  docSite/assets/imgs/image-18.png
  docSite/assets/imgs/image-19.png
  docSite/content/zh-cn/docs/development/custom-models/marker.md
  docSite/content/zh-cn/docs/development/openapi/dataset.md
  docSite/content/zh-cn/docs/development/upgrading/4815.md
  docSite/content/zh-cn/docs/guide/knowledge_base/api_dataset.md
  packages/global/common/layout/constant.ts
  packages/global/common/layout/type.d.ts
  packages/global/common/system/types/index.d.ts
  packages/global/core/dataset/api.d.ts
  packages/global/core/dataset/read.ts
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/dataset.json
  projects/app/src/components/Layout/navbar.tsx
  projects/app/src/components/support/apikey/Table.tsx
  projects/app/src/pages/account/apikey.tsx
  projects/app/src/pages/account/info/index.tsx
  projects/app/src/pages/api/core/dataset/collection/create/reTrainingCollection.ts
  projects/app/src/pages/dataset/detail/components/CollectionCard/index.tsx
  projects/app/src/pages/dataset/detail/components/DataCard.tsx
  projects/app/src/pages/dataset/detail/components/Import/commonProgress/DataProcess.tsx
  projects/app/src/pages/dataset/detail/components/Import/commonProgress/Upload.tsx
  projects/app/src/pages/dataset/detail/components/Import/components/PreviewChunks.tsx
  projects/app/src/pages/dataset/detail/components/Import/components/PreviewRawText.tsx
  projects/app/src/pages/dataset/detail/components/Import/diffSource/ReTraining.tsx
  projects/app/src/pages/dataset/detail/components/Import/utils.ts
  projects/app/src/web/core/dataset/api.ts
Labels: size/XL

#3334 perf: workflow snapshots;fix: extrat node selected
  docSite/assets/imgs/image-20.png
  docSite/assets/imgs/image-21.png
  docSite/assets/imgs/image-22.png
  docSite/assets/imgs/image-23.png
  docSite/assets/imgs/image-24.png
  docSite/content/zh-cn/docs/development/upgrading/4815.md
  packages/web/i18n/en/app.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-Hant/app.json
  projects/app/src/components/core/app/AutoExecConfig.tsx
  projects/app/src/pages/app/detail/components/Plugin/Header.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Edit.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Header.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/index.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/useSnapshots.tsx
  projects/app/src/pages/app/detail/components/Workflow/Header.tsx
  projects/app/src/pages/app/detail/components/Workflow/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/AppCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeExtract/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context/workflowInitContext.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context/workflowStatusContext.tsx
  projects/app/src/pages/dataset/detail/components/Import/diffSource/APIDataset.tsx
  projects/app/src/pages/toolkit/components/PluginCard.tsx
  projects/app/src/pages/toolkit/index.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/XL

#3335 marker doc
  docSite/content/zh-cn/docs/development/custom-models/marker.md
  python/pdf-marker/Readme.md
Labels: size/M

#3339 fix: plugin group api position & team selector optional display
  projects/app/src/pages/account/info/index.tsx
  projects/app/src/pages/api/core/app/plugin/getPluginGroups.ts
  projects/app/src/web/core/app/api/plugin.ts
Labels: size/M

#3345 Update 4814.md
  docSite/content/zh-cn/docs/development/upgrading/4814.md
Labels: size/XS

#3347 perf: load plugin groups code;perf: system plugin schema;fix: special variables replace;perf: retry cron app job
  docSite/content/zh-cn/docs/development/upgrading/4815.md
  packages/global/common/system/utils.ts
  packages/global/core/dataset/type.d.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/service/core/app/plugin/systemPluginSchema.ts
  packages/service/core/app/plugin/type.d.ts
  packages/service/core/app/schema.ts
  packages/service/core/dataset/schema.ts
  packages/web/core/workflow/constants.ts
  projects/app/src/components/Layout/navbar.tsx
  projects/app/src/pages/account/components/AccountContainer.tsx
  projects/app/src/pages/account/info/index.tsx
  projects/app/src/pages/api/core/app/plugin/getPluginGroups.ts
  projects/app/src/service/common/system/cron.ts
  projects/app/src/service/core/app/utils.ts
  projects/app/src/web/core/app/api/plugin.ts
Labels: size/L

#3349 fix: loop node snapshot & infinite reload
  packages/web/hooks/useI18n.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/Loop/NodeLoop.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context/index.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/L

#3350 perf: snap code
  README.md
  packages/web/hooks/useI18n.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context/index.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/S

#3351 perf: speech check
  projects/app/package.json
  projects/app/src/pages/api/v1/audio/transcriptions.ts
  projects/app/src/pages/price/components/Points.tsx
  projects/app/src/web/common/utils/voice.ts
Labels: size/S

#3353 更新 navbarPhone.tsx
  projects/app/src/components/Layout/navbarPhone.tsx
Labels: size/XS

#3352 fix: auto send delay
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
Labels: size/M

#3360 perf: app cron job
  docSite/content/zh-cn/docs/development/upgrading/4815.md
  packages/global/core/chat/constants.ts
  packages/service/core/app/schema.ts
  packages/web/i18n/en/chat.json
  packages/web/i18n/zh-CN/chat.json
  packages/web/i18n/zh-Hant/chat.json
  projects/app/src/pages/api/admin/initv4815.ts
  projects/app/src/pages/api/core/app/version/publish.ts
  projects/app/src/service/core/app/utils.ts
Labels: size/L

#3361 remove test code
  projects/app/src/pages/api/core/app/version/publish.ts
Labels: size/XS

#3362 Update faq.md
  docSite/content/zh-cn/docs/development/faq.md
Labels: size/S

#3363 fix: icon
  docSite/content/zh-cn/docs/development/upgrading/4815.md
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/app/type/pluginLight.svg
  packages/web/core/workflow/constants.ts
Labels: size/S

#3364 update image
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
Labels: size/S

#3367 fix: emb page cannot save lng；feat: Add classify error log
  packages/service/core/workflow/dispatch/agent/classifyQuestion.ts
  packages/web/hooks/useI18n.ts
Labels: size/M

#3368 feat: Sync collection
  docSite/content/zh-cn/docs/development/upgrading/43.md
  docSite/content/zh-cn/docs/development/upgrading/44.md
  docSite/content/zh-cn/docs/development/upgrading/441.md
  docSite/content/zh-cn/docs/development/upgrading/442.md
  docSite/content/zh-cn/docs/development/upgrading/445.md
  docSite/content/zh-cn/docs/development/upgrading/46.md
  docSite/content/zh-cn/docs/development/upgrading/462.md
  docSite/content/zh-cn/docs/development/upgrading/463.md
  docSite/content/zh-cn/docs/development/upgrading/464.md
  docSite/content/zh-cn/docs/development/upgrading/469.md
  docSite/content/zh-cn/docs/development/upgrading/471.md
  docSite/content/zh-cn/docs/development/upgrading/481.md
  docSite/content/zh-cn/docs/development/upgrading/4810.md
  docSite/content/zh-cn/docs/development/upgrading/4812.md
  docSite/content/zh-cn/docs/development/upgrading/4815.md
  docSite/content/zh-cn/docs/development/upgrading/4816.md
  docSite/content/zh-cn/docs/development/upgrading/484.md
  docSite/content/zh-cn/docs/development/upgrading/485.md
  docSite/content/zh-cn/docs/development/upgrading/486.md
  docSite/content/zh-cn/docs/development/upgrading/488.md
  docSite/content/zh-cn/docs/development/upgrading/intro.md
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
  packages/global/core/dataset/api.d.ts
  packages/global/core/dataset/constants.ts
  packages/global/core/dataset/type.d.ts
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/collection/schema.ts
  packages/service/core/dataset/collection/utils.ts
  packages/service/core/dataset/schema.ts
  packages/service/core/dataset/training/controller.ts
  packages/web/components/common/MySelect/CronSelector.tsx
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/dataset.json
  projects/app/src/components/Select/AIModelSelector.tsx
  projects/app/src/pages/api/core/dataset/update.ts
  projects/app/src/pages/dataset/detail/components/Info/index.tsx
  projects/app/src/pages/dataset/detail/components/MetaDataCard.tsx
Labels: size/XL

#3369 feat: login limit
  packages/global/common/error/errorCode.ts
  packages/service/support/tmpData/controller.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/.env.template
  projects/app/src/pages/api/core/dataset/searchTest.ts
  projects/app/src/pages/api/support/user/account/loginByPassword.ts
  projects/app/src/pages/api/v1/audio/transcriptions.ts
Labels: size/L

#3376 perf: private app check
  projects/app/src/pages/api/core/app/list.ts
  projects/app/src/pages/api/core/dataset/list.ts
Labels: size/M

#3375 Update 4815.md
  docSite/content/zh-cn/docs/development/upgrading/4815.md
Labels: size/XS

#3377 perf: remove auto delete invalid item
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Reference.tsx
Labels: size/S

#3381 fix: cost tool tip display
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
Labels: size/S

#3382 Fix workflow detail
  docSite/content/zh-cn/docs/development/upgrading/4815.md
  docSite/content/zh-cn/docs/development/upgrading/4816.md
  packages/global/common/string/tools.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/web/components/common/MySelect/MultipleRowSelect.tsx
  packages/web/hooks/useI18n.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariableInput.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderInput.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/renderPluginInput.tsx
  projects/app/src/components/support/wallet/StandardPlanContentList.tsx
  projects/app/src/global/core/chat/api.d.ts
  projects/app/src/pages/api/core/app/transitionWorkflow.ts
  projects/app/src/pages/api/core/app/version/publish.ts
  projects/app/src/pages/api/core/chat/init.ts
  projects/app/src/pages/api/core/chat/outLink/init.ts
  projects/app/src/pages/api/core/chat/team/init.ts
  projects/app/src/pages/app/detail/components/Logs/DetailLogsModal.tsx
  projects/app/src/pages/app/detail/components/Logs/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/Loop/NodeLoop.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/Loop/NodeLoopStart.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Reference.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context/workflowInitContext.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context/workflowStatusContext.tsx
  projects/app/src/pages/app/detail/components/useChatTest.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/web/common/utils/i18n.ts
  projects/app/src/web/core/chat/context/chatItemContext.tsx
  projects/app/src/web/core/workflow/utils.ts
  projects/app/src/web/support/wallet/sub/constants.ts
Labels: size/XL

#3383 doc
  docSite/content/zh-cn/docs/development/upgrading/4815.md
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
  packages/web/components/common/Icon/icons/phoneTabbar/tool.svg
  projects/app/src/components/Layout/navbar.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariableInput.tsx
Labels: size/L

#3384 fix: render inputs
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/index.tsx
Labels: size/XS

#3385 Fix input
  docSite/content/zh-cn/docs/development/upgrading/4815.md
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/index.tsx
Labels: size/S

#3386 fix: list permission
  projects/app/src/pages/api/core/app/list.ts
  projects/app/src/pages/api/core/dataset/list.ts
Labels: size/XS

#3387 Update 4815.md
  docSite/content/zh-cn/docs/development/upgrading/4815.md
Labels: size/XS

#3388 Update 4815.md
  docSite/content/zh-cn/docs/development/upgrading/4815.md
Labels: size/XS

#3390 fix template
  projects/app/public/appMarketTemplates/CQ/template.json
  projects/app/public/appMarketTemplates/chatGuide/template.json
  projects/app/public/appMarketTemplates/google/template.json
  projects/app/public/appMarketTemplates/simpleDatasetChat/template.json
Labels: size/L

#3392 fix: add multiple selector null check
  packages/web/components/common/MySelect/MultipleRowSelect.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/XS

#3395 fix: sso redirect
  projects/app/src/pages/login/components/LoginForm/components/FormLayout.tsx
Labels: size/XS

#3399 fix: input form value type error
  packages/global/core/workflow/runtime/utils.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/web/components/common/Input/NumberInput/index.tsx
Labels: size/S

#3389 refactor: 知识块都改为markdown渲染
  projects/app/src/components/core/dataset/QuoteItem.tsx
Labels: size/XS

#3402 fix: handle sso state
  projects/app/src/pages/login/provider.tsx
Labels: size/XS

#3403 Add question guide config
  docSite/content/zh-cn/docs/development/configuration.md
  docSite/content/zh-cn/docs/development/openapi/chat.md
  docSite/content/zh-cn/docs/development/upgrading/4816.md
  packages/global/core/ai/prompt/agent.ts
  packages/global/core/app/constants.ts
  packages/global/core/app/type.d.ts
  packages/global/core/workflow/utils.ts
  packages/plugins/src/Doc2X/PDF2text/template.json
  packages/plugins/src/bing/template.json
  packages/plugins/src/databaseConnection/template.json
  packages/plugins/src/drawing/baseChart/template.json
  packages/plugins/src/google/template.json
  packages/plugins/src/wiki/template.json
  packages/service/core/ai/functions/createQuestionGuide.ts
  packages/service/core/app/schema.ts
  packages/web/components/common/Icon/icons/core/chat/QGFill.svg
  packages/web/components/common/Textarea/CustomPromptEditor/index.tsx
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/public/appMarketTemplates/CQ/template.json
  projects/app/public/appMarketTemplates/Chinese/template.json
  projects/app/public/appMarketTemplates/TranslateRobot/template.json
  projects/app/public/appMarketTemplates/animalLife/template.json
  projects/app/public/appMarketTemplates/chatGuide/template.json
  projects/app/public/appMarketTemplates/divination/template.json
  projects/app/public/appMarketTemplates/githubIssue/template.json
  projects/app/public/appMarketTemplates/google/template.json
  projects/app/public/appMarketTemplates/longTranslate/template.json
  projects/app/public/appMarketTemplates/simpleDatasetChat/template.json
  projects/app/public/appMarketTemplates/srt-translate/template.json
  projects/app/public/appMarketTemplates/stock/template.json
  projects/app/public/imgs/app/nextQuestion-icon.svg
  projects/app/public/imgs/app/nextQuestion.svg
  projects/app/public/imgs/model/hunyuan.svg
  projects/app/public/imgs/model/minimax.svg
  projects/app/src/components/core/app/QGConfig.tsx
  projects/app/src/components/core/app/QGSwitch.tsx
  projects/app/src/components/core/app/Tip.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Provider.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/pages/api/core/ai/agent/v2/createQuestionGuide.ts
  projects/app/src/pages/app/detail/components/SimpleApp/EditForm.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/useSnapshots.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeSystemConfig.tsx
  projects/app/src/pages/price/components/Points.tsx
  projects/app/src/web/core/app/templates.ts
Labels: size/XXL

#3404 修复：设置NEXT_PUBLIC_BASE_URL时，图片文件读取URL不正确
  packages/service/common/file/image/controller.ts
Labels: size/XS

#3393 Add wework dingtalk webhook
  packages/plugins/src/DingTalk/template.json
  packages/plugins/src/WeWork/template.json
Labels: size/XL

#3406 Perf webhook
  docSite/content/zh-cn/docs/development/openapi/chat.md
  docSite/content/zh-cn/docs/development/upgrading/4816.md
  docSite/content/zh-cn/docs/guide/workbench/workflow/sandbox.md
  packages/plugins/register.ts
  packages/plugins/src/DingTalkWebhook/template.json
  packages/plugins/src/WeWorkWebhook/template.json
  packages/plugins/src/feishu/template.json
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/plugins/dingding.svg
  packages/web/components/common/Icon/icons/plugins/qiwei.svg
  pnpm-lock.yaml
  projects/app/src/pages/api/core/chat/clearHistories.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/context/workflowStatusContext.tsx
  projects/sandbox/package.json
  projects/sandbox/src/sandbox/jsFn/crypto.ts
  projects/sandbox/src/sandbox/utils.ts
Labels: size/XL

#3409 Update 4815.md
  docSite/content/zh-cn/docs/development/upgrading/4815.md
Labels: size/XS

#3379 feat: add feishu & yuque dataset
  packages/global/common/error/code/dataset.ts
  packages/global/core/dataset/api.d.ts
  packages/global/core/dataset/apiDataset.d.ts
  packages/global/core/dataset/constants.ts
  packages/global/core/dataset/type.d.ts
  packages/service/core/dataset/read.ts
  packages/service/core/dataset/schema.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/dataset/feishuDatasetColor.svg
  packages/web/components/common/Icon/icons/core/dataset/feishuDatasetOutline.svg
  packages/web/components/common/Icon/icons/core/dataset/yuqueDatasetColor.svg
  packages/web/components/common/Icon/icons/core/dataset/yuqueDatasetOutline.svg
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/dataset.json
  projects/app/src/global/core/dataset/api.d.ts
  projects/app/src/pages/api/common/file/previewContent.ts
  projects/app/src/pages/api/core/dataset/apiDataset/list.ts
  projects/app/src/pages/api/core/dataset/collection/create/apiCollection.ts
  projects/app/src/pages/api/core/dataset/collection/read.ts
  projects/app/src/pages/api/core/dataset/create.ts
  projects/app/src/pages/api/core/dataset/detail.ts
  projects/app/src/pages/api/core/dataset/file/getPreviewChunks.ts
  projects/app/src/pages/api/core/dataset/update.ts
  projects/app/src/pages/dataset/detail/components/CollectionCard/Header.tsx
  projects/app/src/pages/dataset/detail/components/Import/diffSource/APIDataset.tsx
  projects/app/src/pages/dataset/detail/components/Info/components/EditApiServiceModal.tsx
  projects/app/src/pages/dataset/detail/components/Info/index.tsx
  projects/app/src/pages/dataset/list/component/CreateModal.tsx
  projects/app/src/pages/dataset/list/component/SideTag.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/service/core/dataset/apiDataset/controller.ts
  projects/app/src/web/core/dataset/api.ts
  projects/app/src/web/core/dataset/context/datasetPageContext.tsx
Labels: size/XL

#3408 feat: dingtalk sso support
  packages/global/common/system/types/index.d.ts
  packages/global/support/outLink/constant.ts
  packages/global/support/outLink/type.d.ts
  packages/global/support/user/constant.ts
  packages/global/support/wallet/usage/constants.ts
  packages/global/support/wallet/usage/tools.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/dingtalkFill.svg
  packages/web/i18n/en/user.json
  packages/web/i18n/zh-CN/user.json
  packages/web/i18n/zh-Hant/user.json
  projects/app/src/pages/login/components/LoginForm/components/FormLayout.tsx
  projects/app/src/pages/login/provider.tsx
Labels: size/M

#3415 feat: dingtalk bot integration
  docSite/assets/imgs/dingtalk-bot-1.png
  docSite/assets/imgs/dingtalk-bot-2.png
  docSite/assets/imgs/dingtalk-bot-3.png
  docSite/assets/imgs/dingtalk-bot-4.png
  docSite/assets/imgs/dingtalk-bot-5.png
  docSite/assets/imgs/dingtalk-bot-6.png
  docSite/assets/imgs/dingtalk-bot-7.png
  docSite/assets/imgs/dingtalk-bot-8.png
  docSite/content/zh-cn/docs/use-cases/external-integration/dingtalk.md
  packages/web/i18n/en/publish.json
  packages/web/i18n/zh-CN/publish.json
  packages/web/i18n/zh-Hant/publish.json
  projects/app/public/imgs/outlink/dingtalk-copylink-instruction.png
  projects/app/src/pages/api/support/outLink/dingtalk/[token].ts
  projects/app/src/pages/app/detail/components/Publish/DingTalk/DingTalkEditModal.tsx
  projects/app/src/pages/app/detail/components/Publish/DingTalk/index.tsx
  projects/app/src/pages/app/detail/components/Publish/index.tsx
  projects/app/src/web/core/app/constants.ts
Labels: size/XL

#3413 feat:sear XNG服务
  docSite/assets/imgs/searxng_plugin_guide1.png
  docSite/assets/imgs/searxng_plugin_guide2.png
  docSite/assets/imgs/searxng_plugin_guide3.png
  docSite/assets/imgs/searxng_plugin_guide4.png
  docSite/assets/imgs/searxng_plugin_guide5.png
  docSite/assets/imgs/searxng_plugin_guide6.png
  docSite/assets/imgs/searxng_plugin_guide7.png
  docSite/content/zh-cn/docs/guide/plugins/searxng_plugin_guide.md
  packages/plugins/package.json
  packages/plugins/register.ts
  packages/plugins/src/searchXNG/index.ts
  packages/plugins/src/searchXNG/template.json
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/workflow/template/searxng.svg
Labels: size/XL

#3423 feat: delete node tracks
  packages/service/common/middle/tracks/utils.ts
  projects/app/src/pages/api/core/app/del.ts
Labels: size/M

#3424 fix: dingtalk bot GET verification
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/src/pages/api/support/outLink/dingtalk/[token].ts
Labels: size/S

#3426 4.8.16 test: fix: plugin inputs render；fix: ui offset
  docSite/content/zh-cn/docs/development/upgrading/4816.md
  packages/global/core/chat/type.d.ts
  packages/service/core/chat/chatSchema.ts
  packages/service/core/chat/saveChat.ts
  packages/web/components/common/MyModal/index.tsx
  projects/app/src/pages/api/core/chat/init.ts
  projects/app/src/pages/api/core/chat/outLink/init.ts
  projects/app/src/pages/api/core/chat/team/init.ts
  projects/app/src/pages/api/support/outLink/dingtalk/[token].ts
  projects/app/src/pages/api/support/outLink/offiaccount/[token].ts
  projects/app/src/pages/app/detail/components/Logs/DetailLogsModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/index.tsx
  projects/app/src/web/styles/reactflow.scss
Labels: size/M

#3429 feat: menu all folder
  docSite/content/zh-cn/docs/development/upgrading/4816.md
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh-CN/workflow.json
  packages/web/i18n/zh-Hant/workflow.json
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/ContextMenu.tsx
Labels: size/L

#3436 add sso auto login config
  packages/global/common/system/types/index.d.ts
  projects/app/src/pages/login/components/LoginForm/components/FormLayout.tsx
  projects/app/src/web/context/useInitApp.ts
Labels: size/XXL

#3427 perf: add contact phone number in invoice header
  packages/global/support/user/team/type.d.ts
  packages/web/i18n/en/account_bill.json
  packages/web/i18n/zh-CN/account_bill.json
  packages/web/i18n/zh-Hant/account_bill.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/pages/account/bill/components/ApplyInvoiceModal.tsx
  projects/app/src/pages/account/bill/components/InvoiceHeaderForm.tsx
  projects/app/src/pages/account/bill/components/InvoiceTable.tsx
Labels: size/M

#3437 4.8.16 test
  packages/web/i18n/en/account_bill.json
  packages/web/i18n/zh-CN/account_bill.json
  packages/web/i18n/zh-Hant/account_bill.json
  projects/app/src/pages/account/bill/components/ApplyInvoiceModal.tsx
  projects/app/src/pages/account/bill/components/InvoiceHeaderForm.tsx
  projects/app/src/pages/login/components/LoginForm/components/FormLayout.tsx
  projects/app/src/pages/login/index.tsx
  projects/app/src/web/context/useInitApp.ts
Labels: size/L

#3439 perf: pay ui；update version doc
  docSite/content/zh-cn/docs/development/upgrading/4816.md
  packages/web/components/common/LightTip/index.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/package.json
  projects/app/public/docs/versionIntro.md
  projects/app/src/components/support/wallet/NotSufficientModal/index.tsx
  projects/app/src/components/support/wallet/QRCodePayModal.tsx
Labels: size/M

#3445 4.8.16 test
  packages/web/components/common/MySelect/MultipleRowSelect.tsx
  projects/app/src/components/Select/AIModelSelector.tsx
Labels: size/S

#3446 perf: schema indexes
  packages/service/core/chat/chatItemSchema.ts
  packages/service/support/user/schema.ts
  packages/service/support/wallet/usage/schema.ts
Labels: size/S

#3447 fix: pc check
  packages/web/common/system/nextjs.ts
  packages/web/context/useSystem.tsx
Labels: size/XS

#3451 perf: ai param config
  docSite/assets/imgs/image-51.png
  docSite/assets/imgs/image-52.png
  docSite/assets/imgs/image-53.png
  docSite/assets/imgs/image-54.png
  docSite/content/zh-cn/docs/guide/course/ai_settings.md
  packages/web/components/common/Image/PhotoView.tsx
  packages/web/components/common/MySlider/InputSlider.tsx
  packages/web/context/useSystem.tsx
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/core/ai/AISettingModal/index.tsx
  projects/app/src/components/core/ai/SettingLLMModel/index.tsx
  projects/app/src/pages/app/list/components/TemplateMarketModal.tsx
  projects/app/src/web/support/wallet/bill/invoice/api.ts
Labels: size/L

#3452 update doc
  docSite/content/zh-cn/docs/development/upgrading/4816.md
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
Labels: size/M

#3453 feat: model select support close params;perf: dataset params slider;update doc
  docSite/content/zh-cn/docs/development/upgrading/4817.md
  docSite/content/zh-cn/docs/guide/course/ai_settings.md
  docSite/content/zh-cn/docs/use-cases/external-integration/official_account.md
  packages/global/core/app/type.d.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/service/core/ai/utils.ts
  packages/service/core/dataset/controller.ts
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/web/components/common/MySlider/InputSlider.tsx
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/core/ai/AISettingModal/index.tsx
  projects/app/src/components/core/ai/SettingLLMModel/index.tsx
  projects/app/src/components/core/app/DatasetParamsModal.tsx
  projects/app/src/components/core/dataset/SearchParamsTip.tsx
  projects/app/src/pages/api/core/app/del.ts
  projects/app/src/pages/api/core/dataset/delete.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SettingLLMModel.tsx
Labels: size/L

#3459 perf: model provider show; perf: get init data buffer
  docSite/assets/imgs/image-55.png
  docSite/assets/imgs/image-56.png
  docSite/assets/imgs/image-57.png
  docSite/assets/imgs/image-58.png
  docSite/content/zh-cn/docs/development/upgrading/4817.md
  docSite/content/zh-cn/docs/shopping_cart/intro.md
  packages/global/common/system/types/index.d.ts
  packages/global/core/ai/model.d.ts
  packages/global/core/ai/model.ts
  packages/global/core/ai/provider.ts
  packages/service/common/system/config/controller.ts
  packages/service/core/ai/utils.ts
  packages/service/core/plugin/type.d.ts
  packages/service/type.d.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/model.svg
  packages/web/components/common/Icon/icons/model/gemini.svg
  packages/web/components/common/Icon/icons/model/groq.svg
  packages/web/components/common/Icon/icons/model/hunyuan.svg
  packages/web/components/common/Icon/icons/model/mistral.svg
  packages/web/components/common/Icon/icons/model/ollama.svg
  packages/web/components/common/Icon/icons/model/yi.svg
  packages/web/components/common/Icon/icons/support/user/individuation.svg
  packages/web/components/common/MySelect/index.tsx
  packages/web/i18n/en/account.json
  packages/web/i18n/en/account_setting.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/user.json
  packages/web/i18n/zh-CN/account.json
  packages/web/i18n/zh-CN/account_setting.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/user.json
  packages/web/i18n/zh-Hant/account.json
  packages/web/i18n/zh-Hant/account_setting.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/user.json
  packages/web/types/i18next.d.ts
  projects/app/src/components/Layout/index.tsx
  projects/app/src/components/Layout/navbar.tsx
  projects/app/src/components/Layout/navbarPhone.tsx
  projects/app/src/components/Select/AIModelSelector.tsx
  projects/app/src/components/core/ai/AISettingModal/index.tsx
  projects/app/src/components/core/ai/ModelTable/index.tsx
  projects/app/src/components/support/wallet/StandardPlanContentList.tsx
  projects/app/src/global/common/api/systemRes.d.ts
  projects/app/src/pages/account/components/AccountContainer.tsx
  projects/app/src/pages/account/info/index.tsx
  projects/app/src/pages/account/model/index.tsx
  projects/app/src/pages/account/setting.tsx
  projects/app/src/pages/api/common/system/getInitData.ts
  projects/app/src/pages/price/components/ExtraPlan.tsx
  projects/app/src/pages/price/components/FAQ.tsx
  projects/app/src/pages/price/components/Points.tsx
  projects/app/src/service/common/system/index.ts
  projects/app/src/types/index.d.ts
  projects/app/src/web/common/system/api.ts
  projects/app/src/web/common/system/staticData.ts
  projects/app/src/web/common/system/useSystemStore.ts
  projects/app/src/web/context/useInitApp.ts
Labels: size/XL

#3443 feat: add third party account config
  packages/global/common/system/types/index.d.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/support/user/team/controller.d.ts
  packages/global/support/user/team/type.d.ts
  packages/global/support/user/type.d.ts
  packages/service/core/ai/config.ts
  packages/service/core/workflow/dispatch/agent/classifyQuestion.ts
  packages/service/core/workflow/dispatch/agent/extract.ts
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/loop/runLoop.ts
  packages/service/core/workflow/dispatch/tools/runUpdateVar.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/service/support/permission/auth/team.ts
  packages/service/support/user/controller.ts
  packages/service/support/user/team/controller.ts
  packages/service/support/user/team/teamSchema.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/thirdParty.svg
  packages/web/components/common/Icon/icons/common/variable.svg
  packages/web/components/common/Icon/icons/support/account/laf.svg
  packages/web/components/common/Textarea/PromptEditor/plugins/VariablePlugin/components/Variable.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/VariablePlugin/index.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/VariablePlugin/node.ts
  packages/web/components/common/Textarea/PromptEditor/plugins/VariablePlugin/node.tsx
  packages/web/components/common/Textarea/PromptEditor/utils.ts
  packages/web/i18n/en/account.json
  packages/web/i18n/en/account_info.json
  packages/web/i18n/en/account_thirdParty.json
  packages/web/i18n/zh-CN/account.json
  packages/web/i18n/zh-CN/account_info.json
  packages/web/i18n/zh-CN/account_thirdParty.json
  packages/web/i18n/zh-Hant/account.json
  packages/web/i18n/zh-Hant/account_info.json
  packages/web/i18n/zh-Hant/account_thirdParty.json
  packages/web/types/i18next.d.ts
  projects/app/src/components/Layout/navbar.tsx
  projects/app/src/components/support/laf/LafAccountModal.tsx
  projects/app/src/pages/account/components/AccountContainer.tsx
  projects/app/src/pages/account/info/index.tsx
  projects/app/src/pages/account/thirdParty/components/OpenAIAccountModal.tsx
  projects/app/src/pages/account/thirdParty/components/WorkflowVariableModal.tsx
  projects/app/src/pages/account/thirdParty/index.tsx
  projects/app/src/pages/api/admin/initv4817.ts
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/core/workflow/debug.ts
  projects/app/src/pages/api/support/user/account/update.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Textarea.tsx
  projects/app/src/service/core/app/utils.ts
  projects/app/src/service/support/permission/auth/outLink.ts
  projects/app/src/service/support/permission/auth/team.ts
  projects/app/src/types/user.d.ts
Labels: size/XXL

#3461 4.8.17 test
  docSite/content/zh-cn/docs/development/upgrading/4817.md
  packages/global/common/system/types/index.d.ts
  packages/global/support/user/team/controller.d.ts
  packages/global/support/user/team/type.d.ts
  packages/service/core/chat/utils.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/loop/runLoop.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/service/support/permission/auth/team.ts
  packages/service/support/user/team/controller.ts
  packages/web/components/common/Textarea/PromptEditor/plugins/VariableLabelPlugin/components/VariableLabel.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/VariablePlugin/components/Variable.tsx
  packages/web/i18n/en/account_thirdParty.json
  packages/web/i18n/zh-CN/account_thirdParty.json
  packages/web/i18n/zh-Hant/account_thirdParty.json
  projects/app/.env.template
  projects/app/src/pages/account/components/AccountContainer.tsx
  projects/app/src/pages/account/team/index.tsx
  projects/app/src/pages/account/thirdParty/components/WorkflowVariableModal.tsx
  projects/app/src/pages/account/thirdParty/index.tsx
  projects/app/src/pages/api/support/user/account/tokenLogin.ts
  projects/app/src/pages/api/support/user/team/thirtdParty/checkUsage.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeLaf.tsx
  projects/app/src/web/common/api/request.ts
Labels: size/XL

#3434 feat: add template config
  packages/global/core/app/type.d.ts
  packages/service/core/app/templates/templateSchema.ts
  packages/service/core/app/templates/templateTypeSchema.ts
  packages/service/type.d.ts
  packages/templates/README.md
  packages/templates/package.json
  packages/templates/register.ts
  packages/templates/src/CQ/template.json
  packages/templates/src/Chinese/template.json
  packages/templates/src/TranslateRobot/template.json
  packages/templates/src/animalLife/template.json
  packages/templates/src/chatGuide/template.json
  packages/templates/src/divination/template.json
  packages/templates/src/flux/template.json
  packages/templates/src/githubIssue/template.json
  packages/templates/src/google/template.json
  packages/templates/src/longTranslate/template.json
  packages/templates/src/plugin-dalle/template.json
  packages/templates/src/plugin-feishu/template.json
  packages/templates/src/simpleDatasetChat/template.json
  packages/templates/src/srt-translate/template.json
  packages/templates/src/stock/template.json
  packages/templates/src/timeBot/template.json
  packages/templates/tsconfig.json
  packages/templates/type.d.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/layer.svg
  packages/web/components/common/Icon/icons/common/templateMarket.svg
  packages/web/components/common/Icon/icons/core/app/templates/TranslateRobot.svg
  packages/web/components/common/Icon/icons/core/app/templates/animalLife.svg
  packages/web/components/common/Icon/icons/core/app/templates/chinese.svg
  packages/web/components/common/Icon/icons/core/app/templates/divination.svg
  packages/web/components/common/Icon/icons/core/app/templates/flux.svg
  packages/web/components/common/Icon/icons/core/app/templates/githubIssue.svg
  packages/web/components/common/Icon/icons/core/app/templates/google.svg
  packages/web/components/common/Icon/icons/core/app/templates/plugin-dalle.svg
  packages/web/components/common/Icon/icons/core/app/templates/plugin-feishu.svg
  packages/web/components/common/Icon/icons/core/app/templates/stock.svg
  packages/web/core/workflow/constants.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/common.json
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/src/instrumentation.ts
  projects/app/src/pages/api/core/app/template/detail.ts
  projects/app/src/pages/api/core/app/template/list.ts
  projects/app/src/pages/app/list/components/CreateModal.tsx
  projects/app/src/pages/app/list/components/TemplateMarketModal.tsx
  projects/app/src/service/common/system/index.ts
  projects/app/src/service/core/app/template.ts
  projects/app/src/web/core/app/api/template.ts
Labels: size/XL

#3464 perf: Mongo visutal field
  docSite/content/zh-cn/docs/development/openapi/dataset.md
  docSite/content/zh-cn/docs/development/upgrading/4817.md
  packages/global/common/system/types/index.d.ts
  packages/global/core/app/type.d.ts
  packages/global/core/dataset/collection/utils.ts
  packages/global/core/dataset/type.d.ts
  packages/global/support/outLink/type.d.ts
  packages/global/support/permission/type.d.ts
  packages/global/support/user/team/controller.d.ts
  packages/global/support/user/team/type.d.ts
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/collection/schema.ts
  packages/service/core/dataset/collection/utils.ts
  packages/service/core/dataset/controller.ts
  packages/service/core/dataset/data/schema.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/core/dataset/training/controller.ts
  packages/service/support/outLink/schema.ts
  packages/service/support/permission/auth/team.ts
  packages/service/support/permission/controller.ts
  packages/service/support/permission/dataset/auth.ts
  packages/service/support/permission/memberGroup/controllers.ts
  packages/service/support/permission/memberGroup/groupMemberSchema.ts
  packages/service/support/permission/schema.ts
  packages/service/support/user/team/controller.ts
  packages/service/support/user/team/teamMemberSchema.ts
  packages/templates/register.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/.env.template
  projects/app/src/components/core/app/DatasetParamsModal.tsx
  projects/app/src/components/core/dataset/SearchParamsTip.tsx
  projects/app/src/pages/api/common/file/read.ts
  projects/app/src/pages/api/common/file/read/[filename].ts
  projects/app/src/pages/api/core/app/template/list.ts
  projects/app/src/pages/api/core/chat/outLink/init.ts
  projects/app/src/pages/api/core/dataset/collection/create/reTrainingCollection.ts
  projects/app/src/pages/api/core/dataset/collection/delete.ts
  projects/app/src/pages/api/core/dataset/collection/detail.ts
  projects/app/src/pages/api/core/dataset/collection/read.ts
  projects/app/src/pages/api/core/dataset/collection/update.ts
  projects/app/src/pages/api/core/dataset/data/insertData.ts
  projects/app/src/pages/api/core/dataset/data/list.ts
  projects/app/src/pages/api/core/dataset/data/pushData.ts
  projects/app/src/pages/api/core/dataset/data/update.ts
  projects/app/src/pages/api/core/dataset/data/v2/list.ts
  projects/app/src/pages/api/support/user/account/tokenLogin.ts
  projects/app/src/pages/app/list/components/CreateModal.tsx
  projects/app/src/pages/app/list/components/TemplateMarketModal.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/dataset/detail/components/InputDataModal.tsx
  projects/app/src/service/common/system/index.ts
  projects/app/src/web/core/dataset/constants.ts
Labels: size/XL

#3472 perf: auth layout；perf: auto save
  docSite/content/zh-cn/docs/development/upgrading/4817.md
  packages/service/core/app/version/schema.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-Hant/app.json
  projects/app/src/components/Layout/auth.tsx
  projects/app/src/components/Layout/index.tsx
  projects/app/src/global/core/app/api.d.ts
  projects/app/src/pages/account/components/TeamSelector.tsx
  projects/app/src/pages/account/info/index.tsx
  projects/app/src/pages/api/core/app/version/publish.ts
  projects/app/src/pages/app/detail/components/SimpleApp/Header.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context/workflowStatusContext.tsx
Labels: size/L

#3471 docs: fix typo
  docSite/content/zh-cn/docs/guide/workbench/intro.md
  docSite/content/zh-cn/docs/guide/workbench/workflow/tool.md
Labels: size/XS

#3475 fix: template guide display & http input support external variables
  packages/global/core/app/type.d.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeHttp/index.tsx
  projects/app/src/pages/app/list/components/TemplateMarketModal.tsx
Labels: size/L

#3478 perf: auto save;fix: ifelse checker line break;
  README.md
  docSite/content/zh-cn/docs/development/upgrading/4817.md
  packages/global/core/workflow/runtime/utils.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/tools/runIfElse.ts
  packages/service/core/workflow/dispatch/tools/runUpdateVar.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/web/components/common/Textarea/PromptEditor/plugins/VariableLabelPlugin/components/VariableLabel.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeVariableUpdate.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Textarea.tsx
Labels: size/L

#3476 Silicon cloud doc
  README.md
  docSite/assets/imgs/image-59.png
  docSite/assets/imgs/image-60.png
  docSite/assets/imgs/image-61.png
  docSite/assets/imgs/image-62.png
  docSite/assets/imgs/image-63.png
  docSite/assets/imgs/image-64.png
  docSite/assets/imgs/image-65.png
  docSite/assets/imgs/image-66.png
  docSite/assets/imgs/image-67.png
  docSite/assets/imgs/image-68.png
  docSite/assets/imgs/image-69.png
  docSite/assets/imgs/image-70.png
  docSite/assets/imgs/image-71.png
  docSite/assets/imgs/image-72.png
  docSite/assets/imgs/image-73.png
  docSite/assets/imgs/image-74.png
  docSite/assets/imgs/image-75.png
  docSite/assets/imgs/image-76.png
  docSite/assets/imgs/image-77.png
  docSite/assets/imgs/image-78.png
  docSite/assets/imgs/image-79.png
  docSite/assets/imgs/image-80.png
  docSite/assets/imgs/image-81.png
  docSite/assets/imgs/image-82.png
  docSite/content/zh-cn/docs/development/configuration.md
  docSite/content/zh-cn/docs/development/custom-models/chatglm2-m3e.md
  docSite/content/zh-cn/docs/development/custom-models/xinference.md
  docSite/content/zh-cn/docs/development/docker.md
  docSite/content/zh-cn/docs/development/faq.md
  docSite/content/zh-cn/docs/development/modelConfig/_index.md
  docSite/content/zh-cn/docs/development/modelConfig/one-api.md
  docSite/content/zh-cn/docs/development/modelConfig/siliconCloud.md
  docSite/content/zh-cn/docs/development/one-api.md
  docSite/content/zh-cn/docs/development/sealos.md
  docSite/content/zh-cn/docs/guide/workbench/workflow/ai_chat.md
  packages/web/i18n/en/app.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-Hant/app.json
  projects/app/data/config.json
Labels: size/XL

#3480 4.8.17 test
  packages/web/components/common/Avatar/index.tsx
  packages/web/components/common/DndDrag/index.tsx
  packages/web/components/common/Input/NumberInput/index.tsx
  packages/web/components/common/Input/SearchInput/index.tsx
  packages/web/components/common/MyBox/index.tsx
  packages/web/components/common/MyLoading/index.tsx
  packages/web/components/common/MySlider/InputSlider.tsx
  packages/web/components/common/MyTooltip/QuestionTip.tsx
  projects/app/src/components/Select/AIModelSelector.tsx
  projects/app/src/components/core/ai/AISettingModal/index.tsx
  projects/app/src/components/core/ai/ModelTable/index.tsx
  projects/app/src/components/support/wallet/StandardPlanContentList.tsx
  projects/app/src/pages/account/info/index.tsx
Labels: size/L

#3481 fix: ts
  packages/web/components/common/DndDrag/index.tsx
Labels: size/XS

#3473 simple app tool select
  packages/global/core/workflow/template/system/workflowStart.ts
  packages/global/core/workflow/type/node.d.ts
  packages/service/core/app/plugin/controller.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/arrowRight.svg
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/styles/theme.ts
  projects/app/src/components/common/Modal/UseGuideModal.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/renderPluginInput.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/EditForm.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/components/ConfigToolModal.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/components/ToolSelect.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/components/ToolSelectModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/app/list/components/TemplateMarketModal.tsx
  projects/app/src/pages/toolkit/components/PluginCard.tsx
  projects/app/src/web/core/app/api.ts
  projects/app/src/web/core/app/constants.ts
  projects/app/src/web/core/app/utils.ts
Labels: size/XXL

#3484 perf: too selector modal
  docSite/content/zh-cn/docs/development/upgrading/4817.md
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/components/ToolSelectModal.tsx
Labels: size/L

#3486 toolkit plugin card course url
  packages/global/core/workflow/type/node.d.ts
  projects/app/src/pages/api/core/app/plugin/getSystemPluginTemplates.ts
  projects/app/src/pages/toolkit/components/PluginCard.tsx
Labels: size/S

#3488 update doc
  docSite/content/zh-cn/docs/development/upgrading/4817.md
Labels: size/S

#3493 V4.8.17 feature
  docSite/content/zh-cn/docs/development/upgrading/4817.md
  packages/global/core/ai/model.d.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/support/wallet/bill/type.d.ts
  packages/global/support/wallet/usage/type.d.ts
  packages/plugins/src/feishu/template.json
  packages/service/common/system/tools.ts
  packages/service/core/ai/functions/createQuestionGuide.ts
  packages/service/core/ai/functions/queryExtension.ts
  packages/service/core/ai/model.ts
  packages/service/core/workflow/dispatch/agent/classifyQuestion.ts
  packages/service/core/workflow/dispatch/agent/extract.ts
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/agent/runTool/type.d.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/core/workflow/dispatch/dataset/search.ts
  packages/service/core/workflow/dispatch/plugin/run.ts
  packages/service/core/workflow/dispatch/plugin/runApp.ts
  packages/service/core/workflow/dispatch/tools/queryExternsion.ts
  packages/service/support/wallet/usage/controller.ts
  packages/service/support/wallet/usage/schema.ts
  packages/service/support/wallet/usage/utils.ts
  packages/service/type.d.ts
  packages/web/i18n/en/account_usage.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/account_usage.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/account_usage.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/core/ai/AISettingModal/index.tsx
  projects/app/src/components/core/ai/ModelTable/index.tsx
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/pages/account/usage/UsageDetail.tsx
  projects/app/src/pages/api/core/ai/agent/createQuestionGuide.ts
  projects/app/src/pages/api/core/ai/agent/v2/createQuestionGuide.ts
  projects/app/src/pages/api/core/dataset/data/insertData.ts
  projects/app/src/pages/api/core/dataset/data/update.ts
  projects/app/src/pages/api/core/dataset/searchTest.ts
  projects/app/src/pages/api/v1/embeddings.ts
  projects/app/src/pages/dataset/detail/components/Import/Context.tsx
  projects/app/src/service/events/generateQA.ts
  projects/app/src/service/events/generateVector.ts
  projects/app/src/service/support/wallet/usage/push.ts
Labels: size/XL

#3380 feat: org CRUD
  packages/global/common/error/code/team.ts
  packages/global/common/file/image/constants.ts
  packages/global/common/system/constants.ts
  packages/global/core/app/collaborator.d.ts
  packages/global/core/dataset/collaborator.d.ts
  packages/global/support/permission/collaborator.d.ts
  packages/global/support/permission/type.d.ts
  packages/global/support/user/team/org/api.d.ts
  packages/global/support/user/team/org/constant.ts
  packages/global/support/user/team/org/type.d.ts
  packages/service/support/permission/auth/org.ts
  packages/service/support/permission/controller.ts
  packages/service/support/permission/inheritPermission.ts
  packages/service/support/permission/org/controllers.ts
  packages/service/support/permission/org/orgMemberSchema.ts
  packages/service/support/permission/org/orgSchema.ts
  packages/service/support/permission/schema.ts
  packages/service/support/user/team/controller.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/downArrowFill.svg
  packages/web/i18n/en/account_team.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/account_team.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/account_team.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/public/imgs/avatar/defaultOrgAvatar.svg
  projects/app/src/components/support/permission/MemberManager/AddMemberModal.tsx
  projects/app/src/components/support/permission/MemberManager/ManageModal.tsx
  projects/app/src/components/support/permission/MemberManager/MemberListCard.tsx
  projects/app/src/components/support/permission/MemberManager/context.tsx
  projects/app/src/pages/account/team/components/OrgManage/IconButton.tsx
  projects/app/src/pages/account/team/components/OrgManage/OrgInfoModal.tsx
  projects/app/src/pages/account/team/components/OrgManage/OrgMemberModal.tsx
  projects/app/src/pages/account/team/components/OrgManage/OrgMoveModal.tsx
  projects/app/src/pages/account/team/components/OrgManage/OrgTree.tsx
  projects/app/src/pages/account/team/components/OrgManage/index.tsx
  projects/app/src/pages/account/team/components/context.tsx
  projects/app/src/pages/account/team/index.tsx
  projects/app/src/pages/app/detail/components/InfoModal.tsx
  projects/app/src/pages/app/list/components/List.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/pages/dataset/detail/components/Info/index.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/web/support/user/team/org/api.ts
  projects/app/src/web/support/user/useUserStore.ts
Labels: size/XXL

#3496 update doc
  docSite/content/zh-cn/docs/development/upgrading/4817.md
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
Labels: size/M

#3497 update config.json
  docSite/content/zh-cn/docs/development/configuration.md
  projects/app/data/config.json
Labels: size/XS

#3499 perf: Team org ui
  docSite/content/zh-cn/docs/development/upgrading/4818.md
  packages/global/support/user/team/org/api.d.ts
  packages/global/support/user/team/type.d.ts
  packages/service/support/permission/auth/org.ts
  packages/service/support/permission/org/controllers.ts
  packages/service/support/permission/org/orgSchema.ts
  packages/service/support/user/team/controller.ts
  projects/app/public/js/iframe.js
  projects/app/src/pages/account/team/components/GroupManage/index.tsx
  projects/app/src/pages/account/team/components/OrgManage/IconButton.tsx
  projects/app/src/pages/account/team/components/OrgManage/OrgInfoModal.tsx
  projects/app/src/pages/account/team/components/OrgManage/OrgMemberManageModal.tsx
  projects/app/src/pages/account/team/components/OrgManage/OrgMoveModal.tsx
  projects/app/src/pages/account/team/components/OrgManage/OrgTree.tsx
  projects/app/src/pages/account/team/components/OrgManage/index.tsx
  projects/app/src/pages/account/team/components/context.tsx
  projects/app/src/pages/account/team/index.tsx
  projects/app/src/pages/app/detail/components/InfoModal.tsx
  projects/app/src/pages/app/list/components/List.tsx
  projects/app/src/web/support/user/team/org/api.ts
  projects/app/src/web/support/user/useUserStore.ts
Labels: size/XXL

#3498 feat: org auth for app & dataset
  packages/service/support/permission/controller.ts
  packages/service/support/permission/org/controllers.ts
  projects/app/src/components/support/permission/MemberManager/AddMemberModal.tsx
  projects/app/src/pages/api/core/app/list.ts
  projects/app/src/pages/api/core/dataset/list.ts
Labels: size/L

#3500 perf: org permission check
  packages/service/support/permission/controller.ts
  packages/service/support/permission/memberGroup/controllers.ts
  packages/service/support/permission/org/controllers.ts
  packages/service/support/permission/org/orgMemberSchema.ts
  projects/app/src/pages/api/core/app/list.ts
  projects/app/src/pages/api/core/dataset/list.ts
Labels: size/L

#3502 Fix tool call, parameter error when running the same tool. Temporarily change to serial, cancel parallel.
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/index.ts
Labels: size/L

#3483 feat: support dataset changeOwner
  projects/app/src/pages/dataset/list/component/List.tsx
  projects/app/src/web/core/dataset/api.ts
Labels: size/S
