Repository labring/FastGPT, pull requests merged in 2024-09, with the labels that each got.

#2580 Style-dataset-2.5
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/book.svg
  packages/web/components/common/Icon/icons/visible.svg
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/common.json
  projects/app/src/components/common/ParentPaths/index.tsx
  projects/app/src/components/core/app/InputGuideConfig.tsx
  projects/app/src/components/core/dataset/QuoteItem.tsx
  projects/app/src/pages/dataset/detail/components/DataCard.tsx
  projects/app/src/pages/dataset/detail/components/InputDataModal.tsx
  projects/app/src/pages/dataset/detail/components/MetaDataCard.tsx
  projects/app/src/pages/dataset/detail/components/NavBar.tsx
  projects/app/src/pages/dataset/detail/components/styles.module.scss
  projects/app/src/web/core/dataset/context/datasetPageContext.tsx
Labels: size/XL

#2590 fix: plugin input type options & save button
  projects/app/src/pages/app/detail/components/Plugin/Header.tsx
  projects/app/src/pages/app/detail/components/Workflow/Header.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/SaveAndPublish.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputEditModal.tsx
Labels: size/S

#2592 perf: workflow&plugins json config import and export
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/importLight.svg
  packages/web/components/common/Icon/icons/configmap.svg
  packages/web/components/common/Icon/icons/file/uploadFile.svg
  packages/web/components/common/MyMenu/index.tsx
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/common.json
  projects/app/src/pages/app/detail/components/WorkflowComponents/AppCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/ImportSettings.tsx
Labels: size/L

#2594 perf: user default avatar
  packages/service/support/user/schema.ts
  projects/app/public/imgs/avatar/AdoraAvatar.svg
  projects/app/public/imgs/avatar/BlueAvatar.svg
  projects/app/public/imgs/avatar/BrightBlueAvatar.svg
  projects/app/public/imgs/avatar/GrayModernAvatar.svg
  projects/app/public/imgs/avatar/GreenAvatar.svg
  projects/app/public/imgs/avatar/OrangeAvatar.svg
  projects/app/public/imgs/avatar/PurpleAvatar.svg
  projects/app/public/imgs/avatar/RedAvatar.svg
  projects/app/public/imgs/avatar/RoyalBlueAvatar.svg
  projects/app/public/imgs/avatar/TealAvatar.svg
Labels: size/S

#2596 4.8.10 workflow perf
  docSite/content/zh-cn/docs/development/upgrading/4810.md
  packages/global/core/workflow/runtime/type.d.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/plugin/run.ts
  packages/service/core/workflow/dispatch/plugin/runApp.ts
  packages/service/support/wallet/sub/utils.ts
  packages/web/components/common/MyMenu/index.tsx
  packages/web/components/common/MySelect/MultipleRowSelect.tsx
  packages/web/styles/theme.ts
  projects/app/src/components/core/ai/SettingLLMModel/index.tsx
  projects/app/src/pages/account/components/Info/index.tsx
  projects/app/src/pages/account/components/UsageTable.tsx
  projects/app/src/pages/app/detail/components/Plugin/Header.tsx
  projects/app/src/pages/app/detail/components/RouteTab.tsx
  projects/app/src/pages/app/detail/components/Workflow/Header.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/AppCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SelectApp.tsx
  projects/app/src/pages/dataset/detail/components/DataCard.tsx
Labels: size/L

#2601 4.8.10 test
  packages/global/core/chat/adapt.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/template/constants.ts
  packages/global/core/workflow/template/system/runApp.ts
  packages/global/core/workflow/utils.ts
  packages/global/package.json
  packages/service/core/chat/utils.ts
  packages/service/core/workflow/dispatch/abandoned/runApp.ts
  packages/service/core/workflow/dispatch/dataset/search.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/interactive/userSelect.ts
  packages/service/core/workflow/dispatch/plugin/run.ts
  packages/service/core/workflow/dispatch/plugin/runApp.ts
  packages/service/core/workflow/dispatch/tools/customFeedback.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  packages/service/core/workflow/dispatch/tools/readFiles.ts
  packages/service/core/workflow/dispatch/tools/runLaf.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/service/core/workflow/utils.ts
  packages/service/support/permission/app/auth.ts
  packages/web/components/common/Textarea/PromptEditor/type.d.ts
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/workflow.json
  pnpm-lock.yaml
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/core/workflow/debug.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/Publish/FeiShu/index.tsx
  projects/app/src/pages/app/detail/components/Publish/OffiAccount/index.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/EditForm.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeHttp/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeIfElse/ListItem.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeVariableUpdate.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeWorkflowStart.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/JsonEditor.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SettingQuotePrompt.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderOutput/Label.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderOutput/index.tsx
  projects/app/src/service/core/app/utils.ts
  projects/app/src/web/core/app/utils.ts
  projects/app/src/web/core/workflow/adapt.ts
  projects/app/src/web/core/workflow/utils.ts
Labels: size/XL

#2604 Update official_account.md
  docSite/content/zh-cn/docs/course/official_account.md
Labels: size/S

#2600 perf: modal add size props&menu add menuItemStyles
  packages/web/components/common/MyMenu/index.tsx
  packages/web/components/common/MyModal/index.tsx
  packages/web/styles/theme.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/AppCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/ImportSettings.tsx
  projects/app/src/pages/dataset/detail/components/InputDataModal.tsx
Labels: size/L

#2603 feat: http body type & http input support editor variable
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/template/system/http468.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  packages/web/components/common/Input/HttpInput/Editor.tsx
  packages/web/components/common/Input/HttpInput/index.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/workflow.json
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeHttp/index.tsx
  projects/app/src/pages/app/list/components/HttpPluginEditModal.tsx
Labels: size/XL

#2610 Update userselect ux
  docSite/content/zh-cn/docs/development/upgrading/4810.md
  packages/global/core/chat/adapt.ts
  packages/global/core/workflow/runtime/constants.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/global/core/workflow/template/system/userSelect/type.d.ts
  packages/service/core/ai/functions/createQuestionGuide.ts
  packages/service/core/chat/controller.ts
  packages/service/core/chat/saveChat.ts
  packages/service/core/chat/utils.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/interactive/userSelect.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/utils.ts
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/web/core/app/utils.ts
Labels: size/XXL

#2611 fix: add http params focus & ui
  packages/web/components/common/Tabs/LightRowTabs.tsx
  packages/web/components/common/Textarea/PromptEditor/Editor.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/VariableLabelPickerPlugin/index.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/workflow.json
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeHttp/index.tsx
Labels: size/L

#2613 feat: add captcha
  packages/global/support/user/auth/constants.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/common.json
  projects/app/src/components/support/user/safe/SendCodeAuthModal.tsx
  projects/app/src/pages/account/components/Info/UpdateNotificationModal.tsx
  projects/app/src/pages/login/components/ForgetPasswordForm.tsx
  projects/app/src/pages/login/components/RegisterForm.tsx
  projects/app/src/web/support/user/api.ts
  projects/app/src/web/support/user/hooks/useSendCode.ts
Labels: size/L

#2618 4.8.10 test
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatController.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/AppCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeHttp/index.tsx
  projects/app/src/pages/dataset/detail/components/InputDataModal.tsx
  projects/app/src/web/common/hooks/useCopyData.tsx
Labels: size/XXL

#2562 add sensevoice & cosevoice
  python/cosevoice/Dockerfile
  python/cosevoice/fastapi/client.py
  python/cosevoice/fastapi/server.py
  python/cosevoice/grpc/client.py
  python/cosevoice/grpc/cosyvoice.proto
  python/cosevoice/grpc/server.py
  python/cosevoice/requirements.txt
  python/sensevoice/Dockerfile
  python/sensevoice/app/=1.13
  python/sensevoice/app/iic/SenseVoiceSmall/.mdl
  python/sensevoice/app/iic/SenseVoiceSmall/.msc
  python/sensevoice/app/iic/SenseVoiceSmall/.mv
  python/sensevoice/app/iic/SenseVoiceSmall/README.md
  python/sensevoice/app/iic/SenseVoiceSmall/am.mvn
  python/sensevoice/app/iic/SenseVoiceSmall/chn_jpn_yue_eng_ko_spectok.bpe.model
  python/sensevoice/app/iic/SenseVoiceSmall/config.yaml
  python/sensevoice/app/iic/SenseVoiceSmall/configuration.json
  python/sensevoice/app/iic/SenseVoiceSmall/fig/aed_figure.png
  python/sensevoice/app/iic/SenseVoiceSmall/fig/asr_results.png
  python/sensevoice/app/iic/SenseVoiceSmall/fig/inference.png
  python/sensevoice/app/iic/SenseVoiceSmall/fig/sensevoice.png
  python/sensevoice/app/iic/SenseVoiceSmall/fig/ser_figure.png
  python/sensevoice/app/iic/SenseVoiceSmall/fig/ser_table.png
  python/sensevoice/app/iic/speech_fsmn_vad_zh-cn-16k-common-pytorch/.mdl
  python/sensevoice/app/iic/speech_fsmn_vad_zh-cn-16k-common-pytorch/.msc
  python/sensevoice/app/iic/speech_fsmn_vad_zh-cn-16k-common-pytorch/.mv
  python/sensevoice/app/iic/speech_fsmn_vad_zh-cn-16k-common-pytorch/README.md
  python/sensevoice/app/iic/speech_fsmn_vad_zh-cn-16k-common-pytorch/am.mvn
  python/sensevoice/app/iic/speech_fsmn_vad_zh-cn-16k-common-pytorch/config.yaml
  python/sensevoice/app/iic/speech_fsmn_vad_zh-cn-16k-common-pytorch/configuration.json
  python/sensevoice/app/iic/speech_fsmn_vad_zh-cn-16k-common-pytorch/example/vad_example.wav
  python/sensevoice/app/iic/speech_fsmn_vad_zh-cn-16k-common-pytorch/fig/struct.png
  python/sensevoice/app/iic/speech_fsmn_vad_zh-cn-16k-common-pytorch/model.pt
  python/sensevoice/app/main.py
  python/sensevoice/app/model.py
  python/sensevoice/app/requirements.txt
  python/sensevoice/main.py
  python/sensevoice/run.sh
Labels: size/XXL

#2620 perf: captcha code
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/common.json
  projects/app/Dockerfile
  projects/app/src/components/support/user/safe/SendCodeAuthModal.tsx
  projects/app/src/pages/account/components/Info/UpdateNotificationModal.tsx
  projects/app/src/pages/login/components/ForgetPasswordForm.tsx
  projects/app/src/pages/login/components/RegisterForm.tsx
  projects/app/src/web/support/user/api.ts
  projects/app/src/web/support/user/hooks/useSendCode.tsx
Labels: size/L

#2621 fix: ts
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderOutput.tsx
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
Labels: size/S

#2609 feat: dynamic website crawler
  packages/service/common/string/cheerio.ts
Labels: size/XS

#2619 I18n: Completed i18n&&proofread some translations
  packages/global/support/permission/app/constant.ts
  packages/global/support/permission/constant.ts
  packages/global/support/permission/dataset/constant.ts
  packages/global/support/permission/user/constant.ts
  packages/global/support/wallet/usage/constants.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/en/chat.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/en/file.json
  packages/web/i18n/en/publish.json
  packages/web/i18n/en/user.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/dataset.json
  packages/web/i18n/zh/user.json
  projects/app/src/components/support/permission/MemberManager/AddMemberModal.tsx
  projects/app/src/components/support/permission/MemberManager/PermissionSelect.tsx
  projects/app/src/components/support/permission/MemberManager/PermissionTags.tsx
  projects/app/src/components/support/permission/PermissionTags/index.tsx
  projects/app/src/components/support/user/team/TeamManageModal/components/PermissionManage/index.tsx
  projects/app/src/pages/account/components/Info/index.tsx
  projects/app/src/pages/app/detail/components/Publish/FeiShu/FeiShuEditModal.tsx
  projects/app/src/pages/app/detail/components/Publish/OffiAccount/OffiAccountEditModal.tsx
  projects/app/src/pages/app/detail/components/Publish/Wecom/WecomEditModal.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/TagManageModal.tsx
  projects/app/src/web/context/useInitApp.ts
  projects/app/src/web/core/app/templates.ts
  projects/app/src/web/core/app/utils.ts
Labels: size/XXL

#2624 chore: template author name & icon border radius
  projects/app/public/appMarketTemplates/CQ/template.json
  projects/app/public/appMarketTemplates/TranslateRobot/template.json
  projects/app/public/appMarketTemplates/chatGuide/template.json
  projects/app/public/appMarketTemplates/flux/template.json
  projects/app/public/appMarketTemplates/google/template.json
  projects/app/public/appMarketTemplates/plugin-dalle/template.json
  projects/app/public/appMarketTemplates/plugin-feishu/template.json
  projects/app/public/appMarketTemplates/simpleDatasetChat/template.json
  projects/app/public/appMarketTemplates/srt-translate/template.json
  projects/app/public/appMarketTemplates/timeBot/template.json
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
Labels: size/S

#2625 Perf: i18n change and captcha code.
  .vscode/settings.json
  docSite/content/zh-cn/docs/development/upgrading/4810.md
  packages/service/common/vectorStore/pg/class.ts
  packages/web/hooks/useI18n.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/en/chat.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/en/file.json
  packages/web/i18n/en/login.json
  packages/web/i18n/en/publish.json
  packages/web/i18n/en/user.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/chat.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/dataset.json
  packages/web/i18n/zh/file.json
  packages/web/i18n/zh/login.json
  packages/web/i18n/zh/publish.json
  packages/web/i18n/zh/user.json
  packages/web/i18n/zh/workflow.json
  packages/web/package.json
  packages/web/types/i18next.d.ts
  pnpm-lock.yaml
  projects/app/next-i18next.config.js
  projects/app/package.json
  projects/app/src/components/Layout/index.tsx
  projects/app/src/components/support/user/safe/SendCodeAuthModal.tsx
  projects/app/src/pages/_app.tsx
  projects/app/src/pages/account/components/Individuation.tsx
  projects/app/src/pages/account/index.tsx
  projects/app/src/pages/app/detail/components/Plugin/Header.tsx
  projects/app/src/pages/app/detail/components/Workflow/Header.tsx
  projects/app/src/pages/dataset/list/component/List.tsx
  projects/app/src/pages/login/components/LoginForm/LoginForm.tsx
  projects/app/src/pages/login/index.tsx
  projects/app/src/web/common/utils/i18n.ts
  projects/app/src/web/context/useInitApp.ts
  scripts/i18n/delete-unused-keys.js
  scripts/i18n/package.json
  scripts/i18n/query.js
  scripts/i18n/query.ts
Labels: size/XXL

#2630 4.8.10 perf
  packages/global/core/workflow/runtime/utils.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/web/styles/theme.ts
  projects/app/Dockerfile
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/type.d.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/utils.ts
  projects/app/src/components/core/chat/ChatContainer/useChat.ts
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/app/detail/components/useChatTest.tsx
  projects/app/src/pages/login/provider.tsx
  projects/app/src/pages/login/sso.tsx
Labels: size/L

#2631 addition i18n
  packages/global/core/ai/prompt/AIChat.ts
  packages/global/core/workflow/node/constant.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/common.json
  projects/app/src/components/PromptTemplate/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/TextInput.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/ValueTypeLabel.tsx
Labels: size/M

#2633 4.8.10 perf
  docSite/content/zh-cn/docs/development/upgrading/4810.md
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  fastgpt@4.0
  zhlint
Labels: size/L

#2634 Update 4810.md
  docSite/content/zh-cn/docs/development/upgrading/4810.md
Labels: size/XS

#2636 fix: mobild sso login
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  projects/app/src/pages/login/provider.tsx
  projects/app/src/pages/login/sso.tsx
Labels: size/M

#2637 Fixs:当最后一条数据因大模型没返回数据时导致调试时前端报错。
  projects/app/src/components/core/chat/ChatContainer/ChatBox/utils.ts
Labels: size/XS

#2640 fix: oauth
  projects/app/src/pages/login/provider.tsx
  projects/app/src/pages/login/sso.tsx
  projects/app/src/web/support/user/auth.ts
Labels: size/M

#2615 perf: logs, auth root as super admin, etc
  packages/service/support/permission/app/auth.ts
  packages/service/support/permission/controller.ts
  packages/service/support/permission/dataset/auth.ts
  packages/service/support/permission/user/auth.ts
  packages/web/hooks/usePagination.tsx
  packages/web/i18n/zh/app.json
  projects/app/src/pages/account/components/Promotion.tsx
  projects/app/src/pages/account/components/bill/BillTable.tsx
  projects/app/src/pages/account/components/bill/InvoiceTable.tsx
  projects/app/src/pages/api/core/app/getChatLogs.ts
  projects/app/src/pages/api/support/user/account/loginByPassword.ts
  projects/app/src/pages/app/detail/components/Logs/index.tsx
  projects/app/src/pages/dataset/detail/components/DataCard.tsx
  projects/app/src/types/app.d.ts
  projects/app/src/web/core/app/api.ts
  projects/app/src/web/core/dataset/api.ts
  projects/app/src/web/support/activity/promotion/api.ts
  projects/app/src/web/support/wallet/bill/api.ts
  projects/app/src/web/support/wallet/bill/invoice/api.ts
Labels: size/L

#2646 fix: workflow clear repeat check run
  packages/service/core/workflow/dispatch/index.ts
  projects/app/src/pages/api/common/system/getInitData.ts
Labels: size/S

#2645 fix: workflow i18n
  packages/global/core/workflow/template/system/classifyQuestion/index.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeDatasetConcat.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/JsonEditor.tsx
Labels: size/S

#2649 Fix: workflow init status
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/interactive/userSelect.ts
  packages/web/i18n/zh/common.json
Labels: size/S

#2644 chore: openapi doc generator
  package.json
  pnpm-lock.yaml
  projects/app/public/openapi/index.html
  projects/app/src/pages/api/support/outLink/list.ts
  scripts/openapi/.env
  scripts/openapi/.gitignore
  scripts/openapi/index.ts
  scripts/openapi/openapi.ts
  scripts/openapi/package.json
  scripts/openapi/template.md
  scripts/openapi/type.d.ts
  scripts/openapi/utils.ts
Labels: size/XXL

#2652 fix: entry
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/index.ts
Labels: size/S

#2654 fix: cq template missing chatconfig
  projects/app/public/appMarketTemplates/CQ/template.json
Labels: size/S

#2655 fix: toolNode max tokens and toolDescription i18n
  projects/app/src/components/support/wallet/QRCodePayModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeDatasetConcat.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SelectDatasetParams.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
  projects/app/src/pages/app/detail/components/WorkflowPublishHistoriesSlider.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/L

#2660 fix: app select dataset
  packages/service/support/permission/dataset/auth.ts
  projects/app/src/components/core/app/FileSelect.tsx
  projects/app/src/pages/api/core/dataset/allDataset.ts
  projects/app/src/pages/app/detail/components/SimpleApp/EditForm.tsx
Labels: size/M

#2659 pay pre wrap
  projects/app/src/components/support/wallet/QRCodePayModal.tsx
Labels: size/XS

#2661 fix: sso
  projects/app/src/pages/login/sso.tsx
Labels: size/XS

#2668 Update 4810.md
  docSite/content/zh-cn/docs/development/upgrading/4810.md
Labels: size/XS

#2672 Add workflow rename; Fix: userselect chatId unrefresh
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  packages/service/core/dataset/training/controller.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatController.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/ChatContainer/useChat.ts
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/NodePluginConfig.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/PluginInput.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/PluginOutput.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeSystemConfig.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeWorkflowStart.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/chat/index.tsx
Labels: size/L

#2665 perf: add scroll list && virtualist
  packages/web/hooks/usePagination.tsx
  packages/web/hooks/useScrollPagination.tsx
  projects/app/src/pages/api/core/chat/getHistories.ts
  projects/app/src/pages/chat/components/ChatHistorySlider.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/pages/dataset/detail/components/DataCard.tsx
  projects/app/src/web/core/chat/api.ts
  projects/app/src/web/core/chat/context/chatContext.tsx
Labels: size/XL

#2674 Fix typo location of python bge-rerank
  python/bge-rerank/README.md
Labels: size/XS

#2676 perf scroll components
  packages/web/hooks/usePagination.tsx
  packages/web/hooks/useScrollPagination.tsx
  projects/app/src/components/core/app/InputGuideConfig.tsx
  projects/app/src/pages/api/core/chat/getHistories.ts
  projects/app/src/pages/app/detail/components/PublishHistoriesSlider.tsx
  projects/app/src/pages/app/detail/components/WorkflowPublishHistoriesSlider.tsx
  projects/app/src/pages/chat/components/ChatHistorySlider.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/Context.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/Header.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/HeaderTagPopOver.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/TagManageModal.tsx
  projects/app/src/pages/dataset/detail/components/DataCard.tsx
  projects/app/src/web/core/chat/api.ts
  projects/app/src/web/core/chat/context/chatContext.tsx
Labels: size/XL

#2677 Update official_account.md
  docSite/content/zh-cn/docs/course/official_account.md
Labels: size/XS

#2681 Workflow experience optimization
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/workflow/mouse.svg
  packages/web/components/common/Icon/icons/core/workflow/touchTable.svg
  packages/web/components/common/MySelect/MultipleRowSelect.tsx
  packages/web/components/common/Textarea/PromptEditor/Editor.tsx
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/workflow.json
  projects/app/src/components/Select/AIModelSelector.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/AppCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/FlowController.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/SaveAndPublish.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useKeyboard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeTools.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/Handle/ToolHandle.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/Handle/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/JsonEditor.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Select.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
  projects/app/src/pages/chat/team.tsx
Labels: size/L

#2688 Perf: worfklow scroll cannot wheel. Adapt wrokflow skip circle. Change tab alway output stream
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  packages/service/core/workflow/dispatch/index.ts
  packages/web/hooks/useScrollPagination.tsx
  projects/app/src/components/Layout/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/ImportSettings.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/FlowController.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useKeyboard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/Handle/ToolHandle.tsx
  projects/app/src/types/index.d.ts
  projects/app/src/web/common/api/fetch.ts
  projects/app/src/web/common/system/utils.ts
Labels: size/L

#2690 fix: share init error
  projects/app/src/global/core/chat/utils.ts
  projects/app/src/pages/api/core/chat/getResData.ts
  projects/app/src/pages/api/core/chat/outLink/init.ts
  projects/app/src/pages/api/core/chat/team/init.ts
Labels: size/M

#2691 fix: ts
  packages/service/type.d.ts
Labels: size/XS

#2692 fix: chat log get member info
  projects/app/src/pages/app/detail/components/Logs/index.tsx
Labels: size/S

#2694 fixSyncLinkChunkSplitterBug
  projects/app/src/pages/api/core/dataset/collection/sync/link.ts
Labels: size/XS

#2697 feat: comment
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
Labels: size/XS

#2699 remove the trailing #xx when copy
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useUtils.tsx
Labels: size/XS

#2700 Update 4810.md
  docSite/content/zh-cn/docs/development/upgrading/4810.md
Labels: size/XS

#2702 feat: sandbox support str to base64 function;feat: compiance text ui
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  projects/app/src/components/common/ComplianceTip/index.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderOutput.tsx
  projects/app/src/pages/dataset/list/component/CreateModal.tsx
  projects/sandbox/src/sandbox/jsFn/str2Base64.ts
  projects/sandbox/src/sandbox/utils.ts
Labels: size/M

#2675 feat: loop node
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/node/constant.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/template/constants.ts
  packages/global/core/workflow/template/system/loop/loop.ts
  packages/global/core/workflow/template/system/loop/loopEnd.ts
  packages/global/core/workflow/template/system/loop/loopStart.ts
  packages/global/core/workflow/type/io.d.ts
  packages/global/core/workflow/type/node.d.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/tools/runLoop.ts
  packages/service/core/workflow/dispatch/tools/runLoopEnd.ts
  packages/service/core/workflow/dispatch/tools/runLoopStart.ts
  packages/web/components/common/EmptyTip/index.tsx
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/workflow/inputType/array.svg
  packages/web/components/common/Icon/icons/core/workflow/template/loop.svg
  packages/web/components/common/Icon/icons/core/workflow/template/loopEnd.svg
  packages/web/components/common/Icon/icons/core/workflow/template/loopStart.svg
  packages/web/components/common/Textarea/PromptEditor/plugins/VariablePickerPlugin/index.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/workflow.json
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/AppCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/Container.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/IOTitle.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useKeyboard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeLoop.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeLoopEnd.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeLoopStart.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/VariableTable.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/Label.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Reference.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/utils.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/XXL

#2708 perf: plugin support files
  packages/service/core/workflow/dispatch/plugin/run.ts
  packages/service/core/workflow/utils.ts
  projects/app/src/pages/api/v1/chat/completions.ts
Labels: size/M

#2706 pref: member group for team
  packages/global/support/user/team/group/constant.ts
  packages/service/support/user/team/controller.ts
  projects/app/src/components/support/user/team/TeamManageModal/TeamCard.tsx
  projects/app/src/components/support/user/team/TeamManageModal/components/GroupManage.tsx
  projects/app/src/components/support/user/team/TeamManageModal/components/PermissionManage/AddMemberWithPermissionModal.tsx
  projects/app/src/components/support/user/team/TeamManageModal/components/PermissionManage/index.tsx
  projects/app/src/components/support/user/team/TeamManageModal/components/SelectMember.tsx
Labels: size/L

#2715 feat: specify the api's auth type
  projects/app/public/openapi/index.html
  scripts/openapi/index.ts
  scripts/openapi/openapi.ts
  scripts/openapi/type.d.ts
  scripts/openapi/utils.ts
Labels: size/L

#2721 feat: doc
  README.md
  docSite/content/zh-cn/docs/development/configuration.md
  docSite/content/zh-cn/docs/development/faq.md
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  packages/web/i18n/zh/workflow.json
Labels: size/L

#2725 Update 4810.md
  docSite/content/zh-cn/docs/development/upgrading/4810.md
Labels: size/XS

#2726 Update intro.md
  docSite/content/zh-cn/docs/development/upgrading/intro.md
Labels: size/XS

#2728 fix: aichat response
  packages/service/core/workflow/dispatch/chat/oneapi.ts
Labels: size/S

#2733 feat: dataset quote role support system; fix: adapt o1 model
  docSite/content/zh-cn/docs/course/fileInput.md
  docSite/content/zh-cn/docs/development/faq.md
  docSite/content/zh-cn/docs/development/openapi/share.md
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  docSite/content/zh-cn/docs/workflow/examples/google_search.md
  packages/global/core/ai/model.d.ts
  packages/global/core/ai/prompt/AIChat.ts
  packages/global/core/dataset/type.d.ts
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/template/system/aiChat/index.ts
  packages/global/core/workflow/template/system/aiChat/type.d.ts
  packages/service/core/ai/functions/createQuestionGuide.ts
  packages/service/core/ai/functions/queryExtension.ts
  packages/service/core/ai/utils.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/core/workflow/dispatch/agent/classifyQuestion.ts
  packages/service/core/workflow/dispatch/agent/extract.ts
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/support/permission/dataset/auth.ts
  packages/web/components/common/LightTip/index.tsx
  packages/web/components/common/MyBox/FormLabel.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/VariablePickerPlugin/index.tsx
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/workflow.json
  projects/app/data/config.json
  projects/app/next-i18next.config.js
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SettingQuotePrompt.tsx
  projects/app/src/pages/dataset/detail/components/InputDataModal.tsx
  projects/app/src/service/events/generateQA.ts
  projects/app/src/web/core/app/utils.ts
Labels: size/XL

#2735 remove code
  packages/service/core/dataset/training/controller.ts
  packages/service/core/workflow/dispatch/agent/classifyQuestion.ts
  packages/service/core/workflow/dispatch/dataset/search.ts
Labels: size/XS

#2732 pref: member group for team
  packages/global/support/user/team/group/constant.ts
  packages/service/support/permission/controller.ts
  packages/service/support/permission/memberGroup/controllers.ts
  packages/service/support/user/team/controller.ts
  projects/app/src/components/support/user/team/TeamManageModal/components/GroupManage.tsx
  projects/app/src/components/support/user/team/TeamManageModal/components/PermissionManage/index.tsx
Labels: size/M

#2736 fix: delete group
  projects/app/src/components/support/user/team/TeamManageModal/components/GroupManage.tsx
Labels: size/XS

#2716 feat: plugin support upload files
  packages/service/core/workflow/dispatch/plugin/runInput.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/chat/imgSelect.svg
  packages/web/i18n/en/chat.json
  packages/web/i18n/zh/chat.json
  projects/app/src/components/core/app/FileSelect.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/hooks/useFileUpload.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderInput.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/context.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/type.d.ts
  projects/app/src/components/core/chat/ChatContainer/components/FilePreview.tsx
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/NodePluginConfig.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/PluginInput.tsx
  projects/app/src/pages/app/detail/components/useChatTest.tsx
Labels: size/XXL

#2744 Update 4810.md
  docSite/content/zh-cn/docs/development/upgrading/4810.md
Labels: size/XS

#2745 Add externalfile api params
  docSite/content/zh-cn/docs/development/openapi/dataset.md
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/collection/schema.ts
  packages/service/core/dataset/collection/utils.ts
  projects/app/src/global/core/dataset/type.d.ts
  projects/app/src/pages/api/core/dataset/collection/detail.ts
  projects/app/src/pages/api/core/dataset/collection/list.ts
  projects/app/src/pages/api/core/dataset/collection/update.ts
  projects/app/src/pages/dataset/detail/components/CollectionCard/TagsPopOver.tsx
  projects/app/src/pages/dataset/detail/components/DataCard.tsx
  projects/app/src/pages/dataset/detail/components/Info.tsx
Labels: size/L

#2707 chore: Jest Testing structure
  fastgpt@4.0
  packages/global/common/type/utils.ts
  pnpm-lock.yaml
  projects/app/jest.config.js
  projects/app/package.json
  projects/app/src/pages/api/__mocks__/base.ts
  projects/app/src/pages/api/__mocks__/db/init.ts
  projects/app/src/pages/api/__mocks__/type.d.ts
  projects/app/src/pages/api/support/outLink/list.test.ts
  projects/app/src/pages/api/support/outLink/list.ts
  projects/app/src/pages/api/support/outLink/update.test.ts
  projects/app/src/pages/api/support/outLink/update.ts
  projects/app/src/test/utils.ts
  scripts/openapi/index.js
  scripts/openapi/openapi.js
  scripts/openapi/openapi.json
  scripts/openapi/openapi.out
  scripts/openapi/utils.js
Labels: size/XXL

#2743 fix: plugin file numbers & plugin template add config
  packages/plugins/src/Doc2X/FileImg2text/template.json
  packages/plugins/src/Doc2X/FilePDF2text/template.json
  packages/plugins/src/Doc2X/URLImg2text/template.json
  packages/plugins/src/Doc2X/URLPDF2text/template.json
  packages/plugins/src/duckduckgo/search/template.json
  packages/plugins/src/duckduckgo/searchImg/template.json
  packages/plugins/src/duckduckgo/searchNews/template.json
  packages/plugins/src/duckduckgo/searchVideo/template.json
  packages/plugins/src/feishu/template.json
  projects/app/public/appMarketTemplates/flux/template.json
  projects/app/public/appMarketTemplates/plugin-dalle/template.json
  projects/app/public/appMarketTemplates/plugin-feishu/template.json
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderInput.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/context.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/PluginInput.tsx
  projects/app/src/pages/dataset/list/component/CreateModal.tsx
  projects/app/src/web/core/app/templates.ts
Labels: size/XXL

#2747 pref: app list save the app type choice
  projects/app/src/pages/app/detail/components/Plugin/Header.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Header.tsx
  projects/app/src/pages/app/detail/components/Workflow/Header.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/web/common/system/useSystemStore.ts
Labels: size/M

#2746 4.8.11 test fix
  docSite/content/zh-cn/docs/course/fileInput.md
  docSite/content/zh-cn/docs/development/openapi/share.md
  docSite/content/zh-cn/docs/workflow/examples/google_search.md
  packages/global/core/ai/prompt/AIChat.ts
  packages/service/core/chat/utils.ts
  packages/web/i18n/en/chat.json
  packages/web/i18n/zh/chat.json
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/pages/api/core/dataset/update.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/Plugin/Header.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Header.tsx
  projects/app/src/pages/app/detail/components/Workflow/Header.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeVariableUpdate.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
  projects/app/src/pages/app/list/components/context.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/web/common/system/useSystemStore.ts
Labels: size/XL

#2755 perf: plugin rerun with last params & plugin log add file
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderInput.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/context.tsx
  projects/app/src/pages/app/detail/components/Logs/DetailLogsModal.tsx
Labels: size/M

#2756 Plugin support select file
  docSite/content/zh-cn/docs/development/openapi/chat.md
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  packages/global/core/workflow/template/system/pluginOutput.ts
  packages/global/core/workflow/utils.ts
  packages/plugins/src/Doc2X/FileImg2text/template.json
  packages/plugins/src/Doc2X/FilePDF2text/template.json
  packages/plugins/src/Doc2X/URLImg2text/template.json
  packages/plugins/src/Doc2X/URLPDF2text/template.json
  packages/plugins/src/duckduckgo/search/template.json
  packages/plugins/src/duckduckgo/searchImg/template.json
  packages/plugins/src/duckduckgo/searchNews/template.json
  packages/plugins/src/duckduckgo/searchVideo/template.json
  packages/plugins/src/feishu/template.json
  packages/plugins/src/fetchUrl/template.json
  packages/plugins/src/getTime/template.json
  packages/plugins/src/mathExprVal/template.json
  packages/service/core/workflow/dispatch/plugin/run.ts
  packages/service/core/workflow/dispatch/plugin/runInput.ts
  packages/service/core/workflow/utils.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/chat/imgSelect.svg
  packages/web/i18n/en/app.json
  packages/web/i18n/en/chat.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/chat.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/workflow.json
  projects/app/data/pluginTemplates/customFeedback.json
  projects/app/data/pluginTemplates/getCurrentTime.json
  projects/app/data/pluginTemplates/textEditor.json
  projects/app/data/pluginTemplates/v1/customFeedback.json
  projects/app/data/pluginTemplates/v1/getCurrentTime.json
  projects/app/data/pluginTemplates/v1/textEditor.json
  projects/app/data/pluginTemplates/v1/tfSwitch.json
  projects/app/public/appMarketTemplates/flux/template.json
  projects/app/public/appMarketTemplates/plugin-dalle/template.json
  projects/app/public/appMarketTemplates/plugin-feishu/template.json
  projects/app/src/components/core/app/FileSelect.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Provider.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/hooks/useFileUpload.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/type.d.ts
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderInput.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/context.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/type.d.ts
  projects/app/src/components/core/chat/ChatContainer/components/FilePreview.tsx
  projects/app/src/components/core/chat/ChatContainer/useChat.ts
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/Logs/DetailLogsModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/NodePluginConfig.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/PluginInput.tsx
  projects/app/src/pages/app/detail/components/useChatTest.tsx
  projects/app/src/pages/dataset/list/component/CreateModal.tsx
  projects/app/src/web/core/app/templates.ts
Labels: size/XXL

#2762 feat: plan index;flat i18n and add variable value type
  packages/global/common/string/textSplitter.ts
  packages/service/support/wallet/sub/schema.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/en/chat.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/en/publish.json
  packages/web/i18n/en/user.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/chat.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/dataset.json
  packages/web/i18n/zh/publish.json
  packages/web/i18n/zh/user.json
  packages/web/i18n/zh/workflow.json
  packages/web/types/i18next.d.ts
  projects/app/src/components/core/app/VariableEdit.tsx
  projects/app/src/pages/account/components/Info/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/Loop/NodeLoop.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/Loop/NodeLoopEnd.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/Loop/NodeLoopStart.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputEditModal.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/pages/dataset/detail/components/MetaDataCard.tsx
Labels: size/XXL

#2769 Update README.md
  README.md
Labels: size/XS

#2768 4.8.11 perf
  .vscode/settings.json
  docSite/content/zh-cn/docs/development/configuration.md
  docSite/content/zh-cn/docs/development/one-api.md
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  files/helm/fastgpt/templates/configmap-config.yaml
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/template/input.ts
  packages/global/core/workflow/utils.ts
  packages/service/core/ai/functions/createQuestionGuide.ts
  packages/service/core/app/plugin/controller.ts
  packages/service/core/app/plugin/utils.ts
  packages/service/core/workflow/dispatch/plugin/run.ts
  packages/service/core/workflow/dispatch/plugin/runApp.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/web/components/common/Textarea/PromptEditor/Editor.tsx
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/workflow.json
  projects/app/data/config.json
  projects/app/src/components/Layout/index.tsx
  projects/app/src/pages/_app.tsx
  projects/app/src/pages/api/core/app/plugin/getPreviewNode.ts
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/Plugin/Header.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Header.tsx
  projects/app/src/pages/app/detail/components/Workflow/Header.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/SaveAndPublish.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/Label.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/utils.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/pages/dataset/list/component/List.tsx
  projects/app/src/web/core/chat/context/chatContext.tsx
  projects/app/src/web/core/chat/storeShareChat.ts
  projects/app/src/web/support/user/useUserStore.ts
Labels: size/L

#2771 updated: docs/docker.md，修改 config.json 的地址
  docSite/content/zh-cn/docs/development/docker.md
Labels: size/XS

#2772 Support simpleApp select workflow
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  packages/global/core/workflow/template/input.ts
  packages/service/core/app/plugin/controller.ts
  packages/web/i18n/zh/app.json
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderOutput.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/renderPluginInput.tsx
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/pages/app/detail/components/Publish/Link/SelectUsingWayModal.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/components/ToolSelectModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputEditModal.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/web/core/app/utils.ts
  projects/app/src/web/core/chat/storeShareChat.ts
Labels: size/L

#2696 perf: history add scrollList
  packages/service/core/chat/controller.ts
  packages/web/hooks/usePagination.tsx
  packages/web/i18n/zh/common.json
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/ChatContainer/useChat.ts
  projects/app/src/global/core/chat/api.d.ts
  projects/app/src/global/core/chat/constants.ts
  projects/app/src/pages/api/core/chat/getPaginationRecords.ts
  projects/app/src/pages/api/core/chat/init.ts
  projects/app/src/pages/api/core/chat/outLink/init.ts
  projects/app/src/pages/api/core/chat/team/init.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/Logs/DetailLogsModal.tsx
  projects/app/src/pages/app/detail/components/useChatTest.tsx
  projects/app/src/pages/chat/components/ChatHeader.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/pages/dataset/detail/components/DataCard.tsx
  projects/app/src/web/core/chat/api.ts
  projects/app/src/web/core/chat/context/chatContext.tsx
Labels: size/XL

#2783 Record scroll test
  packages/service/core/chat/controller.ts
  packages/web/common/fetch/type.d.ts
  packages/web/hooks/useConfirm.tsx
  packages/web/hooks/usePagination.tsx
  packages/web/hooks/useScrollPagination.tsx
  packages/web/i18n/zh/common.json
  projects/app/src/components/Layout/index.tsx
  projects/app/src/components/core/app/InputGuideConfig.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Provider.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/type.d.ts
  projects/app/src/components/core/chat/ChatContainer/useChat.ts
  projects/app/src/global/core/api/datasetReq.d.ts
  projects/app/src/global/core/chat/api.d.ts
  projects/app/src/global/core/chat/constants.ts
  projects/app/src/global/core/chat/utils.ts
  projects/app/src/pages/api/core/app/version/detail.ts
  projects/app/src/pages/api/core/app/version/list.ts
  projects/app/src/pages/api/core/app/version/listWorkflow.tsx
  projects/app/src/pages/api/core/chat/getHistories.ts
  projects/app/src/pages/api/core/chat/getPaginationRecords.ts
  projects/app/src/pages/api/core/chat/init.ts
  projects/app/src/pages/api/core/chat/inputGuide/list.ts
  projects/app/src/pages/api/core/chat/outLink/init.ts
  projects/app/src/pages/api/core/chat/team/init.ts
  projects/app/src/pages/api/core/dataset/collection/scrollList.ts
  projects/app/src/pages/api/core/dataset/data/list.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/Logs/DetailLogsModal.tsx
  projects/app/src/pages/app/detail/components/PublishHistoriesSlider.tsx
  projects/app/src/pages/app/detail/components/WorkflowPublishHistoriesSlider.tsx
  projects/app/src/pages/app/detail/components/useChatTest.tsx
  projects/app/src/pages/chat/components/ChatHeader.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/TagManageModal.tsx
  projects/app/src/pages/dataset/detail/components/DataCard.tsx
  projects/app/src/types/index.d.ts
  projects/app/src/web/common/api/fetch.ts
  projects/app/src/web/common/system/utils.ts
  projects/app/src/web/core/chat/api.ts
  projects/app/src/web/core/chat/context/chatContext.tsx
  projects/app/src/web/core/chat/inputGuide/api.ts
  projects/app/src/web/core/dataset/api.ts
  projects/app/src/web/core/dataset/context/datasetPageContext.tsx
Labels: size/XXL

#2775 Perf ui detail
  packages/global/core/app/utils.ts
  packages/global/core/workflow/template/constants.ts
  packages/global/core/workflow/template/input.ts
  packages/global/core/workflow/template/system/readFiles/index.tsx
  packages/service/core/chat/utils.ts
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/workflow.json
  projects/app/src/pages/app/detail/components/SimpleApp/Header.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/web/core/app/utils.ts
Labels: size/L

#2784 fix: chat page render performance
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  projects/app/src/components/core/chat/ChatContainer/useChat.ts
  projects/app/src/pages/app/detail/components/Logs/DetailLogsModal.tsx
  projects/app/src/pages/chat/components/SliderApps.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
Labels: size/L

#2782 perf: optimize simple app history
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/line.svg
  packages/web/components/common/MyDrawer/CustomRightDrawer.tsx
  projects/app/src/components/common/folder/Path.tsx
  projects/app/src/pages/app/detail/components/Plugin/Header.tsx
  projects/app/src/pages/app/detail/components/PublishHistoriesSlider.tsx
  projects/app/src/pages/app/detail/components/RouteTab.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Edit.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Header.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/index.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/useSnapshots.tsx
  projects/app/src/pages/app/detail/components/Workflow/Header.tsx
  projects/app/src/pages/app/detail/components/Workflow/components/SaveButton.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
  projects/app/src/pages/app/detail/components/WorkflowPublishHistoriesSlider.tsx
  projects/app/src/pages/app/detail/components/context.tsx
  projects/app/src/web/core/app/api/version.ts
  projects/app/src/web/core/workflow/utils.ts
Labels: size/XXL

#2785 remove invalid code
  projects/app/src/pages/api/core/app/version/list.ts
  projects/app/src/pages/api/core/app/version/list.tsx
  projects/app/src/pages/api/core/app/version/revert.ts
  projects/app/src/pages/app/detail/components/PublishHistoriesSlider.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Edit.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Header.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/useSnapshots.tsx
  projects/app/src/pages/app/detail/components/Workflow/Header.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
  projects/app/src/web/core/app/api/version.ts
  projects/app/src/web/core/workflow/utils.ts
Labels: size/L

#2794 4.8.11 test
  .vscode/nextapi.code-snippets
  dev.md
  packages/global/core/app/version.d.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/zh/app.json
  projects/app/src/pages/api/__mocks__/db/init.ts
  projects/app/src/pages/api/__mocks__/demo/demo.test.ts
  projects/app/src/pages/api/__mocks__/demo/demo.ts
  projects/app/src/pages/api/core/app/version/detail.ts
  projects/app/src/pages/api/core/app/version/lis.test.ts
  projects/app/src/pages/api/core/app/version/list.ts
  projects/app/src/pages/app/detail/components/Plugin/Header.tsx
  projects/app/src/pages/app/detail/components/PublishHistoriesSlider.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Edit.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Header.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/index.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/useSnapshots.tsx
  projects/app/src/pages/app/detail/components/Workflow/Header.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/AppCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/NodePluginConfig.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
  projects/app/src/service/common/system/index.ts
  projects/app/src/web/core/app/api/version.ts
Labels: size/XXL

#2799 fix: ts
  projects/app/src/pages/app/detail/components/SimpleApp/useSnapshots.tsx
Labels: size/XS

#2798 feat: support select field as tool output
  packages/global/core/workflow/type/io.d.ts
  packages/service/core/workflow/dispatch/plugin/run.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/workflow/template/pluginOutput.svg
  packages/web/components/common/Icon/icons/core/workflow/template/toolkitActive.svg
  packages/web/components/common/Icon/icons/core/workflow/template/toolkitInactive.svg
  packages/web/components/common/Icon/icons/core/workflow/template/workflowStart.svg
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/workflow.json
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/PluginOutput.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/PluginOutputEditModal.tsx
Labels: size/L

#2803 fix: 网页抓取：正确处理//开头的超链接
  packages/service/common/string/cheerio.ts
Labels: size/S

#2797 feat: support workflow node fold
  packages/global/core/workflow/type/node.d.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/chat/chevronRight.svg
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/ButtonEdge.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/FlowController.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/Loop/NodeLoop.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/Loop/NodeLoopStart.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeUserSelect.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/Handle/ConnectionHandle.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/Handle/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/utils.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/L

#2806 fix: mobile history slider records disappear
  projects/app/src/pages/chat/components/ChatHistorySlider.tsx
  projects/app/src/web/core/chat/context/chatContext.tsx
Labels: size/M

#2804 4.8.11 code perf
  .github/ISSUE_TEMPLATE/config.yml
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  packages/global/core/workflow/template/system/interactive/formInput.ts
  packages/service/core/workflow/dispatch/interactive/formInput.ts
  packages/service/core/workflow/dispatch/plugin/run.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/workflow.json
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/pages/_app.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/ButtonEdge.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/FlowController.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeFormInput/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/PluginOutput.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/PluginOutputEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/Handle/ConnectionHandle.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/utils.tsx
Labels: size/L

#2802 fix: form input value type & default form & ui
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeFormInput/InputFormEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeFormInput/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
Labels: size/S

#2811 fix: tool node fold
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeTools.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
Labels: size/M

#2813 perf: stream response
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  packages/service/core/workflow/dispatch/interactive/formInput.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/web/common/api/fetch.ts
  projects/app/src/web/core/chat/context/chatContext.tsx
Labels: size/L

#2814 rename node
  packages/web/i18n/zh/workflow.json
Labels: size/XS

#2819 feat: add login page ip detect
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/language/America.svg
  packages/web/components/common/Icon/icons/common/language/China.svg
  packages/web/i18n/en/login.json
  packages/web/i18n/zh/login.json
  projects/app/src/components/Select/I18nLngSelector.tsx
  projects/app/src/pages/account/components/Individuation.tsx
  projects/app/src/pages/login/components/LoginForm/components/FormLayout.tsx
  projects/app/src/pages/login/index.tsx
  projects/app/src/types/index.d.ts
  projects/app/src/web/common/utils/i18n.ts
Labels: size/L

#2817 perf: support prompt editor dynamic height & modify aichat placeholder
  packages/global/core/workflow/template/input.ts
  packages/global/core/workflow/template/system/aiChat/index.ts
  packages/global/core/workflow/template/system/tools.ts
  packages/global/core/workflow/template/tip.ts
  packages/web/components/common/Textarea/PromptEditor/Editor.tsx
  packages/web/components/common/Textarea/PromptEditor/index.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/common.json
  projects/app/public/appMarketTemplates/CQ/template.json
  projects/app/public/appMarketTemplates/TranslateRobot/template.json
  projects/app/public/appMarketTemplates/chatGuide/template.json
  projects/app/public/appMarketTemplates/google/template.json
  projects/app/public/appMarketTemplates/simpleDatasetChat/template.json
  projects/app/public/appMarketTemplates/srt-translate/template.json
  projects/app/public/appMarketTemplates/timeBot/template.json
  projects/app/src/components/core/app/DatasetParamsModal.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/EditForm.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeHttp/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeVariableUpdate.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/Handle/ConnectionHandle.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SettingQuotePrompt.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Textarea.tsx
  projects/app/src/web/core/app/templates.ts
  projects/app/src/web/core/app/utils.ts
Labels: size/L

#2779 新增BI圖標功能-柱狀圖
  packages/plugins/package.json
  packages/plugins/register.ts
  packages/plugins/src/drawing/baseChart/index.ts
  packages/plugins/src/drawing/baseChart/template.json
  packages/plugins/src/drawing/template.json
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/workflow/template/BI.svg
  packages/web/components/common/Icon/icons/core/workflow/template/baseChart.svg
Labels: size/XL

#2815 阿里云团队贡献开源surya OCR识别模块
  python/suryaocr/Dockerfile
  python/suryaocr/README.md
  python/suryaocr/app.py
  python/suryaocr/requirements.txt
Labels: size/L

#2827 fix: change ip detect url
  projects/app/src/pages/login/index.tsx
Labels: size/M

#2828 Update configuration.md
  docSite/content/zh-cn/docs/development/configuration.md
Labels: size/XS

#2830 fix:variable not update in nested workflow runs
  packages/global/core/workflow/runtime/constants.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/loop/runLoop.ts
Labels: size/S

#2832 4.8.11 perf
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/service/core/ai/rerank/index.ts
  packages/service/core/app/controller.ts
  packages/service/core/app/plugin/controller.ts
  packages/service/core/app/version/controller.ts
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/service/core/workflow/dispatch/loop/runLoop.ts
  packages/service/core/workflow/dispatch/plugin/run.ts
  packages/service/core/workflow/dispatch/plugin/runApp.ts
  packages/service/support/wallet/sub/schema.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/workflow.json
  projects/app/src/components/Select/I18nLngSelector.tsx
  projects/app/src/pages/api/core/app/version/latest.ts
  projects/app/src/pages/api/core/app/version/publish.ts
  projects/app/src/pages/api/core/chat/init.ts
  projects/app/src/pages/api/core/chat/outLink/init.ts
  projects/app/src/pages/api/core/chat/team/init.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/Workflow/components/SaveButton.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/login/index.tsx
  projects/app/src/service/core/app/workflow.ts
  projects/app/src/types/index.d.ts
  projects/app/src/web/core/app/utils.ts
  python/ocr/surya/Dockerfile
  python/ocr/surya/README.md
  python/ocr/surya/app.py
  python/ocr/surya/requirements.txt
  python/suryaocr/README.md
Labels: size/XL

#2824 feat: add tool params node & tool params add array type
  packages/global/core/workflow/node/constant.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/global/core/workflow/template/constants.ts
  packages/global/core/workflow/template/system/toolParams.ts
  packages/global/core/workflow/type/io.d.ts
  packages/global/core/workflow/utils.ts
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolParams.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/workflow/template/toolParams.svg
  packages/web/i18n/en/common.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/workflow.json
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeToolParams/ToolParamsEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeToolParams/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeVariableUpdate.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderToolInput/EditFieldModal.tsx
  projects/app/src/web/core/workflow/constants/dataType.ts
Labels: size/L

#2835 perf: change tool params type label & enum input conditional rendering
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeToolParams/ToolParamsEditModal.tsx
  projects/app/src/web/core/workflow/constants/dataType.ts
Labels: size/M

#2834 feat: add context menu & comment node
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/node/constant.ts
  packages/global/core/workflow/template/system/comment.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/comment.svg
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/workflow.json
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/ContextMenu.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeComment.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
Labels: size/XL

#2843 4.8.11 test
  .vscode/settings.json
  docSite/assets/imgs/image-1.png
  docSite/assets/imgs/image-2.png
  docSite/assets/imgs/image-3.png
  docSite/assets/imgs/image-4.png
  docSite/assets/imgs/image.png
  docSite/content/zh-cn/docs/course/openapi.md
  docSite/content/zh-cn/docs/development/openapi/auth.md
  docSite/content/zh-cn/docs/development/openapi/chat.md
  docSite/content/zh-cn/docs/development/openapi/dataset.md
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  docSite/content/zh-cn/docs/use-cases/onwechat.md
  docSite/content/zh-cn/docs/workflow/modules/sandbox.md
  docSite/content/zh-cn/docs/workflow/modules/tool.md
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/template/system/toolParams.ts
  packages/service/common/mongo/index.ts
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/web/hooks/usePagination.tsx
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/workflow.json
  projects/app/src/pages/api/__mocks__/base.ts
  projects/app/src/pages/api/__mocks__/db/init.ts
  projects/app/src/pages/api/core/app/version/latest.test.ts
  projects/app/src/pages/api/core/app/version/publish.test.ts
  projects/app/src/pages/api/core/app/version/publish.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeComment.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeExtract/ExtractFieldModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeToolParams/ToolParamsEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeToolParams/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeTools.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderToolInput/EditFieldModal.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/Header.tsx
  projects/app/src/pages/dataset/detail/index.tsx
  projects/app/src/test/utils.ts
  projects/app/src/web/core/workflow/constants/dataType.ts
  projects/sandbox/src/sandbox/jsFn/str2Base64.ts
Labels: size/XL

#2845 fix: loop node cannot save parentId
  packages/global/core/workflow/type/node.d.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/utils.tsx
Labels: size/XS

#2848 fix: login ip check
  projects/app/src/pages/login/index.tsx
Labels: size/XS
