Repository labring/FastGPT, pull requests merged in 2024-11, with the labels that each got.

#3051 Update 4812.md
  docSite/content/zh-cn/docs/development/upgrading/4812.md
Labels: size/XS

#3038 perf: forbid image to base64
  docSite/content/zh-cn/docs/development/upgrading/4813.md
  packages/plugins/src/drawing/baseChart/index.ts
  packages/plugins/type.d.ts
  packages/plugins/utils.ts
  packages/service/common/file/gridfs/controller.ts
  packages/service/core/chat/utils.ts
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  projects/app/Dockerfile
  projects/app/src/pages/api/common/file/read/[filename].ts
  projects/app/src/pages/api/common/file/upload.ts
Labels: size/L

#3043 feat(voice): add fallback for browsers without MediaSource support
  projects/app/src/web/common/utils/voice.ts
Labels: size/M

#3052 fix: node version update flicker
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
Labels: size/S

#3058 New file upload
  docSite/content/zh-cn/docs/development/upgrading/4813.md
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
  packages/global/common/file/constants.ts
  packages/global/common/file/tools.ts
  packages/global/core/chat/utils.ts
  packages/global/core/workflow/node/constant.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/template/input.ts
  packages/global/core/workflow/template/system/aiChat/index.ts
  packages/global/core/workflow/template/system/readFiles/index.tsx
  packages/global/core/workflow/template/system/tools.ts
  packages/global/core/workflow/type/io.d.ts
  packages/global/core/workflow/utils.ts
  packages/service/core/chat/utils.ts
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/service/core/workflow/dispatch/agent/runTool/type.d.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/core/workflow/dispatch/plugin/runApp.ts
  packages/service/core/workflow/dispatch/plugin/runInput.ts
  packages/service/core/workflow/dispatch/tools/readFiles.ts
  packages/service/core/workflow/utils.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/en/chat.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/chat.json
  packages/web/i18n/zh/workflow.json
  projects/app/.env.template
  projects/app/public/imgs/app/visionModel.png
  projects/app/public/imgs/app/visionModel.svg
  projects/app/src/components/core/app/Tip.tsx
  projects/app/src/components/core/app/VariableEdit.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariableInput.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/hooks/useFileUpload.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/type.d.ts
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderInput.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/renderPluginInput.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/context.tsx
  projects/app/src/components/core/chat/ChatContainer/components/FilePreview.tsx
  projects/app/src/components/core/chat/ChatContainer/useChat.ts
  projects/app/src/pages/app/detail/components/SimpleApp/components/ToolSelectModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeFormInput/InputFormEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/NodePluginConfig.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/PluginInput.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/Label.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/index.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/web/core/app/utils.ts
Labels: size/XXL

#3024 feat: add chat history time label
  packages/global/common/string/time.ts
  packages/global/core/chat/type.d.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/common.json
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Provider.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/pages/account/components/InformTable.tsx
  projects/app/src/pages/api/core/chat/getPaginationRecords.ts
  projects/app/src/pages/app/detail/components/Logs/DetailLogsModal.tsx
  projects/app/src/pages/app/detail/components/Publish/FeiShu/index.tsx
  projects/app/src/pages/app/detail/components/Publish/Link/index.tsx
  projects/app/src/pages/app/detail/components/Publish/OffiAccount/index.tsx
  projects/app/src/pages/app/detail/components/Publish/Wecom/index.tsx
  projects/app/src/pages/app/list/components/List.tsx
  projects/app/src/pages/chat/components/ChatHistorySlider.tsx
  projects/app/src/pages/dataset/detail/components/Test.tsx
Labels: size/L

#3060 feat: add chat history time label
  packages/global/common/string/time.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Provider.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/pages/app/detail/components/Logs/DetailLogsModal.tsx
Labels: size/S

#3044 pref: slow query of full text search
  packages/service/core/dataset/search/controller.ts
Labels: size/M

#3066 Adapt findLast api;perf: markdown zh format.
  docSite/content/zh-cn/docs/development/upgrading/4813.md
  packages/global/core/workflow/runtime/utils.ts
  packages/service/core/app/plugin/utils.ts
  packages/service/core/workflow/dispatch/plugin/run.ts
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/WelcomeBox.tsx
  projects/app/src/pages/app/detail/components/Plugin/Header.tsx
  projects/app/src/pages/app/detail/components/Workflow/Header.tsx
Labels: size/M

#3067 perf: dockerfile proxy
  docSite/content/zh-cn/docs/development/upgrading/4813.md
  projects/app/Dockerfile
Labels: size/S

#3069 Docs: add docs for loop node
  docSite/assets/imgs/fastgpt-loop-node-config.png
  docSite/assets/imgs/fastgpt-loop-node-example-1.png
  docSite/assets/imgs/fastgpt-loop-node-example-2.png
  docSite/assets/imgs/fastgpt-loop-node-example-3.png
  docSite/assets/imgs/fastgpt-loop-node-example-4.png
  docSite/assets/imgs/fastgpt-loop-node-example-5.png
  docSite/assets/imgs/fastgpt-loop-node.png
  docSite/content/zh-cn/docs/workflow/modules/loop.md
Labels: size/L

#3065 fix ui
  packages/global/core/workflow/template/input.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/AppCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeIfElse/ListItem.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeIfElse/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/PluginInput.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeVariableUpdate.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/Handle/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
Labels: size/L

#3041 feat: support array reference multi-select
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/global/core/workflow/template/system/datasetConcat.ts
  packages/service/core/workflow/dispatch/tools/runUpdateVar.ts
  packages/web/components/common/MySelect/MultipleRowSelect.tsx
  packages/web/components/common/MySelect/type.d.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariableInput.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderInput.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/renderPluginInput.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/Loop/NodeLoop.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/Loop/NodeLoopStart.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeDatasetConcat.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeIfElse/ListItem.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/PluginOutput.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeVariableUpdate.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/DynamicInputs/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Reference.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/XL

#3076 feat: iframe code block；perf: workflow selector type
  packages/global/core/workflow/runtime/utils.ts
  packages/global/core/workflow/template/system/ifElse/type.d.ts
  packages/global/core/workflow/template/system/variableUpdate/type.d.ts
  packages/global/core/workflow/template/system/workflowStart.ts
  packages/global/core/workflow/type/io.d.ts
  packages/global/core/workflow/utils.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  packages/service/core/workflow/dispatch/tools/runUpdateVar.ts
  packages/web/components/common/Icon/icons/core/workflow/template/loopEnd.svg
  packages/web/components/common/Icon/icons/core/workflow/template/loopStart.svg
  packages/web/components/common/MySelect/MultipleRowSelect.tsx
  packages/web/components/common/MySelect/type.d.ts
  packages/web/styles/theme.ts
  projects/app/src/components/Markdown/codeBlock/Iframe.tsx
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/components/Markdown/utils.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/Loop/NodeLoop.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeDatasetConcat.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeIfElse/ListItem.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/PluginOutput.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeVariableUpdate.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/DynamicInputs/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Reference.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/XXL

#3074 node pluginoutput check
  projects/app/src/web/core/workflow/utils.ts
Labels: size/S

#3077 feat: View will move when workflow check error;fix: ui refresh error when continuous file upload
  docSite/content/zh-cn/docs/development/upgrading/4813.md
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/loop/runLoop.ts
  projects/app/src/components/core/app/VariableEdit.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/hooks/useFileUpload.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderInput.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/renderPluginInput.tsx
  projects/app/src/pages/app/detail/components/Plugin/index.tsx
  projects/app/src/pages/app/detail/components/Workflow/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Reference.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
  projects/app/src/web/common/file/hooks/useSelectFile.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/L

#3075 add dispatch try catch
  packages/service/core/workflow/dispatch/index.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/context.tsx
Labels: size/M

#3086 Optimize InputDataModal and useEditTitle in main project
  projects/app/src/pages/dataset/detail/components/InputDataModal.tsx
  projects/app/src/web/common/hooks/useEditTitle.tsx
Labels: size/XS

#3071 feat: support sub route config
  packages/global/common/file/constants.ts
  packages/global/core/chat/adapt.ts
  packages/web/common/system/utils.ts
  packages/web/components/common/Avatar/index.tsx
  packages/web/components/common/Image/MyImage.tsx
  packages/web/components/common/Image/PhotoView.tsx
  packages/web/components/common/MyDrawer/CustomRightDrawer.tsx
  packages/web/components/common/MyDrawer/MyRightDrawer.tsx
  packages/web/components/common/Textarea/CodeEditor/Editor.tsx
  packages/web/components/common/Textarea/JsonEditor/index.tsx
  packages/web/components/common/Textarea/PromptEditor/modules/ComfirmVar/index.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/common.json
  projects/app/.env.template
  projects/app/Dockerfile
  projects/app/next.config.js
  projects/app/src/components/MyImage/index.tsx
  projects/app/src/components/core/app/TTSSelect.tsx
  projects/app/src/components/core/app/Tip.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatController.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/QuoteModal.tsx
  projects/app/src/components/core/chat/ChatContainer/components/FilePreview.tsx
  projects/app/src/components/support/user/safe/SendCodeAuthModal.tsx
  projects/app/src/pages/_app.tsx
  projects/app/src/pages/account/components/Info/index.tsx
  projects/app/src/pages/account/index.tsx
  projects/app/src/pages/app/detail/components/Publish/Link/SelectUsingWayModal.tsx
  projects/app/src/pages/app/detail/components/Publish/components/showShareLinkModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/login/components/LoginForm/WechatForm.tsx
  projects/app/src/pages/login/components/LoginForm/components/FormLayout.tsx
  projects/app/src/pages/login/index.tsx
  projects/app/src/web/common/api/fetch.ts
  projects/app/src/web/common/api/request.ts
  projects/app/src/web/common/hooks/useMarkdown.ts
  projects/app/src/web/common/system/doc.ts
  projects/app/src/web/common/utils/voice.ts
Labels: size/L

#3087 4.8.13 test
  .github/workflows/fastgpt-image.yml
  packages/service/common/file/read/utils.ts
  projects/app/.env.template
  projects/app/src/pages/dataset/detail/components/NavBar.tsx
Labels: size/M

#3088 fix: workflow file upload refresh
  projects/app/src/pages/app/detail/components/Plugin/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/NodePluginConfig.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeSystemConfig.tsx
Labels: size/S

#3097 fix: http tool response
  packages/service/core/workflow/dispatch/tools/http468.ts
Labels: size/XS

#3092 loop node dynamic height
  packages/global/core/workflow/runtime/utils.ts
  packages/global/core/workflow/template/input.ts
  packages/global/core/workflow/utils.ts
  packages/service/core/workflow/dispatch/index.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/FlowController.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/Loop/NodeLoop.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/DynamicInputs/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Reference.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context/index.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/L

#3093 feat: support push chat log
  packages/service/core/chat/pushChatLog.ts
  packages/service/core/chat/saveChat.ts
  projects/app/.env.template
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/chat/share.tsx
Labels: size/L

#3098 4.8.13 test
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/global/core/workflow/template/system/variableUpdate/type.d.ts
  packages/global/core/workflow/type/io.d.ts
  packages/global/core/workflow/utils.ts
  packages/service/core/chat/pushChatLog.ts
  packages/service/core/workflow/dispatch/loop/runLoop.ts
  packages/service/core/workflow/dispatch/tools/runUpdateVar.ts
  projects/app/.env.template
  projects/app/src/pages/app/detail/components/Plugin/Header.tsx
  projects/app/src/pages/app/detail/components/Workflow/Header.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/ButtonEdge.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/ContextMenu.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/FlowController.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useDebug.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useKeyboard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/Loop/NodeLoop.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeDatasetConcat.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeHttp/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeIfElse/ListItem.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/PluginOutput.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeVariableUpdate.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/Handle/ConnectionHandle.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/Handle/ToolHandle.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/Handle/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/DynamicInputs/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Reference.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/TextInput.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Textarea.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context/workflowInitContext.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/XL

#3100 array reference check & node ui
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeIfElse/ListItem.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeIfElse/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeVariableUpdate.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/JsonEditor.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/S

#3101 feat: loop start add index
  docSite/content/zh-cn/docs/development/upgrading/4813.md
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/template/system/loop/loopStart.ts
  packages/service/core/workflow/dispatch/loop/runLoop.ts
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/workflow.json
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/Loop/NodeLoop.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/Loop/NodeLoopStart.tsx
Labels: size/L

#3102 4.8.13 test
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/global/core/workflow/template/system/loop/loopStart.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/loop/runLoop.ts
  packages/service/core/workflow/dispatch/loop/runLoopStart.ts
  packages/service/core/workflow/dispatch/plugin/runInput.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/zh/app.json
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/context.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/ButtonEdge.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/Loop/NodeLoop.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/Loop/NodeLoopStart.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Reference.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context/index.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/L

#3104 fix: plugin select files and ai response check
  docSite/content/zh-cn/docs/development/upgrading/4813.md
  packages/global/common/file/tools.ts
  packages/global/core/ai/prompt/AIChat.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/global/core/workflow/template/system/aiChat/index.ts
  packages/global/core/workflow/template/system/datasetConcat.ts
  packages/global/core/workflow/template/system/textEditor.ts
  packages/global/core/workflow/template/system/tools.ts
  packages/service/core/chat/utils.ts
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/core/workflow/dispatch/dataset/concat.ts
  packages/service/core/workflow/dispatch/dataset/search.ts
  packages/service/core/workflow/dispatch/tools/readFiles.ts
  packages/web/components/common/MySelect/MultipleRowSelect.tsx
  packages/web/i18n/en/chat.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/chat.json
  packages/web/i18n/zh/workflow.json
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeIfElse/ListItem.tsx
Labels: size/L

#3103 feat: add source id prefix env
  packages/service/core/chat/pushChatLog.ts
  projects/app/.env.template
Labels: size/L

#3106 4.8.13 test
  projects/app/.env.template
Labels: size/XS

#3107 4.8.13 test
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/zh/app.json
  projects/app/src/web/core/app/utils.ts
Labels: size/S

#3108 Update 4813.md
  docSite/content/zh-cn/docs/development/upgrading/4813.md
Labels: size/M

#3109 perf: push chat log
  docSite/content/zh-cn/docs/development/upgrading/4813.md
  packages/service/core/chat/chatSchema.ts
  packages/service/core/chat/pushChatLog.ts
  packages/service/core/chat/saveChat.ts
  packages/service/support/openapi/auth.ts
  packages/service/support/permission/controller.ts
  projects/app/.env.template
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/Logs/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/service/support/permission/auth/outLink.ts
  projects/app/src/types/app.d.ts
Labels: size/L

#3113 perf: auto add empty response
  docSite/content/zh-cn/docs/development/openapi/chat.md
  packages/service/core/workflow/dispatch/index.ts
Labels: size/L

#3117 4.8.13 test
  .github/workflows/build-sandbox-image.yml
  .github/workflows/fastgpt-image.yml
  docSite/content/zh-cn/docs/development/upgrading/4813.md
  packages/plugins/src/databaseConnection/template.json
  packages/plugins/src/drawing/baseChart/template.json
  packages/plugins/src/drawing/template.json
Labels: size/M

#3120 feat: add more share config
  packages/global/core/chat/utils.ts
  packages/global/support/outLink/api.d.ts
  packages/global/support/outLink/type.d.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/service/support/outLink/schema.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/en/chat.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/en/publish.json
  packages/web/i18n/en/user.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/publish.json
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Provider.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ResponseTags.tsx
  projects/app/src/components/core/dataset/QuoteItem.tsx
  projects/app/src/components/core/dataset/RawSourceBox.tsx
  projects/app/src/pages/api/core/dataset/collection/read.ts
  projects/app/src/pages/api/support/outLink/update.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/Publish/Link/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/pages/dataset/detail/components/MetaDataCard.tsx
  projects/app/src/service/support/permission/auth/outLink.ts
  projects/app/src/web/core/app/constants.ts
  projects/app/src/web/core/chat/context/chatContext.tsx
  projects/app/src/web/core/dataset/api.ts
  projects/app/src/web/core/dataset/hooks/readCollectionSource.ts
Labels: size/XL

#3121 fix: missing subroute
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/pages/price/index.tsx
Labels: size/XS

#3128 perf: outlink config
  .github/workflows/fastgpt-image.yml
  packages/global/core/chat/adapt.ts
  packages/global/support/outLink/api.d.ts
  packages/global/support/outLink/type.d.ts
  packages/service/core/chat/chatSchema.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/service/support/outLink/schema.ts
  packages/web/i18n/en/publish.json
  packages/web/i18n/zh/chat.json
  packages/web/i18n/zh/publish.json
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Provider.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ContextModal.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/QuoteModal.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ResponseTags.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/components/core/dataset/QuoteItem.tsx
  projects/app/src/components/core/dataset/RawSourceBox.tsx
  projects/app/src/pages/api/core/chat/getHistories.ts
  projects/app/src/pages/api/core/chat/getPaginationRecords.ts
  projects/app/src/pages/api/core/chat/outLink/init.ts
  projects/app/src/pages/api/core/dataset/collection/read.ts
  projects/app/src/pages/api/support/outLink/update.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/Logs/DetailLogsModal.tsx
  projects/app/src/pages/app/detail/components/Publish/Link/index.tsx
  projects/app/src/pages/app/detail/components/useChatTest.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/pages/dataset/detail/components/InputDataModal.tsx
  projects/app/src/pages/dataset/detail/components/MetaDataCard.tsx
  projects/app/src/service/support/permission/auth/outLink.ts
  projects/app/src/web/core/app/constants.ts
  projects/app/src/web/core/chat/context/chatContext.tsx
  projects/app/src/web/core/dataset/api.ts
  projects/app/src/web/core/dataset/hooks/readCollectionSource.ts
Labels: size/XL

#3129 fix: ts
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderResponseDetail.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
Labels: size/XS

#3127 add baidu keywords
  packages/global/support/user/type.d.ts
  packages/service/support/user/schema.ts
  projects/app/src/pages/login/components/LoginForm/components/FormLayout.tsx
  projects/app/src/pages/login/components/RegisterForm.tsx
  projects/app/src/pages/login/index.tsx
  projects/app/src/web/context/useInitApp.ts
  projects/app/src/web/support/user/api.ts
Labels: size/M

#3130 fix: null pointer
  packages/global/core/workflow/template/system/aiChat/index.ts
  packages/global/core/workflow/template/system/assignedAnswer.ts
  packages/global/core/workflow/template/system/classifyQuestion/index.ts
  packages/global/core/workflow/template/system/contextExtract/index.ts
  packages/global/core/workflow/template/system/customFeedback.ts
  packages/global/core/workflow/template/system/datasetConcat.ts
  packages/global/core/workflow/template/system/datasetSearch.ts
  packages/global/core/workflow/template/system/http468.ts
  packages/global/core/workflow/template/system/ifElse/index.ts
  packages/global/core/workflow/template/system/interactive/userSelect.ts
  packages/global/core/workflow/template/system/laf.ts
  packages/global/core/workflow/template/system/loop/loop.ts
  packages/global/core/workflow/template/system/readFiles/index.tsx
  packages/global/core/workflow/template/system/sandbox/index.ts
  packages/global/core/workflow/template/system/textEditor.ts
  packages/global/core/workflow/template/system/tools.ts
  packages/global/core/workflow/template/system/variableUpdate/index.tsx
  packages/global/core/workflow/template/system/workflowStart.ts
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  projects/app/src/components/core/ai/AISettingModal/index.tsx
  projects/app/src/components/core/app/InputGuideConfig.tsx
  projects/app/src/components/support/laf/LafAccountModal.tsx
  projects/app/src/pages/app/detail/components/Publish/FeiShu/FeiShuEditModal.tsx
  projects/app/src/pages/app/detail/components/Publish/FeiShu/index.tsx
  projects/app/src/pages/app/detail/components/Publish/OffiAccount/OffiAccountEditModal.tsx
  projects/app/src/pages/app/detail/components/Publish/OffiAccount/index.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/WebsiteConfig.tsx
  projects/app/src/pages/dataset/detail/components/Import/diffSource/FileLink.tsx
  projects/app/src/pages/dataset/detail/components/InputDataModal.tsx
Labels: size/L

#3132 解决第二次运行pnpm i时报错：File exists
  scripts/postinstall.sh
Labels: size/XS

#3136 update doc
  docSite/content/zh-cn/docs/development/upgrading/4813.md
  projects/app/package.json
  projects/app/src/pages/app/detail/components/SimpleApp/EditForm.tsx
Labels: size/M

#3138 Restore docSite content based on upstream/4.8.13-dev
  docSite/content/zh-cn/docs/development/upgrading/464.md
  docSite/content/zh-cn/docs/development/upgrading/465.md
  docSite/content/zh-cn/docs/development/upgrading/466.md
  docSite/content/zh-cn/docs/development/upgrading/468.md
  docSite/content/zh-cn/docs/guide/course/ai_settings.md
  docSite/content/zh-cn/docs/guide/workbench/workflow/ai_chat.md
  docSite/content/zh-cn/docs/guide/workbench/workflow/coreferenceResolution.md
  docSite/content/zh-cn/docs/guide/workbench/workflow/http.md
  docSite/content/zh-cn/docs/guide/workbench/workflow/text_editor.md
  docSite/content/zh-cn/docs/guide/workbench/workflow/tool.md
  docSite/content/zh-cn/docs/use-cases/external-integration/onwechat.md
Labels: size/M

#3141 update doc
  docSite/content/zh-cn/docs/development/upgrading/4813.md
Labels: size/XS

#3145 fix extra point number input register
  projects/app/src/pages/account/components/Info/index.tsx
  projects/app/src/pages/price/components/ExtraPlan.tsx
Labels: size/XS

#3147 fix: share page data;Adapt findLastIndex api
  packages/global/core/chat/utils.ts
  packages/service/core/workflow/dispatch/dataset/search.ts
  packages/web/hooks/useWidthVariable.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ResponseTags.tsx
  projects/app/src/global/core/chat/utils.ts
  projects/app/src/pages/api/core/chat/getPaginationRecords.ts
  projects/app/src/pages/api/core/chat/getResData.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/service/support/permission/auth/chat.ts
Labels: size/L

#3146 更新中文文档内容及相关图片
  docSite/assets/imgs/flow-tool1.png
  docSite/assets/imgs/flow-tool2.png
  docSite/assets/imgs/flow-tool3.png
  docSite/assets/imgs/flow-tool4.png
  docSite/assets/imgs/flow-tool5.png
  docSite/assets/imgs/flow-tool6.png
  docSite/assets/imgs/flow-tool7.png
  docSite/assets/imgs/form_input1.png
  docSite/assets/imgs/form_input2.png
  docSite/assets/imgs/form_input3.png
  docSite/content/zh-cn/docs/guide/workbench/workflow/form_input.md
  docSite/content/zh-cn/docs/guide/workbench/workflow/tool.md
Labels: size/M

#3143 Remove some global variables
  projects/app/src/pages/app/detail/components/SimpleApp/EditForm.tsx
Labels: size/XS

#3126 Fix garbled code
  packages/web/common/file/utils.ts
Labels: size/M

#3149 perf: checkbox dom
  docSite/content/zh-cn/docs/development/upgrading/4813.md
  packages/global/common/file/constants.ts
  packages/global/core/workflow/template/system/datasetSearch.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/core/workflow/dispatch/dataset/search.ts
  packages/web/common/file/utils.ts
  packages/web/components/common/MySelect/MultipleRowSelect.tsx
  packages/web/components/common/Textarea/CodeEditor/Editor.tsx
  packages/web/components/common/Textarea/CodeEditor/index.tsx
  packages/web/hooks/useI18n.ts
  projects/app/src/components/core/app/DatasetParamsModal.tsx
  projects/app/src/components/support/permission/MemberManager/AddMemberModal.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/EditForm.tsx
Labels: size/L

#3152 feat: add microsoft oauth
  packages/global/common/system/types/index.d.ts
  packages/global/support/user/constant.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/microsoft.svg
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/common.json
  projects/app/src/pages/login/components/LoginForm/components/FormLayout.tsx
Labels: size/M

#3151 update doc
  docSite/content/zh-cn/docs/development/upgrading/4813.md
  docSite/content/zh-cn/docs/development/upgrading/4814.md
Labels: size/S

#3158 Update 4813.md
  docSite/content/zh-cn/docs/development/upgrading/4813.md
Labels: size/XS

#3160 4.8.14 test
  docSite/content/zh-cn/docs/development/upgrading/4813.md
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
  packages/service/core/chat/utils.ts
Labels: size/S

#3161 remove log
  packages/service/core/workflow/dispatch/chat/oneapi.ts
Labels: size/XS

#3159 更新Doc2X插件：适配新接口
  packages/plugins/register.ts
  packages/plugins/src/Doc2X/FileImg2text/index.ts
  packages/plugins/src/Doc2X/FilePDF2text/index.ts
  packages/plugins/src/Doc2X/FilePDF2text/template.json
  packages/plugins/src/Doc2X/PDF2text/index.ts
  packages/plugins/src/Doc2X/PDF2text/template.json
  packages/plugins/src/Doc2X/URLImg2text/index.ts
  packages/plugins/src/Doc2X/URLImg2text/template.json
  packages/plugins/src/Doc2X/URLPDF2text/index.ts
  packages/plugins/src/Doc2X/URLPDF2text/template.json
Labels: size/XXL

#3162 perf: doc2x plugins
  packages/plugins/register.ts
  packages/plugins/src/Doc2X/PDF2text/index.ts
  packages/plugins/src/Doc2X/PDF2text/template.json
  packages/service/core/workflow/dispatch/tools/http468.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/service/common/system/volumnMongoWatch.ts
  projects/app/src/service/core/app/plugin.ts
  projects/app/src/service/mongo.ts
Labels: size/L

#3163 更新 plugin.ts
  projects/app/src/service/core/app/plugin.ts
Labels: size/XS

#3164 4.8.14 test
  packages/global/common/string/markdown.ts
  packages/plugins/register.ts
  packages/service/common/file/read/utils.ts
  packages/service/worker/htmlStr2Md/utils.ts
  projects/app/src/components/support/user/inform/SystemMsgModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/Handle/ConnectionHandle.tsx
  projects/app/src/service/common/system/volumnMongoWatch.ts
  projects/app/src/service/core/app/plugin.ts
  projects/app/src/service/mongo.ts
Labels: size/L

#3169 Update official_account.md
  docSite/content/zh-cn/docs/use-cases/external-integration/official_account.md
Labels: size/M

#3174 更新 4813.md
  docSite/content/zh-cn/docs/development/upgrading/4813.md
Labels: size/XS

#3177 fix: custom uid
  docSite/content/zh-cn/docs/development/openapi/chat.md
  projects/app/src/pages/chat/share.tsx
Labels: size/XS

#3179 app auto exec
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/pages/app/detail/components/Logs/DetailLogsModal.tsx
  projects/app/src/pages/app/detail/components/useChatTest.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
Labels: size/M

#3180 Update official_account.md
  docSite/content/zh-cn/docs/use-cases/external-integration/official_account.md
Labels: size/S

#3181 Update official_account.md
  docSite/content/zh-cn/docs/use-cases/external-integration/official_account.md
Labels: size/M

#3185 Update 4813.md
  docSite/content/zh-cn/docs/development/upgrading/4813.md
Labels: size/XS

#3184 add chat records loaded state
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/web/core/chat/context/chatRecordContext.tsx
Labels: size/M

#3187 feat: add training retry time
  packages/service/core/dataset/training/schema.ts
  projects/app/src/pages/api/core/dataset/update.ts
  projects/app/src/service/events/generateQA.ts
  projects/app/src/service/events/generateVector.ts
Labels: size/M

#3188 更新 configuration.md
  docSite/content/zh-cn/docs/development/configuration.md
Labels: size/XS

#3189 4.8.14 test
  docSite/content/zh-cn/docs/development/upgrading/4814.md
  packages/service/core/dataset/training/controller.ts
  packages/web/components/common/Icon/button.tsx
  packages/web/components/common/MyMenu/index.tsx
  projects/app/src/components/core/app/VariableEdit.tsx
  projects/app/src/pages/api/support/outLink/update.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeExtract/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeFormInput/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/VariableTable.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/chat/components/ChatHistorySlider.tsx
Labels: size/L

#3194 feat: share page support configuration Whether to allow the original …
  docSite/content/zh-cn/docs/development/upgrading/4814.md
  packages/global/common/file/type.d.ts
  packages/global/core/chat/utils.ts
  packages/service/support/permission/controller.ts
  packages/web/hooks/useToast.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ContextModal.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/QuoteModal.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ResponseTags.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderResponseDetail.tsx
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/components/core/dataset/QuoteItem.tsx
  projects/app/src/components/core/dataset/RawSourceBox.tsx
  projects/app/src/global/core/chat/utils.ts
  projects/app/src/pages/api/core/chat/getPaginationRecords.ts
  projects/app/src/pages/api/core/dataset/collection/read.ts
  projects/app/src/pages/app/detail/components/Publish/Link/index.tsx
  projects/app/src/service/support/permission/auth/chat.ts
  projects/app/src/web/common/api/request.ts
  projects/app/src/web/core/dataset/hooks/readCollectionSource.ts
Labels: size/L

#3200 rFix textspliter
  docSite/content/zh-cn/docs/development/upgrading/4814.md
  packages/global/common/string/textSplitter.ts
  projects/app/.env.template
Labels: size/M

#3155 refactor: snapshot store to diff
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/src/pages/app/detail/components/Plugin/Header.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Edit.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Header.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/useSnapshots.tsx
  projects/app/src/pages/app/detail/components/Workflow/Header.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/ContextMenu.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context/index.tsx
  projects/app/src/web/core/app/diff.ts
  projects/app/src/web/core/workflow/utils.ts
Labels: size/L

#3204 Snip test
  docSite/content/zh-cn/docs/development/upgrading/4814.md
  packages/service/core/dataset/collection/schema.ts
  projects/app/src/pages/app/detail/components/Plugin/Header.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Edit.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Header.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/index.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/useSnapshots.tsx
  projects/app/src/pages/app/detail/components/Workflow/Header.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context/index.tsx
  projects/app/src/web/core/app/diff.ts
  projects/app/src/web/core/workflow/utils.ts
Labels: size/L

#3207 simple app snapshot init
  projects/app/src/pages/app/detail/components/SimpleApp/Edit.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/useSnapshots.tsx
Labels: size/S

#3210 图片路径问题和示意图任务
  docSite/content/zh-cn/docs/development/openapi/auth.md
  projects/app/public/imgs/app/userSelect.svg
Labels: size/M

#3224 update deploy yml
  docSite/content/zh-cn/docs/development/docker.md
  docSite/content/zh-cn/docs/development/openapi/dataset.md
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
Labels: size/M

#3220 Add zh_TW Traditional Chinese translation
  packages/web/i18n/zh_TW/app.json
  packages/web/i18n/zh_TW/chat.json
  packages/web/i18n/zh_TW/common.json
  packages/web/i18n/zh_TW/dataset.json
  packages/web/i18n/zh_TW/file.json
  packages/web/i18n/zh_TW/login.json
  packages/web/i18n/zh_TW/publish.json
  packages/web/i18n/zh_TW/user.json
  packages/web/i18n/zh_TW/workflow.json
  projects/app/next-i18next.config.js
Labels: size/XXL

#3226 perf: Add service entry
  packages/service/type.d.ts
  projects/app/next.config.js
  projects/app/src/instrumentation.ts
  projects/app/src/service/common/system/index.ts
  projects/app/src/service/middleware/entry.ts
  projects/app/src/service/mongo.ts
Labels: size/L

#3228 4.8.14 test
  packages/global/common/string/textSplitter.ts
  packages/service/core/ai/config.ts
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  projects/app/src/pages/app/detail/components/Publish/Link/index.tsx
Labels: size/L

#3232 perf: code
  docSite/content/zh-cn/docs/development/upgrading/4814.md
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/web/components/common/MySelect/MultipleRowSelect.tsx
  packages/web/components/common/MySelect/type.d.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/global/core/app/api.d.ts
  projects/app/src/pages/api/core/app/transitionWorkflow.ts
  projects/app/src/pages/api/core/app/version/publish.ts
  projects/app/src/pages/app/detail/components/SimpleApp/AppCard.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/ChatTest.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Header.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/ChatTest.tsx
  projects/app/src/pages/app/detail/components/useChatTest.tsx
Labels: size/L

#3235 Update intro.md
  docSite/content/zh-cn/docs/shopping_cart/intro.md
Labels: size/XS

#3237 doc
  docSite/assets/imgs/image-8.png
  docSite/assets/imgs/image-9.png
  docSite/content/zh-cn/docs/development/upgrading/4814.md
  projects/app/public/docs/versionIntro.md
Labels: size/M

#3238 fix: base64 image
  docSite/content/zh-cn/docs/development/upgrading/4814.md
  packages/global/common/file/tools.ts
  packages/service/core/chat/utils.ts
  packages/service/core/workflow/dispatch/utils.ts
  projects/app/src/pages/api/core/chat/chatTest.ts
Labels: size/M

#3239 Update official_account.md
  docSite/content/zh-cn/docs/use-cases/external-integration/official_account.md
Labels: size/XS

#3240 fix: check reference
  projects/app/src/web/core/workflow/utils.ts
Labels: size/XS

#3249 fix: milvus sdk
  .github/ISSUE_TEMPLATE/bugs.md
  files/docker/docker-compose-pgvector.yml
  projects/app/next.config.js
  projects/app/src/instrumentation.ts
Labels: size/S

#3213 pdf2md
  python/pdf-marker/Dockerfile
  python/pdf-marker/Readme.md
  python/pdf-marker/api_mp.py
  python/pdf-marker/pip.conf
  python/pdf-marker/requirements.txt
  python/pdf-marker/test/test.py
Labels: size/L

#3258 调整系统插件代码。增加html 渲染安全配置。
  docSite/content/zh-cn/docs/development/configuration.md
  docSite/content/zh-cn/docs/development/custom-models/xinference.md
  docSite/content/zh-cn/docs/development/upgrading/4815.md
  packages/global/common/string/markdown.ts
  packages/plugins/type.d.ts
  packages/service/core/app/plugin/pluginGroupSchema.ts
  packages/service/core/app/plugin/type.d.ts
  packages/service/core/app/store/type.d.ts
  packages/service/support/permission/memberGroup/memberGroupSchema.ts
  packages/web/components/common/Icon/icons/common/more.svg
  packages/web/core/workflow/constants.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-TW/common.json
  projects/app/src/components/Layout/index.tsx
  projects/app/src/components/Layout/navbar.tsx
  projects/app/src/components/Layout/navbarPhone.tsx
  projects/app/src/components/Markdown/codeBlock/iframe-html.tsx
  projects/app/src/instrumentation.ts
  projects/app/src/pages/api/core/app/list.ts
  projects/app/src/pages/api/core/app/plugin/getPluginGroups.ts
  projects/app/src/pages/api/core/dataset/list.ts
  projects/app/src/pages/chat/components/ToolMenu.tsx
  projects/app/src/pages/toolkit/components/PluginCard.tsx
  projects/app/src/pages/toolkit/index.tsx
  projects/app/src/service/common/system/index.ts
  projects/app/src/service/core/app/plugin.ts
  projects/app/src/web/core/app/api/plugin.ts
Labels: size/XL

#3260 Update 4814.md
  docSite/content/zh-cn/docs/development/upgrading/4814.md
Labels: size/XS

#3268 perf: i18n
  packages/web/hooks/useI18n.ts
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/chat.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/dataset.json
  packages/web/i18n/zh-Hant/file.json
  packages/web/i18n/zh-Hant/login.json
  packages/web/i18n/zh-Hant/publish.json
  packages/web/i18n/zh-Hant/user.json
  packages/web/i18n/zh-Hant/workflow.json
  projects/app/next-i18next.config.js
  projects/app/src/web/common/utils/i18n.ts
Labels: size/S

#3267 4.8.15 test
  projects/app/src/components/Markdown/codeBlock/iframe-html.tsx
  projects/app/src/pages/login/index.tsx
Labels: size/L

#3271 Fix plugin runtime cannot upload files
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/hooks/useFileUpload.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderInput.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/renderPluginInput.tsx
  projects/app/src/pages/app/list/components/CreateModal.tsx
Labels: size/M

#3276 Update README.md
  README.md
Labels: size/XS

#3277 fix: plugin standalone display
  packages/global/core/workflow/type/node.d.ts
  packages/plugins/register.ts
  projects/app/src/pages/api/core/app/plugin/getSystemPluginTemplates.ts
  projects/app/src/pages/app/detail/components/SimpleApp/components/ToolSelectModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pages/toolkit/components/PluginCard.tsx
  projects/app/src/pages/toolkit/index.tsx
  projects/app/src/service/common/system/index.ts
Labels: size/M

#3280 Fix: Sandbox Dockerfile
  projects/sandbox/Dockerfile
Labels: size/XS
