Repository labring/FastGPT, pull requests merged in 2024-08, with the labels that each got.

#2234 Update 488.md
  docSite/content/zh-cn/docs/development/upgrading/488.md
Labels: size/XS

#2236 fix(appList): 删除应用后回到聊天选择最后一次对话的应用为删除的应用时提示无该应用问题
  projects/app/src/pages/app/list/components/List.tsx
Labels: size/XS

#2233 perf: optimize chat init api
  packages/global/core/chat/type.d.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Provider.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ContextModal.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ResponseTags.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/ChatContainer/useChat.ts
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/pages/api/core/chat/getResData.ts
  projects/app/src/pages/api/core/chat/init.ts
  projects/app/src/pages/api/core/chat/outLink/init.ts
  projects/app/src/pages/api/core/chat/team/init.ts
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/service/core/chat/utils.ts
  projects/app/src/web/core/chat/api.ts
Labels: size/L

#2250 fix: Fix the bug in debugging Tag
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ResponseTags.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/global/core/chat/utils.ts
  projects/app/src/pages/api/core/chat/init.ts
  projects/app/src/pages/api/core/chat/outLink/init.ts
  projects/app/src/pages/api/core/chat/team/init.ts
  projects/app/src/service/core/chat/utils.ts
Labels: size/L

#2252 Chat perf test
  packages/global/core/chat/type.d.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Provider.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ContextModal.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ResponseTags.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/ChatContainer/useChat.ts
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/global/core/chat/utils.ts
  projects/app/src/pages/api/core/chat/getResData.ts
  projects/app/src/pages/api/core/chat/init.ts
  projects/app/src/pages/api/core/chat/outLink/init.ts
  projects/app/src/pages/api/core/chat/team/init.ts
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/web/core/chat/api.ts
Labels: size/L

#2255 fix: get plugin input variables from history
  packages/global/core/app/plugin/utils.ts
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderInput.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/context.tsx
  projects/app/src/pages/api/v1/chat/completions.ts
Labels: size/M

#2257 fix: workflow plugin module default input value
  packages/global/core/workflow/utils.ts
Labels: size/XS

#2263 System inform
  packages/global/common/string/time.ts
  packages/global/common/type/utils.ts
  packages/global/support/user/auth/constants.ts
  packages/global/support/user/inform/constants.ts
  packages/global/support/user/inform/type.d.ts
  packages/global/support/user/team/type.d.ts
  packages/global/support/user/type.d.ts
  packages/service/common/system/timerLock/constants.ts
  packages/service/common/system/timerLock/schema.ts
  packages/service/common/system/timerLock/utils.ts
  packages/service/support/user/controller.ts
  packages/service/support/user/schema.ts
  packages/service/support/user/team/controller.ts
  packages/service/support/user/team/teamSchema.ts
  packages/service/support/wallet/sub/schema.ts
  packages/service/support/wallet/usage/schema.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/en/user.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/user.json
  projects/app/src/pages/account/components/Info.tsx
  projects/app/src/pages/account/components/UpdateNotificationModal.tsx
  projects/app/src/pages/api/support/user/account/loginByPassword.ts
  projects/app/src/pages/api/support/user/account/tokenLogin.ts
  projects/app/src/pages/api/support/user/account/update.ts
  projects/app/src/pages/app/list/components/List.tsx
  projects/app/src/service/events/generateQA.ts
  projects/app/src/service/events/generateVector.ts
  projects/app/src/service/events/utils.ts
  projects/app/src/web/support/user/api.ts
  projects/app/src/web/support/user/hooks/useSendCode.ts
Labels: size/XL

#2249 fix: collection tags
  docSite/assets/imgs/collection-tags-1.png
  docSite/assets/imgs/collection-tags-2.png
  docSite/assets/imgs/collection-tags-3.png
  docSite/content/zh-cn/docs/course/chat_input_guide.md
  docSite/content/zh-cn/docs/course/collection_tags.md
  packages/global/core/dataset/type.d.ts
  packages/global/core/workflow/template/system/datasetSearch.ts
  packages/service/core/dataset/search/controller.ts
  projects/app/src/pages/api/core/dataset/collection/list.ts
  projects/app/src/pages/dataset/detail/components/CollectionCard/Header.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/HeaderTagPopOver.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/TagManageModal.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/TagsPopOver.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/index.tsx
  projects/app/src/pages/dataset/detail/components/DataCard.tsx
Labels: size/L

#2264 fix: collection tags
  packages/web/components/common/MyModal/index.tsx
  packages/web/components/common/MyPopover/index.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/HeaderTagPopOver.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/TagManageModal.tsx
  projects/app/src/pages/dataset/detail/components/DataCard.tsx
  projects/app/src/pages/dataset/detail/components/Slider.tsx
  projects/app/src/pages/dataset/detail/index.tsx
Labels: size/M

#2268 feat: allow adding tags when creating collections via api
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/collection/utils.ts
  projects/app/src/pages/api/core/dataset/collection/create/csvTable.ts
  projects/app/src/pages/dataset/detail/components/CollectionCard/HeaderTagPopOver.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/TagManageModal.tsx
Labels: size/M

#2235 feat(chatbot-extension): a Chrome extension that can be using for chat with AI on any website
  projects/app/public/chrome_extension/fastgpt_agent/img/favicon16.png
  projects/app/public/chrome_extension/fastgpt_agent/img/favicon32.png
  projects/app/public/chrome_extension/fastgpt_agent/img/fullScreen.png
  projects/app/public/chrome_extension/fastgpt_agent/img/setting.png
  projects/app/public/chrome_extension/fastgpt_agent/manifest.json
  projects/app/public/chrome_extension/fastgpt_agent/src/background.js
  projects/app/public/chrome_extension/fastgpt_agent/src/content.js
  projects/app/public/chrome_extension/fastgpt_agent/src/popup.html
  projects/app/public/chrome_extension/fastgpt_agent/src/popup.js
  projects/app/public/chrome_extension/fastgpt_agent/src/setting.html
  projects/app/public/chrome_extension/fastgpt_agent/src/setting.js
Labels: size/XXL

#2273 Fix navbar
  docSite/content/zh-cn/docs/development/upgrading/489.md
  packages/web/components/common/Tabs/LightRowTabs.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/EditForm.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/index.tsx
  projects/app/src/pages/dataset/detail/components/Import/components/FileSelector.tsx
  projects/app/src/web/common/file/hooks/useSelectFile.tsx
Labels: size/L

#2274 Update README.md
  README.md
Labels: size/XS

#2271 feat: app owner change
  packages/global/common/error/code/app.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/lineChange.svg
  packages/web/i18n/zh/common.json
  projects/app/src/components/support/permission/ChangeOwnerModal/index.tsx
  projects/app/src/components/support/permission/ConfigPerModal/index.tsx
  projects/app/src/global/core/app/api.d.ts
  projects/app/src/pages/app/detail/components/InfoModal.tsx
  projects/app/src/pages/app/list/components/List.tsx
  projects/app/src/web/core/app/api.ts
Labels: size/L

#2278 docs: Repair and supplement document content xinference.md
  docSite/content/zh-cn/docs/development/custom-models/xinference.md
Labels: size/M

#2283 Update 482.md
  docSite/content/zh-cn/docs/development/upgrading/482.md
Labels: size/XS

#2280 Move app owner
  docSite/content/zh-cn/docs/development/upgrading/489.md
  packages/global/common/error/code/app.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/lineChange.svg
  packages/web/components/common/Icon/icons/modal/changePer.svg
  packages/web/i18n/zh/common.json
  projects/app/src/components/support/permission/ChangeOwnerModal/index.tsx
  projects/app/src/components/support/permission/ConfigPerModal/index.tsx
  projects/app/src/global/core/app/api.d.ts
  projects/app/src/pages/app/detail/components/InfoModal.tsx
  projects/app/src/pages/app/detail/index.tsx
  projects/app/src/pages/app/list/components/List.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/web/core/app/api.ts
Labels: size/L

#2139 Adjust the parameters of gpt-40-mini model, custom for QA mode Add chunkSize setting input
  projects/app/data/config.json
  projects/app/src/pages/dataset/detail/components/Import/Context.tsx
Labels: size/S

#2291 4.8.9 test fix
  docSite/content/zh-cn/docs/development/openapi/dataset.md
  docSite/content/zh-cn/docs/development/upgrading/489.md
  packages/global/common/error/utils.ts
  packages/global/common/file/constants.ts
  packages/global/common/file/type.d.ts
  packages/global/common/frequenctLimit/type.d.ts
  packages/global/core/ai/prompt/agent.ts
  packages/global/core/workflow/template/system/readFiles/index.tsx
  packages/global/support/wallet/usage/constants.ts
  packages/service/common/file/gridfs/utils.ts
  packages/service/common/file/multer.ts
  packages/service/core/workflow/dispatch/agent/extract.ts
  packages/service/core/workflow/dispatch/tools/readFiles.ts
  packages/service/core/workflow/dispatchV1/agent/classifyQuestion.ts
  packages/service/support/permission/controller.ts
  packages/web/components/common/Avatar/index.tsx
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/app/simpleMode/tts.svg
  packages/web/components/common/Icon/icons/core/workflow/template/readFiles.svg
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/user.json
  projects/app/public/imgs/app/fileUploadPlaceholder.png
  projects/app/public/imgs/app/fileUploadPlaceholder.svg
  projects/app/public/imgs/app/question.svg
  projects/app/public/imgs/app/visionModel.png
  projects/app/src/components/core/app/FileSelect.tsx
  projects/app/src/components/core/app/TTSSelect.tsx
  projects/app/src/components/core/app/Tip.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/type.d.ts
  projects/app/src/pages/account/components/Info.tsx
  projects/app/src/pages/api/common/file/upload.ts
  projects/app/src/pages/api/core/dataset/list.ts
  projects/app/src/pages/dataset/detail/components/Import/Context.tsx
  projects/app/src/pages/dataset/detail/components/Import/commonProgress/DataProcess.tsx
  projects/app/src/service/common/frequencyLimit/api.ts
  projects/app/src/service/core/app/utils.ts
  projects/app/src/web/core/dataset/context/datasetPageContext.tsx
  projects/app/src/web/support/user/hooks/useSendCode.ts
Labels: size/XXL

#2295 chore(notification bind): team member notification bind hint text adjusting
  packages/web/i18n/zh/user.json
  projects/app/src/pages/account/components/Info.tsx
Labels: size/S

#2297 fix: bind notification account
  projects/app/src/pages/account/components/Info.tsx
Labels: size/XS

#2298 fix: quote display error
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ResponseTags.tsx
Labels: size/XS

#2299 4.8.9 test
  packages/service/core/ai/model.ts
  packages/service/core/workflow/dispatch/tools/readFiles.ts
  projects/app/public/imgs/app/templates/flux.svg
  projects/app/src/components/core/ai/AISettingModal/index.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/components/core/dataset/SearchParamsTip.tsx
  projects/app/src/pages/api/common/file/upload.ts
  projects/app/src/pages/app/detail/components/SimpleApp/EditForm.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeDatasetConcat.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SelectDatasetParams.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/service/support/permission/auth/chat.ts
  projects/app/src/web/common/file/controller.ts
  projects/app/src/web/common/system/utils.ts
  projects/app/src/web/core/app/templates.ts
  projects/app/src/web/core/chat/utils.ts
Labels: size/XXL

#2288 fix(query): extension prompt template
  packages/service/core/ai/functions/queryExtension.ts
Labels: size/XS

#2012 feat: add app template market
  packages/global/core/app/constants.ts
  packages/global/core/workflow/type/index.d.ts
  packages/service/type.d.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/app/type/templateFill.svg
  packages/web/components/common/MyModal/index.tsx
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/common.json
  projects/app/public/appTemplateMarketTemplates/TranslateRobot/avatar.svg
  projects/app/public/appTemplateMarketTemplates/TranslateRobot/template.json
  projects/app/public/appTemplateMarketTemplates/chatGuide/avatar.png
  projects/app/public/appTemplateMarketTemplates/chatGuide/template.json
  projects/app/public/appTemplateMarketTemplates/dalle/avatar.svg
  projects/app/public/appTemplateMarketTemplates/dalle/template.json
  projects/app/public/appTemplateMarketTemplates/google/avatar.svg
  projects/app/public/appTemplateMarketTemplates/google/template.json
  projects/app/public/appTemplateMarketTemplates/toolChat/avatar.png
  projects/app/public/appTemplateMarketTemplates/toolChat/template.json
  projects/app/src/pages/api/core/app/template/getTemplateMarketItemDetail.ts
  projects/app/src/pages/api/core/app/template/getTemplateMarketList.ts
  projects/app/src/pages/app/list/components/CreateModal.tsx
  projects/app/src/pages/app/list/components/TemplateMarketModal.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/service/core/app/template.ts
  projects/app/src/web/core/app/api/template.ts
Labels: size/XXL

#2310 chore: change notification account bind hint text
  packages/web/i18n/zh/user.json
Labels: size/XS

#2290 feat(app publish): feishu bot
  docSite/assets/imgs/feishu-bot-1.png
  docSite/assets/imgs/feishu-bot-2.png
  docSite/assets/imgs/feishu-bot-3.png
  docSite/assets/imgs/feishu-bot-4.png
  docSite/assets/imgs/feishu-bot-5.png
  docSite/assets/imgs/feishu-bot-6.png
  docSite/assets/imgs/feishu-bot-7.png
  docSite/assets/imgs/feishu-bot-8.png
  docSite/assets/imgs/feishu-bot-9.png
  docSite/content/zh-cn/docs/use-cases/feishu-bot.md
  packages/global/support/outLink/type.d.ts
  packages/global/support/tmpData/constant.ts
  packages/global/support/tmpData/type.d.ts
  packages/service/core/chat/saveChat.ts
  packages/service/support/outLink/schema.ts
  packages/service/support/permission/auth/team.ts
  packages/service/support/permission/publish/authLink.ts
  packages/service/support/tmpData/controller.ts
  packages/service/support/tmpData/schema.ts
  packages/web/components/common/MyModal/index.tsx
  packages/web/i18n/zh/publish.json
  projects/app/public/imgs/outlink/feishu-copylink-instruction.png
  projects/app/src/components/support/apikey/Table.tsx
  projects/app/src/pages/api/support/outLink/feishu/[token].ts
  projects/app/src/pages/api/support/outLink/update.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/Publish/FeiShu/FeiShuEditModal.tsx
  projects/app/src/pages/app/detail/components/Publish/FeiShu/index.tsx
  projects/app/src/pages/app/detail/components/Publish/components/BasicInfo.tsx
  projects/app/src/pages/app/detail/components/Publish/components/showShareLinkModal.tsx
  projects/app/src/pages/app/detail/components/Publish/index.tsx
  projects/app/src/web/core/app/constants.ts
  projects/app/src/web/support/outLink/api.ts
Labels: size/XL

#2330 4.8.9 test fix
  packages/global/common/string/tools.ts
  packages/global/core/chat/utils.ts
  packages/service/core/ai/functions/queryExtension.ts
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/common.json
  projects/app/package.json
  projects/app/src/pages/app/detail/components/constants.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
Labels: size/M

#2332 fix: doc
  docSite/content/zh-cn/docs/development/upgrading/489.md
  projects/app/public/docs/versionIntro.md
Labels: size/M

#2334 feat: 4.8.9 doc
  README.md
  docSite/assets/imgs/sealos-deploy1.jpg
  docSite/content/zh-cn/docs/development/sealos.md
  docSite/content/zh-cn/docs/development/upgrading/4810.md
  docSite/content/zh-cn/docs/development/upgrading/489.md
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
Labels: size/M

#2335 Update README.md
  README.md
Labels: size/XS

#2337 App template market
  packages/global/common/system/types/index.d.ts
  packages/global/core/app/constants.ts
  packages/global/core/workflow/type/index.d.ts
  packages/service/type.d.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/searchLight.svg
  packages/web/components/common/Icon/icons/common/upRightArrowLight.svg
  packages/web/components/common/Input/SearchInput/index.tsx
  packages/web/components/common/MyMenu/index.tsx
  packages/web/components/common/MyModal/index.tsx
  packages/web/components/common/Textarea/PromptEditor/Editor.tsx
  packages/web/components/common/Textarea/PromptEditor/index.module.scss
  packages/web/components/common/Textarea/PromptEditor/index.tsx
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/common.json
  projects/app/data/pluginTemplates/customFeedback.json
  projects/app/data/pluginTemplates/getCurrentTime.json
  projects/app/data/pluginTemplates/textEditor.json
  projects/app/data/pluginTemplates/v1/customFeedback.json
  projects/app/data/pluginTemplates/v1/getCurrentTime.json
  projects/app/data/pluginTemplates/v1/textEditor.json
  projects/app/data/pluginTemplates/v1/tfSwitch.json
  projects/app/public/appMarketTemplates/CQ/template.json
  projects/app/public/appMarketTemplates/TranslateRobot/avatar.svg
  projects/app/public/appMarketTemplates/TranslateRobot/template.json
  projects/app/public/appMarketTemplates/chatGuide/template.json
  projects/app/public/appMarketTemplates/flux/avatar.svg
  projects/app/public/appMarketTemplates/flux/template.json
  projects/app/public/appMarketTemplates/google/avatar.svg
  projects/app/public/appMarketTemplates/google/template.json
  projects/app/public/appMarketTemplates/plugin-dalle/avatar.svg
  projects/app/public/appMarketTemplates/plugin-dalle/template.json
  projects/app/public/appMarketTemplates/plugin-feishu/avatar.svg
  projects/app/public/appMarketTemplates/plugin-feishu/template.json
  projects/app/public/appMarketTemplates/simpleDatasetChat/template.json
  projects/app/public/appMarketTemplates/srt-translate/template.json
  projects/app/public/appMarketTemplates/timeBot/template.json
  projects/app/public/imgs/app/templateFill.svg
  projects/app/public/imgs/app/templates/dalle.svg
  projects/app/src/components/core/ai/SettingLLMModel/index.tsx
  projects/app/src/components/core/app/WelcomeTextConfig.tsx
  projects/app/src/pages/api/core/app/create.ts
  projects/app/src/pages/api/core/app/template/detail.ts
  projects/app/src/pages/api/core/app/template/list.ts
  projects/app/src/pages/app/detail/components/SimpleApp/Edit.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/EditForm.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Header.tsx
  projects/app/src/pages/app/list/components/CreateModal.tsx
  projects/app/src/pages/app/list/components/TemplateMarketModal.tsx
  projects/app/src/pages/app/list/components/TypeTag.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/pages/login/components/RegisterForm.tsx
  projects/app/src/service/common/system/index.ts
  projects/app/src/service/core/app/template.ts
  projects/app/src/web/core/app/api/template.ts
  projects/app/src/web/core/app/templates.ts
Labels: size/XXL

#2341 fix(docs): reranker typo
  docSite/content/zh-cn/docs/development/custom-models/bge-rerank.md
  python/bge-rerank/README.md
Labels: size/S

#2352 fix(docs): home host typo
  python/bge-rerank/README.md
Labels: size/XS

#2353 Update 489.md
  docSite/content/zh-cn/docs/development/upgrading/489.md
Labels: size/XS

#2358 docs(bge-rerank): qa docs
  docSite/content/zh-cn/docs/development/custom-models/bge-rerank.md
Labels: size/S

#2356 feat: add workflow helperline
  packages/global/core/workflow/type/index.d.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/HelperLines.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useUtils.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
Labels: size/L

#2382 Update feishu.md
  docSite/content/zh-cn/docs/use-cases/feishu.md
Labels: size/XS

#2397 User select node
  packages/global/core/ai/type.d.ts
  packages/global/core/chat/adapt.ts
  packages/global/core/chat/constants.ts
  packages/global/core/chat/type.d.ts
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/node/constant.ts
  packages/global/core/workflow/runtime/constants.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/global/core/workflow/template/constants.ts
  packages/global/core/workflow/template/system/userSelect/index.ts
  packages/global/core/workflow/template/system/userSelect/type.d.ts
  packages/global/core/workflow/type/node.d.ts
  packages/service/core/chat/controller.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/interactive/userSelect.ts
  packages/service/core/workflow/dispatch/plugin/run.ts
  packages/service/core/workflow/dispatch/tools/runApp.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/workflow/template/userSelect.svg
  packages/web/components/common/Icon/icons/minus.svg
  packages/web/core/workflow/constants.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/en/chat.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/chat.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/workflow.json
  packages/web/styles/theme.ts
  projects/app/public/imgs/app/userSelect.svg
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/type.d.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/utils.ts
  projects/app/src/components/core/chat/ChatContainer/type.d.ts
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/Plugin/Header.tsx
  projects/app/src/pages/app/detail/components/Workflow/Header.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeUserSelect.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
  projects/app/src/pages/app/detail/components/useChatTest.tsx
  projects/app/src/service/core/app/utils.ts
  projects/app/src/web/common/api/fetch.ts
Labels: size/XXL

#2378 4.8.10 perf
  docSite/content/zh-cn/docs/development/upgrading/4810.md
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  projects/app/src/global/core/chat/api.d.ts
  projects/app/src/global/core/chat/constants.ts
  projects/app/src/pages/api/core/chat/getResData.ts
  projects/app/src/pages/api/core/chat/init.ts
  projects/app/src/pages/api/core/chat/outLink/init.ts
  projects/app/src/pages/api/core/chat/team/init.ts
  projects/app/src/pages/api/core/dataset/exportAll.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/HelperLines.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useUtils.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
  projects/app/src/pages/chat/components/ChatHeader.tsx
  projects/app/src/service/support/permission/auth/chat.ts
Labels: size/XL

#2398 调整.env.template关于mongodb的说明，使得更易于理解
  projects/app/.env.template
Labels: size/XS

#2376 feat(http): text/plain is allowed
  packages/global/core/workflow/runtime/type.d.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
Labels: size/XS

#2401 4.8.10 test
  .github/imgs/intro1.png
  .github/imgs/intro2.png
  .github/imgs/intro3.png
  .github/imgs/intro4.png
  docSite/content/zh-cn/docs/development/upgrading/4810.md
  docSite/content/zh-cn/docs/use-cases/feishu.md
  packages/global/core/workflow/constants.ts
  packages/service/core/chat/utils.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  packages/web/components/common/MyModal/index.tsx
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/publish.json
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/publish.json
  projects/app/public/imgs/app/fileinput.svg
  projects/app/public/imgs/app/variable.svg
  projects/app/public/imgs/app/welcome.svg
  projects/app/src/components/common/MyRadio/index.tsx
  projects/app/src/components/core/ai/AISettingModal/index.tsx
  projects/app/src/components/core/app/Tip.tsx
  projects/app/src/components/support/wallet/StandardPlanContentList.tsx
  projects/app/src/pages/api/core/app/copy.ts
  projects/app/src/pages/api/core/dataset/collection/update.ts
  projects/app/src/pages/app/detail/components/Publish/FeiShu/FeiShuEditModal.tsx
  projects/app/src/pages/app/detail/components/Publish/OffiAccount/OffiAccountEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SettingLLMModel.tsx
  projects/app/src/pages/dataset/detail/index.tsx
Labels: size/XL

#2411 4.8.10 test
  docSite/assets/imgs/collection-tags-1.png
  docSite/assets/imgs/fastgpt-api.jpg
  docSite/assets/imgs/fastgpt-api1.jpg
  docSite/assets/imgs/fileinpu-1.png
  docSite/assets/imgs/fileinpu-3.jpg
  docSite/assets/imgs/fileinpu-4.jpg
  docSite/assets/imgs/fileinpu-5.jpg
  docSite/assets/imgs/fileinpu-7.jpg
  docSite/assets/imgs/gpt-translate-example.png
  docSite/assets/imgs/sealos-deploy1.jpg
  docSite/content/zh-cn/docs/commercial/intro.md
  docSite/content/zh-cn/docs/course/ai_settings.md
  docSite/content/zh-cn/docs/course/feishu.md
  docSite/content/zh-cn/docs/course/openapi.md
  docSite/content/zh-cn/docs/development/openapi/chat.md
  docSite/content/zh-cn/docs/use-cases/onwechat.md
  projects/app/src/pages/app/detail/components/Publish/FeiShu/FeiShuEditModal.tsx
  projects/app/src/pages/app/detail/components/Publish/OffiAccount/OffiAccountEditModal.tsx
Labels: size/M

#2413 perf: change value desc position & fix templates
  packages/global/core/workflow/node/constant.ts
  packages/global/core/workflow/template/system/aiChat.ts
  packages/global/core/workflow/template/system/datasetConcat.ts
  packages/global/core/workflow/template/system/datasetSearch.ts
  packages/global/core/workflow/template/system/runApp/index.ts
  packages/global/core/workflow/type/io.d.ts
  projects/app/public/appMarketTemplates/CQ/template.json
  projects/app/public/appMarketTemplates/simpleDatasetChat/template.json
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeDatasetConcat.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/PluginOutput.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeWorkflowStart.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/FieldEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/Label.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/DynamicInputs/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SettingQuotePrompt.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderOutput/FieldEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderOutput/Label.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/ValueTypeLabel.tsx
Labels: size/L

#2412 fix(publish): generate correct chat history and usage
  packages/global/core/chat/constants.ts
  packages/global/core/chat/utils.ts
  packages/global/support/wallet/usage/constants.ts
  packages/global/support/wallet/usage/tools.ts
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/user.json
Labels: size/M

#2415 chore(ui): dataset-tags
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/add2.svg
  packages/web/components/common/Icon/icons/common/check.svg
  packages/web/styles/theme.ts
  projects/app/src/components/core/app/DatasetParamsModal.tsx
  projects/app/src/components/core/app/InputGuideConfig.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/dataset/RawSourceBox.tsx
  projects/app/src/components/support/permission/MemberManager/AddMemberModal.tsx
  projects/app/src/components/support/user/team/TeamManageModal/components/PermissionManage/AddManager.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/AppCard.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/HeaderTagPopOver.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/TagManageModal.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/TagsPopOver.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/index.tsx
Labels: size/M

#2427 docs(offiaccount): add offiaccount docs
  docSite/assets/imgs/offiaccount-1.png
  docSite/assets/imgs/offiaccount-2.png
  docSite/assets/imgs/offiaccount-3.png
  docSite/assets/imgs/offiaccount-4.png
  docSite/assets/imgs/offiaccount-5.png
  docSite/assets/imgs/offiaccount-6.png
  docSite/assets/imgs/offiaccount-7.png
  docSite/assets/imgs/offiaccount-8.png
  docSite/assets/imgs/offiaccount-9.png
  docSite/content/zh-cn/docs/course/official_account.md
Labels: size/M

#2429 fix: i18n display
  projects/app/src/components/support/wallet/StandardPlanContentList.tsx
  projects/app/src/pages/chat/components/ChatHeader.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/pages/price/components/Standard.tsx
Labels: size/S

#2435 Invoice
  packages/global/support/user/team/type.d.ts
  packages/global/support/wallet/bill/constants.ts
  packages/global/support/wallet/bill/invoice/constants.ts
  packages/global/support/wallet/bill/type.d.ts
  packages/web/common/file/hooks/useSelectFile.tsx
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/infoRounded.svg
  packages/web/components/common/Icon/icons/paragraph.svg
  packages/web/components/common/Icon/icons/point.svg
  packages/web/components/common/MyPopover/PopoverConfirm.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/VariableLabelPickerPlugin/index.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/VariableLabelPlugin/components/VariableLabel.tsx
  packages/web/hooks/usePagination.tsx
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/publish.json
  packages/web/i18n/en/user.json
  packages/web/i18n/zh/common.json
  projects/app/public/imgs/modal/invoice.svg
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderInput.tsx
  projects/app/src/components/support/permission/DefaultPerList/index.tsx
  projects/app/src/pages/account/components/Info.tsx
  projects/app/src/pages/account/components/bill/ApplyInvoiceModal.tsx
  projects/app/src/pages/account/components/bill/BillAndInvoice.tsx
  projects/app/src/pages/account/components/bill/BillTable.tsx
  projects/app/src/pages/account/components/bill/InvoiceHeaderForm.tsx
  projects/app/src/pages/account/components/bill/InvoiceTable.tsx
  projects/app/src/pages/account/index.tsx
  projects/app/src/pages/api/common/file/upload.ts
  projects/app/src/pages/app/detail/components/Publish/components/BasicInfo.tsx
  projects/app/src/pages/app/detail/components/Publish/components/showShareLinkModal.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/HeaderTagPopOver.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/TagsPopOver.tsx
  projects/app/src/pages/dataset/list/component/List.tsx
  projects/app/src/pages/dataset/list/context.tsx
  projects/app/src/web/support/user/team/api.ts
  projects/app/src/web/support/wallet/bill/invoice/api.ts
Labels: size/XXL

#2437 feat: custom-censor-check
  packages/service/common/api/requestPlusApi.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
Labels: size/XS

#2449 perf: add docs entries in the publish page
  projects/app/src/pages/app/detail/components/Publish/FeiShu/index.tsx
  projects/app/src/pages/app/detail/components/Publish/OffiAccount/index.tsx
Labels: size/M

#2414 feat: SSO
  packages/global/common/system/types/index.d.ts
  projects/app/src/components/Layout/auth.tsx
  projects/app/src/pages/login/components/LoginForm/components/FormLayout.tsx
  projects/app/src/pages/login/sso.tsx
  projects/app/src/web/support/user/api.ts
Labels: size/M

#2448 style: 知识库新列表
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/dataset/commonDatasetColor.svg
  packages/web/components/common/Icon/icons/core/dataset/externalDatasetColor.svg
  packages/web/components/common/Icon/icons/core/dataset/websiteDatasetColor.svg
  packages/web/i18n/en/common.json
  packages/web/i18n/en/publish.json
  packages/web/i18n/en/user.json
  packages/web/i18n/zh/common.json
  projects/app/src/pages/dataset/list/component/CreateModal.tsx
  projects/app/src/pages/dataset/list/component/List.tsx
  projects/app/src/pages/dataset/list/context.tsx
  projects/app/src/pages/dataset/list/index.tsx
Labels: size/L

#2457 pref: login/forgetpass texts
  packages/global/common/system/types/index.d.ts
  projects/app/src/pages/account/components/UpdateNotificationModal.tsx
  projects/app/src/pages/login/components/ForgetPasswordForm.tsx
  projects/app/src/pages/login/components/LoginForm/LoginForm.tsx
  projects/app/src/pages/login/components/LoginForm/components/FormLayout.tsx
  projects/app/src/pages/login/components/RegisterForm.tsx
Labels: size/L

#2460 style: database refactor
  packages/global/core/dataset/type.d.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/help.svg
  packages/web/components/common/Icon/icons/core/dataset/commonDatasetColor.svg
  packages/web/components/common/Icon/icons/core/dataset/commonDatasetOutline.svg
  packages/web/components/common/Icon/icons/core/dataset/externalDatasetColor.svg
  packages/web/components/common/Icon/icons/core/dataset/externalDatasetOutline.svg
  packages/web/components/common/Icon/icons/core/dataset/websiteDatasetColor.svg
  packages/web/components/common/Icon/icons/core/dataset/websiteDatasetOutline.svg
  packages/web/components/common/MyMenu/index.tsx
  projects/app/src/pages/api/core/dataset/list.ts
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/pages/dataset/list/component/CreateModal.tsx
  projects/app/src/pages/dataset/list/component/List.tsx
  projects/app/src/pages/dataset/list/component/SideTag.tsx
  projects/app/src/pages/dataset/list/index.tsx
Labels: size/XL

#2465 feat: add http node timeout
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/template/system/http468.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/common.json
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeHttp/index.tsx
Labels: size/L

#2468 Update README.md
  README.md
Labels: size/XS

#2469 perf: invoice page refresh after apply
  projects/app/src/pages/account/components/bill/ApplyInvoiceModal.tsx
  projects/app/src/pages/account/components/bill/BillAndInvoice.tsx
  projects/app/src/pages/account/index.tsx
Labels: size/M

#2471 Update official_account.md
  docSite/content/zh-cn/docs/course/official_account.md
Labels: size/M

#2472 Update official_account.md
  docSite/content/zh-cn/docs/course/official_account.md
Labels: size/XS

#2470 4.8.10 test
  docSite/content/zh-cn/docs/development/upgrading/4810.md
  packages/global/core/workflow/template/system/http468.ts
  packages/global/support/user/team/type.d.ts
  packages/global/support/wallet/bill/type.d.ts
  packages/service/common/file/multer.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  packages/web/i18n/en/dataset.json
  packages/web/i18n/en/user.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/dataset.json
  packages/web/i18n/zh/user.json
  projects/app/.env.template
  projects/app/src/components/Markdown/img/Image.tsx
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/components/common/NextHead/index.tsx
  projects/app/src/pages/account/components/Info.tsx
  projects/app/src/pages/account/components/bill/ApplyInvoiceModal.tsx
  projects/app/src/pages/account/components/bill/BillAndInvoice.tsx
  projects/app/src/pages/account/components/bill/BillTable.tsx
  projects/app/src/pages/account/components/bill/InvoiceHeaderForm.tsx
  projects/app/src/pages/account/components/bill/InvoiceTable.tsx
  projects/app/src/pages/api/common/file/upload.ts
  projects/app/src/pages/api/core/dataset/collection/create/localFile.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeHttp/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/app/list/components/List.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/pages/dataset/detail/components/Info.tsx
  projects/app/src/pages/dataset/list/component/CreateModal.tsx
  projects/app/src/pages/dataset/list/component/List.tsx
  projects/app/src/pages/dataset/list/component/SideTag.tsx
  projects/app/src/service/mongo.ts
Labels: size/XXL

#2473 Update official_account.md
  docSite/content/zh-cn/docs/course/official_account.md
Labels: size/XS

#2477 Update README.md
  README.md
Labels: size/XS

#2488 4.8.10 test fix
  docSite/content/zh-cn/docs/development/upgrading/4810.md
  packages/global/core/workflow/template/system/aiChat.ts
  packages/web/components/common/MyDrawer/MyRightDrawer.tsx
  projects/app/src/pages/dataset/detail/components/Info.tsx
  projects/app/src/web/context/QueryClient.tsx
Labels: size/S

#2436 feat: undo-redo & edit snapshots
  packages/global/common/string/time.ts
  packages/global/core/app/version.d.ts
  packages/service/core/app/controller.ts
  packages/service/core/app/version/schema.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/paused.svg
  packages/web/components/common/Icon/icons/common/subtract.svg
  packages/web/components/common/Icon/icons/common/warn.svg
  packages/web/components/common/Icon/icons/core/modules/fixview.svg
  packages/web/components/common/Icon/icons/core/workflow/publish.svg
  packages/web/components/common/Icon/icons/core/workflow/redo.svg
  packages/web/components/common/Icon/icons/core/workflow/undo.svg
  packages/web/components/common/Icon/icons/core/workflow/upload.svg
  packages/web/components/common/MyPopover/index.tsx
  packages/web/components/common/MyTooltip/index.tsx
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/workflow.json
  projects/app/src/global/core/app/api.d.ts
  projects/app/src/pages/api/core/app/create.ts
  projects/app/src/pages/api/core/app/version/publish.ts
  projects/app/src/pages/api/core/app/version/update.ts
  projects/app/src/pages/api/core/chat/init.ts
  projects/app/src/pages/api/core/chat/outLink/init.ts
  projects/app/src/pages/api/core/chat/team/init.ts
  projects/app/src/pages/app/detail/components/Plugin/Header.tsx
  projects/app/src/pages/app/detail/components/Workflow/Header.tsx
  projects/app/src/pages/app/detail/components/Workflow/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/AppCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/ChatTest.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/ButtonEdge.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/FlowController.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/SaveAndPublish.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/index.module.scss
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeSystemConfig.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Textarea.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
  projects/app/src/pages/app/detail/components/WorkflowPublishHistoriesSlider.tsx
  projects/app/src/pages/app/detail/components/constants.tsx
  projects/app/src/pages/app/detail/components/context.tsx
  projects/app/src/web/core/app/api/version.ts
  projects/app/src/web/core/workflow/utils.ts
Labels: size/XXL

#2492 perf: workflow code
  docSite/content/zh-cn/docs/development/upgrading/4810.md
  projects/app/src/pages/account/components/Info/ConversionModal.tsx
  projects/app/src/pages/account/components/Info/OpenAIAccountModal.tsx
  projects/app/src/pages/account/components/Info/UpdateNotificationModal.tsx
  projects/app/src/pages/account/components/Info/UpdatePswModal.tsx
  projects/app/src/pages/account/components/Info/index.tsx
  projects/app/src/pages/account/components/Info/standardDetailModal.tsx
  projects/app/src/pages/account/index.tsx
  projects/app/src/pages/app/detail/components/Plugin/index.tsx
  projects/app/src/pages/app/detail/components/Workflow/Header.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
Labels: size/L

#2493 fix: undo & redo
  packages/web/components/common/MyDrawer/CustomRightDrawer.tsx
  packages/web/i18n/en/app.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/app.json
  packages/web/i18n/zh/workflow.json
  projects/app/src/pages/api/core/app/version/detail.ts
  projects/app/src/pages/api/core/app/version/listWorkflow.tsx
  projects/app/src/pages/app/detail/components/Plugin/Header.tsx
  projects/app/src/pages/app/detail/components/PublishHistoriesSlider.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Header.tsx
  projects/app/src/pages/app/detail/components/Workflow/Header.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/FlowController.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/SaveAndPublish.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
  projects/app/src/pages/app/detail/components/WorkflowPublishHistoriesSlider.tsx
  projects/app/src/pages/app/detail/components/context.tsx
  projects/app/src/web/core/app/api/version.ts
Labels: size/L

#2496 fix: dispatch workflow skip status
  packages/service/core/workflow/dispatch/index.ts
Labels: size/L

#2498 perf: onpublish app
  projects/app/src/pages/app/detail/components/Plugin/Header.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/Header.tsx
  projects/app/src/pages/app/detail/components/Workflow/Header.tsx
  projects/app/src/pages/app/detail/components/WorkflowPublishHistoriesSlider.tsx
  projects/app/src/pages/app/detail/components/context.tsx
Labels: size/L

#2497 perf: disabled change version when change version name
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/FlowController.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowPublishHistoriesSlider.tsx
Labels: size/M

#2499 4.8.10 test
  projects/app/src/pages/api/admin/initv4810.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/FlowController.tsx
  projects/app/src/web/core/app/constants.ts
Labels: size/M

#2504 4810 doc
  docSite/content/zh-cn/docs/course/feishu.md
  docSite/content/zh-cn/docs/development/upgrading/4810.md
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  projects/app/src/pages/api/admin/initv4810.ts
Labels: size/M

#2510 New pay (#2484)
  packages/global/support/wallet/bill/api.d.ts
  packages/global/support/wallet/bill/type.d.ts
  packages/global/support/wallet/sub/constants.ts
  packages/global/support/wallet/sub/type.d.ts
  packages/service/support/wallet/sub/schema.ts
  packages/service/support/wallet/sub/utils.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/en/user.json
  packages/web/i18n/zh/common.json
  packages/web/i18n/zh/user.json
  projects/app/src/components/support/wallet/QRCodePayModal.tsx
  projects/app/src/pages/account/components/PayModal.tsx
  projects/app/src/pages/api/support/user/team/plan/getTeamPlanStatus.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pages/price/components/Standard.tsx
  projects/app/src/pages/price/index.tsx
  projects/app/src/web/support/wallet/sub/api.ts
Labels: size/XL

#2513 perf: plan tip
  packages/global/support/wallet/sub/constants.ts
  packages/web/i18n/en/user.json
  packages/web/i18n/zh/user.json
  projects/app/src/pages/account/components/Info/standardDetailModal.tsx
  projects/app/src/pages/price/components/Standard.tsx
  scripts/icon/index.js
Labels: size/M

#2514 conversion points
  projects/app/src/pages/account/components/Info/index.tsx
Labels: size/XS

#2516 fix: fix i18n
  packages/web/i18n/zh/user.json
  projects/app/src/pages/account/components/Info/ConversionModal.tsx
  projects/app/src/pages/account/components/Info/index.tsx
Labels: size/S

#2518 chore: i18n query script
  package.json
  pnpm-lock.yaml
  scripts/i18n/package.json
  scripts/i18n/query.js
  scripts/i18n/query.ts
Labels: size/L

#2517 4.8.10 test fix
  packages/global/core/ai/prompt/agent.ts
  packages/service/core/app/controller.ts
Labels: size/XS

#2525 fix welcome text rerender & add copyright
  packages/web/components/common/Input/HttpInput/Editor.tsx
  packages/web/components/common/Textarea/PromptEditor/Editor.tsx
  packages/web/components/common/Textarea/PromptEditor/utils.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeSystemConfig.tsx
Labels: size/M

#2521 feat(workflow): allow apps to be invoked like plugins
  packages/global/core/workflow/node/constant.ts
  packages/global/core/workflow/template/constants.ts
  packages/global/core/workflow/template/system/runAppPlugin.ts
  packages/global/core/workflow/utils.ts
  packages/service/core/app/plugin/controller.ts
  packages/service/core/workflow/dispatch/agent/runAppModule.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/web/components/core/workflow/NodeInputSelect.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/common.json
  projects/app/src/pages/api/core/app/create.ts
  projects/app/src/pages/api/core/app/version/publish.ts
  projects/app/src/pages/api/core/app/version/revert.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/index.tsx
  projects/app/src/web/core/app/api/plugin.ts
Labels: size/L

#2530 Encapsulate SSE response methods
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/global/core/workflow/template/system/userSelect/type.d.ts
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/interactive/userSelect.ts
  packages/service/core/workflow/dispatch/tools/answer.ts
  packages/service/core/workflow/dispatch/tools/customFeedback.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  packages/service/core/workflow/dispatch/tools/runApp.ts
  packages/service/core/workflow/dispatch/tools/runUpdateVar.ts
  packages/service/core/workflow/dispatch/type.d.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/service/core/workflow/dispatchV1/agent/classifyQuestion.ts
  packages/service/core/workflow/dispatchV1/agent/extract.ts
  packages/service/core/workflow/dispatchV1/agent/runTool/constants.ts
  packages/service/core/workflow/dispatchV1/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatchV1/agent/runTool/index.ts
  packages/service/core/workflow/dispatchV1/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatchV1/agent/runTool/stopTool.ts
  packages/service/core/workflow/dispatchV1/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatchV1/agent/runTool/type.d.ts
  packages/service/core/workflow/dispatchV1/chat/oneapi.ts
  packages/service/core/workflow/dispatchV1/dataset/concat.ts
  packages/service/core/workflow/dispatchV1/dataset/search.ts
  packages/service/core/workflow/dispatchV1/index.ts
  packages/service/core/workflow/dispatchV1/init/history.tsx
  packages/service/core/workflow/dispatchV1/init/userChatInput.tsx
  packages/service/core/workflow/dispatchV1/plugin/run.ts
  packages/service/core/workflow/dispatchV1/plugin/runInput.ts
  packages/service/core/workflow/dispatchV1/plugin/runOutput.ts
  packages/service/core/workflow/dispatchV1/tools/answer.ts
  packages/service/core/workflow/dispatchV1/tools/http.ts
  packages/service/core/workflow/dispatchV1/tools/http468.ts
  packages/service/core/workflow/dispatchV1/tools/queryExternsion.ts
  packages/service/core/workflow/dispatchV1/tools/runApp.ts
  packages/service/core/workflow/dispatchV1/tools/runLaf.ts
  packages/service/core/workflow/dispatchV1/type.d.ts
  packages/service/core/workflow/dispatchV1/utils.ts
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/core/workflow/debug.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/service/core/app/utils.ts
Labels: size/XXL

#2533 Docs: update baseURL
  docSite/hugo.toml
Labels: size/XS

#2536 fix: load member list
  docSite/content/zh-cn/docs/development/upgrading/4810.md
  packages/global/core/workflow/template/system/contextExtract/type.d.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ResponseTags.tsx
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/components/support/permission/ChangeOwnerModal/index.tsx
  projects/app/src/components/support/permission/MemberManager/AddMemberModal.tsx
  projects/app/src/components/support/user/team/TeamManageModal/context.tsx
  projects/app/src/global/core/chat/utils.ts
  projects/app/src/pages/account/components/UsageTable.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeExtract/ExtractFieldModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeExtract/index.tsx
  projects/app/src/pages/app/list/components/List.tsx
  projects/app/src/web/support/user/useUserStore.ts
Labels: size/M

#2527 fix: change workflow start node output when change file config
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeSystemConfig.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeWorkflowStart.tsx
Labels: size/M

#2540 fix: global variable key repeat & value type
  packages/global/core/app/type.d.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/common.json
  projects/app/src/components/core/app/VariableEdit.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/M

#2545 fix: toolCall.function.arguments maybe undefined
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
Labels: size/XS

#2546 fix: run app node display
  packages/global/core/workflow/template/constants.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
Labels: size/XS

#2544 fix: global variable persist during api calls
  packages/service/core/chat/controller.ts
  projects/app/src/pages/api/v1/chat/completions.ts
Labels: size/M

#2535 style: pay page perf
  packages/global/support/wallet/sub/constants.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/en/user.json
  packages/web/i18n/zh/common.json
  packages/web/styles/theme.ts
  projects/app/public/imgs/priceBg.svg
  projects/app/src/components/support/wallet/QRCodePayModal.tsx
  projects/app/src/components/support/wallet/StandardPlanContentList.tsx
  projects/app/src/pages/account/components/Info/ConversionModal.tsx
  projects/app/src/pages/account/components/Info/standardDetailModal.tsx
  projects/app/src/pages/price/components/ExtraPlan.tsx
  projects/app/src/pages/price/components/FAQ.tsx
  projects/app/src/pages/price/components/Points.tsx
  projects/app/src/pages/price/components/Standard.tsx
  projects/app/src/pages/price/index.tsx
Labels: size/XL

#2539 4.8.10 test
  docSite/content/zh-cn/docs/development/upgrading/4810.md
  packages/global/core/workflow/template/constants.ts
  packages/global/support/wallet/sub/constants.ts
  packages/service/core/chat/controller.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/web/components/common/MyMenu/index.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/common.json
  projects/app/src/components/support/apikey/Table.tsx
  projects/app/src/components/support/wallet/QRCodePayModal.tsx
  projects/app/src/components/support/wallet/StandardPlanContentList.tsx
  projects/app/src/pages/account/components/ApiKeyTable.tsx
  projects/app/src/pages/account/components/Info/standardDetailModal.tsx
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/Logs/DetailLogsModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeWorkflowStart.tsx
  projects/app/src/pages/chat/components/ChatHeader.tsx
  projects/app/src/pages/price/components/Standard.tsx
  projects/app/src/web/common/hooks/useCopyData.tsx
Labels: size/L

#2501 style: dataset detail page style refactor
  packages/global/core/dataset/constants.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/addUser.svg
  packages/web/components/common/Icon/icons/common/arrowLeft.svg
  packages/web/components/common/Icon/icons/common/folderImport.svg
  packages/web/components/common/Icon/icons/common/list.svg
  packages/web/components/common/Icon/icons/common/monitor.svg
  packages/web/components/common/Icon/icons/common/setting.svg
  packages/web/components/common/Tabs/LightRowTabs.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/common.json
  projects/app/src/components/common/Modal/EditResourceModal.tsx
  projects/app/src/components/core/dataset/DatasetTypeTag.tsx
  projects/app/src/components/support/permission/DefaultPerList/index.tsx
  projects/app/src/pages/dataset/component/MemberManager.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/Header.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/HeaderTagPopOver.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/TagManageModal.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/TagsPopOver.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/index.tsx
  projects/app/src/pages/dataset/detail/components/DataCard.tsx
  projects/app/src/pages/dataset/detail/components/Import/Context.tsx
  projects/app/src/pages/dataset/detail/components/Import/commonProgress/DataProcess.tsx
  projects/app/src/pages/dataset/detail/components/Info.tsx
  projects/app/src/pages/dataset/detail/components/MetaDataCard.tsx
  projects/app/src/pages/dataset/detail/components/NavBar.tsx
  projects/app/src/pages/dataset/detail/components/Slider.tsx
  projects/app/src/pages/dataset/detail/components/Test.tsx
  projects/app/src/pages/dataset/detail/index.tsx
  projects/app/src/pages/dataset/list/component/CreateModal.tsx
  projects/app/src/pages/dataset/list/component/List.tsx
  projects/app/src/pages/dataset/list/component/SideTag.tsx
  projects/app/src/pages/dataset/list/index.tsx
Labels: size/XXL

#2548 feat: custom read file service
  packages/global/core/dataset/type.d.ts
  packages/service/common/file/read/utils.ts
  packages/service/core/dataset/collection/schema.ts
  projects/app/src/web/common/file/api.ts
  projects/app/src/web/core/dataset/api.ts
Labels: size/M

#2554 style: dataset II
  projects/app/src/components/support/permission/DefaultPerList/index.tsx
  projects/app/src/pages/dataset/detail/components/Import/index.tsx
  projects/app/src/pages/dataset/detail/components/Info.tsx
  projects/app/src/pages/dataset/detail/components/MetaDataCard.tsx
  projects/app/src/pages/dataset/detail/components/NavBar.tsx
Labels: size/M

#2555 perf: Dataset new ui
  packages/web/components/common/Image/PhotoView.tsx
  packages/web/components/common/MySelect/index.tsx
  packages/web/components/common/Tabs/LightRowTabs.tsx
  projects/app/src/components/Markdown/img/Image.tsx
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/components/Select/AIModelSelector.tsx
  projects/app/src/components/support/permission/DefaultPerList/index.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/Header.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/TagManageModal.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/index.tsx
  projects/app/src/pages/dataset/detail/components/DataCard.tsx
  projects/app/src/pages/dataset/detail/components/Info.tsx
  projects/app/src/pages/dataset/detail/components/NavBar.tsx
  projects/app/src/pages/dataset/detail/components/Test.tsx
  projects/app/src/pages/dataset/detail/index.tsx
  projects/app/src/web/core/dataset/api.ts
Labels: size/XL

#2558 template add i18n
  packages/global/core/workflow/template/input.ts
  packages/global/core/workflow/template/system/aiChat.ts
  packages/global/core/workflow/template/system/assignedAnswer.ts
  packages/global/core/workflow/template/system/classifyQuestion/index.ts
  packages/global/core/workflow/template/system/contextExtract/index.ts
  packages/global/core/workflow/template/system/customFeedback.ts
  packages/global/core/workflow/template/system/datasetConcat.ts
  packages/global/core/workflow/template/system/datasetSearch.ts
  packages/global/core/workflow/template/system/http468.ts
  packages/global/core/workflow/template/system/ifElse/constant.ts
  packages/global/core/workflow/template/system/ifElse/index.ts
  packages/global/core/workflow/template/system/laf.ts
  packages/global/core/workflow/template/system/pluginInput.ts
  packages/global/core/workflow/template/system/pluginOutput.ts
  packages/global/core/workflow/template/system/queryExtension.ts
  packages/global/core/workflow/template/system/runApp/index.ts
  packages/global/core/workflow/template/system/sandbox/index.ts
  packages/global/core/workflow/template/system/stopTool.ts
  packages/global/core/workflow/template/system/textEditor.ts
  packages/global/core/workflow/template/system/tools.ts
  packages/global/core/workflow/template/system/variableUpdate/index.tsx
  packages/global/core/workflow/template/system/workflowStart.ts
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/workflow.json
Labels: size/XL

#2565 Fix: Custom delimiter does not take effect when document type is link
  packages/service/core/dataset/collection/utils.ts
Labels: size/XS

#2556 fix: tags manage
  packages/web/hooks/useScrollPagination.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/TagManageModal.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/TagsPopOver.tsx
Labels: size/L

#2553 fix: global variable during debug & variable update textarea rerender
  packages/service/core/workflow/dispatch/tools/runUpdateVar.ts
  packages/web/components/common/Textarea/PromptEditor/index.tsx
  projects/app/src/global/core/workflow/api.d.ts
  projects/app/src/pages/api/core/workflow/debug.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeVariableUpdate.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Textarea.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/utils.tsx
Labels: size/L

#2567 fix: plugin input
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderInput.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputEditModal.tsx
Labels: size/XS

#2568 4.8.10 test
  docSite/content/zh-cn/docs/development/upgrading/4810.md
  packages/global/core/workflow/utils.ts
  packages/service/common/file/read/utils.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/tools/readFiles.ts
  packages/service/core/workflow/dispatch/tools/runUpdateVar.ts
  packages/web/i18n/en/user.json
  packages/web/i18n/zh/user.json
  projects/app/src/pages/account/components/Promotion.tsx
  projects/app/src/pages/api/admin/initv4810.ts
  projects/app/src/pages/api/common/file/upload.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/dataset/detail/components/CollectionCard/Header.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/HeaderTagPopOver.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/TagManageModal.tsx
  projects/app/src/pages/dataset/detail/components/CollectionCard/TagsPopOver.tsx
  projects/app/src/pages/dataset/detail/index.tsx
  projects/app/src/web/core/dataset/context/datasetPageContext.tsx
Labels: size/L

#2572 4.8.10 fix
  packages/global/core/chat/type.d.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/tools/runUpdateVar.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/common.json
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/components/FlowController.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeIfElse/ListItem.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/utils.tsx
Labels: size/L

#2573 4.8.10 test
  docSite/content/zh-cn/docs/development/upgrading/4810.md
  packages/global/core/workflow/runtime/type.d.ts
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/init/workflowStart.tsx
  packages/service/core/workflow/dispatch/tools/runIfElse.ts
  packages/web/components/common/Image/PhotoView.tsx
  packages/web/i18n/en/chat.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/chat.json
  packages/web/i18n/zh/common.json
  projects/app/package.json
  projects/app/src/components/Layout/index.tsx
  projects/app/src/components/Markdown/img/Image.tsx
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/components/support/wallet/QRCodePayModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/context.tsx
  projects/app/src/pages/dataset/detail/components/DataCard.tsx
Labels: size/L

#2578 4.8.10 test
  packages/global/core/workflow/type/index.d.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/support/permission/app/auth.ts
  packages/service/support/permission/auth/openapi.ts
  packages/service/support/permission/dataset/auth.ts
  packages/service/support/permission/publish/authLink.ts
  projects/app/src/components/support/user/team/TeamManageModal/context.tsx
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/list/components/List.tsx
  projects/app/src/pages/dataset/detail/components/Info.tsx
  projects/app/src/web/common/hooks/useCopyData.tsx
Labels: size/L

#2579 feat: add plugin instruction config
  packages/global/core/app/type.d.ts
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/node/constant.ts
  packages/global/core/workflow/template/constants.ts
  packages/global/core/workflow/template/system/pluginConfig.ts
  packages/global/core/workflow/utils.ts
  packages/service/core/app/schema.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh/workflow.json
  projects/app/public/imgs/app/help.svg
  projects/app/public/imgs/app/instruction.svg
  projects/app/src/components/core/app/Tip.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderInput.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/type.d.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/NodePluginConfig.tsx
  projects/app/src/pages/app/detail/components/useChatTest.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/L

#2571 feat: plugin input type add select and custom var
  packages/global/core/workflow/node/constant.ts
  packages/global/core/workflow/utils.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/workflow/inputType/customVariable.svg
  packages/web/components/common/Icon/icons/core/workflow/inputType/dynamic.svg
  packages/web/components/common/Icon/icons/core/workflow/inputType/file.svg
  packages/web/components/common/Icon/icons/core/workflow/inputType/input.svg
  packages/web/components/common/Icon/icons/core/workflow/inputType/jsonEditor.svg
  packages/web/components/common/Icon/icons/core/workflow/inputType/numberInput.svg
  packages/web/components/common/Icon/icons/core/workflow/inputType/option.svg
  packages/web/components/common/Icon/icons/core/workflow/inputType/reference.svg
  packages/web/components/common/Icon/icons/core/workflow/inputType/selectApp.svg
  packages/web/components/common/Icon/icons/core/workflow/inputType/selectDataset.svg
  packages/web/components/common/Icon/icons/core/workflow/inputType/selectLLM.svg
  packages/web/components/common/Icon/icons/core/workflow/inputType/switch.svg
  packages/web/components/common/Icon/icons/core/workflow/inputType/textarea.svg
  packages/web/components/common/MySelect/MultipleSelect.tsx
  packages/web/components/core/workflow/NodeInputSelect.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/zh/common.json
  projects/app/public/appMarketTemplates/CQ/template.json
  projects/app/public/appMarketTemplates/simpleDatasetChat/template.json
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderInput.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/renderPluginInput.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/components/ToolSelectModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeCode.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputEditModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/VariableTable.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeVariableUpdate.tsx
Labels: size/XL

#2582 feat: admin add custom plugin
  docSite/content/zh-cn/docs/development/upgrading/4810.md
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/template/constants.ts
  packages/global/core/workflow/template/system/abandoned/runApp/index.ts
  packages/global/core/workflow/template/system/abandoned/runApp/type.d.ts
  packages/global/core/workflow/type/index.d.ts
  packages/global/core/workflow/utils.ts
  packages/service/core/app/plugin/systemPluginSchema.ts
  packages/service/core/app/plugin/type.d.ts
  packages/service/core/workflow/dispatch/abandoned/runApp.ts
  packages/service/core/workflow/dispatch/agent/runApp.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/plugin/run.ts
  packages/service/core/workflow/dispatch/utils.ts
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderInput.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/SelectAppModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SelectApp.tsx
  projects/app/src/service/common/system/volumnMongoWatch.ts
Labels: size/L
