Repository labring/FastGPT, pull requests merged in 2025-06, with the labels that each got.

#4946 add secondary.tsx
  packages/web/components/common/MyMenu/secondary.tsx
  projects/app/src/pages/dataset/list/index.tsx
Labels: size/L

#4974 Fix the incompatibility of drag-and-drop upload to Windows
  projects/app/src/pageComponents/dataset/detail/Import/components/FileSelector.tsx
  projects/app/src/pageComponents/dataset/detail/components/FileSelector.tsx
Labels: size/S

#4979 fix: ui
  package.json
  projects/app/src/pageComponents/app/detail/Workflow/components/SaveButton.tsx
  projects/app/src/web/styles/chakraui.scss
Labels: size/M

#4985 Feat: ai proxy monitor
  docSite/content/zh-cn/docs/development/upgrading/4912.md
  packages/web/i18n/en/account_model.json
  packages/web/i18n/zh-CN/account_model.json
  packages/web/i18n/zh-Hant/account_model.json
  projects/app/src/global/aiproxy/type.d.ts
  projects/app/src/pageComponents/account/model/ModelDashboard/LineChartComponent.tsx
  projects/app/src/pageComponents/account/model/ModelDashboard/index.tsx
  projects/app/src/pages/account/model/index.tsx
  projects/app/src/pages/api/aiproxy/[...path].ts
  projects/app/src/web/core/ai/channel.ts
Labels: size/XL

#4993 fix iframe.js to support microphone
  projects/app/public/js/iframe.js
Labels: size/XS

#4996 fix: resizer.svg load error
  packages/web/styles/theme.ts
Labels: size/XS

#4982 add http header auth config
  packages/global/common/secret/constants.ts
  packages/global/common/secret/type.d.ts
  packages/global/core/app/mcpTools/utils.ts
  packages/global/core/app/utils.ts
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/template/system/http468.ts
  packages/service/core/app/mcp.ts
  packages/service/core/app/utils.ts
  packages/service/core/workflow/dispatch/plugin/runTool.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/service/support/secret/controller.ts
  packages/service/support/secret/schema.ts
  packages/web/components/common/Radio/LeftRadio.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/common/secret/HeaderAuthConfig.tsx
  projects/app/src/components/core/app/DatasetParamsModal.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/Edit.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/EditForm.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/Header.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeHttp/index.tsx
  projects/app/src/pageComponents/dashboard/apps/MCPToolsEditModal.tsx
  projects/app/src/pageComponents/dataset/detail/Import/components/FileSourceSelector.tsx
  projects/app/src/pages/api/core/app/del.ts
  projects/app/src/pages/api/core/app/mcpTools/create.ts
  projects/app/src/pages/api/core/app/mcpTools/update.ts
  projects/app/src/pages/api/core/app/version/publish.ts
  projects/app/src/pages/api/support/mcp/client/getTools.ts
  projects/app/src/pages/api/support/mcp/client/runTool.ts
Labels: size/XXL

#4990 Time granularity and Table of a single model
  packages/web/i18n/en/account_model.json
  packages/web/i18n/zh-CN/account_model.json
  packages/web/i18n/zh-Hant/account_model.json
  projects/app/src/global/aiproxy/type.d.ts
  projects/app/src/pageComponents/account/model/ModelDashboard/DataTableComponent.tsx
  projects/app/src/pageComponents/account/model/ModelDashboard/LineChartComponent.tsx
  projects/app/src/pageComponents/account/model/ModelDashboard/index.tsx
  projects/app/src/web/core/ai/channel.ts
Labels: size/XXL

#4995 New chatinput
  packages/web/components/common/Icon/icons/close.svg
  packages/web/styles/theme.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/VoiceInput.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/web/common/hooks/useSpeech.ts
Labels: size/XL

#5011 Test secret
  docSite/content/zh-cn/docs/development/upgrading/4912.md
  env.d.ts
  packages/global/common/secret/constants.ts
  packages/global/common/secret/type.d.ts
  packages/global/core/app/mcpTools/utils.ts
  packages/global/core/app/utils.ts
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/template/system/http468.ts
  packages/service/common/secret/aes256gcm.ts
  packages/service/common/secret/constants.ts
  packages/service/common/secret/utils.ts
  packages/service/core/app/controller.ts
  packages/service/core/app/mcp.ts
  packages/service/core/app/utils.ts
  packages/service/core/workflow/dispatch/plugin/runTool.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/styles/theme.ts
  projects/app/.env.template
  projects/app/src/components/common/secret/HeaderAuthConfig.tsx
  projects/app/src/pageComponents/account/thirdParty/WorkflowVariableModal.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/Edit.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/EditForm.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/Header.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeHttp/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeVariableUpdate.tsx
  projects/app/src/pageComponents/dashboard/apps/MCPToolsEditModal.tsx
  projects/app/src/pages/api/core/app/del.ts
  projects/app/src/pages/api/core/app/mcpTools/create.ts
  projects/app/src/pages/api/core/app/mcpTools/update.ts
  projects/app/src/pages/api/core/app/update.ts
  projects/app/src/pages/api/core/app/version/publish.ts
  projects/app/src/pages/api/support/mcp/client/getTools.ts
  projects/app/src/pages/api/support/mcp/client/runTool.ts
Labels: size/XXL

#5013 feat: cq and extrat AI memory
  deploy/helm/fastgpt/templates/configmap-config.yaml
  docSite/content/zh-cn/docs/development/custom-models/xinference.md
  docSite/content/zh-cn/docs/development/faq.md
  docSite/content/zh-cn/docs/development/modelConfig/intro.md
  docSite/content/zh-cn/docs/development/upgrading/4811.md
  docSite/content/zh-cn/docs/development/upgrading/4816.md
  docSite/content/zh-cn/docs/development/upgrading/4912.md
  docSite/static/llms-full.txt
  packages/global/core/ai/model.d.ts
  packages/global/core/ai/model.ts
  packages/global/core/ai/prompt/agent.ts
  packages/global/core/chat/type.d.ts
  packages/global/core/workflow/runtime/constants.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/template/system/classifyQuestion/index.ts
  packages/service/core/ai/config/provider/ChatGLM.json
  packages/service/core/ai/config/provider/Claude.json
  packages/service/core/ai/config/provider/DeepSeek.json
  packages/service/core/ai/config/provider/Doubao.json
  packages/service/core/ai/config/provider/Ernie.json
  packages/service/core/ai/config/provider/Gemini.json
  packages/service/core/ai/config/provider/Grok.json
  packages/service/core/ai/config/provider/Groq.json
  packages/service/core/ai/config/provider/Hunyuan.json
  packages/service/core/ai/config/provider/Intern.json
  packages/service/core/ai/config/provider/MiniMax.json
  packages/service/core/ai/config/provider/MistralAI.json
  packages/service/core/ai/config/provider/Moonshot.json
  packages/service/core/ai/config/provider/OpenAI.json
  packages/service/core/ai/config/provider/Qwen.json
  packages/service/core/ai/config/provider/Siliconflow.json
  packages/service/core/ai/config/provider/SparkDesk.json
  packages/service/core/ai/config/provider/StepFun.json
  packages/service/core/ai/config/provider/Yi.json
  packages/service/core/chat/chatItemSchema.ts
  packages/service/core/chat/controller.ts
  packages/service/core/workflow/dispatch/abandoned/runApp.ts
  packages/service/core/workflow/dispatch/agent/classifyQuestion.ts
  packages/service/core/workflow/dispatch/agent/extract.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/plugin/run.ts
  packages/service/core/workflow/dispatch/plugin/runApp.ts
  packages/service/core/workflow/dispatch/type.d.ts
  projects/app/data/model.json
  projects/app/src/pageComponents/account/model/AddModelBox.tsx
  projects/app/src/pages/api/common/system/getInitData.ts
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/api/v2/chat/completions.ts
  projects/app/src/service/core/app/utils.ts
  projects/app/src/service/support/mcp/utils.ts
  test/setupModels.ts
Labels: size/XXL

#5015 feat: Users can download the invoice by self
  packages/web/i18n/en/account_bill.json
  packages/web/i18n/zh-CN/account_bill.json
  packages/web/i18n/zh-Hant/account_bill.json
  projects/app/src/pageComponents/account/bill/InvoiceTable.tsx
  projects/app/src/web/support/wallet/bill/invoice/api.ts
Labels: size/M

#5018 Chatbox-fix
  docSite/content/zh-cn/docs/development/upgrading/4912.md
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
Labels: size/XL

#5021 fix: dataset image will expired
  packages/service/core/dataset/collection/controller.ts
  projects/app/src/pages/api/core/dataset/collection/create/apiCollection.ts
  projects/app/src/pages/api/core/dataset/collection/create/link.ts
  projects/app/src/pages/api/core/dataset/collection/create/localFile.ts
  projects/app/src/pages/api/core/dataset/collection/create/reTrainingCollection.ts
  projects/app/src/service/core/dataset/queues/datasetParse.ts
Labels: size/M

#5016 if else node support reference
  packages/global/core/workflow/template/system/ifElse/constant.ts
  packages/global/core/workflow/template/system/ifElse/index.ts
  packages/global/core/workflow/template/system/ifElse/type.d.ts
  packages/service/core/workflow/dispatch/tools/runIfElse.ts
  packages/web/components/common/Input/NumberInput/index.tsx
  packages/web/components/common/MySelect/MultipleRowSelect.tsx
  packages/web/components/common/Textarea/PromptEditor/index.module.scss
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariableInput.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/renderPluginInput.tsx
  projects/app/src/components/core/chat/components/Interactive/InteractiveComponents.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeDatasetConcat.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeIfElse/ListItem.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeIfElse/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeVariableUpdate.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/NumberInput.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Reference.tsx
  projects/app/src/pageComponents/dataset/detail/Form/CollectionChunkForm.tsx
Labels: size/XL

#5024 optimize ifelse node ui
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/circleMinus.svg
  packages/web/components/common/Icon/icons/minus.svg
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh-CN/workflow.json
  packages/web/i18n/zh-Hant/workflow.json
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeCQNode.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeIfElse/ListItem.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeUserSelect.tsx
Labels: size/L

#5028 fix mcp tools save
  packages/service/common/secret/utils.ts
Labels: size/XS

#5030 perf: mcp save raw schema
  docSite/content/zh-cn/docs/development/upgrading/4912.md
  packages/global/core/app/jsonschema.ts
  packages/global/core/app/mcpTools/type.d.ts
  packages/global/core/app/mcpTools/utils.ts
  packages/global/core/app/type.d.ts
  packages/global/core/workflow/constants.ts
  packages/global/tsconfig.json
  packages/plugins/tsconfig.json
  packages/service/common/file/gridfs/controller.ts
  packages/service/common/secret/utils.ts
  packages/service/core/workflow/dispatch/agent/extract.ts
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/agent/runTool/type.d.ts
  packages/service/core/workflow/dispatch/plugin/runTool.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/service/package.json
  packages/service/tsconfig.json
  packages/web/i18n/en/account_model.json
  packages/web/i18n/zh-CN/account_model.json
  packages/web/i18n/zh-Hant/account_model.json
  packages/web/tsconfig.json
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/src/pageComponents/account/model/Channel/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/Loop/NodeLoopStart.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeToolSet.tsx
  projects/app/src/pages/api/core/app/mcpTools/create.ts
  projects/app/src/service/support/mcp/utils.ts
  projects/app/src/web/core/ai/channel.ts
  projects/mcp_server/package.json
  test/cases/global/core/app/jsonschema.test.ts
  test/cases/web/core/ai/channel.test.ts
Labels: size/XL

#5038 perf: dashboard
  packages/web/components/common/charts/LineChartComponent.tsx
  packages/web/i18n/en/account_model.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/account_model.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/account_model.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/package.json
  pnpm-lock.yaml
  projects/app/src/pageComponents/account/model/ModelDashboard/index.tsx
  projects/app/src/web/core/ai/channel.ts
Labels: size/M

#5040 perf: yuque dataset
  docSite/content/zh-cn/docs/development/upgrading/4912.md
  packages/service/core/ai/config/provider/Doubao.json
  packages/service/core/ai/config/provider/Qwen.json
  packages/service/core/dataset/apiDataset/custom/api.ts
  packages/service/core/dataset/apiDataset/yuqueDataset/api.ts
  packages/service/core/dataset/read.ts
  projects/app/src/pageComponents/account/model/ModelDashboard/DataTableComponent.tsx
  projects/app/src/pageComponents/account/model/ModelDashboard/index.tsx
  projects/app/src/pageComponents/dataset/detail/Import/diffSource/APIDataset.tsx
Labels: size/L

#5047 perf: api dataset create
  docSite/content/zh-cn/docs/development/upgrading/4912.md
  docSite/content/zh-cn/docs/development/upgrading/4913.md
  docSite/content/zh-cn/docs/guide/knowledge_base/api_dataset.md
  packages/global/core/dataset/api.d.ts
  packages/global/core/dataset/apiDataset/type.d.ts
  packages/service/core/dataset/apiDataset/custom/api.ts
  packages/service/core/dataset/apiDataset/feishuDataset/api.ts
  packages/service/core/dataset/apiDataset/yuqueDataset/api.ts
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/dataset.json
  projects/app/src/pageComponents/dataset/detail/Import/commonProgress/PreviewData.tsx
  projects/app/src/pageComponents/dataset/detail/Import/commonProgress/Upload.tsx
  projects/app/src/pageComponents/dataset/detail/Import/diffSource/APIDataset.tsx
  projects/app/src/pages/api/core/dataset/apiDataset/getCatalog.ts
  projects/app/src/pages/api/core/dataset/collection/create/apiCollection.ts
  projects/app/src/pages/api/core/dataset/collection/create/apiCollectionV2.ts
  projects/app/src/pages/api/core/dataset/detail.ts
  projects/app/src/service/core/dataset/queues/datasetParse.ts
  projects/app/src/web/core/dataset/api.ts
  projects/app/src/web/core/dataset/type.d.ts
Labels: size/XL

#5048 Fix some bug
  docSite/content/zh-cn/docs/development/upgrading/4912.md
  docSite/content/zh-cn/docs/development/upgrading/4913.md
  packages/global/core/app/mcpTools/utils.ts
  packages/global/tsconfig.json
  packages/plugins/tsconfig.json
  packages/service/core/chat/utils.ts
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/service/tsconfig.json
  packages/web/components/common/DateRangePicker/index.tsx
  packages/web/hooks/usePagination.tsx
  packages/web/tsconfig.json
  projects/app/src/components/core/app/VariableEdit.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/pageComponents/app/detail/Logs/index.tsx
  projects/app/src/pageComponents/dataset/detail/Test.tsx
  projects/app/src/pages/api/core/dataset/collection/list.ts
  projects/app/src/pages/api/core/dataset/collection/listV2.ts
  projects/app/src/pages/api/support/outLink/create.ts
  tsconfig.json
Labels: size/L

#5007 add cache for team member,app,dataset
  packages/service/common/redis/cache.ts
  packages/service/common/vectorDB/controller.ts
  packages/service/support/permission/teamLimit.ts
  packages/service/support/wallet/sub/utils.ts
Labels: size/L

#5052 Feat: Plan cache
  docSite/content/zh-cn/docs/development/upgrading/4913.md
  packages/service/common/redis/cache.ts
  packages/service/common/vectorDB/controller.ts
  packages/service/support/permission/teamLimit.ts
  packages/service/support/wallet/sub/utils.ts
  projects/app/src/pageComponents/dataset/detail/Test.tsx
Labels: size/L

#5050 Change the default MongoDB image source to Docker Hub.
  deploy/docker/docker-compose-milvus.yml
Labels: size/XS

#5058 Test audit
  dev.md
  docSite/content/zh-cn/docs/development/upgrading/4913.md
  packages/global/support/audit/constants.ts
  packages/global/support/audit/type.d.ts
  packages/service/common/file/image/schema.ts
  packages/service/core/dataset/collection/schema.ts
  packages/service/core/dataset/data/schema.ts
  packages/service/support/audit/schema.ts
  packages/service/support/audit/util.ts
  packages/service/support/operationLog/addOperationLog.ts
  packages/web/support/audit/constants.ts
  projects/app/src/pageComponents/account/team/Audit/index.tsx
  projects/app/src/pageComponents/account/team/Audit/processors/appProcessors.ts
  projects/app/src/pageComponents/account/team/Audit/processors/commonProcessor.ts
  projects/app/src/pageComponents/account/team/Audit/processors/datasetProcessors.ts
  projects/app/src/pageComponents/account/team/Audit/processors/index.ts
  projects/app/src/pageComponents/account/team/Audit/processors/teamProcessors.ts
  projects/app/src/pageComponents/account/team/OperationLog/processors/adminProcessors.ts
  projects/app/src/pageComponents/account/team/OperationLog/processors/index.ts
  projects/app/src/pages/account/team/index.tsx
  projects/app/src/pages/api/admin/clearInvalidData.ts
  projects/app/src/pages/api/core/app/copy.ts
  projects/app/src/pages/api/core/app/create.ts
  projects/app/src/pages/api/core/app/del.ts
  projects/app/src/pages/api/core/app/folder/create.ts
  projects/app/src/pages/api/core/app/getChatLogs.ts
  projects/app/src/pages/api/core/app/update.ts
  projects/app/src/pages/api/core/app/version/publish.ts
  projects/app/src/pages/api/core/dataset/collection/create.ts
  projects/app/src/pages/api/core/dataset/collection/create/reTrainingCollection.ts
  projects/app/src/pages/api/core/dataset/collection/delete.ts
  projects/app/src/pages/api/core/dataset/collection/update.ts
  projects/app/src/pages/api/core/dataset/create.ts
  projects/app/src/pages/api/core/dataset/data/delete.ts
  projects/app/src/pages/api/core/dataset/data/insertData.ts
  projects/app/src/pages/api/core/dataset/data/update.ts
  projects/app/src/pages/api/core/dataset/delete.ts
  projects/app/src/pages/api/core/dataset/folder/create.ts
  projects/app/src/pages/api/core/dataset/searchTest.ts
  projects/app/src/pages/api/core/dataset/update.ts
  projects/app/src/pages/api/support/openapi/create.ts
  projects/app/src/pages/api/support/openapi/delete.ts
  projects/app/src/pages/api/support/openapi/update.ts
  projects/app/src/pages/api/support/outLink/create.ts
  projects/app/src/pages/api/support/outLink/delete.ts
  projects/app/src/pages/api/support/outLink/update.ts
  projects/app/src/pages/api/support/user/account/loginByPassword.ts
  projects/app/src/pages/api/support/user/account/updatePasswordByOld.ts
  projects/app/src/pages/api/support/user/team/limit/exportDatasetLimit.ts
  projects/app/src/service/common/system/cronTask.ts
  projects/app/src/service/core/dataset/data/controller.ts
  projects/app/src/web/support/user/team/operantionLog/api.ts
  test/mocks/index.ts
Labels: size/XL

#5061 feat: dataset index prefix
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-oceanbase/docker-compose.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  docSite/content/zh-cn/docs/development/upgrading/4912.md
  docSite/content/zh-cn/docs/development/upgrading/4913.md
  docSite/content/zh-cn/docs/development/upgrading/4914.md
  packages/global/core/dataset/controller.d.ts
  packages/global/core/dataset/training/type.d.ts
  packages/global/core/dataset/type.d.ts
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/schema.ts
  packages/service/core/dataset/training/controller.ts
  packages/service/core/dataset/training/schema.ts
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/dataset.json
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/pageComponents/dataset/detail/Form/CollectionChunkForm.tsx
  projects/app/src/pageComponents/dataset/detail/Import/Context.tsx
  projects/app/src/pageComponents/dataset/detail/Import/diffSource/ReTraining.tsx
  projects/app/src/pageComponents/dataset/detail/InputDataModal.tsx
  projects/app/src/pageComponents/dataset/detail/MetaDataCard.tsx
  projects/app/src/pages/api/core/dataset/data/insertData.ts
  projects/app/src/pages/api/core/dataset/data/update.ts
  projects/app/src/pages/dataset/detail/index.tsx
  projects/app/src/service/core/dataset/data/controller.ts
  projects/app/src/service/core/dataset/queues/datasetParse.ts
  projects/app/src/service/core/dataset/queues/generateQA.ts
  projects/app/src/service/core/dataset/queues/generateVector.ts
  projects/app/test/api/core/dataset/training/deleteTrainingData.test.ts
  projects/app/test/api/core/dataset/training/getTrainingDataDetail.test.ts
  projects/app/test/api/core/dataset/training/getTrainingError.test.ts
  projects/app/test/api/core/dataset/training/updateTrainingData.test.ts
Labels: size/XL

#5068 Feat: admin audit
  dev.md
  docSite/content/zh-cn/docs/development/upgrading/4914.md
  docSite/content/zh-cn/docs/guide/knowledge_base/third_dataset.md
  packages/global/support/user/audit/constants.ts
  packages/global/support/user/audit/type.d.ts
  packages/service/support/operationLog/addOperationLog.ts
  packages/service/support/user/audit/schema.ts
  packages/service/support/user/audit/util.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/audit.svg
  packages/web/i18n/en/account_team.json
  packages/web/i18n/zh-CN/account_team.json
  packages/web/i18n/zh-Hant/account_team.json
  packages/web/support/user/audit/constants.ts
  projects/app/package.json
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/pageComponents/account/team/Audit/index.tsx
  projects/app/src/pageComponents/account/team/Audit/processors/appProcessors.ts
  projects/app/src/pageComponents/account/team/Audit/processors/commonProcessor.ts
  projects/app/src/pageComponents/account/team/Audit/processors/datasetProcessors.ts
  projects/app/src/pageComponents/account/team/Audit/processors/index.ts
  projects/app/src/pageComponents/account/team/Audit/processors/teamProcessors.ts
  projects/app/src/pages/account/team/index.tsx
  projects/app/src/pages/api/core/app/copy.ts
  projects/app/src/pages/api/core/app/create.ts
  projects/app/src/pages/api/core/app/del.ts
  projects/app/src/pages/api/core/app/folder/create.ts
  projects/app/src/pages/api/core/app/getChatLogs.ts
  projects/app/src/pages/api/core/app/update.ts
  projects/app/src/pages/api/core/app/version/publish.ts
  projects/app/src/pages/api/core/dataset/collection/create.ts
  projects/app/src/pages/api/core/dataset/collection/create/reTrainingCollection.ts
  projects/app/src/pages/api/core/dataset/collection/delete.ts
  projects/app/src/pages/api/core/dataset/collection/update.ts
  projects/app/src/pages/api/core/dataset/create.ts
  projects/app/src/pages/api/core/dataset/data/delete.ts
  projects/app/src/pages/api/core/dataset/data/insertData.ts
  projects/app/src/pages/api/core/dataset/data/update.ts
  projects/app/src/pages/api/core/dataset/delete.ts
  projects/app/src/pages/api/core/dataset/folder/create.ts
  projects/app/src/pages/api/core/dataset/searchTest.ts
  projects/app/src/pages/api/core/dataset/update.ts
  projects/app/src/pages/api/support/openapi/create.ts
  projects/app/src/pages/api/support/openapi/delete.ts
  projects/app/src/pages/api/support/openapi/update.ts
  projects/app/src/pages/api/support/outLink/create.ts
  projects/app/src/pages/api/support/outLink/delete.ts
  projects/app/src/pages/api/support/outLink/update.ts
  projects/app/src/pages/api/support/user/account/loginByPassword.ts
  projects/app/src/pages/api/support/user/account/updatePasswordByOld.ts
  projects/app/src/pages/api/support/user/team/limit/exportDatasetLimit.ts
  projects/app/src/web/support/user/team/operantionLog/api.ts
  test/mocks/index.ts
Labels: size/XL

#5053 Update sso.md
  docSite/content/zh-cn/docs/guide/admin/sso.md
Labels: size/XS

#5076 update mcp server
  docSite/content/zh-cn/docs/development/upgrading/4913.md
  docSite/content/zh-cn/docs/development/upgrading/4914.md
  pnpm-lock.yaml
  projects/mcp_server/Dockerfile
  projects/mcp_server/package.json
  projects/mcp_server/src/api/fastgpt.ts
  projects/mcp_server/src/api/request.ts
  projects/mcp_server/src/index.ts
  projects/mcp_server/src/utils/error.ts
  projects/mcp_server/src/utils/string.ts
  projects/mcp_server/tsconfig.json
Labels: size/L

#5073 fix:sandbox misspelling
  packages/global/core/workflow/template/system/sandbox/constants.ts
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeCode.tsx
Labels: size/XS

#5089 fix: update input schema structure in getTools method
  packages/service/core/app/mcp.ts
Labels: size/XS

#5087 fix bugs
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/search/controller.ts
  projects/app/src/pageComponents/app/ImportAppConfigEditor.tsx
  projects/app/src/pages/account/info/index.tsx
Labels: size/L

#5096 Mcp db fix
  packages/service/core/app/schema.ts
  packages/service/core/app/version/schema.ts
Labels: size/L

#5098 fix vulnerability
  packages/service/common/file/csv.ts
  packages/service/support/permission/controller.ts
  packages/service/support/user/session.ts
  projects/app/next.config.js
  projects/app/src/pages/api/core/app/exportChatLogs.ts
  projects/app/src/pages/api/core/dataset/collection/export.ts
  projects/app/src/pages/api/core/dataset/exportAll.ts
  projects/app/src/pages/api/support/user/account/resetExpiredPsw.ts
  projects/app/src/pages/api/support/user/account/updatePasswordByOld.ts
Labels: size/L

#5093 Update doc
  docSite/content/zh-cn/docs/development/upgrading/4914.md
Labels: size/XS

#5106 update version doc
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-oceanbase/docker-compose.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  docSite/content/zh-cn/docs/development/upgrading/4914.md
  projects/app/src/pageComponents/login/LoginForm/FormLayout.tsx
  projects/app/src/pages/api/support/user/account/loginout.ts
  projects/app/src/pages/login/provider.tsx
Labels: size/M

#5108 fix: input modal
  docSite/content/zh-cn/docs/development/upgrading/4914.md
  packages/service/core/chat/chatItemSchema.ts
  projects/app/src/pageComponents/dataset/detail/InputDataModal.tsx
  projects/app/src/pages/api/core/app/getChatLogs.ts
Labels: size/L

#5111 Proxies image requests to plugin service
  packages/service/common/system/constants.ts
  projects/app/next.config.js
  projects/app/src/pages/api/system/pluginImgs/[...path].ts
Labels: size/M

#5118 fix: local file relatedImageId error
  projects/app/src/pages/api/core/dataset/collection/create/localFile.ts
Labels: size/XS
