Repository labring/FastGPT, pull requests merged in 2025-05, with the labels that each got.

#4742 Yuque dataset baseurl
  docSite/content/zh-cn/docs/development/upgrading/498.md
  packages/global/core/dataset/apiDataset.d.ts
  packages/service/common/api/type.d.ts
  packages/service/core/dataset/apiDataset/proApi.ts
  packages/service/core/dataset/controller.ts
  packages/service/core/dataset/schema.ts
  packages/service/core/workflow/dispatch/dataset/search.ts
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/dataset.json
  projects/app/src/pageComponents/dataset/ApiDatasetForm.tsx
  projects/app/src/pageComponents/dataset/detail/Info/components/EditApiServiceModal.tsx
  projects/app/src/pageComponents/dataset/list/CreateModal.tsx
  projects/app/src/pages/api/core/dataset/apiDataset/getCatalog.ts
  projects/app/src/pages/api/core/dataset/apiDataset/getPathNames.ts
  projects/app/src/pages/api/core/dataset/detail.ts
  projects/app/src/pages/api/core/dataset/update.ts
  projects/app/src/service/common/system/index.ts
  projects/app/src/service/core/dataset/apiDataset/controller.ts
  projects/app/src/web/core/dataset/api.ts
  projects/app/src/web/core/dataset/context/datasetPageContext.tsx
Labels: size/XL

#4743 update next version
  packages/global/package.json
  packages/service/package.json
  pnpm-lock.yaml
  projects/app/package.json
Labels: size/XS

#4747 Update dataset.md
  docSite/content/zh-cn/docs/development/openapi/dataset.md
Labels: size/XS

#4752 Update dataset.md
  docSite/content/zh-cn/docs/development/openapi/dataset.md
Labels: size/XS

#4757 fix: json schema parse error;fix: retraining image reset
  docSite/content/zh-cn/docs/development/upgrading/498.md
  packages/service/core/ai/utils.ts
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/web/i18n/en/account_bill.json
  packages/web/i18n/zh-CN/account_bill.json
  packages/web/i18n/zh-Hant/account_bill.json
  projects/app/src/pages/api/core/dataset/collection/create/reTrainingCollection.ts
  projects/app/src/pages/api/core/dataset/searchTest.ts
  projects/app/src/service/support/wallet/usage/push.ts
Labels: size/M

#4748 Psw
  env.d.ts
  packages/global/support/user/type.d.ts
  packages/service/support/user/controller.ts
  packages/service/support/user/schema.ts
  packages/web/i18n/en/account_info.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/user.json
  packages/web/i18n/zh-CN/account_info.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/user.json
  packages/web/i18n/zh-Hant/account_info.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/user.json
  projects/app/.env.template
  projects/app/src/components/Layout/ResetPswModal.tsx
  projects/app/src/components/Layout/index.tsx
  projects/app/src/pages/api/support/user/account/checkReset.ts
  projects/app/src/pages/api/support/user/account/nopswResetPsw.ts
  projects/app/src/pages/api/support/user/account/updatePasswordByOld.ts
  projects/app/src/pages/login/fastlogin.tsx
  projects/app/src/service/support/user/account/check.ts
  projects/app/src/web/support/user/api.ts
Labels: size/L

#4765 Password security policy
  docSite/content/zh-cn/docs/development/upgrading/498.md
  env.d.ts
  packages/global/support/user/type.d.ts
  packages/service/support/user/schema.ts
  packages/web/i18n/en/account_info.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/user.json
  packages/web/i18n/zh-CN/account_info.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/user.json
  packages/web/i18n/zh-Hant/account_info.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/user.json
  projects/app/.env.template
  projects/app/src/components/Layout/index.tsx
  projects/app/src/components/support/user/inform/SystemMsgModal.tsx
  projects/app/src/components/support/user/safe/ResetExpiredPswModal.tsx
  projects/app/src/components/support/wallet/NotSufficientModal/index.tsx
  projects/app/src/pages/api/support/user/account/checkPswExpired.ts
  projects/app/src/pages/api/support/user/account/resetExpiredPsw.ts
  projects/app/src/pages/api/support/user/account/updatePasswordByOld.ts
  projects/app/src/pages/login/fastlogin.tsx
  projects/app/src/service/support/user/account/password.ts
  projects/app/src/web/support/user/api.ts
Labels: size/XXL

#4768 perf: replace cite;perf: app card ui
  packages/service/core/ai/utils.ts
  packages/web/components/common/UserBox/index.tsx
  projects/app/src/pageComponents/dashboard/apps/List.tsx
  projects/app/src/pages/dashboard/apps/index.tsx
  test/cases/function/packages/service/core/ai/parseStreamResponse.test.ts
Labels: size/L

#4762 add prelogin api
  packages/global/support/user/api.d.ts
  packages/global/support/user/auth/constants.ts
  packages/global/support/user/auth/controller.ts
  packages/global/support/user/auth/schema.ts
  projects/app/src/global/support/user/auth/type.d.ts
  projects/app/src/pageComponents/login/LoginForm/LoginForm.tsx
  projects/app/src/pages/api/support/user/account/loginByPassword.ts
  projects/app/src/pages/api/support/user/account/preLogin.ts
  projects/app/src/web/support/user/api.ts
Labels: size/L

#4773 Feat: prelogin
  docSite/content/zh-cn/docs/development/upgrading/498.md
  packages/global/support/user/api.d.ts
  packages/global/support/user/auth/constants.ts
  packages/global/support/user/auth/type.d.ts
  packages/service/support/user/auth/controller.ts
  packages/service/support/user/auth/schema.ts
  projects/app/src/pageComponents/login/LoginForm/LoginForm.tsx
  projects/app/src/pages/api/support/user/account/loginByPassword.ts
  projects/app/src/pages/api/support/user/account/preLogin.ts
  projects/app/src/web/support/user/api.ts
Labels: size/L

#4760 plugin node version select
  packages/global/core/workflow/node/constant.ts
  packages/global/core/workflow/template/system/aiChat/index.ts
  packages/global/core/workflow/template/system/assignedAnswer.ts
  packages/global/core/workflow/template/system/classifyQuestion/index.ts
  packages/global/core/workflow/template/system/contextExtract/index.ts
  packages/global/core/workflow/template/system/customFeedback.ts
  packages/global/core/workflow/template/system/datasetConcat.ts
  packages/global/core/workflow/template/system/datasetSearch.ts
  packages/global/core/workflow/template/system/http468.ts
  packages/global/core/workflow/template/system/ifElse/index.ts
  packages/global/core/workflow/template/system/interactive/userSelect.ts
  packages/global/core/workflow/template/system/laf.ts
  packages/global/core/workflow/template/system/loop/loop.ts
  packages/global/core/workflow/template/system/sandbox/index.ts
  packages/global/core/workflow/template/system/textEditor.ts
  packages/global/core/workflow/template/system/tools.ts
  packages/global/core/workflow/template/system/variableUpdate/index.tsx
  packages/global/core/workflow/type/index.d.ts
  packages/global/core/workflow/type/io.d.ts
  packages/global/core/workflow/type/node.d.ts
  packages/service/core/app/plugin/controller.ts
  packages/service/core/app/utils.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/web/components/common/MySelect/index.tsx
  packages/web/hooks/useScrollPagination.tsx
  packages/web/i18n/en/app.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-Hant/app.json
  projects/app/src/pageComponents/app/detail/PublishHistoriesSlider.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/Label.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderOutput/Label.tsx
  projects/app/src/pages/api/core/app/plugin/getPreviewNode.ts
  projects/app/src/service/core/app/utils.ts
  projects/app/src/web/core/app/api/version.ts
  projects/app/src/web/core/workflow/utils.ts
Labels: size/XL

#4778 feat: Update the system configuration type, add visibility controls f…
  packages/global/common/system/types/index.d.ts
  projects/app/src/pageComponents/app/detail/Publish/index.tsx
  projects/app/src/pages/dataset/list/index.tsx
Labels: size/M

#4788 Update official_account.md
  docSite/content/zh-cn/docs/use-cases/external-integration/official_account.md
Labels: size/XS

#4789 Update official_account.md
  docSite/content/zh-cn/docs/use-cases/external-integration/official_account.md
Labels: size/XS

#4784 feat: add html video tag convertion
  packages/service/common/string/cheerio.ts
  packages/service/worker/htmlStr2Md/utils.ts
Labels: size/M

#4790 4.9.8 test
  docSite/content/zh-cn/docs/development/upgrading/498.md
  packages/global/core/workflow/template/system/aiChat/index.ts
  packages/global/core/workflow/template/system/assignedAnswer.ts
  packages/global/core/workflow/template/system/classifyQuestion/index.ts
  packages/global/core/workflow/template/system/contextExtract/index.ts
  packages/global/core/workflow/template/system/customFeedback.ts
  packages/global/core/workflow/template/system/datasetConcat.ts
  packages/global/core/workflow/template/system/datasetSearch.ts
  packages/global/core/workflow/template/system/http468.ts
  packages/global/core/workflow/template/system/ifElse/index.ts
  packages/global/core/workflow/template/system/interactive/userSelect.ts
  packages/global/core/workflow/template/system/laf.ts
  packages/global/core/workflow/template/system/loop/loop.ts
  packages/global/core/workflow/template/system/sandbox/index.ts
  packages/global/core/workflow/template/system/textEditor.ts
  packages/global/core/workflow/template/system/tools.ts
  packages/global/core/workflow/template/system/variableUpdate/index.tsx
  projects/app/src/components/support/laf/LafAccountModal.tsx
Labels: size/M

#4786 fix: improve handling of interactive node responses in workflow dispatch
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
Labels: size/S

#4793 fix monaco editor default value
  packages/web/components/common/Textarea/JsonEditor/index.tsx
  projects/app/src/web/core/chat/context/chatItemContext.tsx
Labels: size/M

#4794 optimize editor default value code
  packages/web/components/common/Textarea/JsonEditor/index.tsx
  projects/app/src/web/core/chat/context/chatItemContext.tsx
Labels: size/S

#4796 Test media tag
  docSite/content/zh-cn/docs/development/upgrading/498.md
  packages/service/common/string/cheerio.ts
  packages/service/worker/htmlStr2Md/utils.ts
Labels: size/S

#4797 remove system plugin node version
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
Labels: size/S

#4791 Fix the parentId type in ParentTreePathItemType by changing it from a…
  docSite/content/zh-cn/docs/guide/knowledge_base/api_dataset.md
Labels: size/XS

#4798 doc
  docSite/content/zh-cn/docs/development/upgrading/498.md
  packages/web/hooks/useScrollPagination.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/core/app/InputGuideConfig.tsx
  projects/app/src/components/core/app/VariableEdit.tsx
  projects/app/src/components/support/permission/MemberManager/MemberModal.tsx
  projects/app/src/pageComponents/account/team/EditInfoModal.tsx
  projects/app/src/pageComponents/app/detail/Logs/DetailLogsModal.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeFormInput/InputFormEditModal.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodePluginIO/InputEditModal.tsx
Labels: size/S

#4803 filter tool type version & fix unpublished version
  packages/service/core/app/plugin/controller.ts
  packages/service/core/app/version/controller.ts
  packages/web/components/common/MySelect/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
Labels: size/L

#4804 change password rule
  packages/global/common/string/password.ts
  packages/web/i18n/en/account_info.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/login.json
  packages/web/i18n/zh-CN/account_info.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/login.json
  packages/web/i18n/zh-Hant/account_info.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/login.json
  test/cases/function/packages/global/common/string/password.test.ts
Labels: size/M

#4806 update doc
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-oceanbase/docker-compose.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  docSite/content/zh-cn/docs/development/upgrading/498.md
Labels: size/M

#4809 New license
  packages/global/common/error/code/system.ts
  packages/global/common/system/types/index.d.ts
  packages/service/common/system/config/controller.ts
  packages/service/core/app/schema.ts
  packages/service/core/dataset/schema.ts
  packages/service/support/permission/teamLimit.ts
  packages/service/type.d.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/instrumentation.ts
  projects/app/src/pageComponents/dataset/detail/Form/CollectionChunkForm.tsx
  projects/app/src/pages/account/apikey.tsx
  projects/app/src/pages/account/bill/index.tsx
  projects/app/src/pages/account/info/index.tsx
  projects/app/src/pages/account/inform.tsx
  projects/app/src/pages/account/model/index.tsx
  projects/app/src/pages/account/promotion.tsx
  projects/app/src/pages/account/setting.tsx
  projects/app/src/pages/account/team/index.tsx
  projects/app/src/pages/account/usage/index.tsx
  projects/app/src/pages/api/admin/initv4820.ts
  projects/app/src/pages/api/core/app/httpPlugin/create.ts
  projects/app/src/pages/api/core/app/mcpTools/create.ts
  projects/app/src/pages/app/detail/index.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/dashboard/[pluginGroupId]/index.tsx
  projects/app/src/pages/dashboard/apps/index.tsx
  projects/app/src/pages/dashboard/mcpServer/index.tsx
  projects/app/src/pages/dashboard/templateMarket/index.tsx
  projects/app/src/pages/dataset/detail/index.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/service/common/system/index.ts
  projects/app/src/service/common/system/volumnMongoWatch.ts
Labels: size/L

#4817 feat: session id
  docSite/content/zh-cn/docs/development/upgrading/499.md
  env.d.ts
  packages/service/common/redis/cache.ts
  packages/service/common/redis/index.ts
  packages/service/common/redis/type.d.ts
  packages/service/core/ai/utils.ts
  packages/service/support/permission/controller.ts
  packages/service/support/user/session.ts
  projects/app/.env.template
  projects/app/src/pages/api/support/user/account/loginByPassword.ts
Labels: size/L

#4814 fix version match
  projects/app/src/pages/api/core/app/version/list.ts
Labels: size/XS

#4818 perf: tool call check
  docSite/content/zh-cn/docs/development/upgrading/499.md
  packages/global/core/ai/prompt/AIChat.ts
  packages/global/core/ai/prompt/dataset.ts
  packages/global/core/app/utils.ts
  packages/service/common/file/read/utils.ts
  packages/service/core/ai/utils.ts
  packages/service/core/app/utils.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/dataset/search.ts
  packages/web/components/common/Icon/button.tsx
  packages/web/i18n/en/account_team.json
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/account_team.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/account_team.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/Markdown/A.tsx
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ResponseTags.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/pageComponents/app/detail/Logs/DetailLogsModal.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/EditForm.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/components/ToolSelect.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pageComponents/app/detail/context.tsx
  projects/app/src/pageComponents/chat/ChatHistorySlider.tsx
  projects/app/src/pages/_app.tsx
  projects/app/src/pages/api/core/app/mcpTools/create.ts
  projects/app/src/pages/api/core/app/mcpTools/update.ts
  projects/app/src/pages/api/core/chat/quote/getQuote.ts
  projects/app/src/pages/api/core/dataset/data/getQuoteData.ts
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/pages/dashboard/mcpServer/index.tsx
  projects/app/src/service/core/app/utils.ts
  projects/app/src/web/core/chat/api.ts
  projects/app/src/web/core/chat/context/chatItemContext.tsx
  projects/app/src/web/core/dataset/api.ts
  test/cases/function/packages/service/core/ai/parseStreamResponse.test.ts
Labels: size/XXL

#4820 perf: mcp tool type
  packages/global/core/app/mcpTools/utils.ts
  packages/global/core/app/type.d.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/type/node.d.ts
  packages/service/core/app/mcp.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/context.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/Edit.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/EditForm.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/Header.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeToolSet.tsx
  projects/app/src/pageComponents/dashboard/apps/MCPToolsEditModal.tsx
  projects/app/src/pages/api/core/app/mcpTools/create.ts
  projects/app/src/pages/api/core/app/mcpTools/update.ts
  projects/app/src/pages/api/support/mcp/client/getTools.ts
  projects/app/src/pages/dashboard/apps/index.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/web/core/app/api/plugin.ts
Labels: size/L

#4826 feat: chat error msg
  docSite/assets/imgs/official_account_faq.png
  docSite/content/zh-cn/docs/development/upgrading/499.md
  docSite/content/zh-cn/docs/use-cases/external-integration/official_account.md
  packages/global/core/chat/type.d.ts
  packages/service/common/system/log.ts
  packages/service/core/chat/chatItemSchema.ts
  packages/service/core/chat/saveChat.ts
  packages/web/i18n/en/chat.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/chat.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/chat.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/package.json
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/pageComponents/price/Standard.tsx
  projects/app/src/pages/api/core/chat/getPaginationRecords.ts
  projects/app/src/web/common/api/request.ts
Labels: size/L

#4828 fix: handle optional indexes in InputDataModal
  projects/app/src/pageComponents/dataset/detail/InputDataModal.tsx
Labels: size/XS

#4827 offiaccount welcome text
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/Markdown/img/Image.tsx
Labels: size/S

#4822 Dataset
  docSite/content/zh-cn/docs/guide/knowledge_base/api_dataset.md
  packages/service/core/dataset/apiDataset/api.ts
  projects/app/src/pageComponents/dataset/ApiDatasetForm.tsx
  projects/app/src/pages/api/core/dataset/apiDataset/getPathNames.ts
  projects/app/src/pages/api/core/dataset/detail.ts
  projects/app/src/pages/api/core/dataset/update.ts
  projects/app/src/web/core/dataset/context/datasetPageContext.tsx
Labels: size/L

#4830 Test apidataset
  docSite/content/zh-cn/docs/guide/knowledge_base/api_dataset.md
  packages/service/core/dataset/apiDataset/api.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/Markdown/img/Image.tsx
  projects/app/src/pageComponents/dataset/ApiDatasetForm.tsx
  projects/app/src/pages/api/core/dataset/apiDataset/getPathNames.ts
  projects/app/src/pages/api/core/dataset/detail.ts
  projects/app/src/pages/api/core/dataset/update.ts
  projects/app/src/web/core/dataset/context/datasetPageContext.tsx
Labels: size/L

#4831 Update doc
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-oceanbase/docker-compose.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  docSite/content/zh-cn/docs/development/upgrading/499.md
Labels: size/M

#4838 perf: stream timeout;feat: hnsw max_scan_tuples config;fix: fulltext search merge error
  docSite/content/zh-cn/docs/development/upgrading/4910.md
  packages/global/common/system/types/index.d.ts
  packages/service/common/string/jieba/index.ts
  packages/service/common/vectorDB/pg/index.ts
  packages/service/core/ai/config.ts
  packages/service/core/dataset/data/dataTextSchema.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/core/workflow/dispatch/code/run.ts
  projects/app/data/config.json
  projects/app/src/pageComponents/dataset/detail/Test.tsx
Labels: size/L

#4843 perf: confirm ux
  docSite/content/zh-cn/docs/development/upgrading/4910.md
  packages/web/components/common/MyPopover/PopoverConfirm.tsx
  packages/web/styles/theme.ts
  projects/app/src/components/common/folder/SlideCard.tsx
  projects/app/src/components/core/app/InputGuideConfig.tsx
  projects/app/src/pageComponents/account/model/ModelConfigTable.tsx
  projects/app/src/pageComponents/account/team/MemberTable.tsx
  projects/app/src/pageComponents/account/team/OrgManage/IconButton.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeCode.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodePluginIO/PluginOutput.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderDebug/NodeDebugResponse.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/DynamicInputs/index.tsx
  projects/app/src/pageComponents/chat/ChatHistorySlider.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/Context.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/WebsiteConfig.tsx
  projects/app/src/pageComponents/dataset/detail/DataCard.tsx
  projects/app/src/pageComponents/dataset/detail/Info/index.tsx
  projects/app/src/pages/dashboard/mcpServer/index.tsx
Labels: size/XL

#4841 fix:修正docker-compose-pgvecto.yml文件中，健康检查参数错误
  deploy/docker/docker-compose-pgvector.yml
Labels: size/XS

#4845 fix quote reader duplicate rendering
  projects/app/src/pageComponents/chat/ChatQuoteList/index.tsx
Labels: size/S

#4851 change ui of price
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/price/pricearrow.svg
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/pageComponents/price/Standard.tsx
Labels: size/M

#4852 perf: chat history api;perf: full text error
  docSite/content/zh-cn/docs/development/openapi/chat.md
  packages/global/core/chat/type.d.ts
  packages/service/core/chat/chatSchema.ts
  packages/service/core/dataset/search/controller.ts
  packages/web/common/system/utils.ts
  packages/web/hooks/useCopyData.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/global/core/chat/api.d.ts
  projects/app/src/pageComponents/price/Standard.tsx
  projects/app/src/pages/api/core/chat/getHistories.ts
Labels: size/L

#4872 perf: isPc check;perf: dataset max token checker
  docSite/content/zh-cn/docs/development/upgrading/4910.md
  packages/global/core/app/constants.ts
  packages/service/core/app/controller.ts
  packages/web/common/system/utils.ts
  projects/app/src/components/core/app/DatasetParamsModal.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/VoiceInput.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeDatasetConcat.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SelectDatasetParams.tsx
Labels: size/L

#4867 Open Yufu Feishu Knowledge Base Permissions
  packages/service/common/api/type.d.ts
  packages/service/core/dataset/apiDataset/index.ts
  packages/service/core/dataset/apiDataset/proApi.ts
  packages/service/core/dataset/feishuDataset/api.ts
  packages/service/core/dataset/read.ts
  packages/service/core/dataset/yuqueDataset/api.ts
  projects/app/src/pages/api/core/dataset/apiDataset/getCatalog.ts
  projects/app/src/pages/api/core/dataset/apiDataset/getPathNames.ts
  projects/app/src/pages/api/core/dataset/apiDataset/list.ts
  projects/app/src/pages/api/core/dataset/collection/read.ts
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/service/common/system/index.ts
  projects/app/src/service/core/dataset/apiDataset/controller.ts
Labels: size/XL

#4875 perf: dataset import params code
  docSite/content/zh-cn/docs/development/upgrading/4910.md
  packages/global/core/dataset/api.d.ts
  packages/global/core/dataset/constants.ts
  packages/global/core/dataset/data/constants.ts
  packages/global/core/dataset/type.d.ts
  packages/service/core/ai/config/provider/Claude.json
  packages/service/core/ai/config/provider/Gemini.json
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/read.ts
  packages/service/core/dataset/schema.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/dataset.json
  projects/app/src/pageComponents/dataset/detail/CollectionCard/WebsiteConfig.tsx
  projects/app/src/pageComponents/dataset/detail/Form/CollectionChunkForm.tsx
  projects/app/src/pageComponents/dataset/detail/Import/Context.tsx
  projects/app/src/pageComponents/dataset/detail/Import/commonProgress/PreviewData.tsx
  projects/app/src/pageComponents/dataset/detail/Import/commonProgress/Upload.tsx
  projects/app/src/pageComponents/dataset/detail/Import/diffSource/ReTraining.tsx
  projects/app/src/pageComponents/dataset/detail/MetaDataCard.tsx
Labels: size/XL

#4874 Feature: Add additional dataset options and their descriptions, updat…
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/dataset/externalDatasetColor.svg
  packages/web/components/common/Icon/icons/core/dataset/otherDataset.svg
  packages/web/components/common/MyMenu/index.tsx
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/dataset.json
  projects/app/src/pages/dataset/list/index.tsx
Labels: size/L

#4883 optimize add node by handle
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/components/NodeTemplates/list.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/hooks/useWorkflow.tsx
Labels: size/M

#4882 feat: The workflow quickly adds applications
  docSite/content/zh-cn/docs/development/upgrading/4910.md
  packages/web/components/common/Tabs/FillRowTabs.tsx
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh-CN/workflow.json
  packages/web/i18n/zh-Hant/workflow.json
  projects/app/src/pageComponents/app/detail/SimpleApp/Header.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/NodeTemplatesPopover.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/components/ButtonEdge.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/components/NodeTemplates/header.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/components/NodeTemplates/list.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/components/NodeTemplates/useNodeTemplates.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/hooks/useWorkflow.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeCQNode.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeIfElse/ListItem.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeIfElse/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeUserSelect.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/Handle/ConnectionHandle.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/Handle/ToolHandle.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/Handle/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/Handle/style.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderOutput/Label.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/context/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/context/workflowEventContext.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/utils.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/XXL

#4887 Test add menu
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/dataset/externalDatasetColor.svg
  packages/web/components/common/Icon/icons/core/dataset/otherDataset.svg
  packages/web/components/common/MyMenu/index.tsx
  packages/web/components/common/MyPopover/index.tsx
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/dataset.json
  projects/app/src/pages/dataset/list/index.tsx
Labels: size/M

#4893 perf: chunk trigger and paragraph split
  docSite/content/zh-cn/docs/development/upgrading/4910.md
  packages/global/common/string/textSplitter.ts
  packages/global/core/dataset/training/utils.ts
  packages/global/core/dataset/type.d.ts
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/read.ts
  packages/service/core/dataset/schema.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/worker/readFile/extension/rawText.ts
  packages/web/components/common/Radio/RadioGroup.tsx
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/dataset.json
  projects/app/src/pageComponents/dataset/detail/CollectionCard/WebsiteConfig.tsx
  projects/app/src/pageComponents/dataset/detail/Form/CollectionChunkForm.tsx
  projects/app/src/pageComponents/dataset/detail/Import/Context.tsx
  projects/app/src/pageComponents/dataset/detail/Import/diffSource/ReTraining.tsx
  projects/app/src/pages/api/core/dataset/file/getPreviewChunks.ts
  projects/app/src/web/core/dataset/api.ts
  test/cases/function/packages/global/common/string/textSplitter.test.ts
  test/cases/function/packages/service/core/dataset/textSplitter.test.ts
Labels: size/XXL

#4897 version doc
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-oceanbase/docker-compose.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  docSite/content/zh-cn/docs/development/upgrading/4910.md
Labels: size/M

#4898 fix: dataset chunk description
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/dataset.json
Labels: size/XS

#4907 fix has tool node condition
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/components/NodeTemplates/useNodeTemplates.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/context/index.tsx
Labels: size/S

#4905 Feat: Node latest version
  docSite/content/zh-cn/docs/development/upgrading/4910.md
  docSite/content/zh-cn/docs/development/upgrading/4911.md
  packages/global/core/app/utils.ts
  packages/global/core/workflow/type/node.d.ts
  packages/plugins/src/DingTalkWebhook/template.json
  packages/plugins/src/Doc2X/PDF2text/template.json
  packages/plugins/src/Doc2X/template.json
  packages/plugins/src/WeWorkWebhook/template.json
  packages/plugins/src/bing/template.json
  packages/plugins/src/databaseConnection/template.json
  packages/plugins/src/delay/template.json
  packages/plugins/src/drawing/baseChart/template.json
  packages/plugins/src/drawing/template.json
  packages/plugins/src/duckduckgo/search/template.json
  packages/plugins/src/duckduckgo/searchImg/template.json
  packages/plugins/src/duckduckgo/searchNews/template.json
  packages/plugins/src/duckduckgo/searchVideo/template.json
  packages/plugins/src/duckduckgo/template.json
  packages/plugins/src/feishu/template.json
  packages/plugins/src/fetchUrl/template.json
  packages/plugins/src/getTime/template.json
  packages/plugins/src/google/template.json
  packages/plugins/src/mathExprVal/template.json
  packages/plugins/src/searchXNG/template.json
  packages/plugins/src/smtpEmail/template.json
  packages/plugins/src/template/template.json
  packages/plugins/src/wiki/template.json
  packages/service/core/app/plugin/controller.ts
  packages/service/core/app/plugin/utils.ts
  packages/service/core/app/utils.ts
  packages/service/core/app/version/controller.ts
  packages/service/support/permission/app/auth.ts
  packages/web/components/common/Textarea/PromptEditor/plugins/VariablePlugin/components/Variable.tsx
  packages/web/hooks/useScrollPagination.tsx
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/global/core/chat/api.d.ts
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/api/core/app/detail.ts
  projects/app/src/pages/api/core/app/plugin/getPreviewNode.ts
  projects/app/src/pages/api/core/app/plugin/getVersionList.ts
  projects/app/src/pages/api/core/app/version/detail.ts
  projects/app/src/pages/api/core/app/version/latest.ts
  projects/app/src/service/core/app/utils.ts
  projects/app/src/web/core/app/api/plugin.ts
  projects/app/src/web/core/chat/context/chatRecordContext.tsx
Labels: size/L

#4914 feat: remove buffer;fix: custom pdf parse
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-oceanbase/docker-compose.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  docSite/content/zh-cn/docs/development/upgrading/4910.md
  docSite/content/zh-cn/docs/development/upgrading/4911.md
  packages/service/common/buffer/rawText/controller.ts
  packages/service/common/file/read/utils.ts
  packages/service/common/system/timerLock/constants.ts
  projects/app/src/instrumentation.ts
  projects/app/src/service/common/system/cron.ts
Labels: size/L

#4919 fix child app external variables
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/plugin/run.ts
  packages/service/core/workflow/dispatch/plugin/runApp.ts
Labels: size/S

#4902 add node find
  packages/global/core/workflow/type/node.d.ts
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh-CN/workflow.json
  packages/web/i18n/zh-Hant/workflow.json
  projects/app/src/pageComponents/app/detail/Plugin/Header.tsx
  projects/app/src/pageComponents/app/detail/Workflow/Header.tsx
  projects/app/src/pageComponents/app/detail/Workflow/components/SaveButton.tsx
  projects/app/src/pageComponents/app/detail/Workflow/components/SearchButton.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
Labels: size/L

#4924 feat: text collecion auto save for a txt file
  packages/global/core/dataset/utils.ts
  packages/service/common/file/gridfs/controller.ts
  packages/service/common/file/gridfs/utils.ts
  projects/app/src/pageComponents/dataset/detail/Import/diffSource/FileCustomText.tsx
  projects/app/src/pages/api/core/dataset/collection/create/text.ts
  projects/app/src/service/core/dataset/queues/generateQA.ts
  projects/app/src/service/core/dataset/queues/generateVector.ts
  projects/app/src/service/core/dataset/queues/utils.ts
  projects/app/src/service/core/dataset/training/utils.ts
Labels: size/M

#4927 Update dataset.md
  docSite/content/zh-cn/docs/development/openapi/dataset.md
Labels: size/XS

#4933 add Bocha search template
  packages/plugins/register.ts
  packages/plugins/src/bocha/template.json
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/workflow/template/bocha.svg
Labels: size/XL
