Repository labring/FastGPT, pull requests merged in 2025-08, with the labels that each got.

#5363 fix: plugin not get system input config
  packages/global/core/app/plugin/type.d.ts
  packages/service/core/app/plugin/controller.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/service/core/workflow/utils.ts
  packages/service/package.json
  pnpm-lock.yaml
Labels: size/L

#5364 fix: tool not clone
  packages/service/core/app/plugin/controller.ts
Labels: size/XS

#5365 fix: simple mode toolset not refresh tool config
  packages/global/core/app/utils.ts
Labels: size/XS

#5366 fix: missing build mcp image args
  projects/mcp_server/Dockerfile
Labels: size/XS

#5372 feat: move robots.txt to toc.mdx
  document/app/[lang]/robots.txt/route.ts
  document/app/api/robots/route.ts
  document/content/docs/toc.en.mdx
  document/content/docs/toc.mdx
  document/data/doc-last-modified.json
  document/lib/generateToc.js
  package.json
Labels: size/XL

#5381 Update dataset.mdx
  document/content/docs/introduction/development/openapi/dataset.mdx
Labels: size/XS

#5383 fix: doc preview action;update doc
  .github/workflows/docs-preview.yml
  document/content/docs/introduction/development/openapi/share.mdx
  document/content/docs/upgrading/4-8/464.mdx
  document/content/docs/upgrading/4-8/467.mdx
  document/content/docs/upgrading/4-8/469.mdx
  document/content/docs/upgrading/4-9/490.mdx
  document/content/docs/upgrading/4-9/492.mdx
  document/content/docs/use-cases/external-integration/openapi.mdx
  document/data/doc-last-modified.json
  packages/service/support/wallet/usage/schema.ts
Labels: size/XL

#5386 update doc search engine
  .github/workflows/docs-deploy.yml
  .github/workflows/docs-preview.yml
  document/.env.template
  document/Dockerfile
  document/README.md
  document/app/api/search/route.ts
  document/clean-frontmatter.js
  document/components/CustomSearchDialog.tsx
  document/content/docs/faq/other.mdx
  document/content/docs/introduction/commercial.mdx
  document/content/docs/introduction/development/configuration.mdx
  document/content/docs/introduction/development/custom-models/marker.mdx
  document/content/docs/upgrading/4-8/462.mdx
  document/content/docs/upgrading/4-8/47.mdx
  document/content/docs/upgrading/4-9/4910.mdx
  document/content/docs/upgrading/4-9/496.mdx
  document/lib/tokenizer.ts
  document/meta-order.js
  document/meta.js
  document/package-lock.json
  document/package.json
  document/script/initDocTime.js
  document/update-index.mjs
  package.json
  packages/web/i18n/zh-CN/common.json
Labels: size/XL

#5387 更新 4112.mdx
  document/content/docs/upgrading/4-11/4112.mdx
Labels: size/XS

#5388 fix: mcp not response output
  packages/service/common/file/image/controller.ts
  packages/service/common/response/index.ts
  packages/service/core/dataset/image/controller.ts
  packages/service/core/workflow/dispatch/child/runTool.ts
Labels: size/S

#5357 refactor: tweak login loyout
  packages/web/i18n/en/login.json
  packages/web/i18n/zh-CN/login.json
  packages/web/i18n/zh-Hant/login.json
  projects/app/src/components/PageContainer/index.tsx
  projects/app/src/pageComponents/login/LoginForm/FormLayout.tsx
  projects/app/src/pageComponents/login/LoginForm/LoginForm.tsx
  projects/app/src/pageComponents/login/LoginModal.tsx
  projects/app/src/pageComponents/login/index.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/login/index.tsx
Labels: size/M

#5391 Update dataset.mdx
  document/content/docs/introduction/development/openapi/dataset.mdx
Labels: size/XS

#5392 app chat log chart pro display
  packages/global/core/app/logs/constants.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/star.svg
  packages/web/components/common/MyModal/index.tsx
  packages/web/components/common/charts/BarChartComponent.tsx
  packages/web/components/common/charts/LineChartComponent.tsx
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/public/imgs/proModalBg.png
  projects/app/public/imgs/proTag.svg
  projects/app/public/imgs/proTagEng.svg
  projects/app/src/components/ProModal/index.tsx
  projects/app/src/pageComponents/app/detail/Logs/LogChart.tsx
  projects/app/src/pageComponents/app/detail/Logs/index.tsx
Labels: size/XL

#5401 doc
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-oceanbase/docker-compose.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  deploy/docker/yml.js
  document/content/docs/upgrading/4-11/4111.mdx
Labels: size/M

#5407 perf: emb batch
  document/content/docs/upgrading/4-11/4112.mdx
  document/data/doc-last-modified.json
  packages/global/core/dataset/training/utils.ts
  packages/service/common/vectorDB/controller.d.ts
  packages/service/common/vectorDB/controller.ts
  packages/service/common/vectorDB/milvus/index.ts
  packages/service/common/vectorDB/oceanbase/index.ts
  packages/service/common/vectorDB/pg/index.ts
  packages/service/core/ai/embedding/index.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/core/dataset/training/controller.ts
  packages/service/package.json
  pnpm-lock.yaml
  projects/app/src/pages/api/core/dataset/data/insertData.ts
  projects/app/src/pages/api/v1/embeddings.ts
  projects/app/src/service/core/dataset/data/controller.ts
  projects/app/src/service/core/dataset/queues/generateVector.ts
Labels: size/XXL

#5409 fix: max tokens config
  packages/service/core/ai/config/utils.ts
Labels: size/S

#5411 doc
  document/content/docs/toc.mdx
  document/content/docs/upgrading/4-11/4112.mdx
  document/data/doc-last-modified.json
  document/lib/generateToc.js
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/components/NodeTemplates/list.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/TrainingStates.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/index.tsx
Labels: size/M

#5376 Tool price
  packages/global/core/app/plugin/type.d.ts
  packages/global/core/workflow/type/node.d.ts
  packages/service/core/app/plugin/controller.ts
  packages/service/core/app/plugin/systemPluginSchema.ts
  packages/service/core/app/plugin/type.d.ts
  packages/service/core/app/utils.ts
  packages/service/core/workflow/dispatch/child/runTool.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-Hant/app.json
  projects/app/src/components/core/app/plugin/CostTooltip.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/components/ConfigToolModal.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/components/ToolSelectModal.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/components/NodeTemplates/list.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/components/ToolParamConfig.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pageComponents/app/plugin/SecretInputModal.tsx
Labels: size/L

#5419 perf: toolset price config;fix: workflow array selector ui
  document/content/docs/introduction/development/faq.mdx
  document/content/docs/introduction/development/modelConfig/intro.mdx
  document/content/docs/introduction/development/openapi/dataset.mdx
  document/content/docs/upgrading/4-11/4112.mdx
  document/data/doc-last-modified.json
  packages/global/core/ai/model.ts
  packages/global/core/app/constants.ts
  packages/global/core/app/utils.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/service/core/app/plugin/controller.ts
  packages/service/core/dataset/schema.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/service/core/workflow/utils.ts
  packages/templates/src/CQ/template.json
  packages/templates/src/longTranslate/template.json
  packages/templates/src/simpleDatasetChat/template.json
  packages/web/context/useSystem.tsx
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/data/config.local.json
  projects/app/data/model.json
  projects/app/package.json
  projects/app/src/components/core/app/plugin/CostTooltip.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeToolSet.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Reference.tsx
  projects/app/src/pageComponents/app/plugin/SecretInputModal.tsx
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/core/workflow/debug.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/api/v2/chat/completions.ts
  projects/app/src/web/core/app/templates.ts
  projects/app/test/api/core/dataset/training/deleteTrainingData.test.ts
  projects/app/test/api/core/dataset/training/getTrainingDataDetail.test.ts
  projects/app/test/api/core/dataset/training/getTrainingError.test.ts
  projects/app/test/api/core/dataset/training/updateTrainingData.test.ts
  test/setupModels.ts
Labels: size/L

#5400 feat: llm directory optimization
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/dataset.json
  projects/app/src/pageComponents/dataset/detail/Form/CollectionChunkForm.tsx
  projects/app/src/service/core/dataset/queues/datasetParse.ts
Labels: size/M

#5434 Fix/chat
  packages/service/support/permission/app/auth.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/chat/sidebar/menu.svg
  packages/web/i18n/en/app.json
  packages/web/i18n/en/chat.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/chat.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/chat.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/.env.template
  projects/app/src/components/Select/AIModelSelector.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/components/core/chat/ChatSetting/HomepageSetting.tsx
  projects/app/src/components/core/chat/ChatSetting/index.tsx
  projects/app/src/components/core/chat/ChatTeamApp/List.tsx
  projects/app/src/components/core/chat/ChatTeamApp/TypeTag.tsx
  projects/app/src/components/core/chat/ChatTeamApp/index.tsx
  projects/app/src/components/core/chat/ChatWindow/AppChatWindow.tsx
  projects/app/src/components/core/chat/ChatWindow/HomeChatWindow.tsx
  projects/app/src/global/core/chat/constants.ts
  projects/app/src/pageComponents/chat/ChatHeader.tsx
  projects/app/src/pageComponents/chat/ChatHistorySlider.tsx
  projects/app/src/pageComponents/chat/SliderApps.tsx
  projects/app/src/pages/api/core/chat/getPaginationRecords.ts
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/dashboard/apps/index.tsx
  projects/app/src/web/core/chat/context/chatSettingContext.tsx
Labels: size/XL

#5436 optimize export app chat log
  projects/app/src/pageComponents/app/detail/Logs/LogTable.tsx
  projects/app/src/pages/api/core/app/exportChatLogs.ts
Labels: size/L

#5437 fix: move components to proper directory; make sure api be invoked to get app list
  projects/app/src/pageComponents/chat/ChatSetting/DiagramModal.tsx
  projects/app/src/pageComponents/chat/ChatSetting/HomepageSetting.tsx
  projects/app/src/pageComponents/chat/ChatSetting/ImageUpload/hooks/useImageUpload.tsx
  projects/app/src/pageComponents/chat/ChatSetting/ImageUpload/index.tsx
  projects/app/src/pageComponents/chat/ChatSetting/SettingTabs.tsx
  projects/app/src/pageComponents/chat/ChatSetting/ToolSelectModal.tsx
  projects/app/src/pageComponents/chat/ChatSetting/index.tsx
  projects/app/src/pageComponents/chat/ChatTeamApp/List.tsx
  projects/app/src/pageComponents/chat/ChatTeamApp/TypeTag.tsx
  projects/app/src/pageComponents/chat/ChatTeamApp/index.tsx
  projects/app/src/pageComponents/chat/ChatWindow/AppChatWindow.tsx
  projects/app/src/pageComponents/chat/ChatWindow/HomeChatWindow.tsx
  projects/app/src/pageComponents/chat/useChat.ts
  projects/app/src/pages/chat/index.tsx
  projects/app/src/web/core/app/api.ts
Labels: size/M

#5438 chore: improve team app panel display form
  packages/web/i18n/en/chat.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/chat.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/chat.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/pageComponents/app/detail/Logs/LogChart.tsx
  projects/app/src/pageComponents/app/detail/Logs/LogTable.tsx
  projects/app/src/pageComponents/app/detail/Logs/index.tsx
  projects/app/src/pageComponents/chat/ChatHeader.tsx
  projects/app/src/pageComponents/chat/ChatHistorySlider.tsx
  projects/app/src/pageComponents/chat/ChatSetting/DataDashboard.tsx
  projects/app/src/pageComponents/chat/ChatSetting/HomepageSetting.tsx
  projects/app/src/pageComponents/chat/ChatSetting/LogDetails.tsx
  projects/app/src/pageComponents/chat/ChatSetting/SettingTabs.tsx
  projects/app/src/pageComponents/chat/ChatSetting/index.tsx
  projects/app/src/pageComponents/chat/ChatTeamApp/List.tsx
  projects/app/src/pageComponents/chat/ChatTeamApp/index.tsx
  projects/app/src/pageComponents/chat/ChatWindow/HomeChatWindow.tsx
  projects/app/src/pageComponents/chat/constants.ts
Labels: size/XL

#5440 redirect
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/pageComponents/chat/ChatWindow/HomeChatWindow.tsx
  projects/app/src/pageComponents/chat/SliderApps.tsx
  projects/app/src/web/core/chat/context/useChatStore.ts
Labels: size/M

#5448 Update dataset.mdx
  document/content/docs/introduction/development/openapi/dataset.mdx
Labels: size/XS

#5446 fix: update runningUserInfo retrieval in chat completions API
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/api/v2/chat/completions.ts
Labels: size/XS

#5444 feat: add prompt optimizer
  packages/global/support/wallet/usage/constants.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/optimizer.svg
  packages/web/components/common/MyModal/index.tsx
  packages/web/components/common/MyPopover/index.tsx
  packages/web/components/common/Textarea/PromptEditor/Editor.tsx
  packages/web/components/common/Textarea/PromptEditor/index.tsx
  packages/web/components/common/Textarea/PromptEditor/modules/OptimizerPopover/index.tsx
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/core/app/formRender/index.tsx
  projects/app/src/components/core/app/formRender/type.d.ts
  projects/app/src/pageComponents/app/detail/SimpleApp/EditForm.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/CommonInputForm.tsx
  projects/app/src/pages/api/core/ai/optimizePrompt.ts
Labels: size/XL

#5457 fix dataset auth filter
  packages/service/core/dataset/utils.ts
Labels: size/M

#5455 fix instructions
  packages/service/core/app/plugin/controller.ts
  projects/app/src/pages/api/core/app/plugin/getSystemPluginTemplates.ts
Labels: size/XS

#5461 prompt optimze loading
  packages/web/i18n/en/app.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-Hant/app.json
  projects/app/src/components/common/PromptEditor/OptimizerPopover/index.tsx
Labels: size/M

#5458 fix: index
  document/content/docs/introduction/development/openapi/chat.mdx
  document/content/docs/introduction/development/openapi/dataset.mdx
  document/content/docs/introduction/development/openapi/intro.mdx
  document/content/docs/upgrading/4-12/4121.mdx
  document/content/docs/use-cases/external-integration/openapi.mdx
  document/data/doc-last-modified.json
  packages/service/core/chat/chatSchema.ts
  packages/web/i18n/zh-CN/chat.json
  packages/web/i18n/zh-Hant/chat.json
  projects/app/src/pageComponents/app/plugin/SecretInputModal.tsx
  projects/app/src/pageComponents/chat/ChatWindow/HomeChatWindow.tsx
  projects/app/src/pages/api/admin/initv4121.ts
  projects/app/src/service/support/wallet/usage/push.ts
  projects/app/src/web/core/chat/context/chatRecordContext.tsx
Labels: size/L

#5456 fix: sync pane with URL appId vs Home appId to avoid cross-tab interference
  projects/app/src/pageComponents/app/detail/SimpleApp/AppCard.tsx
  projects/app/src/pageComponents/chat/ChatHeader.tsx
  projects/app/src/pageComponents/chat/ChatTeamApp/List.tsx
  projects/app/src/pageComponents/chat/ChatWindow/AppChatWindow.tsx
  projects/app/src/pageComponents/chat/ChatWindow/HomeChatWindow.tsx
  projects/app/src/pageComponents/chat/SliderApps.tsx
  projects/app/src/pageComponents/chat/useChat.ts
  projects/app/src/pageComponents/dashboard/apps/List.tsx
  projects/app/src/web/core/chat/context/chatSettingContext.tsx
Labels: size/L

#5462 perf: chat pane
  document/components/docs/not-found.tsx
  document/content/docs/upgrading/4-12/4121.mdx
  document/data/doc-last-modified.json
  packages/service/core/app/logs/chatLogsSchema.ts
  packages/service/core/chat/chatSchema.ts
  packages/service/core/chat/saveChat.ts
  packages/service/support/wallet/usage/schema.ts
  projects/app/src/components/Layout/navbar.tsx
  projects/app/src/components/Layout/navbarPhone.tsx
  projects/app/src/components/Markdown/A.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/AppCard.tsx
  projects/app/src/pageComponents/chat/ChatHeader.tsx
  projects/app/src/pageComponents/chat/ChatTeamApp/List.tsx
  projects/app/src/pageComponents/chat/ChatWindow/AppChatWindow.tsx
  projects/app/src/pageComponents/chat/ChatWindow/HomeChatWindow.tsx
  projects/app/src/pageComponents/chat/SliderApps.tsx
  projects/app/src/pageComponents/chat/constants.ts
  projects/app/src/pageComponents/chat/useChat.ts
  projects/app/src/pageComponents/dashboard/apps/List.tsx
  projects/app/src/pages/api/admin/initv4121.ts
  projects/app/src/pages/api/core/app/getChatLogs.ts
  projects/app/src/pages/api/core/chat/feedback/updateUserFeedback.ts
  projects/app/src/web/core/chat/context/chatSettingContext.tsx
  projects/app/src/web/core/chat/context/useChatStore.ts
Labels: size/L

#5452 feat: enhance workflow types and runtime nodes with toolDescription
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/global/core/workflow/type/index.d.ts
  packages/global/core/workflow/type/node.d.ts
  packages/service/core/app/plugin/controller.ts
  packages/service/core/app/plugin/type.d.ts
  packages/service/core/workflow/dispatch/ai/agent/functionCall.ts
  packages/service/core/workflow/dispatch/ai/agent/promptCall.ts
  packages/service/core/workflow/dispatch/ai/agent/toolChoice.ts
  packages/service/package.json
  pnpm-lock.yaml
  projects/app/src/pages/api/core/app/plugin/getSystemPluginTemplates.ts
Labels: size/M

#5465 perF: getInitData api cache;perf: tool description field;signoz store level
  .claude/design/service/common/cache/version.md
  document/components/docs/not-found.tsx
  document/content/docs/upgrading/4-12/4121.mdx
  document/data/doc-last-modified.json
  packages/service/common/system/log.ts
  packages/service/core/ai/config/utils.ts
  packages/service/core/ai/type.d.ts
  packages/service/core/app/plugin/controller.ts
  packages/service/core/app/utils.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-Hant/app.json
  projects/app/.env.template
  projects/app/src/components/common/PromptEditor/OptimizerPopover/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/utils.ts
  projects/app/src/pages/api/common/system/getInitData.ts
  projects/app/src/pages/api/core/app/exportChatLogs.ts
  projects/app/src/pages/api/core/app/getChatLogs.ts
  projects/app/src/web/core/app/utils.ts
Labels: size/L

#5469 perf: page ui
  .claude/design/web/common/hook/tableMultiple/index.md
  document/content/docs/upgrading/4-12/4121.mdx
  document/data/doc-last-modified.json
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/first_page.svg
  packages/web/components/common/Icon/icons/common/latest_page.svg
  packages/web/components/common/Icon/icons/common/leftArrowLight.svg
  packages/web/components/common/Icon/icons/common/rightArrowLight.svg
  packages/web/hooks/usePagination.tsx
  packages/web/hooks/useTableMultipleSelect.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/dataset.json
  packages/web/styles/theme.ts
  projects/app/src/pageComponents/account/bill/BillTable.tsx
  projects/app/src/pageComponents/account/bill/InvoiceTable.tsx
  projects/app/src/pageComponents/account/usage/UsageTable.tsx
  projects/app/src/pageComponents/app/detail/Logs/LogChart.tsx
  projects/app/src/pageComponents/app/detail/Logs/LogTable.tsx
  projects/app/src/pageComponents/app/detail/Plugin/Header.tsx
  projects/app/src/pageComponents/app/detail/Workflow/Header.tsx
  projects/app/src/pageComponents/app/evaluation/DetailModal.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/Context.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/index.tsx
  projects/app/src/pages/account/bill/index.tsx
  projects/app/src/pages/account/inform.tsx
  projects/app/src/pages/account/promotion.tsx
  projects/app/src/pages/api/admin/initv4121.ts
  projects/app/src/pages/api/core/dataset/collection/delete.ts
  projects/app/src/pages/api/core/dataset/collection/list.ts
  projects/app/src/pages/api/core/dataset/collection/listV2.ts
  projects/app/src/pages/dashboard/evaluation/index.tsx
  projects/app/src/web/core/dataset/api.ts
Labels: size/XL

#5470 version package
  projects/app/package.json
Labels: size/XS

#5471 fix: fe
  projects/app/src/pageComponents/app/detail/Plugin/Header.tsx
  projects/app/src/pageComponents/app/detail/Workflow/Header.tsx
Labels: size/S

#5472 doc
  document/content/docs/upgrading/4-12/4121.mdx
  document/data/doc-last-modified.json
  projects/app/src/web/core/chat/context/chatSettingContext.tsx
  projects/app/src/web/core/chat/context/useChatStore.ts
Labels: size/M

#5473 deploy doc
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-oceanbase/docker-compose.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  deploy/docker/yml.js
  document/content/docs/upgrading/4-12/4121.mdx
  document/data/doc-last-modified.json
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/pageComponents/chat/ChatWindow/HomeChatWindow.tsx
Labels: size/L

#5474 Upgrate doc
  document/content/docs/upgrading/4-12/4121.mdx
  document/data/doc-last-modified.json
Labels: size/S

#5404 feat: Global variables add
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/node/constant.ts
  packages/global/core/workflow/utils.ts
  packages/service/core/ai/config/utils.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/password.svg
  packages/web/components/common/MySelect/MultipleSelect.tsx
  packages/web/components/core/workflow/NodeInputSelect.tsx
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/common/HiddenInput/index.tsx
  projects/app/src/components/core/app/VariableEdit.tsx
  projects/app/src/components/core/app/formRender/constant.ts
  projects/app/src/components/core/app/formRender/index.tsx
  projects/app/src/components/core/app/formRender/type.d.ts
  projects/app/src/components/core/app/formRender/utils.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Provider.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariableInputForm.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariablePopover.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/pageComponents/account/AccountContainer.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/hooks/useDebug.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeFormInput/InputFormEditModal.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodePluginIO/InputEditModal.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/index.tsx
  projects/app/src/pageComponents/dashboard/apps/List.tsx
  projects/app/src/pageComponents/dataset/list/List.tsx
Labels: size/L

#5487 fix: multiple select value type when empty string does not have map function
  packages/web/components/common/MySelect/MultipleSelect.tsx
Labels: size/XS

#5494 perf: customizable embedding chunk size via env var
  packages/service/core/ai/embedding/index.ts
  projects/app/.env.template
Labels: size/XS

#5486 docs: update dev system tool
  document/content/docs/introduction/development/design/design_plugin.mdx
  document/content/docs/introduction/guide/plugins/dev_system_tool.mdx
  document/data/doc-last-modified.json
Labels: size/S

#5511 fix: model selector overlay
  document/content/docs/toc.mdx
  document/content/docs/upgrading/4-12/4122.mdx
  document/data/doc-last-modified.json
  packages/web/i18n/en/common.json
  projects/app/src/components/Select/AIModelSelector.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/pageComponents/chat/ChatWindow/HomeChatWindow.tsx
Labels: size/M

#5516 perf: vector format
  document/content/docs/upgrading/4-12/4122.mdx
  document/data/doc-last-modified.json
  packages/global/core/ai/model.d.ts
  packages/global/core/workflow/node/constant.ts
  packages/service/core/ai/embedding/index.ts
  packages/web/i18n/en/account_model.json
  packages/web/i18n/zh-CN/account_model.json
  packages/web/i18n/zh-Hant/account_model.json
  projects/app/src/components/Select/AIModelSelector.tsx
  projects/app/src/pageComponents/account/model/AddModelBox.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/hooks/useDebug.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/context/index.tsx
  projects/app/src/pageComponents/chat/ChatWindow/HomeChatWindow.tsx
  projects/app/src/web/core/workflow/utils.ts
  test/cases/service/core/ai/embedding.test.ts
Labels: size/L

#5518 fix: version schema ref error
  document/content/docs/upgrading/4-12/4122.mdx
  document/data/doc-last-modified.json
  packages/service/core/app/version/schema.ts
  projects/app/src/pages/api/core/app/version/list.ts
Labels: size/S

#5515 feat: favorite apps & quick apps with their own configuration
  packages/global/core/app/type.d.ts
  packages/global/core/chat/favouriteApp/type.d.ts
  packages/global/core/chat/setting/type.d.ts
  packages/service/core/app/controller.ts
  packages/service/core/app/schema.ts
  packages/service/core/chat/favouriteApp/schema.ts
  packages/service/core/chat/setting/schema.ts
  packages/service/support/permission/app/auth.ts
  packages/web/components/common/DndDrag/index.tsx
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/chat/sidebar/star.svg
  packages/web/i18n/en/chat.json
  packages/web/i18n/zh-CN/chat.json
  packages/web/i18n/zh-Hant/chat.json
  projects/app/public/imgs/modal/add.svg
  projects/app/public/imgs/modal/tag.svg
  projects/app/public/imgs/modal/warn.svg
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Provider.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatHomeVariablesForm.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/pageComponents/app/detail/Logs/LogChart.tsx
  projects/app/src/pageComponents/app/detail/Logs/LogTable.tsx
  projects/app/src/pageComponents/chat/ChatFavouriteApp/index.tsx
  projects/app/src/pageComponents/chat/ChatHeader.tsx
  projects/app/src/pageComponents/chat/ChatSetting/AppTree.tsx
  projects/app/src/pageComponents/chat/ChatSetting/DataDashboard.tsx
  projects/app/src/pageComponents/chat/ChatSetting/FavouriteAppSetting/AddFavouriteAppModal.tsx
  projects/app/src/pageComponents/chat/ChatSetting/FavouriteAppSetting/TagManageModal.tsx
  projects/app/src/pageComponents/chat/ChatSetting/FavouriteAppSetting/index.tsx
  projects/app/src/pageComponents/chat/ChatSetting/HomepageSetting/AddQuickAppModal.tsx
  projects/app/src/pageComponents/chat/ChatSetting/HomepageSetting/index.tsx
  projects/app/src/pageComponents/chat/ChatSetting/LogDetails.tsx
  projects/app/src/pageComponents/chat/ChatSetting/SettingTabs.tsx
  projects/app/src/pageComponents/chat/ChatSetting/index.tsx
  projects/app/src/pageComponents/chat/ChatWindow/HomeChatWindow.tsx
  projects/app/src/pageComponents/chat/SliderApps.tsx
  projects/app/src/pageComponents/chat/constants.ts
  projects/app/src/pageComponents/chat/slider/ChatSliderHeader.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/web/core/app/api.ts
  projects/app/src/web/core/chat/api.ts
  projects/app/src/web/core/chat/context/chatSettingContext.tsx
  projects/app/src/web/core/chat/context/useChatStore.ts
Labels: size/XXL

#5523 fix: increase MCP auth config value field maxLength
  projects/app/src/components/common/secret/HeaderAuthConfig.tsx
Labels: size/XS

#5528 fix: incorrect select quick apps state; filter apps type
  projects/app/src/pageComponents/chat/ChatSetting/FavouriteAppSetting/AddFavouriteAppModal.tsx
  projects/app/src/pageComponents/chat/ChatSetting/HomepageSetting/AddQuickAppModal.tsx
Labels: size/S

#5530 perf: search key refresh parentId
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/plugin/runOutput.ts
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/NodeTemplatesPopover.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/components/NodeTemplates/header.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/components/NodeTemplates/useNodeTemplates.tsx
  projects/app/src/pageComponents/dashboard/apps/List.tsx
  projects/app/src/pages/api/core/app/plugin/getSystemPluginTemplates.ts
  projects/app/src/pages/dashboard/apps/index.tsx
Labels: size/L

#5534 feat: Store pdfparse in local
  README.md
  document/content/docs/upgrading/4-12/4122.mdx
  document/data/doc-last-modified.json
  packages/global/core/app/constants.ts
  projects/app/src/pageComponents/app/detail/SimpleApp/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/EditForm.tsx
  projects/app/src/pageComponents/dataset/detail/Import/Context.tsx
  projects/app/src/pageComponents/dataset/detail/Import/diffSource/ReTraining.tsx
Labels: size/M

#5535 update package
  projects/app/package.json
Labels: size/XS

#5537 fix: chat navbar
  document/content/docs/upgrading/4-12/4122.mdx
  document/data/doc-last-modified.json
  projects/app/src/components/Layout/navbar.tsx
Labels: size/S

#5541 fix: read permission; incorrect name; redirect
  packages/service/support/permission/app/auth.ts
  projects/app/src/pageComponents/chat/ChatSetting/index.tsx
  projects/app/src/pageComponents/chat/UserAvatarPopover.tsx
Labels: size/S

#5542 fix: team avatar select
  projects/app/src/pageComponents/account/team/context.tsx
  projects/app/src/pages/account/team/index.tsx
Labels: size/XS

#5543 update doc
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-oceanbase/docker-compose.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  deploy/docker/yml.js
  document/content/docs/upgrading/4-12/4122.mdx
  document/data/doc-last-modified.json
Labels: size/M

#5544 fix: ai response test
  document/content/docs/upgrading/4-12/4122.mdx
  document/data/doc-last-modified.json
  packages/global/common/error/utils.ts
  packages/global/core/app/mcpTools/utils.ts
  packages/service/core/ai/llm/request.ts
  packages/service/core/workflow/dispatch/ai/agent/toolCall.ts
  packages/service/core/workflow/dispatch/ai/chat.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/tools/codeSandbox.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/service/core/workflow/utils.ts
  projects/app/src/pageComponents/chat/slider/index.tsx
  projects/app/src/pages/api/core/app/list.ts
  projects/app/src/pages/api/core/app/mcpTools/getChildren.ts
  projects/app/src/web/core/app/api/plugin.ts
Labels: size/L

#5545 Update doc
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-oceanbase/docker-compose.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  deploy/docker/yml.js
  document/content/docs/upgrading/4-12/4122.mdx
  document/data/doc-last-modified.json
Labels: size/S

#5547 fix: mcp tool node hide the version selection
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
Labels: size/XS

#5548 perf: workflow code
  packages/global/core/workflow/runtime/type.d.ts
  packages/service/core/ai/llm/promptToolCall.ts
  packages/service/core/ai/llm/request.ts
  packages/service/core/workflow/dispatch/abandoned/runApp.ts
  packages/service/core/workflow/dispatch/ai/agent/index.ts
  packages/service/core/workflow/dispatch/ai/agent/toolCall.ts
  packages/service/core/workflow/dispatch/child/runApp.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/loop/runLoop.ts
  packages/service/core/workflow/dispatch/plugin/run.ts
  test/cases/service/core/ai/llm/toolCall.test.ts
Labels: size/L

#5550 Update teamMode.mdx
  document/content/docs/introduction/guide/admin/teamMode.mdx
Labels: size/XS

#5555 fix: extract node can not extract when using tool-calling-able model.
  packages/service/core/workflow/dispatch/ai/extract.ts
Labels: size/XS

#5551 Modified the weight calculation method when performing RRF merging
  .gitignore
  packages/global/core/dataset/search/utils.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/core/workflow/dispatch/dataset/concat.ts
Labels: size/M
