Repository labring/FastGPT, pull requests merged in 2025-04, with the labels that each got.

#4403 perf: introduce BullMQ for website sync
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  packages/global/core/dataset/api.d.ts
  packages/global/core/dataset/constants.ts
  packages/global/core/dataset/type.d.ts
  packages/service/common/bullmq/index.ts
  packages/service/common/bullmq/type.d.ts
  packages/service/common/redis/index.ts
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/collection/schema.ts
  packages/service/core/dataset/controller.ts
  packages/service/core/dataset/schema.ts
  packages/service/core/dataset/websiteSync.ts
  packages/service/package.json
  packages/web/components/common/Icon/icons/change.svg
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/dataset.json
  pnpm-lock.yaml
  projects/app/.env.template
  projects/app/src/instrumentation.ts
  projects/app/src/pageComponents/dataset/detail/CollectionCard/Context.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/EmptyCollectionTip.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/Header.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/WebsiteConfig.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/index.tsx
  projects/app/src/pages/api/core/dataset/detail.ts
  projects/app/src/pages/api/core/dataset/update.ts
  projects/app/src/web/core/dataset/constants.ts
  test/cases/pages/api/core/dataset/paths.test.ts
Labels: size/XXL

#4420 fix: clean up website dataset when updating chunk settings
  packages/service/core/dataset/controller.ts
  projects/app/src/pages/api/core/dataset/delete.ts
  projects/app/src/pages/api/core/dataset/update.ts
Labels: size/S

#4422 add chunk reader doc
  docSite/assets/imgs/chunkReader1.png
  docSite/assets/imgs/chunkReader2.jpg
  docSite/assets/imgs/chunkReader3.webp
  docSite/assets/imgs/chunkReader4.jpg
  docSite/assets/imgs/chunkReader5.jpg
  docSite/assets/imgs/chunkReader6.png
  docSite/assets/imgs/chunkReader7.jpg
  docSite/assets/imgs/chunkReader8.png
  docSite/assets/imgs/chunkReader9.jpg
  docSite/content/zh-cn/docs/guide/DialogBoxes/quoteList.md
Labels: size/M

#4424 Training status
  packages/global/core/dataset/type.d.ts
  packages/service/core/dataset/training/schema.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/check.svg
  packages/web/components/common/Icon/icons/common/maximize.svg
  packages/web/components/common/Icon/icons/common/running.svg
  packages/web/hooks/useScrollPagination.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/dataset.json
  projects/app/src/global/core/dataset/type.d.ts
  projects/app/src/pageComponents/app/list/List.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/TrainingStates.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/index.tsx
  projects/app/src/pageComponents/dataset/detail/DataCard.tsx
  projects/app/src/pages/api/core/dataset/collection/detail.ts
  projects/app/src/pages/api/core/dataset/collection/listV2.ts
  projects/app/src/pages/api/core/dataset/collection/trainingDetail.ts
  projects/app/src/pages/api/core/dataset/training/deleteTrainingData.ts
  projects/app/src/pages/api/core/dataset/training/getTrainingDataDetail.ts
  projects/app/src/pages/api/core/dataset/training/getTrainingError.ts
  projects/app/src/pages/api/core/dataset/training/updateTrainingData.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/service/events/generateQA.ts
  projects/app/src/service/events/generateVector.ts
  projects/app/src/web/core/dataset/api.ts
  projects/app/src/web/core/dataset/constants.ts
  test/cases/api/core/dataset/training/deleteTrainingData.test.ts
  test/cases/api/core/dataset/training/getTrainingDataDetail.test.ts
  test/cases/api/core/dataset/training/getTrainingError.test.ts
  test/cases/api/core/dataset/training/updateTrainingData.test.ts
Labels: size/XXL

#4402 feat: team permission refine
  package.json
  packages/global/support/permission/memberGroup/type.d.ts
  packages/global/support/permission/user/constant.ts
  packages/service/common/mongo/index.ts
  packages/service/support/permission/auth/org.ts
  packages/web/i18n/en/account_team.json
  packages/web/i18n/en/user.json
  packages/web/i18n/zh-CN/account_team.json
  packages/web/i18n/zh-CN/user.json
  packages/web/i18n/zh-Hant/account_team.json
  packages/web/i18n/zh-Hant/user.json
  projects/app/src/components/support/permission/MemberManager/context.tsx
  projects/app/src/pageComponents/account/team/PermissionManage/index.tsx
  projects/app/src/pages/api/admin/initv493.ts
  projects/app/src/pages/api/core/app/copy.ts
  projects/app/src/pages/api/core/app/create.ts
  projects/app/src/pages/api/core/app/folder/create.ts
  projects/app/src/pages/api/core/app/httpPlugin/create.ts
  projects/app/src/pages/api/core/app/update.ts
  projects/app/src/pages/api/core/dataset/create.ts
  projects/app/src/pages/api/core/dataset/folder/create.ts
  projects/app/src/pages/api/core/dataset/update.ts
  projects/app/src/pages/api/support/openapi/create.ts
  projects/app/test/api/core/app/create.test.ts
  projects/app/test/api/core/app/version/list.test.ts
  projects/app/test/api/core/dataset/collection/paths.test.ts
  projects/app/test/api/core/dataset/create.test.ts
  projects/app/test/api/core/dataset/paths.test.ts
  projects/app/test/api/support/openapi/create.test.ts
  projects/app/test/tsconfig.json
  test/datas/users.ts
  test/globalSetup.ts
  test/mocks/request.ts
  test/setup.ts
  test/setupModels.ts
  test/utils/request.ts
  vitest.config.mts
Labels: size/XXL

#4429 website sync feature
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  docSite/assets/imgs/sealos-redis1.png
  docSite/assets/imgs/sealos-redis2.png
  docSite/assets/imgs/sealos-redis3.png
  docSite/content/zh-cn/docs/development/upgrading/494.md
  packages/global/core/dataset/api.d.ts
  packages/global/core/dataset/constants.ts
  packages/global/core/dataset/type.d.ts
  packages/service/common/bullmq/index.ts
  packages/service/common/bullmq/type.d.ts
  packages/service/common/redis/index.ts
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/collection/schema.ts
  packages/service/core/dataset/controller.ts
  packages/service/core/dataset/schema.ts
  packages/service/core/dataset/websiteSync/index.ts
  packages/service/package.json
  packages/web/components/common/Icon/icons/change.svg
  packages/web/components/common/Input/NumberInput/index.tsx
  packages/web/components/common/Tag/index.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/dataset.json
  pnpm-lock.yaml
  projects/app/.env.template
  projects/app/src/instrumentation.ts
  projects/app/src/pageComponents/dataset/detail/CollectionCard/Context.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/EmptyCollectionTip.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/Header.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/WebsiteConfig.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/index.tsx
  projects/app/src/pageComponents/dataset/detail/Form/CollectionChunkForm.tsx
  projects/app/src/pageComponents/dataset/detail/Import/Context.tsx
  projects/app/src/pageComponents/dataset/detail/Import/commonProgress/DataProcess.tsx
  projects/app/src/pageComponents/dataset/detail/MetaDataCard.tsx
  projects/app/src/pages/api/admin/initv494.ts
  projects/app/src/pages/api/core/dataset/delete.ts
  projects/app/src/pages/api/core/dataset/detail.ts
  projects/app/src/pages/api/core/dataset/update.ts
  projects/app/src/web/core/dataset/constants.ts
  test/cases/pages/api/core/dataset/paths.test.ts
Labels: size/XXL

#4362 update:Mobile voice interaction
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/chat/backText.svg
  packages/web/i18n/en/chat.json
  packages/web/i18n/zh-CN/chat.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/chat.json
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/VoiceInput.tsx
  projects/app/src/web/common/hooks/useSpeech.ts
Labels: size/XXL

#4388 pro migration
  packages/global/common/system/types/index.d.ts
Labels: size/S

#4433 pro migration (#4388)
  packages/global/common/system/types/index.d.ts
Labels: size/S

#4434 fix: add connection timeout to database settings
  packages/plugins/src/databaseConnection/index.ts
  projects/app/src/pageComponents/app/list/List.tsx
Labels: size/S

#4432 perf: add Redis cache for vector counting
  packages/service/common/redis/index.ts
  packages/service/common/redis/type.d.ts
  packages/service/common/vectorStore/controller.ts
Labels: size/M

#4438 Test completion v2
  docSite/content/zh-cn/docs/development/openapi/chat.md
  packages/global/core/workflow/runtime/constants.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/utils.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/ChatContainer/type.d.ts
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/v2/chat/completions.ts
  projects/app/src/web/common/api/fetch.ts
Labels: size/XXL

#4426 feat: mongodb-log
  env.d.ts
  packages/service/common/mongo/index.ts
  packages/service/common/mongo/init.ts
  packages/service/common/mongo/type.d.ts
  packages/service/common/system/log/schema.ts
  packages/service/tsconfig.json
Labels: size/M

#4443 Test mongo log
  env.d.ts
  packages/global/core/ai/constants.ts
  packages/global/core/ai/type.d.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/service/common/mongo/index.ts
  packages/service/common/mongo/init.ts
  packages/service/common/mongo/type.d.ts
  packages/service/common/system/log/schema.ts
  packages/service/core/ai/utils.ts
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/agent/runTool/type.d.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/tsconfig.json
  packages/web/i18n/en/chat.json
  packages/web/i18n/zh-CN/chat.json
  packages/web/i18n/zh-Hant/chat.json
  projects/app/.env.template
  projects/app/src/components/core/ai/SettingLLMModel/index.tsx
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/instrumentation.ts
  projects/app/src/pages/api/admin/clearInvalidData.ts
  projects/app/src/pages/api/admin/initv47.ts
  projects/app/src/pages/api/admin/initv471.ts
  projects/app/src/pages/api/admin/initv4810.ts
  projects/app/src/pages/api/admin/initv4823.ts
  projects/app/src/pages/api/admin/initv486.ts
  projects/app/src/pages/api/admin/initv488.ts
  projects/app/src/pages/api/common/file/read.ts
  projects/app/src/pages/api/common/file/read/[filename].ts
  projects/app/src/pages/api/common/file/uploadImage.ts
  projects/app/src/pages/api/common/system/unlockTask.ts
  projects/app/src/pages/api/common/tools/urlFetch.ts
  projects/app/src/pages/api/core/ai/agent/createQuestionGuide.ts
  projects/app/src/pages/api/core/chat/feedback/adminUpdate.ts
  projects/app/src/pages/api/core/chat/feedback/closeCustom.ts
  projects/app/src/pages/api/core/chat/item/getSpeech.ts
  projects/app/src/pages/api/lafApi/[...path].ts
  projects/app/src/pages/api/proApi/[...path].ts
  projects/app/src/pages/api/support/user/account/updatePasswordByOld.ts
  projects/app/src/pages/api/support/user/team/limit/datasetSizeLimit.ts
  projects/app/src/pages/api/support/user/team/limit/webSyncLimit.ts
  projects/app/src/pages/api/system/img/[id].ts
  projects/app/src/pages/chat/share.tsx
  projects/app/src/service/mongo.ts
  test/setup.ts
Labels: size/L

#4444 fix external var ui
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
Labels: size/XS

#4445 Enhance GitHub Actions workflows security and permissions
  .github/workflows/docs-deploy-kubeconfig.yml
  .github/workflows/docs-deploy-vercel.yml
Labels: size/S

#4447 chore: security update
  .github/gh-bot.yml
  .github/workflows/docs-preview.yml
  .github/workflows/docs-sync_imgs.yml
  .github/workflows/fastgpt-build-image-personal.yml
  .github/workflows/fastgpt-build-image.yml
  .github/workflows/fastgpt-preview-image.yml
  .github/workflows/helm-release.yaml
  .github/workflows/sandbox-build-image.yml
Labels: size/L

#4453 更新 491.md
  docSite/content/zh-cn/docs/development/upgrading/491.md
Labels: size/XS

#4456 test
  .github/workflows/docs-deploy-kubeconfig.yml
  .github/workflows/docs-preview.yml
  .github/workflows/fastgpt-build-image-personal.yml
  .github/workflows/fastgpt-build-image.yml
  .github/workflows/fastgpt-preview-image.yml
Labels: size/M

#4458 fix: ts
  docSite/content/zh-cn/docs/development/openapi/chat.md
  docSite/content/zh-cn/docs/development/upgrading/494.md
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/context.tsx
  projects/app/src/pageComponents/app/detail/useChatTest.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
Labels: size/M

#4460 update doc
  .github/workflows/docs-preview.yml
  docSite/content/zh-cn/docs/intro.md
  packages/service/common/buffer/rawText/schema.ts
  packages/service/common/buffer/tts/schema.ts
  packages/service/common/file/gridfs/schema.ts
  packages/service/common/file/image/schema.ts
Labels: size/S

#4469 Updated the dynamic display of the voice input pop-up
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/VoiceInput.tsx
Labels: size/XS

#4471 Action test
  .github/sync_imgs.yml
  .github/workflows/docs-deploy-vercel.yml
  .github/workflows/docs-preview.yml
  docSite/content/zh-cn/docs/development/upgrading/494.md
  docSite/content/zh-cn/docs/intro.md
Labels: size/M

#4475 feat: Add docs deploy to cf
  .github/workflows/docs-deploy-cf.yml
Labels: size/M

#4478 Fix: log error when the loop input array is too long
  packages/service/core/workflow/dispatch/loop/runLoop.ts
Labels: size/XS

#4479 fix: Add patch for mdast-util-gfm-autolink-literal@2.0.1
  patches/mdast-util-gfm-autolink-literal@2.0.1.patch
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: size/S

#4485 fix: queue
  docSite/content/zh-cn/docs/development/upgrading/494.md
  packages/service/common/vectorStore/controller.ts
  projects/app/src/pageComponents/dataset/detail/Form/CollectionChunkForm.tsx
  projects/app/src/pageComponents/dataset/detail/Import/commonProgress/DataProcess.tsx
  projects/app/src/service/core/dataset/data/controller.ts
  projects/app/src/service/events/generateVector.ts
Labels: size/L

#4476 fix plus request
  packages/service/common/api/type.d.ts
  packages/service/core/chat/postTextCensor.ts
  packages/service/core/dataset/read.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/support/openapi/auth.ts
  packages/service/support/wallet/usage/controller.ts
  projects/app/src/service/common/system/index.ts
Labels: size/L

#4492 fix: package plus request
  docSite/content/zh-cn/docs/development/openapi/chat.md
  docSite/content/zh-cn/docs/development/upgrading/494.md
  packages/service/common/api/type.d.ts
  packages/service/common/system/constants.ts
  packages/service/core/chat/postTextCensor.ts
  packages/service/core/dataset/apiDataset/proApi.ts
  packages/service/core/dataset/read.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/support/openapi/auth.ts
  packages/service/support/wallet/usage/controller.ts
  packages/service/support/wallet/usage/utils.ts
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/dataset.json
  projects/app/src/pages/api/core/dataset/apiDataset/list.ts
  projects/app/src/pages/api/core/dataset/collection/read.ts
  projects/app/src/service/common/system/index.ts
  projects/app/src/service/core/dataset/apiDataset/controller.ts
  projects/app/src/web/core/dataset/api.ts
Labels: size/L

#4491 deps: bump pdfjs-dist to 4.10.38
  packages/service/package.json
  pnpm-lock.yaml
Labels: size/XS

#4493 4.9.4 doc
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  docSite/content/zh-cn/docs/development/upgrading/494.md
  pnpm-lock.yaml
Labels: size/M

#4498 feat: team permission refine (#4494)
  .github/workflows/fastgpt-test.yaml
  package.json
  packages/global/support/permission/collaborator.d.ts
  packages/global/support/permission/controller.ts
  packages/global/support/permission/memberGroup/type.d.ts
  packages/global/support/permission/user/constant.ts
  packages/global/support/permission/user/controller.ts
  packages/service/common/mongo/index.ts
  packages/service/support/permission/auth/org.ts
  packages/web/i18n/en/account_team.json
  packages/web/i18n/en/user.json
  packages/web/i18n/zh-CN/account_team.json
  packages/web/i18n/zh-CN/user.json
  packages/web/i18n/zh-Hant/account_team.json
  packages/web/i18n/zh-Hant/user.json
  pnpm-lock.yaml
  projects/app/src/components/support/permission/MemberManager/MemberItemCard.tsx
  projects/app/src/components/support/permission/MemberManager/MemberModal.tsx
  projects/app/src/components/support/permission/MemberManager/context.tsx
  projects/app/src/components/support/user/team/OrgTags/index.tsx
  projects/app/src/pageComponents/account/AccountContainer.tsx
  projects/app/src/pageComponents/account/team/PermissionManage/index.tsx
  projects/app/src/pageComponents/app/list/List.tsx
  projects/app/src/pages/api/core/app/copy.ts
  projects/app/src/pages/api/core/app/create.ts
  projects/app/src/pages/api/core/app/folder/create.ts
  projects/app/src/pages/api/core/app/httpPlugin/create.ts
  projects/app/src/pages/api/core/app/update.ts
  projects/app/src/pages/api/core/dataset/create.ts
  projects/app/src/pages/api/core/dataset/folder/create.ts
  projects/app/src/pages/api/core/dataset/update.ts
  projects/app/src/pages/api/support/openapi/create.ts
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/test/api/core/app/create.test.ts
  projects/app/test/api/core/app/version/list.test.ts
  projects/app/test/api/core/dataset/collection/paths.test.ts
  projects/app/test/api/core/dataset/create.test.ts
  projects/app/test/api/core/dataset/paths.test.ts
  projects/app/test/api/support/openapi/create.test.ts
  projects/app/test/tsconfig.json
  test/cases/service/core/app/workflow/loopTest.json
  test/cases/service/core/app/workflow/simple.json
  test/cases/service/core/app/workflow/workflowDispatch.test.ts
  test/datas/users.ts
  test/globalSetup.ts
  test/mocks/request.ts
  test/setup.ts
  test/setupModels.ts
  test/utils/request.ts
  vitest.config.mts
Labels: size/XXL

#4497 fix: password check
  docSite/content/zh-cn/docs/development/upgrading/495.md
  pnpm-lock.yaml
  projects/app/src/pageComponents/account/info/UpdatePswModal.tsx
  projects/app/src/pageComponents/login/ForgetPasswordForm.tsx
  projects/app/src/pageComponents/login/RegisterForm.tsx
  projects/app/src/pages/api/admin/initv495.ts
  projects/app/src/web/support/user/login/constants.ts
  test/cases/global/common/string/utils.test.ts
Labels: size/L

#4506 fix share page dataset search show
  packages/global/core/chat/utils.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/service/core/workflow/dispatch/index.ts
  projects/app/src/pages/api/v2/chat/completions.ts
Labels: size/S

#4452 add app submenu
  packages/global/core/app/constants.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/app.svg
  packages/web/hooks/useResizable.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/Layout/navbar.tsx
  projects/app/src/components/Layout/navbarPhone.tsx
  projects/app/src/pageComponents/app/list/CreateModal.tsx
  projects/app/src/pageComponents/app/list/PluginList.tsx
  projects/app/src/pageComponents/app/list/Sidebar.tsx
  projects/app/src/pageComponents/app/list/TemplateList.tsx
  projects/app/src/pageComponents/app/list/TemplateMarketModal.tsx
  projects/app/src/pageComponents/app/list/context.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/pages/toolkit/index.tsx
Labels: size/XXL

#4507 Update zh-Hant Traditional Chinese i18n translation
  packages/web/i18n/zh-Hant/account.json
  packages/web/i18n/zh-Hant/account_bill.json
  packages/web/i18n/zh-Hant/account_info.json
  packages/web/i18n/zh-Hant/account_inform.json
  packages/web/i18n/zh-Hant/account_model.json
  packages/web/i18n/zh-Hant/account_promotion.json
  packages/web/i18n/zh-Hant/account_setting.json
  packages/web/i18n/zh-Hant/account_team.json
  packages/web/i18n/zh-Hant/account_thirdParty.json
  packages/web/i18n/zh-Hant/account_usage.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/chat.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/dataset.json
  packages/web/i18n/zh-Hant/login.json
  packages/web/i18n/zh-Hant/user.json
  packages/web/i18n/zh-Hant/workflow.json
Labels: size/L

#4508 fix: downgrade md lib
  package.json
  patches/mdast-util-gfm-autolink-literal@2.0.1.patch
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: size/M

#4503 Support nested node interaction
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/global/core/workflow/template/system/interactive/type.d.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/interactive/formInput.ts
  packages/service/core/workflow/dispatch/interactive/userSelect.ts
  packages/service/core/workflow/dispatch/plugin/runApp.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/utils.ts
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderDebug/NodeDebugResponse.tsx
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/api/v2/chat/completions.ts
Labels: size/L

#4509 Test interactive
  docSite/content/zh-cn/docs/development/upgrading/495.md
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/global/core/workflow/template/system/interactive/type.d.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/interactive/formInput.ts
  packages/service/core/workflow/dispatch/interactive/userSelect.ts
  packages/service/core/workflow/dispatch/plugin/runApp.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/utils.ts
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderDebug/NodeDebugResponse.tsx
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/api/v2/chat/completions.ts
Labels: size/L

#4519 Test log
  packages/global/support/operationLog/constants.ts
  packages/global/support/operationLog/type.d.ts
  packages/global/support/permission/user/controller.ts
  packages/service/support/operationLog/addOperationLog.ts
  packages/service/support/operationLog/constants.ts
  packages/service/support/operationLog/schema.ts
  packages/service/support/user/utils.ts
  packages/web/i18n/en/account_team.json
  packages/web/i18n/zh-CN/account_team.json
  packages/web/i18n/zh-Hant/account_team.json
  projects/app/src/pageComponents/account/team/MemberTable.tsx
  projects/app/src/pageComponents/account/team/OperationLog/index.tsx
  projects/app/src/pages/account/team/index.tsx
  projects/app/src/pages/api/support/user/account/loginByPassword.ts
  projects/app/src/web/support/user/team/operantionLog/api.ts
Labels: size/L

#4450 Add oceanbase-version docker-compose.yml & Update deployment documents
  deploy/docker/docker-compose-oceanbase/docker-compose.yml
  deploy/docker/docker-compose-oceanbase/init.sql
  docSite/content/zh-cn/docs/development/docker.md
Labels: size/L

#4520 V4.9.5 feature
  README.md
  docSite/content/zh-cn/docs/development/upgrading/495.md
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/global/core/workflow/template/system/interactive/type.d.ts
  packages/global/support/operationLog/constants.ts
  packages/global/support/operationLog/type.d.ts
  packages/global/support/permission/user/controller.ts
  packages/service/core/chat/saveChat.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/interactive/formInput.ts
  packages/service/core/workflow/dispatch/interactive/userSelect.ts
  packages/service/core/workflow/dispatch/plugin/runApp.ts
  packages/service/support/operationLog/addOperationLog.ts
  packages/service/support/operationLog/constants.ts
  packages/service/support/operationLog/schema.ts
  packages/service/support/user/utils.ts
  packages/web/i18n/en/account_team.json
  packages/web/i18n/zh-CN/account_team.json
  packages/web/i18n/zh-Hant/account_team.json
  projects/app/src/components/core/chat/ChatContainer/ChatBox/utils.ts
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/pageComponents/account/team/MemberTable.tsx
  projects/app/src/pageComponents/account/team/OperationLog/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderDebug/NodeDebugResponse.tsx
  projects/app/src/pages/account/team/index.tsx
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/core/workflow/debug.ts
  projects/app/src/pages/api/support/user/account/loginByPassword.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/api/v2/chat/completions.ts
  projects/app/src/service/events/generateQA.ts
  projects/app/src/service/events/generateVector.ts
  projects/app/src/web/support/user/team/operantionLog/api.ts
Labels: size/XL

#4440 feat: 表单组件增加多选
  packages/global/core/workflow/node/constant.ts
  packages/web/components/common/MySelect/MultipleSelect.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/core/chat/components/Interactive/InteractiveComponents.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeFormInput/InputFormEditModal.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SelectMulti.tsx
Labels: size/L

#4527 feat: workflow input node add selectMulti; MultipleSelect component
  packages/global/core/workflow/node/constant.ts
  packages/web/components/common/MySelect/MultipleSelect.tsx
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh-CN/workflow.json
  packages/web/i18n/zh-Hant/workflow.json
  projects/app/src/components/core/chat/components/Interactive/InteractiveComponents.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeFormInput/InputFormEditModal.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SelectMulti.tsx
Labels: size/L

#4529 fix chat test response detail
  projects/app/src/pages/api/core/chat/chatTest.ts
Labels: size/XS

#4530 feat: github workflow arm runner
  .github/workflows/fastgpt-build-image.yml
  .github/workflows/sandbox-build-image.yml
Labels: size/L

#4533 update Log
  projects/app/src/pageComponents/account/team/OperationLog/index.tsx
  projects/app/src/web/support/user/team/operantionLog/api.ts
Labels: size/L

#4540 add system model
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  docSite/content/zh-cn/docs/development/upgrading/495.md
  packages/service/core/ai/config/provider/Gemini.json
  packages/service/core/ai/config/provider/Grok.json
  packages/service/core/ai/config/provider/OpenAI.json
Labels: size/L

#4535 fix: image source
  .github/workflows/fastgpt-build-image.yml
  .github/workflows/sandbox-build-image.yml
Labels: size/XS

#4542 test: add opreationLog mock
  projects/app/test/api/core/app/create.test.ts
  test/datas/users.ts
  test/mocks/index.ts
Labels: size/S

#4464 feat: python sandbox execute with a temporary file
  projects/sandbox/src/sandbox/constants.ts
  projects/sandbox/src/sandbox/utils.ts
Labels: size/M

#4523 变量更新组件处理字符串数组错误修复
  packages/service/core/workflow/dispatch/utils.ts
Labels: size/L

#4547 Test sandbox
  projects/README.md
  projects/sandbox/src/sandbox/constants.ts
  projects/sandbox/src/sandbox/utils.ts
Labels: size/M

#4553 fix: update workflow to use ubuntu-24.04 for consistency across all jobs
  .github/workflows/docs-deploy-cf.yml
  .github/workflows/docs-deploy-kubeconfig.yml
  .github/workflows/docs-preview.yml
  .github/workflows/fastgpt-build-image-personal.yml
  .github/workflows/fastgpt-preview-image.yml
  .github/workflows/helm-release.yaml
Labels: size/S

#4550 docs: team&roles&permissions and intro
  docSite/assets/imgs/ability1.png
  docSite/assets/imgs/ability2.png
  docSite/assets/imgs/ability3.png
  docSite/assets/imgs/ability4.png
  docSite/assets/imgs/ability5.png
  docSite/assets/imgs/guide/team_permissions/team_roles_permissions/image1.jpeg
  docSite/assets/imgs/guide/team_permissions/team_roles_permissions/image2.png
  docSite/assets/imgs/guide/team_permissions/team_roles_permissions/image3.png
  docSite/assets/imgs/guide/team_permissions/team_roles_permissions/image4.png
  docSite/assets/imgs/guide/team_permissions/team_roles_permissions/image5.png
  docSite/assets/imgs/intro/image1.png
  docSite/assets/imgs/intro/image2.png
  docSite/assets/imgs/intro/image3.png
  docSite/assets/imgs/intro/image4.png
  docSite/assets/imgs/intro/image5.png
  docSite/assets/imgs/intro/image6.png
  docSite/assets/imgs/intro/image7.png
  docSite/assets/imgs/intro/image8.png
  docSite/assets/imgs/intro1.webp
  docSite/assets/imgs/intro2.png
  docSite/assets/imgs/intro3.png
  docSite/assets/imgs/intro4.png
  docSite/content/zh-cn/docs/guide/team_permissions/team_roles_permissions.md
  docSite/content/zh-cn/docs/intro.md
Labels: size/L

#4548 test: concurrent test
  test/setup.ts
  vitest.config.mts
Labels: size/S

#4556 perf: path selector
  .github/workflows/fastgpt-preview-image.yml
  docSite/content/zh-cn/docs/development/upgrading/496.md
  projects/app/src/components/common/folder/Path.tsx
  projects/app/src/pageComponents/dashboard/apps/CreateModal.tsx
  projects/app/src/pageComponents/dataset/detail/Import/diffSource/APIDataset.tsx
  projects/app/src/pages/dashboard/apps/index.tsx
Labels: size/M

#4557 perf: add image endpoint to dataset search
  .github/workflows/fastgpt-preview-image.yml
  docSite/content/zh-cn/docs/development/upgrading/496.md
  packages/service/common/file/image/utils.ts
  packages/service/core/chat/utils.ts
  packages/service/core/workflow/dispatch/dataset/search.ts
Labels: size/M

#4549 integrate mcp
  packages/global/core/app/constants.ts
  packages/global/core/app/mcpTools/utils.ts
  packages/global/core/app/type.d.ts
  packages/global/core/app/utils.ts
  packages/global/core/workflow/node/constant.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/global/core/workflow/template/constants.ts
  packages/global/core/workflow/template/system/runTool.ts
  packages/global/core/workflow/template/system/runToolSet.ts
  packages/global/core/workflow/utils.ts
  packages/service/core/app/plugin/controller.ts
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/service/core/workflow/dispatch/agent/runTool/utils.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/plugin/runTool.ts
  packages/service/package.json
  packages/web/components/common/Icon/button.tsx
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/detail.svg
  packages/web/components/common/Icon/icons/core/app/type/mcpTools.svg
  packages/web/components/common/Icon/icons/core/app/type/mcpToolsFill.svg
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/workflow.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/workflow.json
  pnpm-lock.yaml
  projects/app/src/components/core/chat/ChatContainer/ChatBox/hooks/useChatBox.tsx
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/AppCard.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/Edit.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/EditForm.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/Header.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/index.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/components/ToolSelect.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/components/ToolSelectModal.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeTool.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeToolSet.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pageComponents/dashboard/apps/List.tsx
  projects/app/src/pageComponents/dashboard/apps/MCPToolsEditModal.tsx
  projects/app/src/pageComponents/dashboard/apps/TypeTag.tsx
  projects/app/src/pages/api/core/app/mcpTools/create.ts
  projects/app/src/pages/api/core/app/mcpTools/getMCPTools.ts
  projects/app/src/pages/api/core/app/mcpTools/runTest.ts
  projects/app/src/pages/api/core/app/mcpTools/update.ts
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/app/detail/index.tsx
  projects/app/src/pages/dashboard/apps/index.tsx
  projects/app/src/web/core/app/api/plugin.ts
Labels: size/XXL

#4563 fix mcp integrate
  packages/global/core/app/mcpTools/utils.ts
  packages/service/core/workflow/dispatch/agent/runTool/utils.ts
  projects/app/src/pageComponents/app/detail/MCPTools/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/EditForm.tsx
  projects/app/src/pageComponents/dashboard/apps/MCPToolsEditModal.tsx
Labels: size/M

#4564 fix mcp tools avatar
  packages/global/core/app/mcpTools/utils.ts
  packages/global/core/app/type.d.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/service/core/workflow/dispatch/abandoned/runApp.ts
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/service/core/workflow/dispatch/agent/runTool/utils.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/loop/runLoop.ts
  packages/service/core/workflow/dispatch/plugin/run.ts
  packages/service/core/workflow/dispatch/plugin/runApp.ts
  packages/service/core/workflow/dispatch/plugin/runTool.ts
  packages/service/core/workflow/dispatch/utils.ts
  projects/app/src/pageComponents/app/detail/SimpleApp/components/ToolSelect.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderDebug/NodeDebugResponse.tsx
  projects/app/src/pages/api/core/app/mcpTools/create.ts
  projects/app/src/pages/api/core/app/mcpTools/update.ts
  projects/app/src/pages/api/core/app/update.ts
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/support/mcp/server/toolCall.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/api/v2/chat/completions.ts
  projects/app/src/service/core/app/utils.ts
Labels: size/L

#4566 V4.9.6 dev
  .github/workflows/mcp_server-build-image.yml
  docSite/content/zh-cn/docs/development/upgrading/496.md
Labels: size/XS

#4569 Fix: mcp_server build
  docSite/content/zh-cn/docs/development/upgrading/496.md
  projects/mcp_server/Dockerfile
  projects/mcp_server/package.json
Labels: size/S

#4570 fix: mcp_server docker file
  projects/mcp_server/Dockerfile
Labels: size/XS

#4562 Updated package.json to add js-yaml dependencies and configure husky hooks to generate documentation; New llms-full.txt
  docSite/content/zh-cn/docs/development/custom-models/ollama.md
  docSite/static/js/doc-generate-llms.js
  docSite/static/llms-full.txt
  docSite/static/llms.txt
  package.json
  pnpm-lock.yaml
Labels: size/XXL

#4575 fix: llms encode
  docSite/doc-generate-llms.js
Labels: size/XS

#4576 fix: tool call history
  docSite/content/zh-cn/docs/development/upgrading/496.md
  packages/service/core/ai/config/provider/OpenAI.json
  packages/service/core/chat/utils.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
Labels: size/L

#4577 Update doc images
  docSite/content/zh-cn/docs/guide/dashboard/workflow/document_parsing.md
  docSite/content/zh-cn/docs/guide/dashboard/workflow/tool.md
  docSite/static/llms-full.txt
  llms-full.txt
  llms.txt
Labels: size/XXL

#4583 Fixed: Updated the iframe allow property in the SelectUsingWayModal
  projects/app/src/pageComponents/app/detail/Publish/Link/SelectUsingWayModal.tsx
Labels: size/XS

#4580 fix: ob docker compose file
  deploy/docker/docker-compose-oceanbase/docker-compose.yml
Labels: size/S

#4584 perf: text splitter
  docSite/content/zh-cn/docs/development/upgrading/496.md
  packages/global/common/string/textSplitter.ts
  packages/global/common/string/utils.ts
  projects/app/src/pageComponents/dataset/detail/DataCard.tsx
  projects/app/src/service/core/dataset/data/controller.ts
  test/cases/function/packages/global/common/string/chunks.json
  test/cases/function/packages/global/common/string/textSplitter.test.ts
Labels: size/XL

#4585 doc: mcp tools
  docSite/assets/imgs/mcp_tools1.PNG
  docSite/assets/imgs/mcp_tools3.PNG
  docSite/assets/imgs/mcp_tools4.png
  docSite/assets/imgs/mcp_tools5.png
  docSite/assets/imgs/mcp_tools6.png
  docSite/assets/imgs/mcp_tools7.png
  docSite/assets/imgs/mcp_tools8.png
  docSite/content/zh-cn/docs/guide/dashboard/mcp_tools.md
Labels: size/M

#4586 update package version
  deploy/docker/docker-compose-pgvector.yml
  packages/service/common/api/type.d.ts
  packages/service/support/openapi/auth.ts
  projects/app/package.json
  projects/app/src/service/common/system/constants.ts
  projects/app/src/service/common/system/index.ts
  projects/app/src/service/core/app/utils.ts
Labels: size/S

#4587 Update yml
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-oceanbase/docker-compose.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  docSite/content/zh-cn/docs/development/docker.md
Labels: size/L

#4589 update doc
  docSite/content/zh-cn/docs/development/upgrading/496.md
Labels: size/M

#4591 perf: doc2x parse
  docSite/content/zh-cn/docs/development/upgrading/497.md
  packages/global/common/error/utils.ts
  packages/service/common/file/read/utils.ts
  packages/service/thirdProvider/doc2x/index.ts
Labels: size/L

#4593 Llms 1
  docSite/Dockerfile
  docSite/nginx.conf
Labels: size/M

#4594 fix: mongodb file oversize 160MB
  docSite/content/zh-cn/docs/development/upgrading/497.md
  packages/service/common/file/gridfs/controller.ts
  projects/app/src/pageComponents/dataset/detail/Import/components/FileSelector.tsx
  projects/app/src/pageComponents/dataset/detail/Import/components/RenderFiles.tsx
Labels: size/L

#4596 perf: hnsw query
  docSite/content/zh-cn/docs/development/upgrading/497.md
  packages/service/common/vectorStore/pg/class.ts
Labels: size/S

#4604 fix: timezone count
  docSite/content/zh-cn/docs/development/upgrading/497.md
  packages/global/common/time/timezone.ts
  packages/global/support/wallet/usage/api.d.ts
  packages/service/core/ai/config.ts
  packages/service/core/ai/config/utils.ts
  packages/web/components/common/MySelect/TimezoneSelect.tsx
  projects/app/src/pageComponents/account/usage/Dashboard.tsx
  projects/app/src/pageComponents/account/usage/UsageTable.tsx
  projects/app/src/pages/account/usage/index.tsx
  projects/app/src/service/common/system/index.ts
Labels: size/L

#4605 fix: action
  .github/workflows/docs-sync_imgs.yml
Labels: size/XS

#4606 Update mcp_server.md
  docSite/content/zh-cn/docs/guide/dashboard/mcp_server.md
Labels: size/XS

#4610 perf: init model
  docSite/content/zh-cn/docs/development/upgrading/497.md
  packages/service/common/system/log.ts
  packages/service/core/ai/config.ts
  packages/service/core/ai/config/utils.ts
  packages/service/core/ai/model.ts
  packages/web/components/common/Input/NumberInput/index.tsx
  packages/web/i18n/en/account_model.json
  packages/web/i18n/zh-CN/account_model.json
  packages/web/i18n/zh-Hant/account_model.json
  projects/app/src/pageComponents/account/model/AddModelBox.tsx
  projects/app/src/pages/api/core/ai/model/test.ts
Labels: size/L

#4600 修复表单单选选中长文本时，文字溢出选择框的问题；修复表单单选下拉选项在移动端界面上触发自动换行时部分文字位于屏幕之外的问题
  packages/web/components/common/MySelect/index.tsx
Labels: size/XS

#4611 Test select
  packages/web/components/common/MySelect/index.tsx
Labels: size/S

#4612 docs: sso oauth2.0 standard doc
  docSite/content/zh-cn/docs/guide/admin/sso.md
Labels: size/L

#4631 fix 4.9.6
  docSite/content/zh-cn/docs/development/upgrading/497.md
  packages/service/core/workflow/dispatch/agent/extract.ts
  packages/web/components/common/Textarea/PromptEditor/utils.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-Hant/app.json
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/QuoteList.tsx
  projects/app/src/pageComponents/chat/ChatQuoteList/QuoteItem.tsx
  projects/app/src/pages/api/core/app/exportChatLogs.ts
Labels: size/M

#4634 auto layout
  docSite/content/zh-cn/docs/development/upgrading/497.md
  packages/service/core/workflow/dispatch/index.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/alignLeft.svg
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh-CN/workflow.json
  packages/web/i18n/zh-Hant/workflow.json
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/components/ContextMenu.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/context/workflowStatusContext.tsx
Labels: size/XL

#4644 fix: share link quote cannot hideen
  docSite/content/zh-cn/docs/development/upgrading/497.md
  packages/global/core/chat/utils.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/service/core/workflow/dispatch/index.ts
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/api/v2/chat/completions.ts
Labels: size/M

#4645 Add workflow run duration；Get audio duration
  docSite/content/zh-cn/docs/development/upgrading/497.md
  packages/global/core/chat/type.d.ts
  packages/global/core/workflow/runtime/constants.ts
  packages/service/core/ai/audio/transcriptions.ts
  packages/service/core/chat/chatItemSchema.ts
  packages/service/core/chat/saveChat.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/type.d.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ResponseTags.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/ChatContainer/type.d.ts
  projects/app/src/global/core/chat/utils.ts
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/core/chat/getPaginationRecords.ts
  projects/app/src/pages/api/support/mcp/server/toolCall.ts
  projects/app/src/pages/api/v1/audio/transcriptions.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/api/v2/chat/completions.ts
  projects/app/src/service/core/app/utils.ts
  projects/app/src/web/common/api/fetch.ts
  projects/app/src/web/common/hooks/useSpeech.ts
  test/cases/global/core/chat/utils.test.ts
Labels: size/XL

#4649 Custom config path
  docSite/content/zh-cn/docs/development/upgrading/497.md
  env.d.ts
  projects/app/.env.template
  projects/app/src/service/common/system/index.ts
Labels: size/M

#3964 api调用场景下，如果大量调用带有图片或视频，产生的聊天记录会导致后台mongo数据库异常
  packages/service/core/chat/saveChat.ts
  projects/app/src/pages/api/v1/chat/completions.ts
Labels: size/XS

#4647 update operationLog
  packages/global/support/operationLog/constants.ts
  packages/global/support/wallet/sub/type.d.ts
  packages/service/support/operationLog/constants.ts
  packages/web/i18n/en/account_team.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/account_team.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/account_team.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/support/wallet/StandardPlanContentList.tsx
  projects/app/src/pageComponents/account/team/OperationLog/index.tsx
  projects/app/src/pages/account/team/index.tsx
Labels: size/L

#4655 refresh concat when update
  packages/service/common/system/timerLock/utils.ts
  projects/app/src/components/support/user/inform/UpdateContactModal.tsx
  projects/app/src/pageComponents/account/team/EditInfoModal.tsx
Labels: size/M

#4650 support mcp client streamable http
  packages/global/package.json
  packages/global/tsconfig.json
  packages/service/core/app/mcp.ts
  packages/service/core/workflow/dispatch/plugin/runTool.ts
  packages/service/package.json
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/src/pageComponents/app/detail/MCPTools/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/EditForm.tsx
  projects/app/src/pageComponents/dashboard/apps/MCPToolsEditModal.tsx
  projects/app/src/pages/api/core/app/mcpTools/create.ts
  projects/app/src/pages/api/core/app/mcpTools/getMCPTools.ts
  projects/app/src/pages/api/core/app/mcpTools/runTest.ts
  projects/app/src/pages/api/support/mcp/client/getTools.ts
  projects/app/src/pages/api/support/mcp/client/runTool.ts
  projects/app/src/web/core/app/api/plugin.ts
Labels: size/L

#4658 add answer quote number
  packages/global/core/ai/prompt/AIChat.ts
  packages/global/core/workflow/template/system/aiChat/index.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/Markdown/A.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/QuoteList.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SettingQuotePrompt.tsx
Labels: size/L

#4665 Fix: pay error
  projects/app/src/components/support/wallet/QRCodePayModal.tsx
Labels: size/XS

#4666 fix quote number
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/Markdown/A.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ResponseTags.tsx
  projects/app/src/web/common/utils/eventbus.ts
Labels: size/L

#4671 feat: get tokens from api usage
  docSite/content/zh-cn/docs/development/upgrading/497.md
  packages/global/core/ai/constants.ts
  packages/global/core/ai/type.d.ts
  packages/global/core/chat/utils.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/service/core/ai/config.ts
  packages/service/core/ai/functions/createQuestionGuide.ts
  packages/service/core/ai/functions/queryExtension.ts
  packages/service/core/ai/utils.ts
  packages/service/core/workflow/dispatch/agent/classifyQuestion.ts
  packages/service/core/workflow/dispatch/agent/extract.ts
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/agent/runTool/type.d.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/web/i18n/en/chat.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/chat.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/chat.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/pages/api/core/ai/model/test.ts
  projects/app/src/service/events/generateQA.ts
Labels: size/L

#4674 fix rerank model undefined
  packages/service/core/workflow/dispatch/dataset/search.ts
Labels: size/XS

#4676 更新Oceanbase镜像版本；修复容器部署时在healthcheck中出现的问题
  deploy/docker/docker-compose-oceanbase/docker-compose.yml
Labels: size/XS

#4673 fix same tag in different datasets
  docSite/content/zh-cn/docs/development/upgrading/497.md
  packages/service/core/dataset/search/controller.ts
Labels: size/M

#4680 fix same tag in different datasets (#4673)
  docSite/content/zh-cn/docs/development/upgrading/497.md
  packages/service/core/dataset/search/controller.ts
Labels: size/M

#4679 fix: chat quote number
  packages/global/core/ai/prompt/AIChat.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  projects/app/src/components/Markdown/A.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SettingQuotePrompt.tsx
  projects/app/src/pageComponents/chat/ChatQuoteList/CollectionQuoteReader.tsx
  projects/app/src/web/core/chat/context/chatItemContext.tsx
Labels: size/L

#4683 perf: Add tool call prompt
  packages/global/core/ai/prompt/dataset.ts
  packages/service/core/workflow/dispatch/dataset/search.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/Markdown/A.tsx
Labels: size/M

#4678 Short-chain burying
  packages/global/support/user/login/api.d.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-Hant/app.json
  projects/app/src/pageComponents/dashboard/apps/JsonImportModal.tsx
  projects/app/src/pages/api/core/app/create.ts
  projects/app/src/pages/api/core/app/fetchWorkflow.ts
  projects/app/src/pages/dashboard/apps/index.tsx
  projects/app/src/pages/login/index.tsx
  projects/app/src/web/context/useInitApp.ts
  projects/app/src/web/core/app/api/app.ts
Labels: size/L

#4686 Test shorurl
  packages/global/support/marketing/type.d.ts
  packages/global/support/user/login/api.d.ts
  packages/service/common/middle/tracks/utils.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-Hant/app.json
  projects/app/src/pageComponents/dashboard/apps/JsonImportModal.tsx
  projects/app/src/pageComponents/login/LoginForm/FormLayout.tsx
  projects/app/src/pageComponents/login/RegisterForm.tsx
  projects/app/src/pages/api/core/app/create.ts
  projects/app/src/pages/api/core/app/fetchWorkflow.ts
  projects/app/src/pages/dashboard/apps/index.tsx
  projects/app/src/pages/login/index.tsx
  projects/app/src/pages/login/provider.tsx
  projects/app/src/web/context/useInitApp.ts
  projects/app/src/web/core/app/api/app.ts
  projects/app/src/web/support/marketing/utils.ts
Labels: size/L

#4687 perf: fetch url
  packages/web/i18n/en/app.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-Hant/app.json
  projects/app/src/pageComponents/dashboard/apps/JsonImportModal.tsx
  projects/app/src/pages/api/core/app/fetchWorkflow.ts
  projects/app/src/pages/api/support/marketing/fetchWorkflow.ts
  projects/app/src/web/context/useInitApp.ts
  projects/app/src/web/core/app/api/app.ts
  projects/app/src/web/support/marketing/api.ts
Labels: size/L

#4690 fix share link chat quote number
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/pageComponents/app/detail/Logs/DetailLogsModal.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/ChatTest.tsx
  projects/app/src/pages/api/core/app/httpPlugin/create.ts
  projects/app/src/pages/api/core/app/mcpTools/create.ts
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/web/core/chat/context/chatItemContext.tsx
Labels: size/M

#4691 perf: add outlink usage
  docSite/content/zh-cn/docs/development/upgrading/497.md
  docSite/content/zh-cn/docs/use-cases/external-integration/dingtalk.md
  docSite/content/zh-cn/docs/use-cases/external-integration/feishu.md
  docSite/content/zh-cn/docs/use-cases/external-integration/official_account.md
  packages/global/core/ai/provider.ts
  packages/service/core/ai/config/provider/jina.json
  packages/service/support/outLink/tools.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/model/jina.svg
Labels: size/M

#4692 update version
  projects/app/package.json
Labels: size/XS

#4693 update 4.9.7 doc
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-oceanbase/docker-compose.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  docSite/content/zh-cn/docs/development/upgrading/497.md
  docSite/content/zh-cn/docs/development/upgrading/498.md
Labels: size/M

#4695 feat: streamable http mcp
  packages/service/package.json
  packages/web/i18n/en/dashboard_mcp.json
  packages/web/i18n/zh-CN/dashboard_mcp.json
  packages/web/i18n/zh-Hant/dashboard_mcp.json
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/src/pageComponents/dashboard/Container.tsx
  projects/app/src/pageComponents/dashboard/mcp/usageWay.tsx
  projects/app/src/pages/api/mcp/app/[key]/mcp.ts
  projects/app/src/pages/api/support/mcp/server/toolCall.ts
  projects/app/src/pages/api/support/mcp/server/toolList.ts
  projects/app/src/service/support/mcp/type.d.ts
  projects/app/src/service/support/mcp/utils.ts
  projects/mcp_server/package.json
  test/cases/pages/api/support/mcp/server/toolList.test.ts
Labels: size/XL

#4694 url params filter logic
  projects/app/src/components/Markdown/A.tsx
  projects/app/src/web/context/useInitApp.ts
Labels: size/M

#4697 Update doc
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-oceanbase/docker-compose.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  docSite/content/zh-cn/docs/development/upgrading/497.md
  packages/web/i18n/en/chat.json
  packages/web/i18n/zh-CN/chat.json
  packages/web/i18n/zh-Hant/chat.json
  projects/app/src/pages/chat/share.tsx
Labels: size/M

#4700 fix chat log list api
  packages/web/i18n/en/chat.json
  packages/web/i18n/zh-CN/chat.json
  packages/web/i18n/zh-Hant/chat.json
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/pages/api/core/app/getChatLogs.ts
Labels: size/L

#4704 perf: chat log list
  docSite/content/zh-cn/docs/development/upgrading/498.md
  projects/app/src/pageComponents/dashboard/apps/JsonImportModal.tsx
  projects/app/src/pages/api/core/app/getChatLogs.ts
  projects/app/src/web/context/useInitApp.ts
Labels: size/L

#4707 perf: Add Redis Health Check
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
Labels: size/S

#4714 fix: app/dataset list peredit bug
  projects/app/src/pageComponents/dashboard/apps/List.tsx
  projects/app/src/pageComponents/dataset/list/List.tsx
Labels: size/S

#4715 Feat: Quote auth
  docSite/content/zh-cn/docs/development/upgrading/498.md
  packages/service/core/ai/config/provider/Qwen.json
  packages/service/core/ai/config/utils.ts
  packages/web/i18n/en/common.json
  projects/app/src/components/Markdown/A.tsx
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/components/Markdown/utils.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Provider.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderOutput.tsx
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/pageComponents/account/model/AddModelBox.tsx
  projects/app/src/pages/api/core/chat/quote/getQuote.ts
  projects/app/src/pages/api/core/dataset/data/getQuoteData.ts
  projects/app/src/service/support/permission/auth/chat.ts
  projects/app/src/web/core/dataset/api.ts
Labels: size/L

#4721 Add test
  projects/app/src/service/support/permission/auth/chat.ts
  test/cases/components/Markdown/utils.test.ts
  test/cases/service/support/permission/auth/chat.test.ts
Labels: size/L

#4720 chat completion add parsequote param
  packages/global/core/ai/prompt/AIChat.ts
  packages/global/core/ai/prompt/dataset.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/core/workflow/dispatch/dataset/search.ts
  packages/service/core/workflow/dispatch/index.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/api/v2/chat/completions.ts
  projects/app/src/web/common/api/fetch.ts
Labels: size/M

#4724 Remove quote prompt in api request
  packages/global/core/ai/prompt/AIChat.ts
  packages/global/core/ai/prompt/dataset.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/core/workflow/dispatch/dataset/search.ts
  packages/service/core/workflow/dispatch/index.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/api/v2/chat/completions.ts
  projects/app/src/web/common/api/fetch.ts
Labels: size/M

#4725 Update doc
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-oceanbase/docker-compose.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  docSite/content/zh-cn/docs/development/upgrading/497.md
  projects/app/src/pageComponents/account/model/AddModelBox.tsx
Labels: size/M

#4726 perf: init token worker
  packages/service/worker/preload.ts
  packages/service/worker/utils.ts
  projects/app/src/service/common/system/index.ts
Labels: size/M

#4727 add quote response filter
  packages/global/core/ai/prompt/AIChat.ts
  packages/global/core/ai/prompt/dataset.ts
  packages/service/core/ai/utils.test.ts
  packages/service/core/ai/utils.ts
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/core/workflow/dispatch/dataset/search.ts
  projects/app/src/components/Markdown/A.tsx
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/web/common/api/fetch.ts
Labels: size/L

#4734 fix: app/dataset list folders' side menu permission bug
  projects/app/src/pages/dashboard/apps/index.tsx
  projects/app/src/pages/dataset/list/index.tsx
Labels: size/M

#4737 Test parse cite and add tool call parallel
  docSite/content/zh-cn/docs/development/upgrading/498.md
  docSite/content/zh-cn/docs/use-cases/app-cases/lab_appointment.md
  packages/global/common/string/password.ts
  packages/global/core/ai/prompt/AIChat.ts
  packages/global/core/ai/prompt/agent.ts
  packages/global/core/ai/prompt/dataset.ts
  packages/global/core/ai/type.d.ts
  packages/global/core/chat/utils.ts
  packages/global/core/dataset/training/utils.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/template/system/datasetSearch.ts
  packages/service/core/ai/config/provider/Qwen.json
  packages/service/core/ai/functions/createQuestionGuide.ts
  packages/service/core/ai/functions/queryExtension.ts
  packages/service/core/ai/utils.test.ts
  packages/service/core/ai/utils.ts
  packages/service/core/app/plugin/utils.ts
  packages/service/core/workflow/dispatch/agent/classifyQuestion.ts
  packages/service/core/workflow/dispatch/agent/extract.ts
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/core/workflow/dispatch/dataset/concat.ts
  packages/service/core/workflow/dispatch/dataset/search.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/templates/src/CQ/template.json
  packages/templates/src/simpleDatasetChat/template.json
  projects/app/src/components/Markdown/A.tsx
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/components/Markdown/utils.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/components/core/dataset/SearchParamsTip.tsx
  projects/app/src/pageComponents/account/info/UpdatePswModal.tsx
  projects/app/src/pageComponents/login/ForgetPasswordForm.tsx
  projects/app/src/pageComponents/login/RegisterForm.tsx
  projects/app/src/pages/api/core/ai/model/test.ts
  projects/app/src/pages/api/core/chat/getPaginationRecords.ts
  projects/app/src/pages/api/core/dataset/searchTest.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/api/v2/chat/completions.ts
  projects/app/src/pages/chat/share.tsx
  projects/app/src/service/events/generateQA.ts
  projects/app/src/service/support/mcp/utils.ts
  projects/app/src/web/common/api/fetch.ts
  projects/app/src/web/support/user/login/constants.ts
  test/cases/components/Markdown/utils.test.ts
  test/cases/function/packages/global/common/string/chunks.json
  test/cases/function/packages/global/common/string/password.test.ts
  test/cases/function/packages/global/common/string/textSplitter.test.ts
  test/cases/function/packages/service/core/ai/parseStreamResponse.test.ts
Labels: size/XXL
