Repository labring/FastGPT, pull requests merged in 2025-02, with the labels that each got.

#3674 feat: support mssql in databaseConnection plugin
  packages/plugins/package.json
  packages/plugins/src/databaseConnection/index.ts
  packages/plugins/src/databaseConnection/template.json
  pnpm-lock.yaml
Labels: size/L

#3681 perf: max_token count;feat: support resoner output;fix: member scroll
  docSite/content/zh-cn/docs/development/upgrading/4820.md
  packages/global/core/ai/model.d.ts
  packages/global/core/ai/provider.ts
  packages/global/core/app/type.d.ts
  packages/global/core/chat/constants.ts
  packages/global/core/chat/type.d.ts
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/global/core/workflow/template/system/aiChat/index.ts
  packages/global/core/workflow/template/system/tools.ts
  packages/service/common/file/image/controller.ts
  packages/service/core/ai/config/provider/DeepSeek.json
  packages/service/core/ai/config/provider/OpenAI.json
  packages/service/core/ai/functions/queryExtension.ts
  packages/service/core/ai/utils.ts
  packages/service/core/chat/utils.ts
  packages/service/core/workflow/dispatch/agent/extract.ts
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/chat/think.svg
  packages/web/hooks/useScrollPagination.tsx
  packages/web/i18n/en/account.json
  packages/web/i18n/en/app.json
  packages/web/i18n/en/chat.json
  packages/web/i18n/zh-CN/account.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/chat.json
  packages/web/i18n/zh-Hant/account.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/chat.json
  projects/app/src/components/core/ai/AISettingModal/index.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/ChatContainer/type.d.ts
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/pageComponents/account/model/ModelConfigTable.tsx
  projects/app/src/pageComponents/account/team/GroupManage/GroupManageMember.tsx
  projects/app/src/pageComponents/account/team/MemberTable.tsx
  projects/app/src/pageComponents/account/team/OrgManage/OrgMemberManageModal.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SettingLLMModel.tsx
  projects/app/src/web/common/api/fetch.ts
  projects/app/src/web/core/app/templates.ts
Labels: size/XL

#3682 fix: stream response
  packages/service/core/ai/config/provider/OpenAI.json
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  projects/app/src/pageComponents/account/model/ModelConfigTable.tsx
Labels: size/M

#3684 fix: reasoning response
  packages/global/core/app/type.d.ts
  packages/global/core/app/utils.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/EditForm.tsx
  projects/app/src/web/core/app/utils.ts
Labels: size/L

#3687 readme
  .github/workflows/docs-deploy-vercel.yml
  .github/workflows/docs-preview.yml
  README.md
  docSite/Dockerfile
Labels: size/XS

#3688 doc
  docSite/content/zh-cn/docs/development/upgrading/4819.md
  docSite/content/zh-cn/docs/development/upgrading/4820.md
Labels: size/XS

#3689 model config doc
  docSite/content/zh-cn/docs/development/modelConfig/intro.md
  packages/web/i18n/en/account.json
  packages/web/i18n/zh-CN/account.json
  packages/web/i18n/zh-Hant/account.json
  projects/app/src/pageComponents/account/model/ModelConfigTable.tsx
Labels: size/M

#3690 update doc
  docSite/content/zh-cn/docs/development/modelConfig/intro.md
Labels: size/S

#3691 fix: replace img host
  packages/service/core/chat/utils.ts
Labels: size/XS

#3692 remove log
  docSite/content/zh-cn/docs/development/upgrading/4820.md
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
  projects/app/src/service/core/app/workflow.ts
Labels: size/M

#3706 4.8.20 update
  packages/global/core/ai/model.ts
  packages/service/common/mongo/index.ts
  packages/service/core/ai/audio/transcriptions.ts
  packages/service/core/ai/config/utils.ts
  packages/service/core/ai/embedding/index.ts
  packages/service/core/ai/rerank/index.ts
  packages/service/core/dataset/data/dataTextSchema.ts
  packages/web/i18n/en/account.json
  packages/web/i18n/zh-CN/account.json
  packages/web/i18n/zh-Hant/account.json
  projects/app/public/docs/chatProblem.md
  projects/app/src/components/Layout/index.tsx
  projects/app/src/pageComponents/account/model/ModelConfigTable.tsx
  projects/app/src/pages/api/core/ai/model/test.ts
Labels: size/M

#3709 fix: yml
  docSite/content/zh-cn/docs/development/upgrading/4820.md
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
Labels: size/S

#3699 Load models error Error: ENOENT: no such file or directory, scandir
  packages/service/core/ai/config/utils.ts
Labels: size/XS

#3707 feat: auto adapt outlink chatwindow position
  projects/app/public/js/iframe.js
Labels: size/M

#3720 4.8.21 feature
  docSite/content/zh-cn/docs/development/docker.md
  docSite/content/zh-cn/docs/development/faq.md
  docSite/content/zh-cn/docs/development/sealos.md
  docSite/content/zh-cn/docs/development/upgrading/4821.md
  packages/global/core/ai/model.d.ts
  packages/global/core/app/type.d.ts
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/template/system/aiChat/index.ts
  packages/global/core/workflow/template/system/tools.ts
  packages/service/core/ai/config/provider/DeepSeek.json
  packages/service/core/ai/config/provider/Doubao.json
  packages/service/core/ai/config/provider/OpenAI.json
  packages/service/core/ai/config/utils.ts
  packages/service/core/ai/utils.ts
  packages/service/core/dataset/search/agent.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/core/workflow/dispatch/agent/runTool/functionCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  packages/service/core/workflow/dispatch/agent/runTool/type.d.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/worker/utils.ts
  packages/templates/register.ts
  packages/web/components/common/MySlider/InputSlider.tsx
  packages/web/i18n/en/account.json
  packages/web/i18n/en/app.json
  packages/web/i18n/en/login.json
  packages/web/i18n/zh-CN/account.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/login.json
  packages/web/i18n/zh-Hant/account.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/login.json
  projects/app/package.json
  projects/app/src/components/core/ai/AISettingModal/index.tsx
  projects/app/src/global/support/api/userRes.d.ts
  projects/app/src/pageComponents/account/model/ModelConfigTable.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/EditForm.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SettingLLMModel.tsx
  projects/app/src/pages/_error.tsx
  projects/app/src/pages/api/core/ai/model/test.ts
  projects/app/src/pages/api/core/dataset/searchTest.ts
  projects/app/src/pages/login/index.tsx
  projects/app/src/web/core/app/utils.ts
Labels: size/XL

#3721 fix: skip thirdparty sso state verification
  projects/app/src/pages/login/provider.tsx
Labels: size/XS

#3723 feat: normalization embedding;feat: model top_p param config
  docSite/content/zh-cn/docs/development/upgrading/4821.md
  docSite/content/zh-cn/docs/development/upgrading/490.md
  packages/global/core/ai/model.d.ts
  packages/service/core/ai/config/provider/ChatGLM.json
  packages/service/core/ai/config/provider/Claude.json
  packages/service/core/ai/config/provider/DeepSeek.json
  packages/service/core/ai/config/provider/Doubao.json
  packages/service/core/ai/config/provider/Ernie.json
  packages/service/core/ai/config/provider/Gemini.json
  packages/service/core/ai/config/provider/Groq.json
  packages/service/core/ai/config/provider/Hunyuan.json
  packages/service/core/ai/config/provider/Intern.json
  packages/service/core/ai/config/provider/MiniMax.json
  packages/service/core/ai/config/provider/MistralAI.json
  packages/service/core/ai/config/provider/Moonshot.json
  packages/service/core/ai/config/provider/OpenAI.json
  packages/service/core/ai/config/provider/Qwen.json
  packages/service/core/ai/config/provider/Siliconflow.json
  packages/service/core/ai/config/provider/SparkDesk.json
  packages/service/core/ai/config/provider/StepFun.json
  packages/service/core/ai/config/provider/Yi.json
  packages/service/core/ai/embedding/index.ts
  packages/web/i18n/en/account.json
  packages/web/i18n/zh-CN/account.json
  packages/web/i18n/zh-Hant/account.json
  projects/app/src/components/common/NextHead/index.tsx
  projects/app/src/pageComponents/account/model/ModelConfigTable.tsx
  projects/app/src/pages/_error.tsx
  projects/app/src/pages/api/core/ai/model/test.ts
  projects/app/src/pages/chat/share.tsx
Labels: size/L

#3730 更新 4820.md
  docSite/content/zh-cn/docs/development/upgrading/4820.md
Labels: size/XS

#3725 Update configuration.md
  docSite/content/zh-cn/docs/development/configuration.md
Labels: size/XS

#3717 add plugin unexist error tips
  packages/global/core/app/utils.ts
  packages/global/core/workflow/type/node.d.ts
  packages/web/components/common/Icon/icons/common/errorFill.svg
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/pageComponents/app/detail/Plugin/Header.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/Header.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/components/ToolSelect.tsx
  projects/app/src/pageComponents/app/detail/Workflow/Header.tsx
  projects/app/src/pageComponents/app/detail/Workflow/components/SaveButton.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pageComponents/app/detail/context.tsx
  projects/app/src/pages/api/core/app/detail.ts
  projects/app/src/pages/api/core/app/version/detail.ts
  projects/app/src/pages/api/core/chat/init.ts
  projects/app/src/pages/api/core/chat/outLink/init.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/service/core/app/utils.ts
  projects/app/src/web/core/app/utils.ts
  projects/app/src/web/core/workflow/utils.ts
Labels: size/L

#3742 4.8.21 feature
  docSite/content/zh-cn/docs/development/faq.md
  docSite/content/zh-cn/docs/development/upgrading/4821.md
  docSite/content/zh-cn/docs/guide/workbench/workflow/dataset_search.md
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/node/constant.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/template/system/aiChat/index.ts
  packages/global/core/workflow/template/system/datasetSearch.ts
  packages/global/core/workflow/type/io.d.ts
  packages/service/core/dataset/search/agent.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/core/workflow/dispatch/dataset/search.ts
  packages/service/worker/readFile/extension/pdf.ts
  packages/web/components/core/workflow/NodeInputSelect.tsx
  packages/web/i18n/en/chat.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh-CN/chat.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/workflow.json
  packages/web/i18n/zh-Hant/chat.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/workflow.json
  projects/app/src/components/Markdown/codeBlock/Audio.tsx
  projects/app/src/components/Markdown/codeBlock/Video.tsx
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/components/core/ai/SettingLLMModel/index.tsx
  projects/app/src/components/core/app/TTSSelect.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/components/support/user/safe/SendCodeAuthModal.tsx
  projects/app/src/global/core/dataset/api.d.ts
  projects/app/src/pageComponents/app/detail/SimpleApp/EditForm.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodePluginIO/NodePluginConfig.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Reference.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SettingLLMModel.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderOutput/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/utils.tsx
  projects/app/src/pages/_error.tsx
  projects/app/src/pages/api/core/dataset/searchTest.ts
  projects/app/src/pages/login/index.tsx
  projects/app/src/service/support/wallet/usage/push.ts
  projects/app/src/web/common/api/fetch.ts
Labels: size/XXL

#3737 chat logs filter & export
  packages/web/i18n/en/app.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-Hant/app.json
  projects/app/src/global/core/api/appReq.d.ts
  projects/app/src/pageComponents/app/detail/Logs/index.tsx
  projects/app/src/pages/api/core/app/exportChatLogs.ts
  projects/app/src/pages/api/core/app/getChatLogs.ts
  projects/app/src/types/app.d.ts
Labels: size/XL

#3746 Update chat.md
  docSite/content/zh-cn/docs/development/openapi/chat.md
Labels: size/XS

#3754 fix: export csv format & log title debounce
  projects/app/src/pageComponents/app/detail/Logs/index.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/index.tsx
  projects/app/src/pages/api/core/app/exportChatLogs.ts
Labels: size/S

#3757 更新 share.md
  docSite/content/zh-cn/docs/development/openapi/share.md
Labels: size/XS

#3763 perf: request quantity;perf: share page error circulation;perf: share chat toast
  docSite/content/zh-cn/docs/development/modelConfig/intro.md
  docSite/content/zh-cn/docs/development/upgrading/4821.md
  packages/service/core/chat/chatSchema.ts
  packages/service/core/dataset/training/utils.ts
  packages/web/hooks/usePagination.tsx
  projects/app/src/pageComponents/app/detail/Logs/index.tsx
  projects/app/src/pages/_error.tsx
  projects/app/src/pages/api/core/app/exportChatLogs.ts
  projects/app/src/pages/api/core/chat/outLink/init.ts
  projects/app/src/pages/api/core/dataset/training/rebuildEmbedding.ts
  projects/app/src/pages/chat/share.tsx
  projects/app/src/service/events/generateQA.ts
  projects/app/src/service/events/generateVector.ts
  projects/app/src/service/support/permission/auth/chat.ts
  projects/app/src/web/common/api/request.ts
  projects/app/src/web/core/app/api.ts
Labels: size/L

#3764 perf: global variable & interactive node dnd
  packages/web/components/common/DndDrag/index.tsx
  projects/app/src/components/core/app/VariableEdit.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeFormInput/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeIfElse/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeUserSelect.tsx
Labels: size/XL

#3767 fix: simple mode variables dnd
  packages/web/components/common/DndDrag/index.tsx
  projects/app/src/components/core/app/VariableEdit.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeFormInput/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeIfElse/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeSystemConfig.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeUserSelect.tsx
Labels: size/L

#3768 optimize dnd drag code
  packages/web/components/common/DndDrag/index.tsx
  projects/app/src/components/core/app/VariableEdit.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeFormInput/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeIfElse/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeUserSelect.tsx
Labels: size/M

#3770 i18n perf
  docSite/content/zh-cn/docs/development/upgrading/490.md
  packages/service/core/ai/rerank/index.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/common/folder/SlideCard.tsx
  projects/app/src/components/core/app/VariableEdit.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/SelectMarkCollection.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeFormInput/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeToolParams/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderToolInput/EditFieldModal.tsx
Labels: size/M

#3773 perf: http empty params
  docSite/content/zh-cn/docs/development/upgrading/4821.md
  packages/global/common/string/tools.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/service/core/ai/config/provider/Qwen.json
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/core/workflow/dispatch/dataset/search.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeHttp/index.tsx
  projects/app/src/pages/login/index.tsx
Labels: size/M

#3775 perf: unlogin user fetch data
  docSite/content/zh-cn/docs/development/upgrading/4821.md
  packages/global/common/file/constants.ts
  packages/service/common/file/image/controller.ts
  projects/app/.env.template
  projects/app/src/components/Layout/index.tsx
  projects/app/src/global/common/api/systemRes.d.ts
  projects/app/src/pages/api/common/file/read.ts
  projects/app/src/pages/api/common/file/read/[filename].ts
  projects/app/src/pages/api/common/system/getInitData.ts
  projects/app/src/pages/login/index.tsx
  projects/app/src/web/common/system/useSystemStore.ts
  projects/app/src/web/context/useInitApp.ts
  projects/app/src/web/support/user/useUserStore.ts
Labels: size/L

#3774 fix embed chatbot default open
  projects/app/public/js/iframe.js
Labels: size/XS

#3777 chatbot not overflow
  projects/app/public/js/iframe.js
Labels: size/M

#3779 4.9.0 test
  docSite/content/zh-cn/docs/development/upgrading/4821.md
  files/docker/docker-compose-pgvector.yml
  projects/app/src/components/core/app/DatasetParamsModal.tsx
  projects/app/src/web/context/useInitApp.ts
Labels: size/M

#3784 fix: app/dataset list api return private flag
  projects/app/src/pages/api/core/app/list.ts
  projects/app/src/pages/api/core/dataset/list.ts
Labels: size/XS

#3782 fix: skip thirdparty sso state verification
  projects/app/src/pages/login/provider.tsx
Labels: size/XS

#3787 update yml version
  docSite/content/zh-cn/docs/development/upgrading/4821.md
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
Labels: size/S

#3789 chore: add ppio provider
  packages/global/core/ai/provider.ts
  packages/service/core/ai/config/provider/PPIO.json
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/model/ppio.svg
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
Labels: size/L

#3805 feat: think tag parse
  docSite/content/zh-cn/docs/development/upgrading/490.md
  packages/global/core/ai/type.d.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/service/core/ai/config.ts
  packages/service/core/ai/config/provider/PPIO.json
  packages/service/core/ai/utils.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/core/workflow/dispatch/index.ts
  projects/app/src/pages/api/v1/chat/utils.test.ts
  projects/app/src/web/common/api/fetch.ts
Labels: size/XL

#3806 fix document
  docSite/content/zh-cn/docs/development/openapi/dataset.md
Labels: size/XS

#3804 fix template market simple app
  projects/app/src/pageComponents/app/list/TemplateMarketModal.tsx
Labels: size/S

#3808 feat: think tag parse (#3805)
  docSite/content/zh-cn/docs/development/upgrading/490.md
  packages/global/core/ai/type.d.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/service/core/ai/config.ts
  packages/service/core/ai/config/provider/PPIO.json
  packages/service/core/ai/utils.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/core/workflow/dispatch/index.ts
  projects/app/src/pages/api/v1/chat/utils.test.ts
  projects/app/src/web/common/api/fetch.ts
Labels: size/XL

#3813 fix: whisper checker;fix: img read
  docSite/content/zh-cn/docs/development/intro.md
  docSite/content/zh-cn/docs/development/upgrading/4822.md
  docSite/content/zh-cn/docs/development/upgrading/490.md
  package.json
  packages/global/common/file/tools.ts
  packages/global/core/chat/adapt.ts
  packages/service/core/chat/utils.ts
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/core/workflow/dispatch/plugin/runApp.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/core/chat/ChatContainer/ChatBox/Input/ChatInput.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderOutput/index.tsx
Labels: size/L

#3814 fix: refresh memberlist when switching account
  projects/app/src/pageComponents/account/TeamSelector.tsx
  projects/app/src/pages/account/info/index.tsx
  projects/app/src/pages/account/team/index.tsx
Labels: size/S

#3818 Update 4818.md
  docSite/content/zh-cn/docs/development/upgrading/4818.md
Labels: size/XS

#3820 download fetch baseurl & node select dnd
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeUserSelect.tsx
  projects/app/src/web/common/system/utils.ts
Labels: size/XS

#3822 fix: app version addSourcemember tmbid could be empty
  packages/service/support/user/utils.ts
Labels: size/XS

#3816 fix: price page init data;perf: usage code;fix: reasoning tokens;fix: workflow basic node cannot upgrade
  docSite/content/zh-cn/docs/development/upgrading/4822.md
  packages/global/common/file/constants.ts
  packages/global/core/ai/type.d.ts
  packages/global/core/chat/adapt.ts
  packages/service/common/file/image/controller.ts
  packages/service/common/string/tiktoken/index.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/support/wallet/usage/controller.ts
  packages/service/support/wallet/usage/type.d.ts
  packages/service/support/wallet/usage/utils.ts
  packages/service/worker/countGptMessagesTokens/index.ts
  packages/web/components/common/Icon/index.tsx
  projects/app/data/config.json
  projects/app/data/model.json
  projects/app/next-i18next.config.js
  projects/app/src/components/Layout/index.tsx
  projects/app/src/components/Select/AIModelSelector.tsx
  projects/app/src/pageComponents/account/TeamSelector.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pageComponents/dataset/detail/Import/components/FileSelector.tsx
  projects/app/src/pages/account/info/index.tsx
  projects/app/src/pages/account/team/index.tsx
  projects/app/src/pages/api/common/system/getInitData.ts
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/core/workflow/debug.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/login/index.tsx
  projects/app/src/service/core/app/utils.ts
  projects/app/src/service/support/wallet/usage/controller.ts
  projects/app/src/service/support/wallet/usage/push.ts
  projects/app/src/web/common/file/controller.ts
Labels: size/XL

#3828 perf: gemini config
  docSite/content/zh-cn/docs/development/upgrading/4822.md
  packages/service/core/ai/config/provider/Gemini.json
Labels: size/M

#3807 chore: team, orgs, search and so on
  packages/global/support/user/api.d.ts
  packages/global/support/user/team/controller.d.ts
  packages/global/support/user/team/type.d.ts
  packages/global/support/user/type.d.ts
  packages/service/common/file/csv.ts
  packages/service/support/user/controller.ts
  packages/service/support/user/schema.ts
  packages/service/support/user/team/teamMemberSchema.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/confirm/deleteTip.svg
  packages/web/components/common/Icon/icons/common/confirm/restoreTip.svg
  packages/web/components/common/Input/SearchInput/index.tsx
  packages/web/components/common/MyModal/index.tsx
  packages/web/hooks/useConfirm.tsx
  packages/web/i18n/zh-CN/account_info.json
  packages/web/i18n/zh-CN/account_team.json
  projects/app/package.json
  projects/app/src/components/Layout/index.tsx
  projects/app/src/components/support/permission/MemberManager/MemberItemCard.tsx
  projects/app/src/components/support/permission/MemberManager/MemberModal.tsx
  projects/app/src/components/support/user/inform/UpdateContactModal.tsx
  projects/app/src/components/support/user/team/OrgTags/index.tsx
  projects/app/src/pageComponents/account/team/EditInfoModal.tsx
  projects/app/src/pageComponents/account/team/GroupManage/GroupManageMember.tsx
  projects/app/src/pageComponents/account/team/MemberTable.tsx
  projects/app/src/pageComponents/account/team/OrgManage/OrgMemberManageModal.tsx
  projects/app/src/pageComponents/account/team/OrgManage/index.tsx
  projects/app/src/pageComponents/account/team/PermissionManage/index.tsx
  projects/app/src/pageComponents/account/team/context.tsx
  projects/app/src/pageComponents/login/LoginForm/FormLayout.tsx
  projects/app/src/pages/account/info/index.tsx
  projects/app/src/pages/account/team/index.tsx
  projects/app/src/pages/api/admin/initv4822.ts
  projects/app/src/web/support/user/api.ts
  projects/app/src/web/support/user/team/api.ts
Labels: size/XXL

#3833 perf: ery extension and fix filter same embedding result
  docSite/assets/imgs/appid.png
  docSite/content/zh-cn/docs/development/openapi/chat.md
  docSite/content/zh-cn/docs/development/openapi/intro.md
  docSite/content/zh-cn/docs/development/upgrading/4822.md
  packages/global/core/ai/provider.ts
  packages/service/core/chat/chatSchema.ts
  packages/service/core/chat/saveChat.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/core/dataset/search/utils.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/Layout/index.tsx
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/components/core/dataset/QuoteItem.tsx
  projects/app/src/components/support/permission/MemberManager/MemberItemCard.tsx
  projects/app/src/components/support/permission/MemberManager/MemberModal.tsx
  projects/app/src/components/support/user/team/OrgTags/index.tsx
  projects/app/src/pageComponents/account/team/MemberTable.tsx
  projects/app/src/pageComponents/account/team/PermissionManage/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeExtract/ExtractFieldModal.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeExtract/index.tsx
  projects/app/src/pages/api/admin/initv4822.ts
  projects/app/src/pages/api/core/dataset/collection/sync.ts
  projects/app/src/pages/api/support/user/account/tokenLogin.ts
  projects/app/src/pages/api/v1/chat/completions.ts
Labels: size/XL

#3836 update doc
  docSite/content/zh-cn/docs/development/faq.md
  docSite/content/zh-cn/docs/development/upgrading/4822.md
Labels: size/XS

#3840 update doc
  docSite/content/zh-cn/docs/development/upgrading/4822.md
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
Labels: size/M

#3869 Marker doc update
  python/pdf-marker/Readme.md
Labels: size/XS

#3853 fix collection folder tags filter
  packages/service/core/dataset/search/controller.ts
Labels: size/M

#3866 feat: model config required check;feat: dataset text model default setting
  docSite/content/zh-cn/docs/development/upgrading/4823.md
  packages/global/core/ai/model.d.ts
  packages/global/core/dataset/type.d.ts
  packages/service/common/system/constants.ts
  packages/service/common/vectorStore/controller.ts
  packages/service/common/vectorStore/milvus/class.ts
  packages/service/common/vectorStore/pg/class.ts
  packages/service/core/ai/config/utils.ts
  packages/service/core/ai/type.d.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/support/wallet/usage/controller.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/dataset.json
  projects/app/src/components/core/ai/SettingLLMModel/index.tsx
  projects/app/src/pageComponents/account/model/ModelConfigTable.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SelectLLMModel.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/TagManageModal.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/index.tsx
  projects/app/src/pageComponents/dataset/detail/DataCard.tsx
  projects/app/src/pageComponents/dataset/detail/Info/index.tsx
  projects/app/src/pageComponents/dataset/list/CreateModal.tsx
  projects/app/src/pages/api/core/ai/model/updateDefault.ts
  projects/app/src/pages/api/core/dataset/collection/detail.ts
  projects/app/src/pages/api/core/dataset/collection/listV2.ts
  projects/app/src/pages/api/core/dataset/collection/scrollList.ts
  projects/app/src/web/common/system/utils.ts
  projects/app/src/web/core/dataset/api.ts
  projects/app/src/web/core/dataset/constants.ts
Labels: size/XL

#3873 更正错别字，规范标点
  docSite/content/zh-cn/docs/guide/course/quick-start.md
Labels: size/XS

#3860 feat/workorder
  packages/global/common/system/types/index.d.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/close.svg
  packages/web/components/common/Icon/icons/core/chat/chevronLeft.svg
  packages/web/components/common/Icon/icons/feedback.svg
  packages/web/i18n/zh-CN/common.json
  projects/app/src/components/Layout/auth.tsx
  projects/app/src/components/Layout/index.tsx
  projects/app/src/components/support/workorder/WorkorderButton.tsx
  projects/app/src/pageComponents/account/team/context.tsx
  projects/app/src/web/common/workorder/api.ts
Labels: size/L

#3874 perf: work order tip
  packages/global/support/user/type.d.ts
  packages/web/components/common/Icon/icons/feedback.svg
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/Layout/WorkorderButton.tsx
  projects/app/src/components/Layout/auth.tsx
  projects/app/src/components/Layout/index.tsx
  projects/app/src/pages/account/info/index.tsx
Labels: size/L

#3877 remove markdown format;refresh username;perf: latext render
  docSite/content/zh-cn/docs/development/upgrading/4823.md
  packages/service/common/file/read/utils.ts
  packages/service/core/ai/config/provider/Claude.json
  packages/service/core/ai/config/provider/Grok.json
  projects/app/next.config.js
  projects/app/src/components/Layout/index.tsx
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/components/Markdown/utils.ts
  projects/app/src/pages/account/info/index.tsx
Labels: size/L

#3893 fix: leave team and refresh memberlist
  projects/app/src/pageComponents/account/team/MemberTable.tsx
Labels: size/XS

#3868 chore: upgrade mongoose to v8.10.x for security
  packages/service/common/file/gridfs/controller.ts
  packages/service/package.json
  packages/service/support/permission/controller.ts
  packages/service/support/permission/publish/authLink.ts
  packages/service/support/permission/teamLimit.ts
  projects/app/src/pages/api/admin/initv481.ts
  projects/app/src/pages/api/support/outLink/delete.ts
Labels: size/M

#3900 Update intro.md
  docSite/content/zh-cn/docs/development/modelConfig/intro.md
Labels: size/XS

#3898 feat: ai proxy v1
  docSite/content/zh-cn/docs/development/upgrading/4823.md
  packages/global/common/string/time.ts
  packages/global/common/system/types/index.d.ts
  packages/service/core/ai/config.ts
  packages/service/support/user/team/controller.ts
  packages/web/components/common/DateRangePicker/index.tsx
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/disable.svg
  packages/web/components/common/Icon/icons/common/enable.svg
  packages/web/components/common/Input/NumberInput/index.tsx
  packages/web/components/common/MySelect/MultipleSelect.tsx
  packages/web/components/common/MySelect/index.tsx
  packages/web/hooks/useScrollPagination.tsx
  packages/web/i18n/en/account_model.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/account.json
  packages/web/i18n/zh-CN/account_model.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/account.json
  packages/web/i18n/zh-Hant/account_model.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/types/i18next.d.ts
  pnpm-lock.yaml
  projects/app/.env.template
  projects/app/src/global/aiproxy/constants.ts
  projects/app/src/global/aiproxy/type.d.ts
  projects/app/src/pageComponents/account/model/AddModelBox.tsx
  projects/app/src/pageComponents/account/model/Channel/EditChannelModal.tsx
  projects/app/src/pageComponents/account/model/Channel/ModelTest.tsx
  projects/app/src/pageComponents/account/model/Channel/index.tsx
  projects/app/src/pageComponents/account/model/Log/index.tsx
  projects/app/src/pageComponents/account/model/ModelConfigTable.tsx
  projects/app/src/pages/account/model/index.tsx
  projects/app/src/pages/api/aiproxy/[...path].ts
  projects/app/src/pages/api/aiproxy/api/createChannel.ts
  projects/app/src/pages/api/core/ai/model/test.ts
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/service/common/system/index.ts
  projects/app/src/web/core/ai/channel.ts
Labels: size/XXL

#3901 fix: upload office file (.pptx) encoding error
  packages/service/worker/readFile/parseOffice.ts
Labels: size/XS

#3905 fix: pptx encoding
  docSite/content/zh-cn/docs/development/upgrading/4823.md
  packages/service/worker/readFile/parseOffice.ts
Labels: size/S

#3906 fix: mongoose strictquery to false
  packages/service/common/mongo/init.ts
Labels: size/XS

#3911 fix: ts error
  packages/service/support/permission/publish/authLink.ts
  projects/app/src/pageComponents/app/detail/Publish/Link/index.tsx
  projects/app/src/web/common/utils/voice.ts
Labels: size/S

#3913 更新 docker.md
  docSite/content/zh-cn/docs/development/docker.md
Labels: size/XS

#3917 4.8.23 dev
  .github/workflows/fastgpt-preview-image.yml
  .github/workflows/helm-release.yaml
  packages/service/common/mongo/index.ts
  packages/web/components/common/Icon/index.tsx
  projects/app/src/components/core/app/TTSSelect.tsx
  projects/app/src/pages/api/aiproxy/[...path].ts
  projects/app/src/pages/api/core/dataset/collection/listV2.ts
Labels: size/M

#3919 Update package.json
  projects/app/package.json
Labels: size/XS

#3923 fix: chat detail order in export chat logs
  projects/app/src/pages/api/core/app/exportChatLogs.ts
Labels: size/XS

#3925 fix: delete dataset field error
  docSite/content/zh-cn/docs/development/upgrading/4823.md
  packages/global/common/error/code/dataset.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/service/core/ai/utils.ts
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/controller.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/service/test/utils.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/core/app/TTSSelect.tsx
  projects/app/src/pages/api/__mocks__/base.ts
  projects/app/src/pages/api/v1/chat/utils.test.ts
  projects/app/src/service/events/generateQA.ts
Labels: size/L

#3926 4.8.23 dev
  .vscode/nextapi.code-snippets
  projects/app/src/pages/api/__mocks__/demo/demo.test.ts
  projects/app/src/pages/api/core/app/version/latest.test.ts
  projects/app/src/pages/api/core/app/version/lis.test.ts
  projects/app/src/pages/api/core/app/version/publish.test.ts
  projects/app/src/pages/api/support/outLink/list.test.ts
  projects/app/src/pages/api/support/outLink/update.test.ts
Labels: size/S

#3927 fix: invalid dataset data clear
  docSite/content/zh-cn/docs/development/upgrading/4823.md
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/collection/utils.ts
  packages/service/core/dataset/data/dataTextSchema.ts
  projects/app/src/pageComponents/account/model/Channel/ModelTest.tsx
  projects/app/src/pageComponents/account/model/Log/index.tsx
  projects/app/src/pages/api/admin/clearInvalidData.ts
  projects/app/src/pages/api/admin/initv4823.ts
  projects/app/src/pages/api/core/dataset/collection/create/reTrainingCollection.ts
  projects/app/src/pages/api/core/dataset/collection/delete.ts
  projects/app/src/service/common/system/cronTask.ts
  projects/app/src/service/core/dataset/data/controller.ts
  projects/app/src/web/core/ai/channel.ts
Labels: size/L

#3924 add webcrawler
  plugins/webcrawler/.dockerignore
  plugins/webcrawler/.gitignore
  plugins/webcrawler/.searchxng.env
  plugins/webcrawler/Caddyfile
  plugins/webcrawler/Dockerfile
  plugins/webcrawler/README.md
  plugins/webcrawler/SPIDER/.env.example
  plugins/webcrawler/SPIDER/package-lock.json
  plugins/webcrawler/SPIDER/package.json
  plugins/webcrawler/SPIDER/src/controllers/quickfetchController.ts
  plugins/webcrawler/SPIDER/src/controllers/readController.ts
  plugins/webcrawler/SPIDER/src/controllers/searchController.ts
  plugins/webcrawler/SPIDER/src/engines/baiduEngine.ts
  plugins/webcrawler/SPIDER/src/engines/searchxngEngine.ts
  plugins/webcrawler/SPIDER/src/index.ts
  plugins/webcrawler/SPIDER/src/middleware/authMiddleware.ts
  plugins/webcrawler/SPIDER/src/routes/quickfetchRoutes.ts
  plugins/webcrawler/SPIDER/src/routes/readRoutes.ts
  plugins/webcrawler/SPIDER/src/routes/searchRoutes.ts
  plugins/webcrawler/SPIDER/src/specialHandlers/index.ts
  plugins/webcrawler/SPIDER/src/utils/cacheUpdater.ts
  plugins/webcrawler/SPIDER/src/utils/deepSearch.ts
  plugins/webcrawler/SPIDER/src/utils/setupPage.ts
  plugins/webcrawler/SPIDER/tsconfig.json
  plugins/webcrawler/SPIDER/webpack.config.js
  plugins/webcrawler/docker-compose.yaml
  plugins/webcrawler/searxng-docker.service.template
  plugins/webcrawler/searxng/limiter.toml
  plugins/webcrawler/searxng/settings.yml
Labels: size/XXL

#3932 4.8.23 dev
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  docSite/content/zh-cn/docs/development/upgrading/4823.md
  packages/web/hooks/useScrollPagination.tsx
  projects/app/src/pageComponents/account/model/Log/index.tsx
  projects/app/src/pages/api/admin/initv4823.ts
Labels: size/M
