Repository labring/FastGPT, pull requests merged in 2025-03, with the labels that each got.

#3939 add env proxypool
  plugins/webcrawler/SPIDER/.env.example
  plugins/webcrawler/SPIDER/src/utils/setupPage.ts
Labels: size/M

#3948 fix: add order:true to all create transactions & file format
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/collection/utils.ts
  packages/service/support/permission/inheritPermission.ts
  packages/service/support/wallet/sub/utils.ts
  packages/service/support/wallet/usage/controller.ts
  plugins/webcrawler/SPIDER/src/controllers/quickfetchController.ts
  plugins/webcrawler/SPIDER/src/controllers/readController.ts
  plugins/webcrawler/SPIDER/src/controllers/searchController.ts
  plugins/webcrawler/SPIDER/src/engines/baiduEngine.ts
  plugins/webcrawler/SPIDER/src/engines/searchxngEngine.ts
  plugins/webcrawler/SPIDER/src/index.ts
  plugins/webcrawler/SPIDER/src/middleware/authMiddleware.ts
  plugins/webcrawler/SPIDER/src/routes/quickfetchRoutes.ts
  plugins/webcrawler/SPIDER/src/routes/readRoutes.ts
  plugins/webcrawler/SPIDER/src/routes/searchRoutes.ts
  plugins/webcrawler/SPIDER/src/specialHandlers/index.ts
  plugins/webcrawler/SPIDER/src/utils/cacheUpdater.ts
  plugins/webcrawler/SPIDER/src/utils/deepSearch.ts
  plugins/webcrawler/SPIDER/src/utils/setupPage.ts
  projects/app/src/pages/api/admin/initv485.ts
  projects/app/src/pages/api/admin/resetMilvus.ts
  projects/app/src/pages/api/core/app/create.ts
  projects/app/src/pages/api/core/app/folder/create.ts
  projects/app/src/pages/api/core/app/version/publish.ts
  projects/app/src/pages/api/core/dataset/create.ts
  projects/app/src/pages/api/core/dataset/folder/create.ts
  projects/app/src/pages/api/core/dataset/training/rebuildEmbedding.ts
  projects/app/src/service/core/dataset/data/controller.ts
  projects/app/src/service/events/generateVector.ts
  projects/app/src/service/mongo.ts
Labels: size/XL

#3945 fix: rerank model cannot use ai proxy
  packages/service/common/mongo/init.ts
  packages/service/core/ai/config.ts
  packages/service/core/ai/config/provider/AliCloud.json
  packages/web/i18n/en/account_model.json
  packages/web/i18n/zh-CN/account_model.json
  packages/web/i18n/zh-Hant/account_model.json
  projects/app/src/pageComponents/account/model/Log/index.tsx
  projects/app/src/web/core/ai/channel.ts
Labels: size/M

#3949 perf: delete dataset
  docSite/content/zh-cn/docs/development/upgrading/4823.md
  packages/service/common/file/image/controller.ts
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/controller.ts
  packages/service/core/dataset/data/dataTextSchema.ts
  projects/app/src/pageComponents/account/model/Log/index.tsx
  projects/app/src/pages/api/core/dataset/delete.ts
Labels: size/L

#3965 fix: Check the url to avoid ssrf attacks
  packages/plugins/src/fetchUrl/template.json
  packages/service/common/string/cheerio.ts
  packages/service/common/system/utils.ts
  projects/app/src/pages/api/core/app/httpPlugin/getApiSchemaByUrl.ts
Labels: size/L

#3967 Create SECURITY.md
  SECURITY.md
Labels: size/S

#3963 plugin customize author
  packages/service/core/app/plugin/type.d.ts
  packages/service/core/app/templates/templateSchema.ts
Labels: size/XS

#3980 fix loop child nodes variables
  packages/service/core/workflow/dispatch/loop/runLoop.ts
Labels: size/XS

#3954 fix ai proxy logs pagination
  packages/web/hooks/useScrollPagination.tsx
  projects/app/src/pageComponents/account/model/Log/index.tsx
Labels: size/S

#3985 fix: 优化读取mongo文件性能，解决因执行Buffer.concat过多造成等待导致整个服务hang住的
  packages/service/common/file/gridfs/utils.ts
Labels: size/XS

#3984 simple mode tool reason
  docSite/content/zh-cn/docs/development/upgrading/490.md
  packages/service/common/file/gridfs/controller.ts
  packages/service/common/file/gridfs/utils.ts
  packages/service/core/ai/audio/speech.ts
  packages/service/core/ai/config/provider/DeepSeek.json
  packages/web/i18n/en/account_model.json
  packages/web/i18n/zh-CN/account_model.json
  packages/web/i18n/zh-Hant/account_model.json
  projects/app/src/pageComponents/account/model/AddModelBox.tsx
  projects/app/src/web/core/app/utils.ts
Labels: size/L

#3987 fix: link cheker
  packages/service/common/system/utils.ts
  projects/app/src/pages/api/core/dataset/collection/create/link.ts
Labels: size/S

#3990 pdf parse doc
  docSite/assets/imgs/image copy.png
  docSite/assets/imgs/marker2.png
  docSite/assets/imgs/marker3.png
  docSite/content/zh-cn/docs/development/configuration.md
  docSite/content/zh-cn/docs/development/custom-models/marker.md
  docSite/content/zh-cn/docs/development/upgrading/490.md
  packages/service/common/file/read/utils.ts
  projects/app/data/config.json
  projects/app/src/pageComponents/dataset/detail/Import/commonProgress/PreviewData.tsx
Labels: size/L

#3989 fix: remove defaultTeam
  packages/global/support/user/team/controller.d.ts
  packages/global/support/user/team/type.d.ts
  packages/service/support/user/team/controller.ts
  packages/service/support/user/team/teamMemberSchema.ts
  projects/app/src/pageComponents/account/team/MemberTable.tsx
Labels: size/S

#4003 perf: http body check
  packages/service/core/workflow/dispatch/tools/http468.ts
Labels: size/L

#3999 Update README.md
  README.md
Labels: size/XS

#3994 pref: set strictQuery to throw.
  packages/service/common/mongo/init.ts
Labels: size/XS

#4008 feat: qwen qwq model config
  docSite/content/zh-cn/docs/development/upgrading/490.md
  packages/service/core/ai/config/provider/Qwen.json
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  projects/app/src/pages/api/core/ai/model/test.ts
  projects/app/src/pages/api/core/chat/chatTest.ts
Labels: size/L

#4009 qwq config
  packages/service/core/ai/config/provider/Qwen.json
Labels: size/XS

#4013 version doc
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  docSite/content/zh-cn/docs/development/upgrading/490.md
Labels: size/M

#4010 翻译缺失
  packages/web/i18n/zh-CN/common.json
Labels: size/XS

#4021 Update official_account.md
  docSite/content/zh-cn/docs/use-cases/external-integration/official_account.md
Labels: size/XS

#4022 Update 490.md
  docSite/content/zh-cn/docs/development/upgrading/490.md
Labels: size/XS

#4028 更新 4820.md
  docSite/content/zh-cn/docs/development/upgrading/4820.md
Labels: size/XS

#4033 fix: 修复知识库问题优化无效的BUG
  packages/service/core/dataset/search/controller.ts
Labels: size/XS

#4037 fix: remove DefaultTeam
  packages/service/support/user/team/controller.ts
Labels: size/XS

#4040 fix: 修复部分参数丢失的问题
  packages/global/core/app/utils.ts
Labels: size/S

#4048 fix: 修复最大响应 tokens 提示显示错误的问题
  packages/web/i18n/en/account_model.json
  packages/web/i18n/zh-CN/account_model.json
  packages/web/i18n/zh-Hant/account_model.json
  projects/app/src/pageComponents/account/model/AddModelBox.tsx
Labels: size/XS

#4070 perf: HTTP node jsonBody support \n
  packages/service/core/workflow/dispatch/tools/http468.ts
Labels: size/XS

#4074 fix: import dataset step error;perf: ai proxy avatar
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  docSite/content/zh-cn/docs/development/upgrading/4823.md
  docSite/content/zh-cn/docs/development/upgrading/490.md
  docSite/content/zh-cn/docs/development/upgrading/491.md
  packages/global/common/string/textSplitter.ts
  packages/service/common/vectorStore/pg/class.ts
  packages/service/core/app/utils.ts
  packages/web/components/common/Icon/button.tsx
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/chat/chevronDown.svg
  packages/web/components/common/Icon/icons/core/chat/chevronUp.svg
  packages/web/components/common/Icon/icons/model/aws.svg
  packages/web/components/common/Icon/icons/model/azure.svg
  packages/web/components/common/Icon/icons/model/cloudflare.svg
  packages/web/components/common/Icon/icons/model/cohere.svg
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/dataset.json
  projects/app/src/global/aiproxy/constants.ts
  projects/app/src/pageComponents/account/model/Channel/EditChannelModal.tsx
  projects/app/src/pageComponents/dataset/detail/Import/Context.tsx
  projects/app/src/pageComponents/dataset/detail/Import/diffSource/APIDataset.tsx
  projects/app/src/pageComponents/dataset/detail/Import/diffSource/ExternalFile.tsx
  projects/app/src/pageComponents/dataset/detail/Import/diffSource/FileCustomText.tsx
  projects/app/src/pageComponents/dataset/detail/Import/diffSource/FileLink.tsx
  projects/app/src/pageComponents/dataset/detail/Import/diffSource/ReTraining.tsx
  projects/app/src/pageComponents/dataset/detail/InputDataModal.tsx
  projects/app/src/pages/account/usage/index.tsx
  projects/app/src/pages/api/core/ai/model/test.ts
  projects/app/src/pages/api/core/app/detail.ts
  projects/app/src/pages/api/core/app/version/detail.ts
  projects/app/src/pages/api/core/app/version/latest.ts
Labels: size/XL

#4079 fix: 文本提取不支持arrayString,arrayNumber等jsonSchema
  packages/service/core/workflow/dispatch/agent/extract.ts
Labels: size/S

#4098 update doc ;perf: model test
  README_en.md
  README_ja.md
  docSite/content/zh-cn/docs/development/configuration.md
  docSite/content/zh-cn/docs/development/modelConfig/intro.md
  docSite/content/zh-cn/docs/development/modelConfig/one-api.md
  docSite/content/zh-cn/docs/development/proxy/nginx.md
  docSite/content/zh-cn/docs/development/sealos.md
  docSite/content/zh-cn/docs/development/upgrading/45.md
  docSite/content/zh-cn/docs/development/upgrading/491.md
  docSite/content/zh-cn/docs/development/upgrading/intro.md
  docSite/content/zh-cn/docs/guide/plugins/searxng_plugin_guide.md
  docSite/content/zh-cn/docs/use-cases/external-integration/wechat.md
  packages/global/core/workflow/template/system/contextExtract/type.d.ts
  packages/service/core/ai/audio/transcriptions.ts
  packages/service/core/ai/config/provider/Qwen.json
  packages/service/core/ai/embedding/index.ts
  packages/service/core/ai/rerank/index.ts
  packages/service/core/app/utils.ts
  packages/service/core/workflow/dispatch/agent/extract.ts
  packages/service/core/workflow/dispatch/index.ts
  projects/app/src/pages/api/core/ai/model/test.ts
Labels: size/L

#4102 perf: think tag parse
  docSite/content/zh-cn/docs/development/upgrading/491.md
  packages/service/core/ai/utils.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
Labels: size/S

#4109 perf: chunk read
  docSite/content/zh-cn/docs/development/upgrading/491.md
  packages/global/core/dataset/data/constants.ts
  packages/service/core/chat/saveChat.ts
  packages/service/core/dataset/data/schema.ts
  packages/web/components/common/Icon/icons/common/download.svg
  packages/web/i18n/en/chat.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/chat.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/chat.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/dataset.json
  projects/app/package.json
  projects/app/src/components/SideBar/index.tsx
  projects/app/src/pageComponents/app/detail/Logs/DetailLogsModal.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/ChatTest.tsx
  projects/app/src/pageComponents/chat/ChatQuoteList/CollectionQuoteReader.tsx
  projects/app/src/pageComponents/chat/ChatQuoteList/DownloadButton.tsx
  projects/app/src/pageComponents/chat/ChatQuoteList/ScoreTag.tsx
  projects/app/src/pages/api/core/chat/quote/getCollectionQuote.ts
  projects/app/src/pages/api/core/chat/quote/getQuote.ts
  projects/app/src/pages/api/core/dataset/collection/export.ts
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/service/core/dataset/data/controller.ts
Labels: size/XL

#4116 feat: aiproxy repo moved
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  docSite/content/zh-cn/docs/development/upgrading/490.md
Labels: size/S

#4117 feat: api dataset support pdf parse;fix: chunk reader auth
  docSite/content/zh-cn/docs/development/upgrading/491.md
  packages/service/core/dataset/apiDataset/api.ts
  packages/service/core/dataset/read.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/QuoteList.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ResponseTags.tsx
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/components/core/dataset/QuoteItem.tsx
  projects/app/src/components/core/dataset/RawSourceBox.tsx
  projects/app/src/pageComponents/app/detail/Logs/DetailLogsModal.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/ChatTest.tsx
  projects/app/src/pageComponents/chat/ChatQuoteList/CollectionQuoteReader.tsx
  projects/app/src/pageComponents/chat/ChatQuoteList/QuoteReader.tsx
  projects/app/src/pageComponents/chat/ChatQuoteList/index.tsx
  projects/app/src/pages/api/core/chat/quote/getCollectionQuote.ts
  projects/app/src/pages/api/core/chat/quote/getQuote.ts
  projects/app/src/pages/api/core/dataset/collection/create/apiCollection.ts
  projects/app/src/pages/api/core/dataset/collection/export.ts
  projects/app/src/pages/api/core/dataset/collection/read.ts
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/service/core/chat/constants.ts
  projects/app/src/service/core/chat/utils.ts
  projects/app/src/service/support/permission/auth/chat.ts
  projects/app/src/web/core/chat/api.ts
  projects/app/src/web/core/chat/context/chatItemContext.tsx
Labels: size/XL

#3979 feat: invitation link
  packages/global/common/error/code/team.ts
  packages/global/support/user/team/constant.ts
  packages/global/support/user/team/controller.d.ts
  packages/service/support/user/team/invitationLink/constants.ts
  packages/service/support/user/team/invitationLink/controllers.ts
  packages/service/support/user/team/invitationLink/schema.ts
  packages/service/support/user/team/invitationLink/type.ts
  packages/web/components/common/Avatar/AvatarGroup.tsx
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/lineStop.svg
  packages/web/components/common/Icon/icons/common/link.svg
  packages/web/i18n/en/account_team.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/account_team.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/account_team.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/Layout/index.tsx
  projects/app/src/components/support/user/team/UpdateInviteModal/index.tsx
  projects/app/src/pageComponents/account/team/CreateInvitationModal.tsx
  projects/app/src/pageComponents/account/team/GroupManage/index.tsx
  projects/app/src/pageComponents/account/team/HandleInviteModal.tsx
  projects/app/src/pageComponents/account/team/InviteModal.tsx
  projects/app/src/pageComponents/account/team/MemberTable.tsx
  projects/app/src/pages/account/team/index.tsx
  projects/app/src/web/support/user/team/api.ts
Labels: size/XL

#4118 perf: invite member code
  docSite/content/zh-cn/docs/development/upgrading/491.md
  packages/service/support/user/team/invitationLink/controllers.ts
  packages/service/support/user/team/invitationLink/schema.ts
  packages/service/support/user/team/invitationLink/type.ts
  packages/web/i18n/en/account_team.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/account_info.json
  packages/web/i18n/zh-CN/account_team.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/account_team.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/support/user/inform/UpdateContactModal.tsx
  projects/app/src/pageComponents/account/team/HandleInviteModal.tsx
  projects/app/src/pageComponents/account/team/Invite/CreateInvitationModal.tsx
  projects/app/src/pageComponents/account/team/Invite/HandleInviteModal.tsx
  projects/app/src/pageComponents/account/team/Invite/InviteModal.tsx
  projects/app/src/pageComponents/account/team/MemberTable.tsx
  projects/app/src/pageComponents/account/team/context.tsx
  projects/app/src/pages/account/info/index.tsx
  projects/app/src/pages/account/team/index.tsx
Labels: size/XL

#4123 fix: model test channel id;fix: quote reader
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ResponseTags.tsx
  projects/app/src/pageComponents/account/model/Channel/ModelTest.tsx
  projects/app/src/pageComponents/account/model/Channel/index.tsx
  projects/app/src/pageComponents/chat/ChatQuoteList/CollectionQuoteReader.tsx
  projects/app/src/pageComponents/chat/ChatQuoteList/QuoteReader.tsx
  projects/app/src/pageComponents/chat/ChatQuoteList/index.tsx
  projects/app/src/pages/api/core/ai/model/test.ts
  projects/app/src/pages/api/core/chat/quote/getCollectionQuote.ts
  projects/app/src/pages/chat/share.tsx
  projects/app/src/web/core/ai/config.ts
  projects/app/src/web/core/chat/context/chatItemContext.tsx
Labels: size/L

#4026 chore: vitest support
  .github/workflows/fastgpt-test.yaml
  .gitignore
  package.json
  packages/service/core/ai/utils.test.ts
  packages/service/test/utils.ts
  pnpm-lock.yaml
  projects/app/jest.config.js
  projects/app/package.json
  projects/app/src/pages/api/__mocks__/base.ts
  projects/app/src/pages/api/__mocks__/db/init.ts
  projects/app/src/pages/api/__mocks__/demo/demo.test.ts
  projects/app/src/pages/api/__mocks__/demo/demo.ts
  projects/app/src/pages/api/__mocks__/type.d.ts
  projects/app/src/pages/api/core/app/version/latest.test.ts
  projects/app/src/pages/api/core/app/version/lis.test.ts
  projects/app/src/pages/api/core/app/version/list.test.ts
  projects/app/src/pages/api/core/app/version/publish.test.ts
  projects/app/src/pages/api/support/outLink/list.test.ts
  projects/app/src/pages/api/support/outLink/update.test.ts
  projects/app/src/test/workflow/loopTest.json
  projects/app/src/test/workflow/simple.json
  projects/app/src/test/workflow/workflow.test.ts
  projects/app/tsconfig.json
  test/datas/users.ts
  test/mocks/index.ts
  test/mocks/request.ts
  test/setup.ts
  test/setupModels.ts
  test/test.ts
  test/utils/request.ts
  tsconfig.json
  vitest.config.mts
Labels: size/XXL

#4132 Update official_account.md
  docSite/content/zh-cn/docs/use-cases/external-integration/official_account.md
Labels: size/XS

#4138 feat/user sync universe api
  packages/global/common/system/types/index.d.ts
  projects/app/src/pageComponents/login/LoginForm/FormLayout.tsx
Labels: size/M

#4139 fix: prompt toolcall ui
  .prettierignore
  docSite/content/zh-cn/docs/development/upgrading/491.md
  packages/global/core/chat/adapt.ts
  packages/service/core/workflow/dispatch/agent/runTool/promptCall.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/src/pageComponents/account/model/Log/index.tsx
  projects/app/src/pageComponents/app/detail/Publish/index.tsx
  projects/app/src/pageComponents/dataset/detail/Import/commonProgress/DataProcess.tsx
  projects/app/src/pageComponents/dataset/detail/Info/index.tsx
  projects/app/src/pageComponents/dataset/list/CreateModal.tsx
  projects/app/src/pages/api/core/app/list.ts
  projects/app/src/pages/dataset/list/index.tsx
  projects/sandbox/package.json
Labels: size/L

#4147 pref: copy link
  packages/web/i18n/en/account_team.json
  packages/web/i18n/zh-CN/account_team.json
  packages/web/i18n/zh-Hant/account_team.json
  projects/app/src/pageComponents/account/team/Invite/InviteModal.tsx
Labels: size/S

#4145 fix: update new user sync api
  projects/app/src/web/support/user/api.ts
Labels: size/XS

#4152 hiden dataset source
  packages/web/hooks/useLinkedScroll.tsx
  packages/web/i18n/en/chat.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/chat.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/chat.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/pageComponents/chat/ChatQuoteList/CollectionQuoteItem.tsx
  projects/app/src/pageComponents/chat/ChatQuoteList/CollectionQuoteReader.tsx
  projects/app/src/pages/api/core/chat/quote/getCollectionQuote.ts
Labels: size/L

#4151 pref/sso
  packages/global/support/user/api.d.ts
  projects/app/src/pages/login/provider.tsx
Labels: size/S

#4160 pref: vitest
  package.json
  test/cases/api/core/app/version/list.test.ts
  test/cases/spec/workflow/loopTest.json
  test/cases/spec/workflow/simple.json
  test/cases/spec/workflow/workflow.test.ts
  test/setup.ts
  vitest.config.mts
Labels: size/S

#4162 fix modal close scroll
  packages/web/components/common/MyModal/index.tsx
  packages/web/hooks/useLinkedScroll.tsx
  projects/app/src/pageComponents/chat/ChatQuoteList/CollectionQuoteReader.tsx
Labels: size/XS

#4169 fix loadInitData refresh
  packages/web/hooks/useLinkedScroll.tsx
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/pageComponents/chat/ChatQuoteList/CollectionQuoteItem.tsx
  projects/app/src/pageComponents/chat/ChatQuoteList/CollectionQuoteReader.tsx
  projects/app/src/pageComponents/dataset/ApiDatasetForm.tsx
Labels: size/S

#4170 feat: mix search weight
  docSite/content/zh-cn/docs/development/upgrading/491.md
  packages/global/core/app/type.d.ts
  packages/global/core/app/utils.ts
  packages/global/core/dataset/constants.ts
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/template/system/datasetSearch.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/core/workflow/dispatch/dataset/search.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/sliderTag.svg
  packages/web/i18n/en/app.json
  packages/web/i18n/en/chat.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/chat.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/chat.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/components/Markdown/utils.ts
  projects/app/src/components/core/app/DatasetParamsModal.tsx
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/global/core/dataset/api.d.ts
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SelectDatasetParams.tsx
  projects/app/src/pageComponents/dataset/detail/Test.tsx
  projects/app/src/pages/api/core/dataset/searchTest.ts
  projects/app/src/web/core/app/utils.ts
Labels: size/L

#4173 fix: avatar error remove
  docSite/content/zh-cn/docs/development/upgrading/491.md
  packages/service/common/file/image/controller.ts
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/components/Markdown/utils.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/ChatItem.tsx
  projects/app/src/pageComponents/chat/ChatQuoteList/CollectionQuoteReader.tsx
  projects/app/src/pages/api/core/chat/quote/getCollectionQuote.ts
Labels: size/M

#4172 pref: sso getauthurl api
  packages/global/common/system/types/index.d.ts
  packages/global/support/user/constant.ts
  projects/app/src/pageComponents/login/LoginForm/FormLayout.tsx
Labels: size/M

#4176 Update docker.md
  docSite/content/zh-cn/docs/development/docker.md
Labels: size/XS

#4181 update package;fix: input data model ui
  package.json
  packages/global/package.json
  packages/service/common/string/jieba.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/package.json
  packages/web/package.json
  pnpm-lock.yaml
  projects/app/next-i18next.config.js
  projects/app/next.config.js
  projects/app/package.json
  projects/app/src/pageComponents/account/bill/BillTable.tsx
  projects/app/src/pageComponents/dataset/detail/InputDataModal.tsx
  projects/app/src/pages/api/admin/initv4818.ts
  projects/app/src/service/core/dataset/data/controller.ts
  projects/app/src/web/core/app/api.ts
  projects/app/src/web/core/app/api/app.ts
  projects/app/src/web/core/app/api/collaborator.ts
  projects/app/src/web/core/app/api/plugin.ts
  projects/app/src/web/core/app/api/template.ts
  projects/app/src/web/core/app/api/version.ts
  projects/app/src/web/core/chat/inputGuide/api.ts
  projects/app/src/web/core/dataset/api.ts
  projects/app/src/web/core/dataset/api/collaborator.ts
  projects/app/src/web/core/workflow/adapt.ts
  projects/app/src/web/core/workflow/api.ts
  projects/app/src/web/support/activity/promotion/api.ts
  projects/app/src/web/support/user/api.ts
  projects/app/src/web/support/user/inform/api.ts
  projects/app/src/web/support/user/team/api.ts
  projects/app/src/web/support/user/team/group/api.ts
  projects/app/src/web/support/user/team/org/api.ts
  projects/app/src/web/support/wallet/bill/api.ts
  projects/app/src/web/support/wallet/bill/invoice/api.ts
  projects/app/src/web/support/wallet/usage/api.ts
Labels: size/L

#4186 fix: page title refresh
  docSite/content/zh-cn/docs/development/upgrading/491.md
  projects/app/src/components/common/NextHead/index.tsx
  projects/app/src/pages/_app.tsx
Labels: size/M

#4193 fix: remove member length check when opening invite create modal
  projects/app/src/pageComponents/account/team/MemberTable.tsx
Labels: size/S

#4187 add env to check internal ip
  .npmrc
  .prettierignore
  docSite/content/zh-cn/docs/development/upgrading/491.md
  packages/service/common/string/jieba.ts
  packages/service/common/string/jieba/index.ts
  packages/service/common/system/utils.ts
  packages/service/core/dataset/data/dataTextSchema.ts
  packages/service/core/dataset/data/schema.ts
  packages/service/core/dataset/search/controller.ts
  projects/app/.env.template
  projects/app/next.config.js
  projects/app/src/pageComponents/account/TeamSelector.tsx
  projects/app/src/pages/account/info/index.tsx
  projects/app/src/pages/account/team/index.tsx
  projects/app/src/pages/api/admin/initv4818.ts
  projects/app/src/pages/api/admin/initv491.ts
  projects/app/src/service/core/dataset/data/controller.ts
Labels: size/L

#4200 update jieba package
  .github/workflows/fastgpt-preview-image.yml
  .npmrc
Labels: size/XS

#4201 package
  pnpm-lock.yaml
  projects/app/package.json
Labels: size/XS

#4208 fix: i18n
  packages/web/hooks/useI18n.ts
  projects/app/next-i18next.config.js
  projects/app/next.config.js
  projects/app/src/pages/_error.tsx
  projects/app/src/pages/account/apikey.tsx
  projects/app/src/pages/account/bill/index.tsx
  projects/app/src/pages/account/info/index.tsx
  projects/app/src/pages/account/inform.tsx
  projects/app/src/pages/account/model/index.tsx
  projects/app/src/pages/account/promotion.tsx
  projects/app/src/pages/account/setting.tsx
  projects/app/src/pages/account/team/index.tsx
  projects/app/src/pages/account/thirdParty/index.tsx
  projects/app/src/pages/account/usage/index.tsx
  projects/app/src/pages/app/detail/index.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/pages/dataset/detail/index.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/pages/index.tsx
  projects/app/src/pages/login/fastlogin.tsx
  projects/app/src/pages/login/index.tsx
  projects/app/src/pages/login/provider.tsx
  projects/app/src/pages/more/index.tsx
  projects/app/src/pages/price/index.tsx
  projects/app/src/pages/toolkit/index.tsx
  projects/app/src/web/common/system/nextjs.ts
Labels: size/M

#4207 fix: next config
  pnpm-lock.yaml
  projects/app/next.config.js
  projects/app/package.json
  projects/app/src/pageComponents/app/list/TypeTag.tsx
  projects/app/src/pageComponents/chat/ChatQuoteList/CollectionQuoteItem.tsx
  projects/app/src/pageComponents/chat/ChatQuoteList/CollectionQuoteReader.tsx
  projects/app/src/pageComponents/chat/ChatQuoteList/DownloadButton.tsx
  projects/app/src/pageComponents/chat/ChatQuoteList/QuoteItem.tsx
  projects/app/src/pageComponents/chat/ChatQuoteList/QuoteReader.tsx
  projects/app/src/pageComponents/chat/ChatQuoteList/ScoreTag.tsx
  projects/app/src/pageComponents/dataset/detail/Import/commonProgress/DataProcess.tsx
  projects/app/src/pages/_error.tsx
  projects/app/src/pages/account/apikey.tsx
  projects/app/src/pages/account/bill/index.tsx
  projects/app/src/pages/account/info/index.tsx
  projects/app/src/pages/account/inform.tsx
  projects/app/src/pages/account/model/index.tsx
  projects/app/src/pages/account/promotion.tsx
  projects/app/src/pages/account/setting.tsx
  projects/app/src/pages/account/team/index.tsx
  projects/app/src/pages/account/thirdParty/index.tsx
  projects/app/src/pages/account/usage/index.tsx
  projects/app/src/pages/api/admin/initv491.ts
  projects/app/src/pages/app/detail/index.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/chat/share.tsx
  projects/app/src/pages/chat/team.tsx
  projects/app/src/pages/dataset/detail/index.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/pages/index.tsx
  projects/app/src/pages/login/fastlogin.tsx
  projects/app/src/pages/login/index.tsx
  projects/app/src/pages/login/provider.tsx
  projects/app/src/pages/more/index.tsx
  projects/app/src/pages/price/index.tsx
  projects/app/src/pages/toolkit/index.tsx
  projects/app/src/web/common/i18n/utils.ts
Labels: size/L

#4217 doc: invitaion link
  docSite/assets/imgs/guide/team_permissions/invitation_link/image1.png
  docSite/assets/imgs/guide/team_permissions/invitation_link/image2.png
  docSite/assets/imgs/guide/team_permissions/invitation_link/image3.png
  docSite/assets/imgs/guide/team_permissions/invitation_link/image4.png
  docSite/assets/imgs/guide/team_permissions/invitation_link/image5.png
  docSite/content/zh-cn/docs/guide/team_permissions/invitation_link.md
Labels: size/M

#4216 docs: Add PPIO integration documentation
  README.md
  docSite/content/zh-cn/docs/development/modelConfig/ppio.md
Labels: size/L

#4211 export chat log with contact
  packages/web/i18n/en/app.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-Hant/app.json
  projects/app/src/pages/api/core/app/exportChatLogs.ts
Labels: size/L

#4221 feat: custom dataset split sign
  docSite/content/zh-cn/docs/development/upgrading/492.md
  packages/global/common/string/textSplitter.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/dataset.json
  projects/app/src/pageComponents/dataset/detail/Import/commonProgress/DataProcess.tsx
Labels: size/L

#4204 add external variable debug
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariableInput.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariablePopover.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderInput.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/renderPluginInput.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/hooks/useDebug.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
  projects/app/src/pageComponents/app/detail/useChatTest.tsx
  projects/app/src/pageComponents/chat/ChatHeader.tsx
  projects/app/src/web/core/chat/context/chatItemContext.tsx
Labels: size/XL

#4225 perf: custom varialbe
  docSite/content/zh-cn/docs/development/upgrading/492.md
  packages/web/i18n/en/chat.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/chat.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/chat.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariableInput.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariablePopover.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/renderPluginInput.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/ChatTest.tsx
Labels: size/M

#4234 solve the root orglist
  projects/app/src/pageComponents/account/team/OrgManage/index.tsx
Labels: size/XS

#4229 fix: invite link
  packages/service/support/user/team/invitationLink/schema.ts
  packages/service/support/user/team/invitationLink/type.ts
  projects/app/src/pageComponents/account/team/Invite/CreateInvitationModal.tsx
  projects/app/src/pageComponents/account/team/Invite/InviteModal.tsx
  projects/app/src/web/support/user/team/api.ts
  test/datas/users.ts
Labels: size/L

#4237 feat: sync api collection will refresh title;perf: invite link ux
  docSite/content/zh-cn/docs/development/upgrading/492.md
  docSite/content/zh-cn/docs/guide/knowledge_base/api_dataset.md
  packages/global/common/string/tools.ts
  packages/global/core/dataset/apiDataset.d.ts
  packages/global/core/dataset/collection/utils.ts
  packages/global/core/dataset/constants.ts
  packages/service/core/dataset/apiDataset/api.ts
  packages/service/core/dataset/collection/utils.ts
  packages/service/core/dataset/read.ts
  packages/service/support/user/team/invitationLink/schema.ts
  packages/web/common/zustand/index.ts
  packages/web/hooks/useCopyData.tsx
  packages/web/i18n/en/account_team.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/account_team.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/account_team.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/dataset.json
  packages/web/package.json
  packages/web/store/useCommonStore.ts
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/src/components/Layout/index.tsx
  projects/app/src/global/core/dataset/api.d.ts
  projects/app/src/pageComponents/account/team/Invite/CreateInvitationModal.tsx
  projects/app/src/pageComponents/account/team/Invite/InviteModal.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/index.tsx
  projects/app/src/pageComponents/dataset/detail/NavBar.tsx
  projects/app/src/pages/api/core/dataset/collection/create/apiCollection.ts
  projects/app/src/pages/api/core/dataset/collection/create/reTrainingCollection.ts
  projects/app/src/pages/api/core/dataset/file/getPreviewChunks.ts
  projects/app/src/pages/api/core/dataset/training/getQueueLen.ts
  projects/app/src/web/common/system/useSystemStore.ts
  projects/app/src/web/core/chat/context/useChatStore.ts
  projects/app/src/web/core/chat/storeShareChat.ts
  projects/app/src/web/core/dataset/api.ts
  projects/app/src/web/core/dataset/context/datasetPageContext.tsx
  projects/app/src/web/core/dataset/store/dataset.ts
  projects/app/src/web/core/dataset/store/markdata.ts
  projects/app/src/web/core/dataset/store/searchTest.ts
  projects/app/src/web/support/user/useUserStore.ts
Labels: size/XL

#4235 Sso
  packages/global/common/system/types/index.d.ts
  packages/global/support/user/api.d.ts
  packages/global/support/user/constant.ts
  projects/app/src/pageComponents/account/team/OrgManage/index.tsx
  projects/app/src/pageComponents/login/LoginForm/FormLayout.tsx
  projects/app/src/pages/login/provider.tsx
  projects/app/src/web/support/user/api.ts
Labels: size/M

#4227 fix variable sync & popover button height
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariableInput.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariablePopover.tsx
Labels: size/L

#4141 feat: node prompt version
  packages/global/core/ai/prompt/AIChat.ts
  packages/global/core/ai/prompt/agent.ts
  packages/global/core/ai/type.d.ts
  packages/global/core/app/constants.ts
  packages/global/core/workflow/template/input.ts
  packages/global/core/workflow/template/system/aiChat/index.ts
  packages/global/core/workflow/template/system/tools.ts
  packages/service/core/ai/functions/createQuestionGuide.ts
  packages/service/core/workflow/dispatch/agent/classifyQuestion.ts
  packages/service/core/workflow/dispatch/agent/extract.ts
  packages/service/core/workflow/dispatch/agent/runTool/index.ts
  packages/service/core/workflow/dispatch/chat/oneapi.ts
  packages/web/i18n/zh-CN/common.json
  projects/app/src/components/core/app/QGConfig.tsx
  projects/app/src/pageComponents/account/model/AddModelBox.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SettingQuotePrompt.tsx
  projects/app/src/web/core/app/utils.ts
Labels: size/L

#4241 fix DatasetSelectModal.tsx
  projects/app/src/components/core/app/DatasetSelectModal.tsx
Labels: size/M

#4243 fix: dataset selector load error
  docSite/content/zh-cn/docs/development/upgrading/491.md
  packages/global/common/parentFolder/type.d.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-Hant/app.json
  projects/app/src/components/core/app/DatasetSelectModal.tsx
  projects/app/src/components/core/dataset/SelectModal.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/Header.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/components/ToolSelectModal.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/NodeTemplatesModal.tsx
  projects/app/src/pageComponents/app/detail/useChatTest.tsx
  projects/app/src/pageComponents/app/list/context.tsx
  projects/app/src/pages/api/core/app/exportChatLogs.ts
  projects/app/src/pages/api/core/app/folder/path.ts
  projects/app/src/pages/api/core/app/plugin/path.ts
  projects/app/src/pages/api/core/dataset/paths.ts
  projects/app/src/pages/dataset/list/context.tsx
  projects/app/src/web/core/app/api/app.ts
  projects/app/src/web/core/app/api/plugin.ts
  projects/app/src/web/core/dataset/api.ts
  projects/app/src/web/core/dataset/context/datasetPageContext.tsx
Labels: size/L

#4246 fix: vector name
  projects/app/src/components/core/app/DatasetSelectModal.tsx
Labels: size/XS

#4249 fix: nextjs 14.2.24 cannot auto create local storage
  projects/app/src/pages/chat/share.tsx
  projects/app/src/web/core/chat/storeShareChat.ts
Labels: size/M

#4250 fix: nextjs 14.2.24 cannot auto create local storage (#4249)
  projects/app/src/pages/chat/share.tsx
  projects/app/src/web/core/chat/storeShareChat.ts
Labels: size/M

#4256 update doc
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  docSite/content/zh-cn/docs/development/upgrading/491.md
Labels: size/S

#4265 perf: ai proxy
  docSite/content/zh-cn/docs/development/upgrading/492.md
  projects/app/src/pageComponents/account/model/Channel/index.tsx
Labels: size/M

#4266 fix input form label overflow
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
Labels: size/M

#4279 4.9.1 fix dataset
  packages/service/core/app/utils.ts
Labels: size/XS

#4280 4.9.1 fix dataset (#4279)
  packages/service/core/app/utils.ts
Labels: size/XS

#4284 add mistral-ocr support as a plugin like pdf-marker
  plugins/model/pdf-mistral/.env
  plugins/model/pdf-mistral/README.md
  plugins/model/pdf-mistral/api_mp.py
  plugins/model/pdf-mistral/requirements.txt
Labels: size/L

#4272 add model test log
  docSite/content/zh-cn/docs/development/upgrading/492.md
  packages/global/core/plugin/type.d.ts
  packages/global/package.json
  packages/service/core/ai/audio/transcriptions.ts
  packages/service/core/app/plugin/controller.ts
  packages/service/core/workflow/dispatch/plugin/run.ts
  packages/service/package.json
  packages/web/i18n/en/account_model.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/account_model.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/account_model.json
  packages/web/i18n/zh-Hant/dataset.json
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/src/components/core/app/DatasetSelectModal.tsx
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/components/core/chat/components/WholeResponseModal.tsx
  projects/app/src/pageComponents/account/model/Channel/index.tsx
  projects/app/src/pageComponents/account/model/Log/index.tsx
  projects/app/src/pageComponents/dataset/detail/Import/commonProgress/PreviewData.tsx
  projects/app/src/pages/api/core/ai/model/test.ts
  projects/app/src/pages/api/core/dataset/file/getPreviewChunks.ts
  projects/app/src/pages/api/v1/audio/transcriptions.ts
Labels: size/L

#4294 Ollama接入文档
  docSite/assets/imgs/Ollama-aiproxy1.png
  docSite/assets/imgs/Ollama-aiproxy2.png
  docSite/assets/imgs/Ollama-aiproxy3.png
  docSite/assets/imgs/Ollama-direct1.png
  docSite/assets/imgs/Ollama-models1.png
  docSite/assets/imgs/Ollama-models2.png
  docSite/assets/imgs/Ollama-models3.png
  docSite/assets/imgs/Ollama-models4.png
  docSite/assets/imgs/Ollama-oneapi1.png
  docSite/assets/imgs/Ollama-oneapi2.png
  docSite/assets/imgs/Ollama-oneapi3 .png
  docSite/assets/imgs/Ollama-pull.png
  docSite/content/zh-cn/docs/development/custom-models/ollama.md
Labels: size/L

#4296 perf: ai proxy log remove retry log；perf: workflow type auto parse；add chunk spliter test
  docSite/content/zh-cn/docs/development/upgrading/492.md
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/template/input.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/web/i18n/en/account_model.json
  packages/web/i18n/zh-CN/account_model.json
  packages/web/i18n/zh-Hant/account_model.json
  projects/app/src/global/aiproxy/type.d.ts
  projects/app/src/pageComponents/account/model/Log/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Reference.tsx
  projects/app/src/web/core/ai/channel.ts
  test/cases/function/packages/global/common/string/textSplitter.test.ts
Labels: size/L

#4276 add pdf-mineru
  plugins/model/pdf-mineru/README.md
  plugins/model/pdf-mineru/main.py
Labels: size/L

#4304 tmp org api rewrite
  docSite/content/zh-cn/docs/development/upgrading/492.md
  packages/global/support/user/team/org/type.d.ts
  packages/service/support/permission/memberGroup/memberGroupSchema.ts
  projects/app/package.json
  projects/app/src/pageComponents/account/team/GroupManage/GroupManageMember.tsx
  projects/app/src/pageComponents/account/team/MemberTable.tsx
  projects/app/src/pageComponents/account/team/OrgManage/OrgInfoModal.tsx
  projects/app/src/pageComponents/account/team/OrgManage/OrgMemberManageModal.tsx
  projects/app/src/pageComponents/account/team/OrgManage/OrgMoveModal.tsx
  projects/app/src/pageComponents/account/team/OrgManage/index.tsx
  projects/app/src/pageComponents/account/team/context.tsx
  projects/app/src/web/support/user/team/org/api.ts
  projects/app/src/web/support/user/useUserStore.ts
Labels: size/L

#4317 update search filter code
  packages/service/core/dataset/search/controller.ts
Labels: size/XS

#4316 pref: member/group/org
  packages/global/support/user/team/org/api.d.ts
  packages/global/support/user/team/org/constant.ts
  packages/global/support/user/team/org/type.d.ts
  packages/service/support/permission/auth/org.ts
  packages/web/components/common/Avatar/AvatarGroup.tsx
  projects/app/src/components/support/permission/ChangeOwnerModal/index.tsx
  projects/app/src/components/support/permission/MemberManager/MemberModal.tsx
  projects/app/src/pageComponents/account/team/GroupManage/GroupInfoModal.tsx
  projects/app/src/pageComponents/account/team/GroupManage/GroupManageMember.tsx
  projects/app/src/pageComponents/account/team/GroupManage/GroupTransferOwnerModal.tsx
  projects/app/src/pageComponents/account/team/GroupManage/index.tsx
  projects/app/src/pageComponents/account/team/MemberTable.tsx
  projects/app/src/pageComponents/account/team/OrgManage/OrgInfoModal.tsx
  projects/app/src/pageComponents/account/team/OrgManage/OrgMemberManageModal.tsx
  projects/app/src/pageComponents/account/team/OrgManage/OrgMoveModal.tsx
  projects/app/src/pageComponents/account/team/OrgManage/OrgTree.tsx
  projects/app/src/pageComponents/account/team/OrgManage/index.tsx
  projects/app/src/pageComponents/account/team/context.tsx
  projects/app/src/web/support/user/team/org/api.ts
  projects/app/src/web/support/user/team/org/hooks/useOrg.tsx
Labels: size/XL

#4322 fix: member list, login button
  projects/app/src/components/support/permission/MemberManager/MemberModal.tsx
  projects/app/src/pageComponents/account/team/OrgManage/OrgMemberManageModal.tsx
  projects/app/src/pageComponents/login/LoginForm/FormLayout.tsx
Labels: size/XS

#4324 perf: member group
  packages/global/support/permission/memberGroup/api.d.ts
  packages/global/support/permission/memberGroup/type.d.ts
  packages/global/support/user/api.d.ts
  packages/service/support/user/team/controller.ts
  projects/app/src/components/support/permission/MemberManager/MemberModal.tsx
  projects/app/src/components/support/user/team/Info/MemberTag.tsx
  projects/app/src/pageComponents/account/team/GroupManage/GroupInfoModal.tsx
  projects/app/src/pageComponents/account/team/GroupManage/GroupManageMember.tsx
  projects/app/src/pageComponents/account/team/GroupManage/GroupTransferOwnerModal.tsx
  projects/app/src/pageComponents/account/team/GroupManage/index.tsx
  projects/app/src/pageComponents/account/team/MemberTable.tsx
  projects/app/src/pageComponents/account/team/OrgManage/index.tsx
  projects/app/src/pageComponents/account/team/context.tsx
  projects/app/src/web/support/user/team/group/api.ts
Labels: size/L

#4308 fixed: permission error when viewing database search node responses
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/QuoteList.tsx
Labels: size/XS

#4330 fix: group
  projects/app/src/pageComponents/account/team/GroupManage/GroupInfoModal.tsx
  projects/app/src/pageComponents/account/team/GroupManage/GroupManageMember.tsx
Labels: size/XS

#4346 perf: intro wrap
  projects/app/src/pageComponents/app/list/List.tsx
  projects/app/src/pageComponents/dataset/list/List.tsx
Labels: size/XS

#4347 perf: long org name ui
  projects/app/src/components/common/folder/Path.tsx
  projects/app/src/components/support/user/team/Info/MemberTag.tsx
  projects/app/src/pageComponents/account/team/OrgManage/index.tsx
Labels: size/S

#4307 Inform
  packages/global/support/user/inform/constants.ts
  packages/global/support/user/inform/type.d.ts
  packages/web/hooks/useEditTextarea.tsx
  packages/web/i18n/en/account_info.json
  packages/web/i18n/en/account_inform.json
  packages/web/i18n/en/account_team.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/user.json
  packages/web/i18n/zh-CN/account_info.json
  packages/web/i18n/zh-CN/account_inform.json
  packages/web/i18n/zh-CN/account_team.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/user.json
  packages/web/i18n/zh-Hant/account_info.json
  packages/web/i18n/zh-Hant/account_inform.json
  packages/web/i18n/zh-Hant/account_team.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/user.json
  projects/app/src/components/support/user/inform/ImportantInform.tsx
  projects/app/src/pageComponents/account/NotificationDetailsModal.tsx
  projects/app/src/pageComponents/account/team/MemberTable.tsx
  projects/app/src/pages/account/info/index.tsx
  projects/app/src/pages/account/inform.tsx
  projects/app/src/web/support/user/inform/api.ts
  projects/app/src/web/support/user/team/api.ts
Labels: size/XL

#4353 perf: member tableui
  docSite/content/zh-cn/docs/development/upgrading/492.md
  packages/web/hooks/useEditTextarea.tsx
  packages/web/i18n/en/account_team.json
  packages/web/i18n/zh-CN/account_team.json
  packages/web/i18n/zh-Hant/account_team.json
  projects/app/src/pageComponents/account/team/MemberTable.tsx
  projects/app/src/web/common/hooks/useEditTitle.tsx
Labels: size/L

#4357 fix: ts
  packages/web/hooks/useEditTextarea.tsx
Labels: size/L

#4334 docs: Add SSO Markdown Doc
  docSite/assets/imgs/sso1.png
  docSite/assets/imgs/sso10.png
  docSite/assets/imgs/sso11.png
  docSite/assets/imgs/sso12.png
  docSite/assets/imgs/sso13.png
  docSite/assets/imgs/sso14.png
  docSite/assets/imgs/sso15.png
  docSite/assets/imgs/sso16.png
  docSite/assets/imgs/sso17.png
  docSite/assets/imgs/sso2.png
  docSite/assets/imgs/sso3.png
  docSite/assets/imgs/sso4.png
  docSite/assets/imgs/sso5.png
  docSite/assets/imgs/sso6.png
  docSite/assets/imgs/sso7.png
  docSite/assets/imgs/sso8.png
  docSite/assets/imgs/sso9.png
  docSite/assets/imgs/sso_update1.png
  docSite/content/zh-cn/docs/development/upgrading/492.md
  docSite/content/zh-cn/docs/guide/admin/sso.md
  docSite/content/zh-cn/docs/guide/admin/sso_dingtalk.md
  docSite/content/zh-cn/docs/guide/admin/teamMode.md
Labels: size/XL

#4355 pref: useScrollPagination support debounce and throttle.
  packages/web/hooks/useScrollPagination.tsx
  projects/app/src/components/support/permission/MemberManager/MemberModal.tsx
  projects/app/src/pageComponents/account/team/GroupManage/GroupManageMember.tsx
  projects/app/src/pageComponents/account/team/GroupManage/GroupTransferOwnerModal.tsx
  projects/app/src/pageComponents/account/team/MemberTable.tsx
  projects/app/src/pageComponents/account/team/OrgManage/OrgMemberManageModal.tsx
  projects/app/src/pageComponents/account/team/OrgManage/index.tsx
  projects/app/src/pageComponents/app/detail/PublishHistoriesSlider.tsx
  projects/app/src/web/support/user/team/org/hooks/useOrg.tsx
Labels: size/L

#4365 fix: simple app all_app button
  projects/app/src/components/common/folder/Path.tsx
Labels: size/XS

#4363 add qwen long
  packages/service/core/ai/config/provider/Qwen.json
Labels: size/S

#4359 add curl and pic
  docSite/assets/imgs/sso18.png
  docSite/assets/imgs/sso2.png
  docSite/content/zh-cn/docs/guide/admin/sso.md
Labels: size/L

#4370 perf: sso doc
  docSite/content/zh-cn/docs/guide/admin/sso.md
Labels: size/L

#4366 feat: Add support for independent loading states to optimize user experience during model testing
  projects/app/src/pageComponents/account/model/Channel/ModelTest.tsx
Labels: size/M

#4375 perf: update test model ux
  docSite/content/zh-cn/docs/development/upgrading/492.md
  projects/app/src/pageComponents/account/model/Channel/ModelTest.tsx
Labels: size/L

#4377 修复了几个链接
  docSite/content/zh-cn/docs/development/custom-models/bge-rerank.md
  docSite/content/zh-cn/docs/development/custom-models/chatglm2.md
  plugins/model/rerank-bge/README.md
Labels: size/S

#4380 Python Sandbox
  packages/global/core/workflow/template/system/sandbox/constants.ts
  packages/global/core/workflow/template/system/sandbox/index.ts
  packages/service/core/workflow/dispatch/code/run.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/service/worker/readFile/extension/docx.ts
  packages/web/components/common/Textarea/CodeEditor/Editor.tsx
  packages/web/components/common/Textarea/CodeEditor/index.tsx
  packages/web/components/common/Textarea/CodeEditor/usePythonCompletion.ts
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh-CN/workflow.json
  packages/web/i18n/zh-Hant/workflow.json
  plugins/webcrawler/deploy/docker-compose.yaml
  plugins/webcrawler/deploy/searxng/limiter.toml
  plugins/webcrawler/deploy/searxng/settings.yml
  projects/README.md
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeCode.tsx
  projects/sandbox/Dockerfile
  projects/sandbox/requirements.txt
  projects/sandbox/src/sandbox/constants.ts
  projects/sandbox/src/sandbox/sandbox.controller.ts
  projects/sandbox/src/sandbox/utils.ts
  projects/sandbox/testSystemCall.sh
  test/cases/function/packages/global/common/string/textSplitter.test.ts
Labels: size/XL

#4381 doc
  docSite/content/zh-cn/docs/development/upgrading/492.md
  packages/web/i18n/en/account_model.json
  packages/web/i18n/zh-CN/account_model.json
  packages/web/i18n/zh-Hant/account_model.json
  projects/app/src/global/aiproxy/constants.ts
Labels: size/M

#4339 feat : Added support for interactive nodes in the debugging interface
  .vscode/launch.json
  packages/global/core/workflow/template/system/interactive/type.d.ts
  packages/global/core/workflow/type/node.d.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/interactive/formInput.ts
  packages/service/core/workflow/dispatch/interactive/userSelect.ts
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/components/core/chat/components/Interactive/InteractiveComponents.tsx
  projects/app/src/global/core/workflow/api.d.ts
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderDebug/InteractiveComponents/DebugInteractive.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderDebug/NodeDebugResponse.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/context/index.tsx
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/core/workflow/debug.ts
Labels: size/XXL

#4385 fix child app update variables
  packages/global/core/workflow/runtime/type.d.ts
  packages/service/core/workflow/dispatch/plugin/run.ts
  packages/service/core/workflow/dispatch/plugin/runApp.ts
  packages/service/core/workflow/dispatch/tools/runUpdateVar.ts
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/ChatTest.tsx
Labels: size/S

#4343 add email plugin
  packages/plugins/package.json
  packages/plugins/register.ts
  packages/plugins/src/email/index.ts
  packages/plugins/src/email/template.json
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/plugins/email.svg
  pnpm-lock.yaml
Labels: size/XL

#4386 update doc
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  docSite/content/zh-cn/docs/development/upgrading/492.md
  docSite/content/zh-cn/docs/development/upgrading/493.md
  test/cases/function/packages/global/common/string/textSplitter.test.ts
Labels: size/M

#4398 chore: edit the version number
  projects/app/package.json
Labels: size/XS

#4401 fix: sso.md
  docSite/content/zh-cn/docs/guide/admin/sso.md
Labels: size/XS

#4404 Update:知识库名称搜索出文件夹后，点击文件夹未置空搜索框，导致进不了文件夹的下一级，工作台搜索也有此问题
  projects/app/src/pageComponents/dataset/list/List.tsx
Labels: size/XS

#4405 Update:同知识库搜索问题
  projects/app/src/pageComponents/app/list/List.tsx
Labels: size/XS

#4408 update doc
  docSite/content/zh-cn/docs/development/upgrading/494.md
  packages/global/core/workflow/runtime/utils.ts
  projects/app/src/pageComponents/account/team/MemberTable.tsx
Labels: size/S

#4412 Update sso.md
  docSite/content/zh-cn/docs/guide/admin/sso.md
Labels: size/XS

#4311 dataset data training state
  packages/global/core/dataset/type.d.ts
  packages/service/core/dataset/training/schema.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/maximize.svg
  packages/web/components/common/Icon/icons/common/running.svg
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/dataset.json
  projects/app/src/global/core/dataset/type.d.ts
  projects/app/src/pageComponents/dataset/detail/CollectionCard/TrainingStates.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/index.tsx
  projects/app/src/pageComponents/dataset/detail/DataCard.tsx
  projects/app/src/pages/api/core/dataset/collection/detail.ts
  projects/app/src/pages/api/core/dataset/collection/listV2.ts
  projects/app/src/pages/api/core/dataset/collection/trainingDetail.ts
  projects/app/src/pages/api/core/dataset/training/deleteTrainingData.ts
  projects/app/src/pages/api/core/dataset/training/getTrainingDataDetail.ts
  projects/app/src/pages/api/core/dataset/training/getTrainingError.ts
  projects/app/src/pages/api/core/dataset/training/updateTrainingData.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/service/events/generateQA.ts
  projects/app/src/service/events/generateVector.ts
  projects/app/src/web/core/dataset/api.ts
  projects/app/src/web/core/dataset/constants.ts
Labels: size/XXL
