Repository labring/FastGPT, pull requests merged in 2025-07, with the labels that each got.

#5123 mcp call tools timeout
  packages/service/core/app/mcp.ts
  projects/app/src/web/core/app/api/plugin.ts
Labels: size/S

#5129 Yamljs
  deploy/docker/yml.js
Labels: size/S

#5135 docs: update plugin design doc
  .github/workflows/docs-preview.yml
  .github/workflows/fastgpt-preview-image.yml
  docSite/content/zh-cn/docs/development/design/design_plugin.md
  docSite/content/zh-cn/docs/guide/plugins/design_plugin.md
Labels: size/L

#5139 update yaml and yml.js
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-oceanbase/docker-compose.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  deploy/docker/yml.js
  docSite/content/zh-cn/docs/development/docker.md
  docSite/content/zh-cn/docs/development/upgrading/4100.md
Labels: size/M

#5145 update deploy doc
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-oceanbase/docker-compose.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  deploy/docker/yml.js
  docSite/content/zh-cn/docs/development/docker.md
  docSite/content/zh-cn/docs/development/upgrading/4100.md
Labels: size/M

#5149 fix: search type
  .github/workflows/fastgpt-preview-image.yml
  packages/web/core/workflow/constants.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-Hant/app.json
Labels: size/S

#5153 fix: reference history format;perf: add error to chat log
  docSite/content/zh-cn/docs/development/upgrading/4101.md
  packages/service/core/workflow/dispatch/utils.ts
  projects/app/src/pageComponents/app/detail/Logs/index.tsx
  projects/app/src/pages/api/core/app/getChatLogs.ts
  projects/app/src/service/common/system/cron.ts
  projects/app/src/service/core/app/utils.ts
  test/cases/function/packages/service/core/app/workflow/dispatch/utils.test.ts
Labels: size/L

#5162 Update 4101.md
  docSite/content/zh-cn/docs/development/upgrading/4101.md
Labels: size/XS

#5156 echarts crush catch
  projects/app/src/components/Markdown/img/EChartsCodeBlock.tsx
Labels: size/XS

#5120 Sync dataset
  docSite/content/zh-cn/docs/guide/knowledge_base/third_dataset.md
  packages/global/core/dataset/api.d.ts
  packages/global/core/dataset/apiDataset/type.d.ts
  packages/global/core/dataset/collection/constants.ts
  packages/global/core/dataset/type.d.ts
  packages/service/common/bullmq/index.ts
  packages/service/core/dataset/apiDataset/custom/api.ts
  packages/service/core/dataset/apiDataset/feishuDataset/api.ts
  packages/service/core/dataset/apiDataset/yuqueDataset/api.ts
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/collection/schema.ts
  packages/service/core/dataset/collection/utils.ts
  packages/service/core/dataset/datasetSync/index.ts
  packages/service/support/permission/teamLimit.ts
  packages/web/common/file/hooks/useSelectFile.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/dataset.json
  pnpm-lock.yaml
  projects/app/src/pageComponents/dataset/detail/CollectionCard/Context.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/Header.tsx
  projects/app/src/pageComponents/dataset/detail/Import/diffSource/APIDataset.tsx
  projects/app/src/pages/api/admin/initv4101.ts
  projects/app/src/pages/api/admin/initv494.ts
  projects/app/src/pages/api/admin/websiteSync.ts
  projects/app/src/pages/api/core/dataset/collection/create/apiCollectionV2.ts
  projects/app/src/pages/api/core/dataset/delete.ts
  projects/app/src/pages/api/core/dataset/detail.ts
  projects/app/src/pages/api/core/dataset/update.ts
  projects/app/src/web/core/dataset/api.ts
Labels: size/XL

#5127 add dynamic inputRender
  packages/web/components/common/MySelect/index.tsx
  packages/web/components/common/Textarea/JsonEditor/index.tsx
  packages/web/components/common/Textarea/PromptEditor/Editor.tsx
  packages/web/components/common/Textarea/PromptEditor/index.module.scss
  packages/web/components/common/Textarea/PromptEditor/index.tsx
  packages/web/styles/theme.ts
  projects/app/src/components/InputRender/constant.ts
  projects/app/src/components/InputRender/index.tsx
  projects/app/src/components/InputRender/type.d.ts
  projects/app/src/components/InputRender/utils.ts
  projects/app/src/components/Select/FileSelector.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariableInput.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariableInputForm.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariableInputItem.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariablePopover.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderInput.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/renderPluginInput.tsx
  projects/app/src/components/core/chat/components/Interactive/InteractiveComponents.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/components/ConfigToolModal.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/hooks/useDebug.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodePluginIO/NodePluginConfig.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeVariableUpdate.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/JsonEditor.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/NumberInput.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Select.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SelectLLMModel.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SelectMulti.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Switch.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/TextInput.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Textarea.tsx
  projects/app/src/pageComponents/app/plugin/SecretInputModal.tsx
Labels: size/XXL

#5166 feat: update success message for dataset sync, revise related i18n te…
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dataset.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/dataset.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/dataset.json
  projects/app/src/pageComponents/dataset/detail/CollectionCard/Context.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/Header.tsx
  projects/app/src/pageComponents/dataset/detail/Import/diffSource/APIDataset.tsx
  projects/app/src/pages/api/admin/initv4101.ts
  projects/app/src/pages/api/core/dataset/collection/create/apiCollectionV2.ts
Labels: size/L

#5177 fix form render
  packages/web/hooks/useSafeTranslation.ts
  packages/web/i18n/constant.ts
  packages/web/types/i18next.d.ts
  projects/app/src/components/core/app/formRender/index.tsx
  projects/app/src/components/core/chat/ChatContainer/PluginRunBox/components/RenderInput.tsx
  projects/app/src/components/core/chat/components/Interactive/InteractiveComponents.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/components/ConfigToolModal.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/CommonInputForm.tsx
  projects/app/src/pageComponents/app/plugin/SecretInputModal.tsx
Labels: size/L

#5176 fix: Fixed the issue where anchor (`<a>`) tags in reply content could not properly open links in a new tab or window.
  projects/app/src/components/Markdown/codeBlock/iframe-html.tsx
Labels: size/XS

#5195 Bing ad
  packages/global/support/marketing/type.d.ts
  projects/app/src/pageComponents/login/RegisterForm.tsx
  projects/app/src/pages/login/provider.tsx
  projects/app/src/web/context/useInitApp.ts
  projects/app/src/web/support/marketing/utils.ts
  projects/app/src/web/support/user/api.ts
Labels: size/M

#5204 Update 4101.md
  docSite/content/zh-cn/docs/development/upgrading/4101.md
Labels: size/XS

#5168 Match SSE for FastGPT
  packages/service/core/app/tool/api.ts
  packages/service/core/workflow/dispatch/plugin/runTool.ts
Labels: size/L

#5206 Feat: system tool support stream response
  docSite/content/zh-cn/docs/development/upgrading/4101.md
  docSite/content/zh-cn/docs/guide/dashboard/workflow/tool.md
  docSite/content/zh-cn/docs/use-cases/app-cases/submit_application_template.md
  docSite/hugo.toml
  docSite/static/llms-full.txt
  packages/global/common/middle/tracks/constants.ts
  packages/service/common/middle/tracks/utils.ts
  packages/service/core/app/tool/api.ts
  packages/service/core/workflow/dispatch/plugin/runTool.ts
  packages/service/package.json
  pnpm-lock.yaml
Labels: size/L

#5207 Update README.md
  README.md
Labels: size/XS

#5208 update project domain
  .github/ISSUE_TEMPLATE/bugs.md
  README.md
  README_en.md
  README_ja.md
  docSite/content/zh-cn/docs/agreement/open-source.md
  docSite/content/zh-cn/docs/development/intro.md
  docSite/content/zh-cn/docs/development/modelConfig/ppio.md
  docSite/content/zh-cn/docs/development/openapi/dataset.md
  docSite/content/zh-cn/docs/development/openapi/share.md
  docSite/content/zh-cn/docs/development/sealos.md
  docSite/content/zh-cn/docs/guide/dashboard/workflow/http.md
  docSite/content/zh-cn/docs/guide/knowledge_base/websync.md
  docSite/content/zh-cn/docs/intro.md
  docSite/static/llms-full.txt
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-Hant/common.json
  plugins/model/rerank-bge/README.md
  projects/app/public/docs/chatProblem.md
  projects/app/src/components/support/apikey/Table.tsx
  projects/app/src/service/common/system/index.ts
  test/cases/function/packages/global/common/string/textSplitter.test.ts
Labels: size/L

#5209 fix: apidataset don`t support pdfEnhance
  packages/service/core/dataset/read.ts
Labels: size/XS

#5211 fix: ns
  packages/web/hooks/useSafeTranslation.ts
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/components/NodeTemplates/list.tsx
Labels: size/S

#5210 update version doc
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-oceanbase/docker-compose.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  deploy/docker/yml.js
  docSite/content/zh-cn/docs/development/upgrading/4101.md
Labels: size/M

#5217 fix:collection search
  projects/app/src/pages/api/core/dataset/collection/listV2.ts
Labels: size/XS

#5213 Enhance WeChat login functionality
  packages/global/support/user/api.d.ts
  projects/app/src/pageComponents/login/LoginForm/WechatForm.tsx
  projects/app/src/pages/login/index.tsx
  projects/app/src/web/support/user/api.ts
Labels: size/M

#5219 compatible with old enums
  packages/global/core/workflow/utils.ts
  packages/web/components/common/Textarea/PromptEditor/type.d.ts
  projects/app/src/components/core/app/VariableEdit.tsx
  projects/app/src/components/core/app/formRender/index.tsx
  projects/app/src/components/core/app/formRender/type.d.ts
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeHttp/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeVariableUpdate.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/CommonInputForm.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SettingQuotePrompt.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/utils.tsx
  projects/app/src/web/core/app/utils.ts
  projects/app/src/web/core/workflow/adapt.ts
Labels: size/M

#5221 compatible with old enums
  projects/app/src/components/core/app/VariableEdit.tsx
  projects/app/src/components/core/app/formRender/index.tsx
  projects/app/src/components/core/app/formRender/type.d.ts
Labels: size/S

#5218 feat: support signoz
  packages/service/common/otel/const.ts
  packages/service/common/otel/log/index.ts
  packages/service/common/otel/trace/register.ts
  packages/service/common/system/log.ts
  packages/service/package.json
  pnpm-lock.yaml
  projects/app/.env.template
  projects/app/src/instrumentation.ts
Labels: size/M

#5241 docs: update design plugin doc
  docSite/content/zh-cn/docs/development/design/design_plugin.md
Labels: size/XS

#5243 fix default model select
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/CommonInputForm.tsx
Labels: size/XS

#5246 perf: copy hook
  docSite/content/zh-cn/docs/development/upgrading/4102.md
  packages/web/hooks/useCopyData.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/TrainingStates.tsx
Labels: size/M

#5247 fix: variables init
  projects/app/src/components/core/app/formRender/LabelAndForm.tsx
  projects/app/src/components/core/app/formRender/utils.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariableInputForm.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariablePopover.tsx
Labels: size/M

#5248 Var render
  projects/app/src/components/core/app/formRender/index.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/VariablePopover.tsx
Labels: size/XS

#5083 add app evaluation
  packages/global/common/error/code/user.ts
  packages/global/core/app/evaluation/api.d.ts
  packages/global/core/app/evaluation/constants.ts
  packages/global/core/app/evaluation/type.d.ts
  packages/global/core/app/evaluation/utils.ts
  packages/global/core/app/type.d.ts
  packages/global/support/user/audit/constants.ts
  packages/global/support/wallet/usage/api.d.ts
  packages/global/support/wallet/usage/constants.ts
  packages/global/support/wallet/usage/type.d.ts
  packages/service/common/bullmq/index.ts
  packages/service/core/app/evaluation/evalItemSchema.ts
  packages/service/core/app/evaluation/evalSchema.ts
  packages/service/core/app/evaluation/mq.ts
  packages/service/support/permission/evaluation/auth.ts
  packages/service/support/wallet/usage/controller.ts
  packages/service/support/wallet/usage/type.d.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/error.svg
  packages/web/components/common/Icon/icons/mcp.svg
  packages/web/components/common/Input/SearchInput/index.tsx
  packages/web/hooks/useScrollPagination.tsx
  packages/web/i18n/constants.ts
  packages/web/i18n/en/account_team.json
  packages/web/i18n/en/account_usage.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/dashboard_evaluation.json
  packages/web/i18n/i18next.d.ts
  packages/web/i18n/zh-CN/account_team.json
  packages/web/i18n/zh-CN/account_usage.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/dashboard_evaluation.json
  packages/web/i18n/zh-Hant/account_team.json
  packages/web/i18n/zh-Hant/account_usage.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/dashboard_evaluation.json
  packages/web/support/user/audit/constants.ts
  projects/app/src/components/Layout/navbar.tsx
  projects/app/src/components/Layout/navbarPhone.tsx
  projects/app/src/components/Select/AppSelect.tsx
  projects/app/src/components/common/folder/SelectOneResource.tsx
  projects/app/src/components/core/app/InputGuideConfig.tsx
  projects/app/src/pageComponents/account/usage/UsageDetail.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/SelectAppModal.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pageComponents/app/evaluation/DetailModal.tsx
  projects/app/src/pageComponents/chat/ChatHeader.tsx
  projects/app/src/pageComponents/chat/SliderApps.tsx
  projects/app/src/pageComponents/dashboard/Container.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/TagManageModal.tsx
  projects/app/src/pages/api/core/app/list.ts
  projects/app/src/pages/dashboard/apps/index.tsx
  projects/app/src/pages/dashboard/evaluation/create.tsx
  projects/app/src/pages/dashboard/evaluation/index.tsx
  projects/app/src/web/core/app/api/evaluation.ts
  projects/app/src/web/core/chat/context/chatContext.tsx
Labels: size/XXL

#5255 perf: value type checker
  packages/global/core/workflow/runtime/utils.ts
  packages/service/core/workflow/dispatch/tools/runUpdateVar.ts
  packages/web/components/common/Textarea/PromptEditor/index.tsx
  test/cases/service/core/app/workflow/dispatch/utils.test.ts
Labels: size/M

#5253 Refactor chat page
  packages/global/common/system/types/index.d.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/chat/sidebar/logout.svg
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/public/imgs/fastgpt_slogan.png
  projects/app/src/components/Layout/auth.tsx
  projects/app/src/components/Layout/navbar.tsx
  projects/app/src/components/Layout/navbarPhone.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/components/Empty.tsx
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/pageComponents/chat/SliderApps.tsx
  projects/app/src/pageComponents/chat/UserAvatarPopover.tsx
  projects/app/src/pageComponents/dashboard/apps/List.tsx
  projects/app/src/pageComponents/login/LoginModal.tsx
  projects/app/src/pageComponents/login/index.tsx
  projects/app/src/pages/chat/index.tsx
  projects/app/src/pages/login/index.tsx
  projects/app/src/service/common/system/index.ts
  projects/app/src/web/common/api/request.ts
Labels: size/XXL

#5258 eval scroll pagination
  packages/web/hooks/useScrollPagination.tsx
  projects/app/src/pageComponents/app/evaluation/DetailModal.tsx
  projects/app/src/pages/dashboard/evaluation/create.tsx
  projects/app/src/pages/dashboard/evaluation/index.tsx
Labels: size/M

#5269 fix: error
  packages/global/common/error/code/common.ts
  packages/global/common/error/utils.ts
  packages/service/common/response/index.ts
Labels: size/S

#5271 doc
  docSite/content/zh-cn/docs/development/upgrading/4110.md
Labels: size/XS

#5272 update version doc
  deploy/docker/yml.js
  docSite/content/zh-cn/docs/development/upgrading/4110.md
Labels: size/S

#5275 version doc
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-oceanbase/docker-compose.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  deploy/docker/yml.js
  docSite/content/zh-cn/docs/development/upgrading/4110.md
Labels: size/M

#5278 update secret
  .github/workflows/docs-sync_imgs.yml
Labels: size/S

#5281 Fix API method for retrieving WX login result from GET to POST
  projects/app/src/web/support/user/api.ts
Labels: size/XS

#5280 查询问题的扩展优化：引入子模优化算法
  packages/service/core/ai/functions/queryExtension.ts
Labels: size/L

#5285 feat: coupoun support bank pay way
  docSite/content/zh-cn/docs/development/upgrading/4111.md
  packages/global/support/wallet/sub/coupon/constants.ts
  packages/global/support/wallet/sub/coupon/type.d.ts
  packages/service/support/wallet/coupon/schema.ts
Labels: size/M

#5302 Doc action test
  .github/workflows/docs-preview.yml
  document/content/docs/introduction/development/upgrading/4110.mdx
Labels: size/S

#5308 Fix document action and content
  .github/workflows/docs-deploy.yml
  .github/workflows/docs-preview.yml
  document/Dockerfile
  document/components/CustomSearchDialog.tsx
  document/content/docs/use-cases/external-integration/feishu.mdx
  document/content/docs/use-cases/index.mdx
  document/source.config.ts
  document/update-index.mjs
Labels: size/M

#5200 perf: system toolset & mcp
  packages/global/core/app/mcpTools/utils.ts
  packages/global/core/app/plugin/constants.ts
  packages/global/core/app/plugin/utils.ts
  packages/global/core/workflow/type/node.d.ts
  packages/global/core/workflow/utils.ts
  packages/service/core/app/mcp.ts
  packages/service/core/app/plugin/controller.ts
  packages/service/core/app/plugin/utils.ts
  packages/service/core/app/tool/api.ts
  packages/service/core/app/utils.ts
  packages/service/core/workflow/dispatch/ai/agent/index.ts
  packages/service/core/workflow/dispatch/child/runTool.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/plugin/run.ts
  packages/service/core/workflow/dispatch/utils.ts
  packages/service/package.json
  packages/service/support/permission/app/auth.ts
  pnpm-lock.yaml
  projects/app/src/pageComponents/app/detail/MCPTools/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/components/NodeTemplates/list.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/components/NodeTemplates/useNodeTemplates.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeToolSet.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/api/core/app/mcpTools/create.ts
  projects/app/src/pages/api/core/app/mcpTools/getChildren.ts
  projects/app/src/pages/api/core/app/mcpTools/update.ts
  projects/app/src/pages/api/core/app/plugin/getPreviewNode.ts
  projects/app/src/pages/api/core/app/plugin/getSystemPluginTemplates.ts
  projects/app/src/pages/api/core/app/plugin/getVersionList.ts
  projects/app/src/pages/api/core/app/plugin/path.ts
  projects/app/src/service/support/mcp/utils.ts
  projects/app/src/web/core/app/api/plugin.ts
Labels: size/XL

#5312 add tool params return
  packages/service/core/workflow/dispatch/ai/agent/toolParams.ts
Labels: size/XS

#5314 feat:get lastmodified time by git log
  document/app/[lang]/docs/[[...slug]]/page.tsx
  document/components/docs/not-found.tsx
  document/data/doc-last-modified.json
  document/github.js
  document/package.json
  package.json
Labels: size/L

#5316 fix: some bug
  packages/global/core/app/jsonschema.ts
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/utils.ts
  packages/service/core/app/plugin/controller.ts
  packages/service/core/app/utils.ts
  projects/app/src/pageComponents/app/detail/MCPTools/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/MCPTools/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/components/NodeTemplates/header.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/components/NodeTemplates/useNodeTemplates.tsx
  projects/app/src/pages/api/support/mcp/client/getTools.ts
  projects/app/src/service/support/mcp/utils.ts
  projects/app/src/web/core/app/api/plugin.ts
  test/cases/global/core/app/jsonschema.test.ts
Labels: size/L

#5310 optimize app logs sort
  packages/global/core/app/logs/constants.ts
  packages/global/core/app/logs/type.d.ts
  packages/service/core/app/logs/logkeysSchema.ts
  packages/web/components/common/DateRangePicker/index.tsx
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/invisible.svg
  packages/web/components/common/Icon/icons/visible.svg
  packages/web/components/common/MySelect/MultipleSelect.tsx
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/global/core/api/appReq.d.ts
  projects/app/src/pageComponents/account/model/Log/index.tsx
  projects/app/src/pageComponents/account/model/ModelDashboard/index.tsx
  projects/app/src/pageComponents/app/detail/Logs/DetailLogsModal.tsx
  projects/app/src/pageComponents/app/detail/Logs/LogKeysConfigPopover.tsx
  projects/app/src/pageComponents/app/detail/Logs/SyncLogKeysPopover.tsx
  projects/app/src/pageComponents/app/detail/Logs/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/ChatTest.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/context/index.tsx
  projects/app/src/pageComponents/chat/ChatHeader.tsx
  projects/app/src/pages/account/usage/index.tsx
  projects/app/src/pages/api/core/app/exportChatLogs.ts
  projects/app/src/pages/api/core/app/getChatLogs.ts
  projects/app/src/pages/api/core/app/logs/getLogKeys.ts
  projects/app/src/pages/api/core/app/logs/updateLogKeys.ts
  projects/app/src/types/app.d.ts
  projects/app/src/web/core/app/api.ts
  projects/app/src/web/core/app/api/log.ts
  projects/app/src/web/core/chat/context/chatItemContext.tsx
Labels: size/XXL

#5320 fix: page /404 translator not working bug
  projects/app/src/pages/404.tsx
Labels: size/XS

#5327 fix: fix the login container; fix the incorrect input of captcha enter trigger
  projects/app/src/components/support/user/safe/SendCodeAuthModal.tsx
  projects/app/src/pageComponents/login/LoginModal.tsx
  projects/app/src/pageComponents/login/index.tsx
Labels: size/M

#5339 feat: add robots.txt
  document/app/[lang]/robots.txt/route.ts
Labels: size/M

#5344 fix: resole crawl cannot get docs
  document/app/[lang]/robots.txt/route.ts
  document/app/api/meta/route.ts
  document/components/docs/not-found.tsx
  document/content/docs/api/index.mdx
  document/content/docs/index.mdx
  document/content/docs/introduction/FAQ/index.mdx
  document/content/docs/introduction/development/custom-models/index.mdx
  document/content/docs/introduction/development/design/index.mdx
  document/content/docs/introduction/development/index.mdx
  document/content/docs/introduction/development/migration/index.mdx
  document/content/docs/introduction/development/modelConfig/index.mdx
  document/content/docs/introduction/development/openapi/index.mdx
  document/content/docs/introduction/development/proxy/index.mdx
  document/content/docs/introduction/development/upgrading/index.mdx
  document/content/docs/introduction/guide/DialogBoxes/index.mdx
  document/content/docs/introduction/guide/admin/index.mdx
  document/content/docs/introduction/guide/course/index.mdx
  document/content/docs/introduction/guide/dashboard/index.mdx
  document/content/docs/introduction/guide/dashboard/workflow/index.mdx
  document/content/docs/introduction/guide/index.mdx
  document/content/docs/introduction/guide/knowledge_base/index.mdx
  document/content/docs/introduction/guide/meta.json
  document/content/docs/introduction/guide/plugins/index.mdx
  document/content/docs/introduction/guide/team_permissions/index.mdx
  document/content/docs/introduction/shopping_cart/index.mdx
  document/content/docs/protocol/index.mdx
  document/content/docs/use-cases/app-cases/index.mdx
  document/content/docs/use-cases/external-integration/index.mdx
  document/data/doc-last-modified.json
Labels: size/XL

#5347 remove log
  document/update-index.mjs
Labels: size/XS

#5335 fix:delete variable id
  packages/global/core/app/type.d.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/core/app/VariableEdit.tsx
Labels: size/M

#5257 Enhance file upload functionality and system tool integration
  docSite/assets/imgs/plugins/entry.png
  docSite/assets/imgs/plugins/file.png
  document/content/docs/introduction/guide/plugins/meta.json
  document/content/docs/introduction/guide/plugins/upload_system_tool.mdx
  packages/global/core/app/plugin/type.d.ts
  packages/global/core/workflow/type/node.d.ts
  packages/service/common/file/plugin/config.ts
  packages/service/common/file/plugin/controller.ts
  packages/service/common/file/plugin/utils.ts
  packages/service/common/minio/index.ts
  packages/service/common/minio/init.ts
  packages/service/common/minio/type.d.ts
  packages/service/core/app/plugin/controller.ts
  packages/service/core/app/tool/api.ts
  packages/service/package.json
  packages/web/core/workflow/constants.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/file.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/file.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/file.json
  projects/app/.env.template
  projects/app/package.json
  projects/app/src/pageComponents/dashboard/SystemPlugin/ToolCard.tsx
  projects/app/src/pages/api/common/file/plugin/confirmUpload.ts
  projects/app/src/pages/api/common/file/plugin/presignedUrl.ts
  projects/app/src/pages/api/core/app/plugin/getSystemPluginTemplates.ts
  projects/app/src/pages/api/plugin/delete.ts
  projects/app/src/pages/api/plugin/upload.ts
  projects/app/src/pages/dashboard/[pluginGroupId]/index.tsx
  projects/app/src/web/common/file/api.ts
Labels: size/XL
