Repository labring/FastGPT, pull requests merged in 2025-01, with the labels that each got.

#3503 feat: permission manage UI for org
  packages/global/support/user/team/org/type.d.ts
  packages/service/support/permission/org/orgSchema.ts
  projects/app/src/pages/account/team/components/PermissionManage/index.tsx
Labels: size/L

#3509 perf: password check;perf: image upload check;perf: sso login check
  docSite/content/zh-cn/docs/development/upgrading/4818.md
  packages/global/common/error/code/common.ts
  packages/global/common/error/code/user.ts
  packages/global/common/file/api.d.ts
  packages/global/common/file/image/constants.ts
  packages/global/common/file/image/type.d.ts
  packages/service/common/file/image/controller.ts
  packages/service/common/file/image/schema.ts
  packages/service/common/file/read/utils.ts
  packages/service/common/middle/reqFrequencyLimit.ts
  packages/service/common/response/index.ts
  packages/service/support/permission/memberGroup/controllers.ts
  packages/service/support/user/team/controller.ts
  packages/web/i18n/en/account_info.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/login.json
  packages/web/i18n/en/user.json
  packages/web/i18n/zh-CN/account_info.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/login.json
  packages/web/i18n/zh-CN/user.json
  packages/web/i18n/zh-Hant/account_info.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/login.json
  packages/web/i18n/zh-Hant/user.json
  projects/app/src/components/common/Modal/EditResourceModal.tsx
  projects/app/src/pages/account/info/components/UpdatePswModal.tsx
  projects/app/src/pages/account/info/index.tsx
  projects/app/src/pages/account/team/components/EditInfoModal.tsx
  projects/app/src/pages/account/team/components/GroupManage/GroupInfoModal.tsx
  projects/app/src/pages/account/team/components/OrgManage/OrgInfoModal.tsx
  projects/app/src/pages/api/common/file/uploadImage.ts
  projects/app/src/pages/api/core/app/create.ts
  projects/app/src/pages/api/core/app/del.ts
  projects/app/src/pages/api/core/app/httpPlugin/update.ts
  projects/app/src/pages/api/core/app/update.ts
  projects/app/src/pages/api/core/dataset/create.ts
  projects/app/src/pages/api/core/dataset/delete.ts
  projects/app/src/pages/api/core/dataset/update.ts
  projects/app/src/pages/api/support/user/account/loginByPassword.ts
  projects/app/src/pages/api/support/user/account/update.ts
  projects/app/src/pages/app/detail/components/InfoModal.tsx
  projects/app/src/pages/app/list/components/CreateModal.tsx
  projects/app/src/pages/app/list/components/HttpPluginEditModal.tsx
  projects/app/src/pages/dataset/detail/components/Info/index.tsx
  projects/app/src/pages/dataset/list/component/CreateModal.tsx
  projects/app/src/pages/dataset/list/component/List.tsx
  projects/app/src/pages/login/components/ForgetPasswordForm.tsx
  projects/app/src/pages/login/components/LoginForm/LoginForm.tsx
  projects/app/src/pages/login/components/RegisterForm.tsx
  projects/app/src/pages/login/provider.tsx
  projects/app/src/web/common/file/controller.ts
  projects/app/src/web/common/file/hooks/useSelectFile.tsx
  projects/app/src/web/common/system/useSystemStore.ts
  projects/app/src/web/core/dataset/api.ts
  projects/app/src/web/support/user/login/constants.ts
Labels: size/XXL

#3511 更新 README.md
  README.md
Labels: size/XS

#3513 feat: new provider
  docSite/content/zh-cn/docs/development/configuration.md
  packages/global/core/ai/provider.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/model/BAAI.svg
  packages/web/components/common/Icon/icons/model/alicloud.svg
  packages/web/components/common/Icon/icons/model/fishaudio.svg
  packages/web/components/common/Icon/icons/model/meta.svg
  packages/web/components/common/Icon/icons/model/stepfun.svg
  packages/web/components/common/Icon/icons/model/yi.svg
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
Labels: size/L

#3515 perf: notify account
  packages/global/support/user/team/type.d.ts
  packages/service/support/user/team/controller.ts
  packages/service/support/user/team/teamSchema.ts
  projects/app/src/pages/account/info/index.tsx
  projects/app/src/pages/account/team/components/OrgManage/OrgInfoModal.tsx
  projects/app/src/pages/account/team/components/OrgManage/OrgMemberManageModal.tsx
  projects/app/src/pages/account/team/components/OrgManage/OrgMoveModal.tsx
  projects/app/src/pages/account/team/components/OrgManage/index.tsx
  projects/app/src/pages/account/team/index.tsx
  projects/app/src/service/mongo.ts
Labels: size/M

#3507 perf(plugin): improve searXNG empty result handling and documentation
  docSite/content/zh-cn/docs/guide/plugins/searxng_plugin_guide.md
  packages/plugins/src/searchXNG/index.ts
Labels: size/S

#3516 refactor: org pathId
  packages/global/support/user/team/org/constant.ts
  packages/global/support/user/team/org/type.d.ts
  packages/service/support/permission/org/controllers.ts
  packages/service/support/permission/org/orgSchema.ts
  projects/app/src/pages/account/team/components/OrgManage/OrgTree.tsx
  projects/app/src/pages/account/team/components/OrgManage/index.tsx
Labels: size/M

#3517 optimize payment process
  packages/global/common/error/code/team.ts
  packages/service/support/permission/teamLimit.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/wallet.svg
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/components/Layout/index.tsx
  projects/app/src/components/support/wallet/NotSufficientModal/index.tsx
  projects/app/src/pages/account/team/index.tsx
  projects/app/src/pages/dataset/component/ApiDatasetForm.tsx
  projects/app/src/pages/price/components/ExtraPlan.tsx
  projects/app/src/pages/price/components/Standard.tsx
  projects/app/src/pages/price/index.tsx
  projects/app/src/web/common/api/fetch.ts
  projects/app/src/web/common/api/request.ts
  projects/app/src/web/common/system/useSystemStore.ts
Labels: size/L

#3518 feat: support wecom sso
  packages/global/common/system/types/index.d.ts
  packages/global/support/user/constant.ts
  packages/service/support/user/wecom.ts
  packages/web/i18n/zh-CN/login.json
  pnpm-lock.yaml
  projects/app/src/pages/login/components/LoginForm/components/FormLayout.tsx
Labels: size/L

#3520 fix qrcode script
  packages/web/i18n/en/common.json
  packages/web/i18n/en/user.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/user.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/user.json
  projects/app/src/components/support/wallet/NotSufficientModal/index.tsx
  projects/app/src/components/support/wallet/QRCodePayModal.tsx
  projects/app/src/pages/price/components/Standard.tsx
  projects/app/src/pages/price/index.tsx
  projects/app/src/web/support/user/hooks/useSendCode.tsx
Labels: size/L

#3519 perf: full text collection and search code;perf: rename function
  docSite/content/zh-cn/docs/development/upgrading/4818.md
  packages/global/core/dataset/type.d.ts
  packages/global/support/user/login/constants.ts
  packages/global/support/user/team/org/constant.ts
  packages/service/core/chat/chatItemSchema.ts
  packages/service/core/chat/chatSchema.ts
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/controller.ts
  packages/service/core/dataset/data/dataTextSchema.ts
  packages/service/core/dataset/data/schema.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/support/permission/org/controllers.ts
  packages/service/support/permission/org/orgSchema.ts
  packages/service/support/user/schema.ts
  packages/service/support/wallet/usage/schema.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/common/wecom.svg
  projects/app/src/components/support/wallet/NotSufficientModal/index.tsx
  projects/app/src/components/support/wallet/QRCodePayModal.tsx
  projects/app/src/pages/account/components/TeamSelector.tsx
  projects/app/src/pages/account/team/components/OrgManage/OrgTree.tsx
  projects/app/src/pages/account/team/components/OrgManage/index.tsx
  projects/app/src/pages/api/admin/initv4818.ts
  projects/app/src/pages/dataset/detail/components/Test.tsx
  projects/app/src/pages/login/components/LoginForm/components/FormLayout.tsx
  projects/app/src/pages/login/index.tsx
  projects/app/src/pages/price/index.tsx
  projects/app/src/service/core/dataset/data/controller.ts
  projects/app/src/service/events/generateVector.ts
  projects/app/src/web/common/system/useSystemStore.ts
Labels: size/XL

#3522 fix: system title
  projects/app/src/web/common/system/staticData.ts
Labels: size/XS

#3523 Update 4817.md
  docSite/content/zh-cn/docs/development/upgrading/4817.md
Labels: size/XS

#3524 4.8.18 test
  packages/service/support/outLink/schema.ts
  projects/app/src/pages/login/fastlogin.tsx
  projects/app/src/pages/login/index.tsx
  projects/app/src/pages/login/provider.tsx
  projects/app/src/pages/price/index.tsx
  projects/app/src/web/support/user/auth.ts
Labels: size/S

#3530 fix: charts plugins
  docSite/content/zh-cn/docs/development/intro.md
  packages/global/common/string/tools.ts
  packages/global/core/workflow/runtime/utils.ts
  packages/global/package.json
  packages/plugins/src/drawing/baseChart/index.ts
  packages/plugins/src/drawing/baseChart/template.json
  packages/service/core/workflow/dispatch/tools/http468.ts
  pnpm-lock.yaml
Labels: size/L

#3533 fix: plugin cost
  packages/service/common/middle/cors.ts
  packages/service/core/app/plugin/utils.ts
  packages/web/i18n/en/app.json
  projects/app/src/pages/api/common/file/read.ts
  projects/app/src/pages/api/common/file/read/[filename].ts
Labels: size/M

#3535 refactor: team permission manager
  packages/global/support/permission/collaborator.d.ts
  packages/service/support/permission/controller.ts
  packages/web/i18n/en/user.json
  packages/web/i18n/zh-CN/user.json
  packages/web/i18n/zh-Hant/user.json
  projects/app/src/components/support/permission/MemberManager/AddMemberModal.tsx
  projects/app/src/components/support/permission/MemberManager/MemberModal.tsx
  projects/app/src/pages/account/team/components/PermissionManage/index.tsx
  projects/app/src/pages/account/team/index.tsx
  projects/app/src/web/support/user/team/api.ts
Labels: size/XXL

#3543 4.8.18 test
  docSite/content/zh-cn/docs/development/upgrading/4818.md
  packages/global/core/ai/model.d.ts
  packages/global/support/permission/collaborator.d.ts
  packages/service/core/ai/config/embedding/text-embedding-ada-002.json
  packages/service/core/ai/config/llm/gpt-4o-mini.json
  packages/service/core/ai/config/rerank/bge-reranker-v2-m3.json
  packages/service/core/ai/config/stt/whisper-1.json
  packages/service/core/ai/config/tts/tts-1.json
  packages/service/core/app/plugin/utils.ts
  packages/service/support/permission/controller.ts
  packages/web/components/common/Icon/button.tsx
  packages/web/components/common/Tabs/FillRowTabs.tsx
  packages/web/i18n/en/account.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh-CN/account.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/user.json
  packages/web/i18n/zh-CN/workflow.json
  packages/web/i18n/zh-Hant/account.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/workflow.json
  projects/app/src/components/common/folder/SlideCard.tsx
  projects/app/src/components/support/permission/MemberManager/AddMemberModal.tsx
  projects/app/src/components/support/permission/MemberManager/MemberModal.tsx
  projects/app/src/components/support/permission/MemberManager/PermissionSelect.tsx
  projects/app/src/components/support/permission/MemberManager/PermissionTags.tsx
  projects/app/src/components/support/permission/MemberManager/context.tsx
  projects/app/src/pages/account/model/components/DefaultModal.tsx
  projects/app/src/pages/account/model/index.tsx
  projects/app/src/pages/account/team/components/GroupManage/index.tsx
  projects/app/src/pages/account/team/components/MemberTable.tsx
  projects/app/src/pages/account/team/components/OrgManage/index.tsx
  projects/app/src/pages/account/team/components/PermissionManage/index.tsx
  projects/app/src/pages/account/team/components/context.tsx
  projects/app/src/pages/account/team/index.tsx
  projects/app/src/pages/api/common/system/writefile.ts
  projects/app/src/pages/app/detail/components/InfoModal.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pages/app/list/components/List.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/pages/dataset/component/MemberManager.tsx
  projects/app/src/pages/dataset/detail/components/Info/index.tsx
  projects/app/src/pages/dataset/list/component/List.tsx
  projects/app/src/pages/dataset/list/index.tsx
  projects/app/src/service/core/ai/apiproxy.d.ts
  projects/app/src/service/core/ai/apiproxy.ts
  projects/app/src/web/common/api/request.ts
  projects/app/src/web/support/user/team/api.ts
Labels: size/XXL

#3553 fix: MemberModal UI
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/modal/key.svg
  packages/web/i18n/en/user.json
  packages/web/i18n/zh-CN/user.json
  packages/web/i18n/zh-Hant/user.json
  projects/app/src/components/support/permission/MemberManager/MemberModal.tsx
  projects/app/src/components/support/permission/MemberManager/context.tsx
  projects/app/src/pages/account/team/components/PermissionManage/index.tsx
Labels: size/M

#3556 perf: org permission
  packages/global/common/error/code/team.ts
  packages/global/common/system/constants.ts
  packages/service/support/permission/controller.ts
  packages/service/support/permission/org/controllers.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/key.svg
  packages/web/components/common/Icon/icons/keyPrimary.svg
  packages/web/components/common/Icon/icons/support/outlink/apikeyLight.svg
  packages/web/i18n/en/common.json
  packages/web/i18n/en/user.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/user.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/user.json
  projects/app/public/imgs/modal/key.svg
  projects/app/src/components/support/apikey/Table.tsx
  projects/app/src/components/support/permission/ConfigPerModal/index.tsx
  projects/app/src/components/support/permission/MemberManager/MemberModal.tsx
  projects/app/src/pages/account/components/AccountContainer.tsx
  projects/app/src/pages/account/team/components/PermissionManage/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/AppCard.tsx
  projects/app/src/pages/app/list/components/List.tsx
  projects/app/src/pages/dataset/list/component/List.tsx
Labels: size/L

#3540 docs:用户答疑的官方文档补充
  docSite/assets/imgs/dataset1.png
  docSite/assets/imgs/dataset2.png
  docSite/content/zh-cn/docs/development/faq.md
  docSite/content/zh-cn/docs/faq/app.md
  docSite/content/zh-cn/docs/faq/dataset.md
Labels: size/M

#3541 share link random avatar
  packages/global/support/user/utils.ts
  packages/service/support/user/schema.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
  projects/app/src/pages/api/core/chat/outLink/init.ts
Labels: size/M

#3558 share page avatar
  docSite/content/zh-cn/docs/development/upgrading/4818.md
  packages/service/support/user/schema.ts
  projects/app/src/pages/api/admin/initv4818.ts
  projects/app/src/pages/api/core/chat/outLink/init.ts
Labels: size/M

#3559 feat: tmp upgrade code
  .github/workflows/preview-fastgpt-image.yml
  packages/global/common/error/code/user.ts
  packages/service/core/dataset/data/dataTextSchema.ts
  packages/service/core/dataset/data/schema.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/support/permission/auth/team.ts
  projects/app/src/pages/api/admin/initv4818.ts
  projects/app/src/pages/api/support/user/account/loginByPassword.ts
  projects/app/src/service/core/dataset/data/controller.ts
Labels: size/M

#3561 full text tmp code
  packages/service/core/dataset/data/dataTextSchema.ts
  packages/service/core/dataset/data/schema.ts
  projects/app/src/pages/api/admin/initv4818.ts
  projects/app/src/service/core/dataset/data/controller.ts
Labels: size/M

#3562 4.8.18 test
  packages/global/common/error/code/user.ts
  packages/service/support/permission/auth/team.ts
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/Dockerfile
  projects/app/package.json
  projects/app/src/pages/api/admin/initv4818.ts
  projects/app/src/pages/api/support/user/account/loginByPassword.ts
Labels: size/L

#3564 chore: update docs app template submission
  dev.md
  docSite/assets/imgs/template_submission2.png
  docSite/content/zh-cn/docs/use-cases/app-cases/submit_application_template.md
Labels: size/XS

#3566 fix: per;fix: invite user un refresh;perf: loginout
  .github/workflows/preview-fastgpt-image.yml
  projects/app/Dockerfile
  projects/app/src/components/support/user/team/UpdateInviteModal/index.tsx
  projects/app/src/pages/account/team/index.tsx
  projects/app/src/pages/api/support/user/account/loginout.ts
Labels: size/M

#3557 feat: create app by json
  packages/global/core/app/utils.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/app/type/jsonImport.svg
  packages/web/components/common/Textarea/DragEditor/index.tsx
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/pages/app/detail/components/SimpleApp/AppCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/AppCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/ImportSettings.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeHttp/CurlImportModal.tsx
  projects/app/src/pages/app/list/components/CreateModal.tsx
  projects/app/src/pages/app/list/components/JsonImportModal.tsx
  projects/app/src/pages/app/list/components/TemplateMarketModal.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/web/common/file/hooks/useSelectFile.tsx
  projects/app/src/web/core/app/templates.ts
  projects/app/src/web/core/app/utils.ts
Labels: size/XXL

#3570 perf: http body;perf: create by json;perf: create by curl
  docSite/content/zh-cn/docs/agreement/open-source.md
  docSite/content/zh-cn/docs/development/upgrading/4818.md
  docSite/content/zh-cn/docs/intro.md
  packages/global/common/error/utils.ts
  packages/global/common/string/http.ts
  packages/global/core/app/utils.ts
  packages/global/package.json
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/app/type/jsonImport.svg
  packages/web/components/common/MyModal/index.tsx
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/common.json
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/src/pageComponents/app/ImportAppConfigEditor.tsx
  projects/app/src/pageComponents/app/constants.ts
  projects/app/src/pageComponents/app/detail/ExportConfigPopover.tsx
  projects/app/src/pages/app/detail/components/SimpleApp/AppCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/AppCard.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/ImportSettings.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodeHttp/CurlImportModal.tsx
  projects/app/src/pages/app/list/components/CreateModal.tsx
  projects/app/src/pages/app/list/components/JsonImportModal.tsx
  projects/app/src/pages/app/list/components/TemplateMarketModal.tsx
  projects/app/src/pages/app/list/index.tsx
  projects/app/src/web/common/file/hooks/useSelectFile.tsx
  projects/app/src/web/core/app/templates.ts
  projects/app/src/web/core/app/utils.ts
Labels: size/XXL

#3571 4.8.18 test
  docSite/content/zh-cn/docs/development/configuration.md
  docSite/content/zh-cn/docs/shopping_cart/intro.md
  docSite/content/zh-cn/docs/shopping_cart/saas.md
  packages/global/core/workflow/runtime/utils.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh-CN/workflow.json
  packages/web/i18n/zh-Hant/workflow.json
Labels: size/M

#3574 faq
  docSite/content/zh-cn/docs/development/faq.md
  docSite/content/zh-cn/docs/development/upgrading/4818.md
Labels: size/L

#3573 curl create plugin with inputs
  packages/global/common/string/http.ts
  projects/app/src/web/core/app/templates.ts
Labels: size/L

#3580 fix: create plugin by curl
  files/docker/docker-compose-milvus.yml
  files/docker/docker-compose-pgvector.yml
  files/docker/docker-compose-zilliz.yml
  packages/global/core/workflow/type/io.d.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
  projects/app/src/web/core/app/templates.ts
Labels: size/L

#3581 4.8.18 test
  docSite/assets/imgs/image-83.png
  docSite/assets/imgs/image-84.png
  docSite/assets/imgs/image-85.png
  docSite/assets/imgs/image-86.png
  docSite/assets/imgs/image-87.png
  docSite/content/zh-cn/docs/development/upgrading/4818.md
  docSite/content/zh-cn/docs/faq/app.md
Labels: size/M

#3577 fix: pagination bug
  packages/service/support/user/utils.ts
  projects/app/src/pages/account/team/components/GroupManage/GroupManageMember.tsx
  projects/app/src/pages/account/team/components/OrgManage/OrgMemberManageModal.tsx
  projects/app/src/pages/api/core/app/getChatLogs.ts
  projects/app/src/pages/api/core/app/list.ts
  projects/app/src/pages/api/core/app/version/list.ts
  projects/app/src/pages/api/core/dataset/list.ts
Labels: size/L

#3584 4.8.19 test
  docSite/content/zh-cn/docs/development/upgrading/4819.md
  packages/global/core/workflow/constants.ts
  packages/global/core/workflow/runtime/type.d.ts
  packages/global/core/workflow/template/system/datasetSearch.ts
  packages/service/core/dataset/utils.ts
  packages/service/core/workflow/dispatch/dataset/search.ts
  packages/service/support/user/utils.ts
  packages/web/i18n/en/workflow.json
  packages/web/i18n/zh-CN/workflow.json
  packages/web/i18n/zh-Hant/workflow.json
  projects/app/.env.template
  projects/app/src/pages/api/core/app/version/list.ts
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/core/dataset/list.ts
  projects/app/src/pages/api/core/workflow/debug.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/Label.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SelectDataset.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/Textarea.tsx
  projects/app/src/service/core/app/utils.ts
Labels: size/L

#3585 fix: http variable
  packages/service/core/workflow/dispatch/tools/http468.ts
Labels: size/S

#3587 update doc
  docSite/content/zh-cn/docs/development/openapi/dataset.md
Labels: size/XS

#3588 update doc
  docSite/content/zh-cn/docs/development/openapi/dataset.md
Labels: size/XS

#3586 fix lexical editor space
  packages/web/components/common/Input/HttpInput/index.tsx
  packages/web/components/common/Textarea/PromptEditor/index.tsx
Labels: size/XS

#3592 fix: scroll fetch
  projects/app/src/components/support/permission/MemberManager/MemberModal.tsx
Labels: size/L

#3593 fix: yuque dataset file folder can enter
  packages/global/core/dataset/apiDataset.d.ts
  packages/service/core/dataset/apiDataset/api.ts
  projects/app/src/pages/dataset/detail/components/Import/diffSource/APIDataset.tsx
Labels: size/S

#3594 perf: load members；perf: yuque load；fix: workflow llm params cannot close
  docSite/content/zh-cn/docs/development/openapi/chat.md
  docSite/content/zh-cn/docs/development/openapi/dataset.md
  docSite/content/zh-cn/docs/development/upgrading/4819.md
  packages/global/core/dataset/apiDataset.d.ts
  packages/global/support/user/team/org/type.d.ts
  packages/service/core/dataset/apiDataset/api.ts
  packages/service/support/permission/org/orgSchema.ts
  packages/web/components/common/Avatar/AvatarGroup.tsx
  packages/web/hooks/useScrollPagination.tsx
  projects/app/package.json
  projects/app/src/components/support/permission/MemberManager/MemberModal.tsx
  projects/app/src/pageComponents/account/team/EditInfoModal.tsx
  projects/app/src/pageComponents/account/team/GroupManage/GroupInfoModal.tsx
  projects/app/src/pageComponents/account/team/GroupManage/GroupManageMember.tsx
  projects/app/src/pageComponents/account/team/GroupManage/GroupTransferOwnerModal.tsx
  projects/app/src/pageComponents/account/team/GroupManage/index.tsx
  projects/app/src/pageComponents/account/team/InviteModal.tsx
  projects/app/src/pageComponents/account/team/MemberTable.tsx
  projects/app/src/pageComponents/account/team/OrgManage/IconButton.tsx
  projects/app/src/pageComponents/account/team/OrgManage/OrgInfoModal.tsx
  projects/app/src/pageComponents/account/team/OrgManage/OrgMemberManageModal.tsx
  projects/app/src/pageComponents/account/team/OrgManage/OrgMoveModal.tsx
  projects/app/src/pageComponents/account/team/OrgManage/OrgTree.tsx
  projects/app/src/pageComponents/account/team/OrgManage/index.tsx
  projects/app/src/pageComponents/account/team/PermissionManage/index.tsx
  projects/app/src/pageComponents/account/team/SelectMember.tsx
  projects/app/src/pageComponents/account/team/context.tsx
  projects/app/src/pages/account/team/index.tsx
  projects/app/src/pages/api/common/system/getInitData.ts
  projects/app/src/pages/dataset/detail/components/Import/diffSource/APIDataset.tsx
  projects/app/src/web/core/workflow/utils.ts
Labels: size/XL

#3596 fix: http
  packages/service/core/workflow/dispatch/tools/http468.ts
Labels: size/XS

#3599 Update docker.md
  docSite/content/zh-cn/docs/development/docker.md
Labels: size/XS

#3634 fix: http parse
  docSite/content/zh-cn/docs/development/upgrading/4819.md
  docSite/content/zh-cn/docs/guide/workbench/workflow/loop.md
  docSite/content/zh-cn/docs/use-cases/app-cases/multi_turn_translation_bot.md
  docSite/content/zh-cn/docs/use-cases/app-cases/translate-subtitle-using-gpt.md
  packages/global/core/app/constants.ts
  packages/service/core/workflow/dispatch/plugin/run.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
Labels: size/M

#3583 feat(core): 添加 sleep 插件
  packages/plugins/register.ts
  packages/plugins/src/sleep/index.ts
  packages/plugins/src/sleep/template.json
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/core/workflow/template/sleep.svg
Labels: size/L

#3637 fix: loal file api error
  docSite/content/zh-cn/docs/development/faq.md
  docSite/content/zh-cn/docs/development/upgrading/4819.md
  docSite/content/zh-cn/docs/faq/other.md
  packages/web/components/common/Icon/index.tsx
  projects/app/src/components/core/ai/ModelTable/index.tsx
  projects/app/src/pages/api/core/dataset/collection/create/localFile.ts
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/render/RenderInput/templates/NumberInput.tsx
Labels: size/L

#3641 fix: 插件输入和表单输入的数字输入框无法输入0
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
Labels: size/XS

#3640 chore: add intern and moka provider
  docSite/content/zh-cn/docs/development/configuration.md
  packages/global/core/ai/provider.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/model/intern.svg
  packages/web/components/common/Icon/icons/model/moka.svg
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
Labels: size/M

#3639 fix: permission conflict after move
  projects/app/src/pages/api/core/app/update.ts
  projects/app/src/pages/api/core/dataset/update.ts
Labels: size/S

#3646 4819 doc
  docSite/content/zh-cn/docs/development/upgrading/4819.md
  projects/app/src/pages/api/admin/initv4819.ts
Labels: size/M

#3538 feat: usage filter & export & dashbord
  packages/global/support/wallet/usage/api.d.ts
  packages/global/support/wallet/usage/constants.ts
  packages/global/support/wallet/usage/type.d.ts
  packages/web/components/common/DateRangePicker/index.tsx
  packages/web/components/common/MySelect/MultipleSelect.tsx
  packages/web/components/common/Tag/index.tsx
  packages/web/i18n/en/account_usage.json
  packages/web/i18n/en/user.json
  packages/web/i18n/zh-CN/account_usage.json
  packages/web/i18n/zh-CN/user.json
  packages/web/i18n/zh-Hant/account_usage.json
  packages/web/i18n/zh-Hant/user.json
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/src/pages/account/bill/components/BillTable.tsx
  projects/app/src/pages/account/usage/components/ExportModal.tsx
  projects/app/src/pages/account/usage/components/UsageDetail.tsx
  projects/app/src/pages/account/usage/components/UsageForm.tsx
  projects/app/src/pages/account/usage/components/UsageTable.tsx
  projects/app/src/pages/account/usage/index.tsx
  projects/app/src/pages/app/detail/components/WorkflowComponents/Flow/nodes/NodePluginIO/InputTypeConfig.tsx
  projects/app/src/web/support/wallet/usage/api.ts
Labels: size/XXL

#3656 4.8.20 test
  packages/global/core/ai/provider.ts
  packages/service/core/ai/config/embedding/Embedding-V1.json
  packages/service/core/ai/config/embedding/baidu-tao-8k.json
  packages/service/core/ai/config/embedding/bge-m3.json
  packages/service/core/ai/config/embedding/doubao-embedding-large.json
  packages/service/core/ai/config/embedding/doubao-embedding.json
  packages/service/core/ai/config/embedding/hunyuan-embedding.json
  packages/service/core/ai/config/embedding/zhipu-embedding-3.json
  packages/service/core/ai/config/llm/gemini-exp-1206.json
  packages/service/core/ai/config/llm/hunyuan-pro-32k.json
  packages/service/core/ai/config/llm/hunyuan-turbo-vision.json
  packages/service/core/ai/config/llm/qwen-coder-turbo.json
  packages/service/core/ai/config/rerank/siliconflow-bge-reranker-v2-m3.json
  packages/service/core/ai/config/stt/FunAudioLLM-SenseVoiceSmall.json
  packages/service/core/ai/config/tts/Minimax-speech-01-turbo.json
  packages/service/core/ai/config/tts/siliconflow-CosyVoice2-0.5B.json
  packages/service/core/ai/config/tts/siliconflow-RVC-Boss-GPT-SoVITS.json
  packages/service/core/ai/config/tts/siliconflow-fish-speech-1.5.json
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/model/siliconflow.svg
  packages/web/i18n/en/account.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/account.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/account.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/src/pageComponents/account/model/ModelConfigTable.tsx
Labels: size/XL

#3655 fix: POST 500 error on dingtalk bot
  projects/app/src/pages/api/support/outLink/dingtalk/[token].ts
Labels: size/XS

#3661 fix: false triggerd org selection
  projects/app/src/components/support/permission/MemberManager/MemberModal.tsx
Labels: size/XS

#3660 export usage csv i18n
  packages/web/i18n/en/account_usage.json
  packages/web/i18n/zh-CN/account_usage.json
  packages/web/i18n/zh-Hant/account_usage.json
  projects/app/src/pageComponents/account/usage/UsageTable.tsx
Labels: size/M

#3663 feat: markdown extension
  docSite/content/zh-cn/docs/development/upgrading/4820.md
  packages/service/common/middle/reqFrequencyLimit.ts
  packages/service/common/response/index.ts
  packages/service/core/ai/config/provider/Doubao.json
  packages/service/core/ai/config/provider/MiniMax.json
  packages/service/core/ai/config/provider/OpenAI.json
  packages/service/core/ai/config/utils.ts
  packages/service/core/ai/rerank/index.ts
  packages/web/components/common/Input/NumberInput/index.tsx
  packages/web/components/common/MySelect/MultipleRowSelect.tsx
  packages/web/i18n/en/account.json
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/account.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/account.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/common.json
  pnpm-lock.yaml
  projects/app/package.json
  projects/app/public/js/qrcode.min.js
  projects/app/src/components/Markdown/codeBlock/Audio.tsx
  projects/app/src/components/Markdown/codeBlock/CodeLight.tsx
  projects/app/src/components/Markdown/codeBlock/Video.tsx
  projects/app/src/components/Markdown/codeBlock/iframe-html.tsx
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/components/Markdown/utils.ts
  projects/app/src/components/core/ai/AISettingModal/index.tsx
  projects/app/src/components/core/ai/SettingLLMModel/index.tsx
  projects/app/src/components/core/app/DatasetParamsModal.tsx
  projects/app/src/components/core/app/TTSSelect.tsx
  projects/app/src/components/core/app/WelcomeTextConfig.tsx
  projects/app/src/components/support/wallet/QRCodePayModal.tsx
  projects/app/src/pageComponents/account/model/ModelConfigTable.tsx
  projects/app/src/pageComponents/account/usage/UsageTable.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/SelectLLMModel.tsx
  projects/app/src/pageComponents/dataset/detail/Test.tsx
  projects/app/src/pageComponents/dataset/list/CreateModal.tsx
  projects/app/src/pages/api/common/tracks/push.ts
  projects/app/src/pages/api/core/ai/model/getDefaultConfig.ts
  projects/app/src/pages/api/core/ai/model/test.ts
  projects/app/src/pages/api/core/ai/model/updateDefault.ts
  projects/app/src/pages/api/core/dataset/searchTest.ts
  projects/app/src/pages/api/support/user/account/loginByPassword.ts
  projects/app/src/pages/api/v1/audio/transcriptions.ts
  projects/app/src/web/common/system/utils.ts
  projects/app/src/web/common/utils/voice.ts
  projects/app/src/web/core/ai/config.ts
Labels: size/XL

#3665 reload buffer
  packages/service/common/system/config/controller.ts
  packages/service/core/ai/config/utils.ts
  projects/app/src/components/core/app/TTSSelect.tsx
  projects/app/src/pages/api/core/ai/model/delete.ts
  projects/app/src/pages/api/core/ai/model/update.ts
  projects/app/src/pages/api/core/ai/model/updateDefault.ts
  projects/app/src/pages/api/core/ai/model/updateWithJson.ts
Labels: size/M

#3666 fix: err tip
  docSite/content/zh-cn/docs/development/upgrading/4820.md
  packages/service/core/ai/utils.ts
  packages/web/hooks/useRequest.tsx
  packages/web/i18n/en/common.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-Hant/common.json
  projects/app/public/docs/versionIntro.md
  projects/app/src/components/support/wallet/NotSufficientModal/index.tsx
  projects/app/src/components/support/wallet/QRCodePayModal.tsx
  projects/app/src/service/events/generateQA.ts
  projects/app/src/service/events/generateVector.ts
  projects/app/src/web/common/api/request.ts
  projects/app/src/web/context/useInitApp.ts
Labels: size/L

#3659 fix interactive edge
  packages/global/core/workflow/runtime/utils.ts
Labels: size/S

#3669 perf: supplement assistant empty response
  docSite/content/zh-cn/docs/development/upgrading/4820.md
  packages/service/core/chat/utils.ts
  packages/service/core/workflow/dispatch/agent/runTool/toolChoice.ts
Labels: size/L
