Repository labring/FastGPT, pull requests merged in 2025-09, with the labels that each got.

#5554 fix: leave team
  packages/web/i18n/en/account_team.json
  packages/web/i18n/zh-CN/account_team.json
  packages/web/i18n/zh-Hant/account_team.json
  projects/app/src/pageComponents/account/team/Invite/InviteModal.tsx
  projects/app/src/pageComponents/account/team/MemberTable.tsx
  projects/app/src/pageComponents/login/LoginModal.tsx
  projects/app/src/pageComponents/login/index.tsx
  projects/app/src/pages/login/index.tsx
  projects/app/src/pages/login/provider.tsx
Labels: size/L

#5570 fix eval create split
  packages/service/core/app/evaluation/utils.ts
Labels: size/L

#5586 fix variable reset
  packages/global/core/workflow/constants.ts
  projects/app/src/components/core/app/VariableEdit.tsx
Labels: size/M

#5592 Fix workflow
  document/content/docs/upgrading/4-12/4123.mdx
  document/data/doc-last-modified.json
  packages/global/core/app/constants.ts
  packages/global/core/workflow/template/system/interactive/type.d.ts
  packages/service/core/workflow/dispatch/index.ts
  packages/service/core/workflow/dispatch/type.d.ts
  projects/app/src/components/core/app/FileSelect.tsx
  projects/app/src/global/core/workflow/api.d.ts
  projects/app/src/pageComponents/app/detail/SimpleApp/EditForm.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderDebug/NodeDebugResponse.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/context/index.tsx
  projects/app/src/pages/api/core/workflow/debug.ts
Labels: size/L

#5602 Update 4101.mdx
  document/content/docs/upgrading/4-10/4101.mdx
Labels: size/XS

#5643 feat: add redis append to resolve wecom stream response
  document/data/doc-last-modified.json
  packages/service/common/redis/cache.ts
Labels: size/S

#5649 fix: gridFs objectId
  packages/service/common/buffer/rawText/controller.ts
  packages/service/core/dataset/image/controller.ts
Labels: size/S

#5651 perf: init shell
  deploy/docker/docker-compose-milvus.yml
  deploy/docker/docker-compose-oceanbase/docker-compose.yml
  deploy/docker/docker-compose-pgvector.yml
  deploy/docker/docker-compose-zilliz.yml
  deploy/docker/yml.js
  document/content/docs/upgrading/4-12/4124.mdx
  document/data/doc-last-modified.json
  packages/service/core/workflow/dispatch/child/runTool.ts
  packages/web/components/common/UserBox/index.tsx
  projects/app/src/pageComponents/app/detail/SimpleApp/components/ConfigToolModal.tsx
  projects/app/src/pages/api/admin/initv4124.ts
Labels: size/L

#5654 Update 4124.mdx
  document/content/docs/upgrading/4-12/4124.mdx
Labels: size/S

#5657 feat: concat usage code
  document/content/docs/toc.mdx
  document/content/docs/upgrading/4-12/4125.mdx
  document/data/doc-last-modified.json
  packages/global/support/wallet/usage/api.d.ts
  packages/global/support/wallet/usage/constants.ts
  packages/global/support/wallet/usage/type.d.ts
  packages/service/common/api/type.d.ts
  packages/service/common/file/gridfs/controller.ts
  packages/service/common/file/read/utils.ts
  packages/service/core/app/evaluation/evalSchema.ts
  packages/service/core/dataset/collection/controller.ts
  packages/service/core/dataset/read.ts
  packages/service/support/wallet/usage/constants.ts
  packages/service/support/wallet/usage/controller.ts
  packages/service/support/wallet/usage/schema.ts
  packages/service/support/wallet/usage/type.d.ts
  packages/service/support/wallet/usage/usageItemSchema.ts
  projects/app/src/pageComponents/account/usage/UsageDetail.tsx
  projects/app/src/pageComponents/account/usage/UsageTable.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/TrainingStates.tsx
  projects/app/src/pages/api/core/dataset/data/insertImages.ts
  projects/app/src/pages/api/core/dataset/training/rebuildEmbedding.ts
  projects/app/src/pages/api/support/wallet/usage/createTrainingUsage.ts
  projects/app/src/service/common/system/index.ts
  projects/app/src/service/core/dataset/queues/datasetParse.ts
  projects/app/src/service/core/dataset/queues/generateQA.ts
  projects/app/src/service/core/dataset/queues/generateVector.ts
  projects/app/src/service/support/wallet/usage/push.ts
  projects/app/src/web/support/wallet/usage/api.ts
  projects/app/test/api/support/wallet/usage/creatTrainingUsage.test.ts
Labels: size/XL

#5660 feat: editor support select app for test
  packages/web/components/common/Textarea/PromptEditor/Editor.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/SkillPickerPlugin/index.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/SkillPlugin/components/SkillLabel.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/SkillPlugin/index.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/SkillPlugin/node.tsx
  projects/app/src/pageComponents/app/detail/Edit/Agent/EditForm.tsx
  projects/app/src/pageComponents/app/detail/Edit/Agent/hooks/useAppManager.ts
Labels: size/XL

#5661 feat: dataset parse queue
  document/content/docs/upgrading/4-12/4125.mdx
  document/data/doc-last-modified.json
  packages/global/common/system/types/index.d.ts
  projects/app/data/config.json
  projects/app/src/pageComponents/dataset/detail/CollectionCard/TrainingStates.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/index.tsx
  projects/app/src/pageComponents/dataset/detail/NavBar.tsx
  projects/app/src/pages/api/core/dataset/collection/trainingDetail.ts
  projects/app/src/pages/api/core/dataset/training/getQueueLen.ts
  projects/app/src/service/common/system/index.ts
  projects/app/src/service/core/dataset/queues/datasetParse.ts
  projects/app/src/types/index.d.ts
  projects/app/src/web/core/dataset/api.ts
Labels: size/XL

#5670 fix: front end render wecom publish without update manually
  projects/app/src/pageComponents/app/detail/Publish/index.tsx
Labels: size/XS

#5672 fix: question guide prompt save & sub route image
  document/content/docs/upgrading/4-12/4125.mdx
  document/data/doc-last-modified.json
  packages/service/common/file/image/utils.ts
  packages/web/components/common/Textarea/CustomPromptEditor/index.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/MarkdownTransformers/index.ts
Labels: size/M

#5675 feat: chat node response store
  document/content/docs/upgrading/4-12/4125.mdx
  packages/global/core/chat/type.d.ts
  packages/global/core/chat/utils.ts
  packages/service/core/app/controller.ts
  packages/service/core/chat/chatItemResponseSchema.ts
  packages/service/core/chat/chatItemSchema.ts
  packages/service/core/chat/chatSchema.ts
  packages/service/core/chat/constants.ts
  packages/service/core/chat/controller.ts
  packages/service/core/chat/pushChatLog.ts
  packages/service/core/chat/saveChat.ts
  packages/service/core/workflow/dispatch/index.ts
  projects/app/src/pages/api/core/app/exportChatLogs.ts
  projects/app/src/pages/api/core/app/getChatLogs.ts
  projects/app/src/pages/api/core/chat/chatTest.ts
  projects/app/src/pages/api/core/chat/clearHistories.ts
  projects/app/src/pages/api/core/chat/delHistory.ts
  projects/app/src/pages/api/core/chat/getPaginationRecords.ts
  projects/app/src/pages/api/core/chat/getResData.ts
  projects/app/src/pages/api/core/chat/item/delete.ts
  projects/app/src/pages/api/core/dataset/data/getQuoteData.ts
  projects/app/src/pages/api/v1/chat/completions.ts
  projects/app/src/pages/api/v2/chat/completions.ts
  projects/app/src/service/core/app/utils.ts
  projects/app/src/service/support/mcp/utils.ts
  projects/app/src/service/support/permission/auth/chat.ts
  projects/app/test/service/support/permission/auth/chat.test.ts
Labels: size/XXL

#5506 add ai generate node
  packages/global/support/wallet/usage/constants.ts
  packages/web/components/common/Icon/constants.ts
  packages/web/components/common/Icon/icons/codeCopilot.svg
  packages/web/components/common/Textarea/PromptEditor/Editor.tsx
  packages/web/components/common/Textarea/PromptEditor/index.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/KeyDownPlugin/index.tsx
  packages/web/i18n/en/app.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-Hant/app.json
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeCode/Copilot.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeCode/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeCode/parser.ts
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/DynamicInputs/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderOutput/DynamicOutputs.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderOutput/index.tsx
  projects/app/src/pages/api/core/workflow/optimizeCode.ts
  projects/app/src/web/common/api/fetch.ts
Labels: size/XXL

#5677 perf: workflow performance
  document/content/docs/upgrading/4-12/4125.mdx
  document/data/doc-last-modified.json
  packages/web/hooks/useMemoEnhance.ts
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeAgent.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeAnswer.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeCode/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeExtract/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeHttp/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeLaf.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeSimple.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeTool.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/NodeCard.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderInput/templates/DynamicInputs/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderOutput/index.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/render/RenderToolInput/index.tsx
Labels: size/L

#5575 feat: multi node data sync & system tool hot-swapping
  document/content/docs/introduction/guide/plugins/meta.json
  document/content/docs/introduction/guide/plugins/upload_system_tool.mdx
  document/content/docs/toc.mdx
  document/data/doc-last-modified.json
  document/public/imgs/plugins/entry.png
  document/public/imgs/plugins/file.png
  packages/global/core/app/plugin/type.d.ts
  packages/global/core/workflow/type/node.d.ts
  packages/global/package.json
  packages/service/common/cache/index.ts
  packages/service/common/cache/init.ts
  packages/service/common/cache/type.ts
  packages/service/common/s3/config.ts
  packages/service/common/s3/const.ts
  packages/service/common/s3/controller.ts
  packages/service/common/s3/index.ts
  packages/service/common/s3/type.ts
  packages/service/common/vectorDB/controller.ts
  packages/service/core/app/plugin/controller.ts
  packages/service/core/app/tool/api.ts
  packages/service/package.json
  packages/web/components/common/DateRangePicker/index.tsx
  packages/web/components/common/MySelect/MultipleSelect.tsx
  packages/web/core/workflow/constants.ts
  packages/web/i18n/en/app.json
  packages/web/i18n/en/common.json
  packages/web/i18n/en/file.json
  packages/web/i18n/zh-CN/app.json
  packages/web/i18n/zh-CN/common.json
  packages/web/i18n/zh-CN/file.json
  packages/web/i18n/zh-Hant/app.json
  packages/web/i18n/zh-Hant/common.json
  packages/web/i18n/zh-Hant/file.json
  pnpm-lock.yaml
  projects/app/.env.template
  projects/app/package.json
  projects/app/src/components/Select/FileSelectorBox.tsx
  projects/app/src/pageComponents/app/plugin/UploadSystemToolModal.tsx
  projects/app/src/pageComponents/dashboard/SystemPlugin/ToolCard.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/BackupImportModal.tsx
  projects/app/src/pageComponents/dataset/detail/CollectionCard/TemplateImportModal.tsx
  projects/app/src/pageComponents/dataset/detail/data/InsertImageModal.tsx
  projects/app/src/pages/api/common/file/plugin/confirmUpload.ts
  projects/app/src/pages/api/common/file/plugin/getUploadURL.ts
  projects/app/src/pages/api/core/app/plugin/getSystemPluginTemplates.ts
  projects/app/src/pages/api/plugin/delete.ts
  projects/app/src/pages/dashboard/[pluginGroupId]/index.tsx
  projects/app/src/pages/dashboard/evaluation/create.tsx
  projects/app/src/service/common/system/volumnMongoWatch.ts
  projects/app/src/web/common/file/api.ts
  projects/app/src/web/core/app/api/plugin.ts
  test/setup.ts
Labels: size/XXL

#5686 Update README.md
  README.md
Labels: size/XS

#5695 fix prompt editor
  packages/web/components/common/Textarea/PromptEditor/plugins/VariableLabelPlugin/index.tsx
  packages/web/components/common/Textarea/PromptEditor/plugins/VariablePlugin/index.tsx
  packages/web/i18n/en/app.json
  packages/web/i18n/zh-Hant/app.json
Labels: size/M

#5698 fix: child usage remove
  packages/service/core/workflow/dispatch/abandoned/runApp.ts
  packages/service/core/workflow/dispatch/ai/agent/toolCall.ts
  packages/service/core/workflow/dispatch/child/runApp.ts
  packages/service/core/workflow/dispatch/loop/runLoop.ts
  packages/service/core/workflow/dispatch/plugin/run.ts
Labels: size/S

#5700 update package version
  projects/app/package.json
Labels: size/XS

#5704 fix: collection ui
  packages/web/hooks/useTableMultipleSelect.tsx
  projects/app/src/components/core/ai/ModelTable/index.tsx
Labels: size/XS

#5709 Update 4130.mdx
  document/content/docs/upgrading/4-13/4130.mdx
Labels: size/XS

#5710 perf: move structured render components
  projects/app/src/components/Markdown/codeBlock/StructureRender/Divider.tsx
  projects/app/src/components/Markdown/codeBlock/StructureRender/Indicator.tsx
  projects/app/src/components/Markdown/codeBlock/StructureRender/Link.tsx
  projects/app/src/components/Markdown/codeBlock/StructureRender/Table.tsx
  projects/app/src/components/Markdown/codeBlock/StructureRender/TextBlock.tsx
  projects/app/src/components/Markdown/codeBlock/StructureRender/Tips.tsx
  projects/app/src/components/Markdown/codeBlock/StructureRender/index.tsx
  projects/app/src/components/Markdown/img/EChartsCodeBlock.tsx
  projects/app/src/components/Markdown/index.tsx
  projects/app/src/components/Markdown/utils.ts
Labels: size/XL

#5712 app doc
  document/content/docs/introduction/development/openapi/app.mdx
  document/content/docs/introduction/development/openapi/meta.json
  document/content/docs/toc.mdx
  document/data/doc-last-modified.json
  document/public/imgs/image-120.png
  projects/app/src/pages/api/admin/initv4124.ts
Labels: size/L

#5713 feat: auth login in getSchemaApi
  document/content/docs/upgrading/4-13/4130.mdx
  document/data/doc-last-modified.json
  projects/app/src/pages/api/core/app/httpTools/getApiSchemaByUrl.ts
Labels: size/S

#5714 fix: loop interactive
  document/content/docs/toc.mdx
  document/content/docs/upgrading/4-13/4131.mdx
  document/content/docs/upgrading/4-13/meta.json
  document/data/doc-last-modified.json
  packages/service/core/workflow/dispatch/loop/runLoop.ts
  projects/app/src/components/core/chat/ChatContainer/ChatBox/index.tsx
Labels: size/M

#5715 fix: react-hook-form Controller crash with special characters in field names
  projects/app/src/components/core/chat/components/AIResponseBox.tsx
  projects/app/src/components/core/chat/components/Interactive/InteractiveComponents.tsx
Labels: size/M

#5716 fix: add missing MongoAppChatLog updates for interactive chat sessions
  document/content/docs/upgrading/4-13/4131.mdx
  document/data/doc-last-modified.json
  packages/service/core/chat/saveChat.ts
Labels: size/L

#5719 feat: response limit;perf: copy avatar image;perf: markdown parse
  document/content/docs/upgrading/4-13/4131.mdx
  document/data/doc-last-modified.json
  packages/global/core/chat/utils.ts
  packages/global/core/workflow/node/constant.ts
  packages/service/common/cache/index.ts
  packages/service/common/cache/init.ts
  packages/service/common/cache/type.ts
  packages/service/common/file/image/controller.ts
  packages/service/common/system/constants.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  projects/app/src/components/Markdown/utils.ts
  projects/app/src/components/core/chat/components/Interactive/InteractiveComponents.tsx
  projects/app/src/pages/api/core/app/copy.ts
Labels: size/L

#5723 update deploy doc
  deploy/README.md
  deploy/docker/cn/docker-compose.milvus.yml
  deploy/docker/cn/docker-compose.oceanbase.yml
  deploy/docker/cn/docker-compose.pg.yml
  deploy/docker/cn/docker-compose.zilliz.yml
  deploy/docker/global/docker-compose.milvus.yml
  deploy/docker/global/docker-compose.oceanbase.yml
  deploy/docker/global/docker-compose.pg.yml
  deploy/docker/global/docker-compose.ziliiz.yml
  deploy/templates/docker-compose.prod.yml
  document/public/deploy/docker/cn/docker-compose.milvus.yml
  document/public/deploy/docker/cn/docker-compose.oceanbase.yml
  document/public/deploy/docker/cn/docker-compose.pg.yml
  document/public/deploy/docker/cn/docker-compose.zilliz.yml
  document/public/deploy/docker/global/docker-compose.milvus.yml
  document/public/deploy/docker/global/docker-compose.oceanbase.yml
  document/public/deploy/docker/global/docker-compose.pg.yml
  document/public/deploy/docker/global/docker-compose.ziliiz.yml
Labels: size/M

#5724 Test doc
  .github/workflows/docs-deploy.yml
  document/content/docs/introduction/development/modelConfig/ppio.mdx
  document/content/docs/introduction/development/sealos.mdx
  document/data/doc-last-modified.json
Labels: size/M

#5725 fix: static file /deploy/*
  document/middleware.ts
  document/next.config.mjs
Labels: size/S

#5726 chore: deploy update cn registry
  deploy/args.json
  deploy/dev/docker-compose.cn.yml
  deploy/docker/cn/docker-compose.milvus.yml
  deploy/docker/cn/docker-compose.oceanbase.yml
  deploy/docker/cn/docker-compose.pg.yml
  deploy/docker/cn/docker-compose.zilliz.yml
  document/public/deploy/docker/cn/docker-compose.milvus.yml
  document/public/deploy/docker/cn/docker-compose.oceanbase.yml
  document/public/deploy/docker/cn/docker-compose.pg.yml
  document/public/deploy/docker/cn/docker-compose.zilliz.yml
  document/public/deploy/install.sh
Labels: size/M

#5728 4.13.1 features
  deploy/docker/cn/docker-compose.milvus.yml
  deploy/docker/cn/docker-compose.oceanbase.yml
  deploy/docker/cn/docker-compose.pg.yml
  deploy/docker/cn/docker-compose.zilliz.yml
  deploy/docker/global/docker-compose.milvus.yml
  deploy/docker/global/docker-compose.oceanbase.yml
  deploy/docker/global/docker-compose.pg.yml
  deploy/docker/global/docker-compose.ziliiz.yml
  deploy/templates/docker-compose.prod.yml
  document/content/docs/upgrading/4-13/4131.mdx
  document/data/doc-last-modified.json
  document/public/deploy/docker/cn/docker-compose.milvus.yml
  document/public/deploy/docker/cn/docker-compose.oceanbase.yml
  document/public/deploy/docker/cn/docker-compose.pg.yml
  document/public/deploy/docker/cn/docker-compose.zilliz.yml
  document/public/deploy/docker/global/docker-compose.milvus.yml
  document/public/deploy/docker/global/docker-compose.oceanbase.yml
  document/public/deploy/docker/global/docker-compose.pg.yml
  document/public/deploy/docker/global/docker-compose.ziliiz.yml
  packages/global/common/middle/tracks/constants.ts
  packages/global/common/string/swagger.ts
  packages/global/core/chat/utils.ts
  packages/global/core/workflow/node/constant.ts
  packages/global/core/workflow/utils.ts
  packages/service/common/cache/index.ts
  packages/service/common/cache/init.ts
  packages/service/common/cache/type.ts
  packages/service/common/file/image/controller.ts
  packages/service/common/middle/tracks/processor.ts
  packages/service/common/middle/tracks/schema.ts
  packages/service/common/middle/tracks/type.d.ts
  packages/service/common/middle/tracks/utils.ts
  packages/service/common/system/constants.ts
  packages/service/core/app/plugin/controller.ts
  packages/service/core/dataset/search/controller.ts
  packages/service/core/workflow/dispatch/dataset/search.ts
  packages/service/core/workflow/dispatch/tools/http468.ts
  packages/web/common/system/utils.ts
  projects/app/.env.template
  projects/app/package.json
  projects/app/src/components/Markdown/utils.ts
  projects/app/src/components/core/chat/components/Interactive/InteractiveComponents.tsx
  projects/app/src/instrumentation.ts
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/components/NodeTemplates/list.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodeFormInput/InputFormEditModal.tsx
  projects/app/src/pageComponents/app/detail/WorkflowComponents/Flow/nodes/NodePluginIO/InputEditModal.tsx
  projects/app/src/pageComponents/dashboard/apps/HttpPluginEditModal.tsx
  projects/app/src/pages/api/core/app/copy.ts
  projects/app/src/pages/api/core/dataset/searchTest.ts
  projects/app/src/web/common/api/request.ts
  projects/app/src/web/core/workflow/utils.ts
  projects/app/test/cases/web/workflow/store2flow.deprecated.test.ts
  projects/app/test/web/common/api/request.test.ts
Labels: size/L

#5729 deploy doc
  deploy/args.json
  deploy/dev/docker-compose.cn.yml
  deploy/dev/docker-compose.yml
  deploy/docker/cn/docker-compose.milvus.yml
  deploy/docker/cn/docker-compose.oceanbase.yml
  deploy/docker/cn/docker-compose.pg.yml
  deploy/docker/cn/docker-compose.zilliz.yml
  deploy/docker/global/docker-compose.milvus.yml
  deploy/docker/global/docker-compose.oceanbase.yml
  deploy/docker/global/docker-compose.pg.yml
  deploy/docker/global/docker-compose.ziliiz.yml
  document/content/docs/upgrading/4-13/4131.mdx
  document/data/doc-last-modified.json
  document/public/deploy/docker/cn/docker-compose.milvus.yml
  document/public/deploy/docker/cn/docker-compose.oceanbase.yml
  document/public/deploy/docker/cn/docker-compose.pg.yml
  document/public/deploy/docker/cn/docker-compose.zilliz.yml
  document/public/deploy/docker/global/docker-compose.milvus.yml
  document/public/deploy/docker/global/docker-compose.oceanbase.yml
  document/public/deploy/docker/global/docker-compose.pg.yml
  document/public/deploy/docker/global/docker-compose.ziliiz.yml
Labels: size/L
